force-app/main/default/objects/Announcements__c/Announcements__c.object-meta.xml
<CustomObject>
    <label>Announcements</label>
    <nameField>
        <displayFormat>AN-{00000000}</displayFormat>
        <label>Announcements Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Announcements__c/fields/Announcement_Description__c.field-meta.xml
<CustomField>
    <fullName>Announcement_Description__c</fullName>
    <label>Announcement Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Announcements__c/fields/Announcement_Title__c.field-meta.xml
<CustomField>
    <fullName>Announcement_Title__c</fullName>
    <label>Announcement Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/CP_SC_ID__c.field-meta.xml
<CustomField>
    <fullName>CP_SC_ID__c</fullName>
    <label>CP/SC ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AnnouncementsTriggerHelper_Test.cls
@isTest
public class AnnouncementsTriggerHelper_Test {
	@isTest
    static void testMethod1() {
        Announcements__c a = new Announcements__c();
        a.Announcement_Title__c = 'Test';
        a.Announcement_Description__c = 'Test';
        a.IsActive__c = true;
        insert a;
        
        a.IsActive__c = false;
        update a;
        
        Notification__c ntRec = new Notification__c();
        ntRec.Object_Type__c = 'Announcement';
        ntRec.CP_SC_ID__c = a.Id;
        insert ntRec;
    }
}