force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>ESCROW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mode__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/DLD_Amount_2__c.field-meta.xml
<CustomField>
    <fullName>DLD_Amount_2__c</fullName>
    <formula>New_Sale_Approval__r.DLD_Amount_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DLD Amount 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/DP_Amount_2__c.field-meta.xml
<CustomField>
    <fullName>DP_Amount_2__c</fullName>
    <formula>New_Sale_Approval__r.DP_Amount_2__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DP Amount 2</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/DP_Amount__c.field-meta.xml
<CustomField>
    <fullName>DP_Amount__c</fullName>
    <formula>New_Sale_Approval__r.DP_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DP Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTC Deposits</fullName>
                <label>OTC Deposit(Cash counter)</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>CDM Cash</fullName>
                <label>CDM Cash (Cash Deposit in Machine)</label>
            </value>
            <value>
                <fullName>CDM Cheque</fullName>
                <label>CDM Cheque (Cheque Deposit in Machine)</label>
            </value>
            <value>
                <fullName>International Wire Transfer</fullName>
                <label>IWT(International)</label>
            </value>
            <value>
                <fullName>Domestic Wire Transfer</fullName>
                <label>DWT(Domestic)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Mode_Option__c.field-meta.xml
<CustomField>
    <fullName>Mode_Option__c</fullName>
    <label>Mode Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Mode</fullName>
                <default>true</default>
                <label>Single Mode</label>
            </value>
            <value>
                <fullName>Multi Mode</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Secondary_Mode__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Mode__c</fullName>
    <label>Primary Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OTC Deposits</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>CDM Cash</fullName>
            </value>
            <value>
                <fullName>International Wire Transfer</fullName>
            </value>
            <value>
                <fullName>CDM Cheque</fullName>
            </value>
            <value>
                <fullName>Domestic Wire Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Accounts Approval</fullName>
            </value>
            <value>
                <fullName>Approved by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by Accounts</fullName>
            </value>
            <value>
                <fullName>Pending for Sales Ops Approval</fullName>
            </value>
            <value>
                <fullName>Rejected by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Resubmitted to SM/SD</fullName>
            </value>
            <value>
                <fullName>Approved by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Submitted to Accounts for Amount Confirmation</fullName>
            </value>
            <value>
                <fullName>Amount Confirmed by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by System</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Payment Link sent to Customer</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>PR was Approved- Booking is cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 5) OR (1 AND 2 AND 3 AND 4) OR (6 AND 2 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Not_Available_for_Sales__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Unit__c.Allocated_SM__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>notEqual</operation>
            <value>Unreleased</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Allocated_SM__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Hold</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Unit_Purchase_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unit_Purchase_Amount__c</fullName>
    <formula>Unit__r.Puchase_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Purchase Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Unit_Hold_min_percentage__c.field-meta.xml
<CustomField>
    <fullName>Unit_Hold_min_percentage__c</fullName>
    <label>Unit Hold min percentage</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/unit_hold_request__c/unit_hold_request__c.object-meta.xml
<CustomObject>
    <label>New Sale Approval</label>
    <nameField>
        <displayFormat>N-{0000}</displayFormat>
        <label>New Sale Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Sale Approvals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/unit_hold_request__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved by Sales VP</fullName>
            </value>
            <value>
                <fullName>Approved by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Rejected by Sales VP</fullName>
            </value>
            <value>
                <fullName>Rejected by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Approved by Sales Head</fullName>
            </value>
            <value>
                <fullName>Rejected by Sales Head</fullName>
            </value>
            <value>
                <fullName>Approved by SVP</fullName>
            </value>
            <value>
                <fullName>Rejected by SVP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/unit_hold_request__c/fields/DP_Amount__c.field-meta.xml
<CustomField>
    <fullName>DP_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>DP Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/unit_hold_request__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OTC Deposits</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>CDM Cash</fullName>
            </value>
            <value>
                <fullName>International Wire Transfer</fullName>
            </value>
            <value>
                <fullName>CDM Cheque</fullName>
            </value>
            <value>
                <fullName>Domestic Wire Transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/unit_hold_request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://ceptessobha.atlassian.net/browse/SOB-133</description>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>New Sale Approvals</relationshipLabel>
    <relationshipName>New_Sale_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateAmountOnNewSaleApprovalController.cls
public without sharing class UpdateAmountOnNewSaleApprovalController {
    @AuraEnabled(cacheable=true)
    public static wrapperObj getNewSaleApproval(String recordId){
        try {
            map<string,decimal> currToRate = new map<string,decimal>();
            for(Currency_Rate__mdt currRate : [select MasterLabel, Rate__c from Currency_Rate__mdt]){
                currToRate.put(currRate.MasterLabel,currRate.Rate__c);
            }
            wrapperObj obj = new wrapperObj();
            obj.existingDpAmount2 = 0;
            obj.existingDldAmount2 = 0;
            obj.existingDldAmount1 = 0;
            obj.showBothDpAndDldField = false;
            obj.currToRate = currToRate;
            obj.showAmountConfirmError = false;
            obj.isPrimaryPR = true;
            obj.skip2PercentError = false;
            obj.differentloggedinUserError = false;
            
            Payment_Request__c pr = [SELECT ID ,Unit_Purchase_Amount__c,amount__c, unit__r.unit_hold_min_percentage__c,mode__c,mode_option__c,payment_request__c,currency__c,payment_request__r.currency__c,payment_request__r.total_Amount__c,payment_request__r.mode__c,
            total_Amount__c,Status__c,payment_request__r.Status__c,secondary_mode__c, account_type__c, payment_request__r.account_type__c  FROM Payment_Request__c where id = :recordId];
            obj.accountType = pr.Account_Type__c;
            obj.accountTypePrimary = pr.payment_request__r.account_type__c;

            //Aayushi :SOB-403 added cdm cash condition
            if(pr.mode_option__c == 'Multi Mode' && pr.mode__c != null && (pr.mode__c.tolowercase() == 'international wire transfer' || pr.mode__c.tolowercase() == 'domestic wire transfer'
            || pr.mode__c.tolowercase() == 'cdm cash')){
                if(pr.total_Amount__c != null && pr.total_Amount__c > 0 && pr.secondary_mode__c != null){
                    obj.isPrimaryPR = false;
                }
                obj.skip2PercentError = true;
               
                List<unit_hold_request__c> nsaList = [select id,ownerId,Payment_Request__c,dld_amount__c,dp_amount__c,payment_request__r.amount__c,dp_amount_2__c,
                dld_amount_2__c,payment_request__r.total_amount__c,Sales_Value__c, payment_request__r.Unit__r.Unit_Hold_min_percentage__c from unit_hold_request__c where 
                ( Approval_Status__c='Approved by Sales Ops' or Approval_Status__c='Pending' 
                 or Approval_Status__c = 'Approved by Sales VP' or Approval_Status__c = 'Approved by Sales Head' or Approval_Status__c = 'Approved')
                 AND (Payment_Request__c =: recordId or Payment_Request__c =: pr.payment_request__c)];
                 if(!nsaList.isEmpty() ){
                    obj.Unithold = nsaList[0];
                    obj.amount = pr.amount__c ;
                    obj.saleValue = pr.Unit_Purchase_Amount__c;
                    obj.existingDpAmount2 = (obj.Unithold.dp_amount_2__c!=null)?obj.Unithold.dp_amount_2__c:0;
                    obj.existingDldAmount2 = (obj.Unithold.dld_amount_2__c!=null)?obj.Unithold.dld_amount_2__c:0;
                    obj.existingDldAmount1 = (obj.Unithold.dld_amount__c!=null)?obj.Unithold.dld_amount__c:0;
                    //obj.saleValue = pr.Unit__r.Unit_Hold_min_percentage__c;
                    obj.currency1 = pr.currency__c;
                    obj.currency2 = pr.payment_request__r.currency__c;
                 }
                 //Aayushi :SOB-403 added cdm cash condition
            
                 if(pr.payment_request__c != null && (pr.payment_request__r.mode__c.tolowercase() == 'international wire transfer' || pr.payment_request__r.mode__c.tolowercase() == 'domestic wire transfer'
                 || pr.payment_request__r.mode__c.tolowercase() == 'cdm cash')){
                    obj.amount =pr.total_Amount__c != null && pr.total_Amount__c != 0? pr.total_Amount__c : pr.payment_request__r.total_Amount__c;
                    obj.showBothDpAndDldField = true;
                    if(pr.Status__c != 'Approved' || pr.payment_request__r.status__c != 'Approved'){
                        obj.showAmountConfirmError = true;
                    }
                }   
               
                       
              
            }else{
                List<unit_hold_request__c> nsaList =  [select id,ownerId,Payment_Request__c,dld_amount__c,dp_amount__c,payment_request__r.amount__c,payment_request__r.currency__c,
                payment_request__r.total_amount__c,Sales_Value__c, payment_request__r.Unit__r.Unit_Hold_min_percentage__c from unit_hold_request__c where 
                ( Approval_Status__c='Approved by Sales Ops' or Approval_Status__c='Pending' 
                 or Approval_Status__c = 'Approved by Sales VP' or Approval_Status__c = 'Approved by Sales Head' or Approval_Status__c = 'Approved')
                 AND Payment_Request__c =: recordId];
                 if(!nsaList.isEmpty()){
                    obj.unithold = nsaList[0];
                    obj.amount = obj.unithold.payment_request__r.total_amount__c != null ?obj.unithold.payment_request__r.total_amount__c : obj.unithold.payment_request__r.amount__c ;
                   
                       obj.saleValue = obj.unithold.Sales_Value__c;
                       obj.currency1 = obj.unithold.payment_request__r.currency__c;
                 }
           
                 
                
            }
            if(obj.unithold.ownerID != userInfo.getUserId()){
                obj.differentloggedinUserError = true;
               
            }
            return obj;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    public class wrapperObj{
        @AuraEnabled
        public unit_hold_request__c unithold;
        @AuraEnabled
        public decimal amount;
        @AuraEnabled
        public boolean skip2PercentError ;
        @AuraEnabled
        public decimal salevalue;
        @AuraEnabled
        public decimal existingDpAmount2;
        @AuraEnabled
        public string currency1;
        @AuraEnabled
        public string currency2;
        @AuraEnabled
        public map<string,decimal> currToRate;
        @AuraEnabled
        public boolean showBothDpAndDldField;
        @AuraEnabled
        public boolean showAmountConfirmError;
        @AuraEnabled
        public boolean isPrimaryPR;
        @AuraEnabled
        public decimal existingDldAmount2;
        @AuraEnabled
        public decimal existingDldAmount1;
        @AuraEnabled
        public boolean differentloggedinUserError;
        @AuraEnabled
        public String accountType;
        @AuraEnabled
        public String accountTypePrimary;
    }
}