force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Instrument_Date__c.field-meta.xml
<CustomField>
    <fullName>Instrument_Date__c</fullName>
    <label>Instrument Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Instrument_Number__c.field-meta.xml
<CustomField>
    <fullName>Instrument_Number__c</fullName>
    <label>Instrument Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Last_POP_Transaction_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_POP_Transaction_Status__c</fullName>
    <label>Last POC Transaction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>INITIATED</fullName>
            </value>
            <value>
                <fullName>AUTHORIZED</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Accounts Approval</fullName>
            </value>
            <value>
                <fullName>Approved by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by Accounts</fullName>
            </value>
            <value>
                <fullName>Pending for Sales Ops Approval</fullName>
            </value>
            <value>
                <fullName>Rejected by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Resubmitted to SM/SD</fullName>
            </value>
            <value>
                <fullName>Approved by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Submitted to Accounts for Amount Confirmation</fullName>
            </value>
            <value>
                <fullName>Amount Confirmed by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by System</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Payment Link sent to Customer</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>PR was Approved- Booking is cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/Payment_Request_POP_Transactions__c.object-meta.xml
<CustomObject>
    <label>Payment Request POP Transactions</label>
    <nameField>
        <displayFormat>POP-{00000000}</displayFormat>
        <label>Payment Request POP Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Request POP Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/acquirerCode__c.field-meta.xml
<CustomField>
    <fullName>acquirerCode__c</fullName>
    <label>acquirerCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/cardLastFourDigit__c.field-meta.xml
<CustomField>
    <fullName>cardLastFourDigit__c</fullName>
    <label>cardLastFourDigit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/cardType__c.field-meta.xml
<CustomField>
    <fullName>cardType__c</fullName>
    <label>cardType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/customerName__c.field-meta.xml
<CustomField>
    <fullName>customerName__c</fullName>
    <label>customerName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/errorMessage__c.field-meta.xml
<CustomField>
    <fullName>errorMessage__c</fullName>
    <label>errorMessage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/formattedPan__c.field-meta.xml
<CustomField>
    <fullName>formattedPan__c</fullName>
    <label>formattedPan</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/invoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>invoiceNumber__c</fullName>
    <label>invoiceNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/Message_Code__c.field-meta.xml
<CustomField>
    <fullName>Message_Code__c</fullName>
    <label>Message Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/mid__c.field-meta.xml
<CustomField>
    <fullName>mid__c</fullName>
    <label>mid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/orderNumber__c.field-meta.xml
<CustomField>
    <fullName>orderNumber__c</fullName>
    <label>orderNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/P2PRequestId__c.field-meta.xml
<CustomField>
    <fullName>P2PRequestId__c</fullName>
    <label>P2PRequestId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Request POP Transactions</relationshipLabel>
    <relationshipName>Payment_Request_POP_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/paymentCardType__c.field-meta.xml
<CustomField>
    <fullName>paymentCardType__c</fullName>
    <label>paymentCardType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/pgInvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>pgInvoiceNumber__c</fullName>
    <label>pgInvoiceNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/Raw_Response__c.field-meta.xml
<CustomField>
    <fullName>Raw_Response__c</fullName>
    <label>Raw Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/receiptUrl__c.field-meta.xml
<CustomField>
    <fullName>receiptUrl__c</fullName>
    <label>receiptUrl</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/reverseReferenceNumber__c.field-meta.xml
<CustomField>
    <fullName>reverseReferenceNumber__c</fullName>
    <label>reverseReferenceNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/rrNumber__c.field-meta.xml
<CustomField>
    <fullName>rrNumber__c</fullName>
    <label>rrNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/sessionKey__c.field-meta.xml
<CustomField>
    <fullName>sessionKey__c</fullName>
    <label>sessionKey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>INITIATED</fullName>
            </value>
            <value>
                <fullName>AUTHORIZED</fullName>
            </value>
            <value>
                <fullName>FAILED</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/txnId__c.field-meta.xml
<CustomField>
    <fullName>txnId__c</fullName>
    <label>txnId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <label>username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EztapStatusCheck.cls
global class EztapStatusCheck implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
    global string status = '';
    global string remarks = '';
    global string msgCode = '';
    global string prId = '';
    global string txnId = '';
    global string rawResponse = '';
    
    public EztapStatusCheck(string txnId){
        this.txnId = txnId;
    }
    
    global List<Payment_Request_POP_Transactions__c> start(Database.BatchableContext BC) {
        List <Payment_Request_POP_Transactions__c> txnList = new List <Payment_Request_POP_Transactions__c> ();
        txnList = [Select Id,Status__c,Payment_Request__c,P2PRequestId__c 
                   from Payment_Request_POP_Transactions__c 
                   where Id =: txnId];
        this.prId = txnList[0].Payment_Request__c;
        return txnList;
    }
    
    global void execute(Database.BatchableContext BC, List<Payment_Request_POP_Transactions__c> txnList) {
        Payment_Request_POP_Transactions__c t = txnList[0];
        if(t.Status__c != 'AUTHORIZED' && t.Status__c != 'FAILED'){
            string response = EzetapIntegrationStatusCallout.sendRequest(String.valueOf(t.P2PRequestId__c));
            this.rawResponse = response;
            Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(response);
            if(responseMap.containsKey('status')){
                this.status = (responseMap.get('status')!=null)?String.valueOf(responseMap.get('status')):'';
            }
            if(responseMap.containsKey('errorMessage')){
                this.remarks = (responseMap.get('errorMessage')!=null)?String.valueOf(responseMap.get('errorMessage')):'';
            }
            if(responseMap.containsKey('messageCode')){
                string messageCode = (responseMap.get('messageCode')!=null)?String.valueOf(responseMap.get('messageCode')):'';
                this.msgCode = messageCode;
                if(messageCode.contains('CANCELED')){
                    this.status = 'CANCELED';
                    InitiateEztapController.deleteScheduledJobs(t.P2PRequestId__c);
                }
            }
        }
    }   
    
    global void finish(Database.BatchableContext BC) {
        Payment_Request_POP_Transactions__c t = new Payment_Request_POP_Transactions__c(Id=txnId);
        Map<String, Object> responseMap = new Map<String, Object>();
        if(status != '')
            t.Status__c = status;
        if(remarks != '')
            t.errorMessage__c = remarks;
        if(msgCode != '')
            t.Message_Code__c = msgCode;
        if(rawResponse != ''){
            responseMap = (Map<String, Object>) JSON.deserializeUntyped(rawResponse);
            if(rawResponse!=null)
                t.Raw_Response__c = String.valueOf(rawResponse);
            if(responseMap.containsKey('amount'))
                t.amount__c = (responseMap.get('amount')!=null)?String.valueOf(responseMap.get('amount')):'';
            if(responseMap.containsKey('cardLastFourDigit'))
                t.cardLastFourDigit__c = (responseMap.get('cardLastFourDigit')!=null)?String.valueOf(responseMap.get('cardLastFourDigit')):'';
            if(responseMap.containsKey('customerName'))
                t.customerName__c = (responseMap.get('customerName')!=null)?String.valueOf(responseMap.get('customerName')):'';
            if(responseMap.containsKey('mid'))
                t.mid__c = (responseMap.get('mid')!=null)?String.valueOf(responseMap.get('mid')):'';
            if(responseMap.containsKey('orderNumber'))
                t.orderNumber__c = (responseMap.get('orderNumber')!=null)?String.valueOf(responseMap.get('orderNumber')):'';
            if(responseMap.containsKey('rrNumber'))
                t.rrNumber__c = (responseMap.get('rrNumber')!=null)?String.valueOf(responseMap.get('rrNumber')):'';
            if(responseMap.containsKey('sessionKey'))
                t.sessionKey__c = (responseMap.get('sessionKey')!=null)?String.valueOf(responseMap.get('sessionKey')):'';
            if(responseMap.containsKey('txnId'))
                t.txnId__c = (responseMap.get('txnId')!=null)?String.valueOf(responseMap.get('txnId')):'';
            if(responseMap.containsKey('username'))
                t.username__c = (responseMap.get('username')!=null)?String.valueOf(responseMap.get('username')):'';
            if(responseMap.containsKey('formattedPan'))
                t.formattedPan__c = (responseMap.get('formattedPan')!=null)?String.valueOf(responseMap.get('formattedPan')):'';
            if(responseMap.containsKey('cardType'))
                t.cardType__c = (responseMap.get('cardType')!=null)?String.valueOf(responseMap.get('cardType')):'';
            if(responseMap.containsKey('paymentCardType'))
                t.paymentCardType__c = (responseMap.get('paymentCardType')!=null)?String.valueOf(responseMap.get('paymentCardType')):'';
            if(responseMap.containsKey('pgInvoiceNumber'))
                t.pgInvoiceNumber__c = (responseMap.get('pgInvoiceNumber')!=null)?String.valueOf(responseMap.get('pgInvoiceNumber')):'';
            if(responseMap.containsKey('tid'))
                t.tid__c = (responseMap.get('tid')!=null)?String.valueOf(responseMap.get('tid')):'';
            if(responseMap.containsKey('receiptUrl'))
                t.receiptUrl__c = (responseMap.get('receiptUrl')!=null)?String.valueOf(responseMap.get('receiptUrl')):'';
            if(responseMap.containsKey('acquirerCode'))
                t.acquirerCode__c = (responseMap.get('acquirerCode')!=null)?String.valueOf(responseMap.get('acquirerCode')):'';
            if(responseMap.containsKey('reverseReferenceNumber'))
                t.reverseReferenceNumber__c = (responseMap.get('reverseReferenceNumber')!=null)?String.valueOf(responseMap.get('reverseReferenceNumber')):'';
            if(responseMap.containsKey('invoiceNumber'))
                t.invoiceNumber__c = (responseMap.get('invoiceNumber')!=null)?String.valueOf(responseMap.get('invoiceNumber')):'';
        }
        update t;
        Payment_Request__c pr = new Payment_Request__c(Id=prId);
        if(status != ''){
            pr.Last_POP_Transaction_Status__c = status;
            if(status == 'AUTHORIZED'){
                pr.Status__c = 'Approved';
                if(responseMap.containsKey('authCode'))
                    pr.Instrument_Number__c = (responseMap.get('authCode')!=null)?String.valueOf(responseMap.get('authCode')):'';
                if(responseMap.containsKey('chargeSlipDate')){
                    string shipDate = (responseMap.get('chargeSlipDate')!=null)?String.valueOf(responseMap.get('chargeSlipDate')):'';
                    if(shipDate!=''){
                        shipDate = shipDate.split('T')[0];
                        pr.Instrument_Date__c = Date.valueOf(shipDate);
                    }
                }
            }
            update pr;
        }
    }
}