force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Mode_Option__c.field-meta.xml
<CustomField>
    <fullName>Mode_Option__c</fullName>
    <label>Mode Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Mode</fullName>
                <default>true</default>
                <label>Single Mode</label>
            </value>
            <value>
                <fullName>Multi Mode</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request_Wrapper__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request_Wrapper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request Wrapper</label>
    <referenceTo>Payment_Request_Wrapper__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Accounts Approval</fullName>
            </value>
            <value>
                <fullName>Approved by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by Accounts</fullName>
            </value>
            <value>
                <fullName>Pending for Sales Ops Approval</fullName>
            </value>
            <value>
                <fullName>Rejected by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Resubmitted to SM/SD</fullName>
            </value>
            <value>
                <fullName>Approved by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Submitted to Accounts for Amount Confirmation</fullName>
            </value>
            <value>
                <fullName>Amount Confirmed by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by System</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Payment Link sent to Customer</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>PR was Approved- Booking is cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/VP_For_PR__c.field-meta.xml
<CustomField>
    <fullName>VP_For_PR__c</fullName>
    <label>VP For PR</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_Wrapper__c/Payment_Request_Wrapper__c.object-meta.xml
<CustomObject>
    <label>Payment Request Wrapper</label>
    <nameField>
        <displayFormat>PRW-{0000000000}</displayFormat>
        <label>Payment  Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Request Wrapper</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request_Wrapper__c/fields/Mode_Option__c.field-meta.xml
<CustomField>
    <fullName>Mode_Option__c</fullName>
    <label>Mode Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Mode</fullName>
            </value>
            <value>
                <fullName>Multi Mode</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentRequest_VP_Update_Test.cls
@isTest public class PaymentRequest_VP_Update_Test {
    
     @isTest public static void test1(){
        Map<String, Id> recordMap = TestDataFactory.createMasterProject('Test Project');
        Id unitId = recordMap.get('UNIT');
        
        ContentVersion contentVersion = new ContentVersion(
            Title          = 'a picture',
            PathOnClient   = 'pic.jpg',
            VersionData    = Blob.valueOf('Test Content'),
            IsMajorVersion = true); 
        insert contentVersion;
        
        PaymentRequestFormController.createPaymentRequest('name','email@test.com','9999999999','p12345','Cheque','AED','12345','12345',string.valueOf(system.today()),null,'1000',string.valueOf(system.today()),'United Arab Emirates',1,new list<string>{unitId},'undefined','undefined','undefined','undefined','undefined','false###false###false###false','','','','','','','test######102',false,false,'Marketing#Digital','');
        Payment_Request__c pr = [select Id, Payment_Request_Wrapper__c from Payment_Request__c Limit 1];
        pr.Mode_Option__c = 'Multi Mode';
        pr.Status__c = 'Approved';
        
        PaymentRequestFormController.createPaymentRequest('name','email@test.com','9999999999','p12345','Cheque','AED','12345','12345',string.valueOf(system.today()),null,'1000',string.valueOf(system.today()),'United Arab Emirates',1,new list<string>{unitId},'undefined','undefined','undefined','undefined','undefined','false###false###false###false','','','','','','','test######102',false,false,'Marketing#Digital','');
        Payment_Request__c pr1 = [select Id, Payment_Request_Wrapper__c from Payment_Request__c where id !=: pr.id];
        Test.startTest();
         
        list<Payment_Request__c> tmpList = [SELECT Id,VP_For_PR__c,CreatedById FROM Payment_Request__c where Id =:  pr1.Id];
        List<Id> prIdList = new List<Id>();
        for(Payment_Request__c prtest : tmpList){
             prIdList.add(prtest.id);
         }

        PaymentRequest_VP_Update batchInstance = new PaymentRequest_VP_Update(prIdList);

        Database.QueryLocator batchStart = batchInstance.start(null);
        batchInstance.execute(null, tmpList);
        System.assertNotEquals(null, batchStart, 'Batch start method should return a QueryLocator');
        Test.stopTest();
    }

}