force-app/main/default/objects/Applicant_Details__c/Applicant_Details__c.object-meta.xml
<CustomObject>
    <label>Applicant Details</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApplicantDetails</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant_Details__c/fields/Applicant_Number__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Number__c</fullName>
    <label>Applicant Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Applicant</fullName>
            </value>
            <value>
                <fullName>Second Applicant</fullName>
            </value>
            <value>
                <fullName>Third Applicant</fullName>
            </value>
            <value>
                <fullName>Fourth Applicant</fullName>
            </value>
            <value>
                <fullName>Fifth Applicant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/Applicant_Signing_Order__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Signing_Order__c</fullName>
    <formula>IF(  ISPICKVAL(Applicant_Number__c, &apos;Primary Applicant&apos;) , 1, IF(ISPICKVAL(Applicant_Number__c, &apos;Second Applicant&apos;), 2, IF(ISPICKVAL(Applicant_Number__c, &apos;Third Applicant&apos;), 3 , IF(ISPICKVAL(Applicant_Number__c, &apos;Fourth Applicant&apos;), 4, 5) ) ) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Signing Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>ApplicantDetails</relationshipLabel>
    <relationshipName>ApplicantDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/Corporate_Stamping_Required__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Stamping_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Corporate Stamping Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/Resale_Process__c.field-meta.xml
<CustomField>
    <fullName>Resale_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resale Process</label>
    <referenceTo>Resale_Process__c</referenceTo>
    <relationshipLabel>ApplicantDetails</relationshipLabel>
    <relationshipName>ApplicantDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/Type_Of_Applicant__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Applicant__c</fullName>
    <label>Type Of Applicant</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Individual Purchaser</fullName>
            </value>
            <value>
                <fullName>Corporate Purchaser</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Applicant Details</relationshipLabel>
    <relationshipName>ApplicantDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Applicant_Details__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Details</label>
    <referenceTo>Applicant_Details__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Sub Project</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/CRM_Document_Controller__c.field-meta.xml
<CustomField>
    <fullName>CRM_Document_Controller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRM Document Controller</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking0e8R</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Sales_Managers__c.field-meta.xml
<CustomField>
    <fullName>Sales_Managers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/SPA_Docusign_Envelope_Id__c.field-meta.xml
<CustomField>
    <fullName>SPA_Docusign_Envelope_Id__c</fullName>
    <label>SPA Docusign Envelope Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <label>Tower</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Buyer__c/Buyer__c.object-meta.xml
<CustomObject>
    <label>Buyer</label>
    <nameField>
        <label>Buyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Buyer__c/fields/Buyer_Type__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Type__c</fullName>
    <label>Buyer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary Applicant</fullName>
            </value>
            <value>
                <fullName>Second Applicant</fullName>
            </value>
            <value>
                <fullName>Third Applicant</fullName>
            </value>
            <value>
                <fullName>Fourth Applicant</fullName>
            </value>
            <value>
                <fullName>Fifth Applicant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Buyer__c/fields/Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>Passport_Number__c</fullName>
    <label>Passport Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Buyer__c/fields/Resale_Process__c.field-meta.xml
<CustomField>
    <fullName>Resale_Process__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resale Process</label>
    <referenceTo>Resale_Process__c</referenceTo>
    <relationshipLabel>Buyers</relationshipLabel>
    <relationshipName>Buyers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/CRM.recordType-meta.xml
<RecordType>
    <fullName>CRM</fullName>
    <active>true</active>
    <businessProcess>CRM Support Process</businessProcess>
    <label>CRM</label>
</RecordType>

force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <label>Sub Project</label>
    <nameField>
        <label>Sub Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Docusign_Result__e/Docusign_Result__e.object-meta.xml
<CustomObject>
    <label>Docusign Result</label>
    <pluralLabel>Docusign Result</pluralLabel>
</CustomObject>

force-app/main/default/objects/Docusign_Result__e/fields/Booking_Id__c.field-meta.xml
<CustomField>
    <fullName>Booking_Id__c</fullName>
    <label>Booking Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Docusign_Result__e/fields/MessageToDisplay__c.field-meta.xml
<CustomField>
    <fullName>MessageToDisplay__c</fullName>
    <label>MessageToDisplay</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Resale_Process__c/Resale_Process__c.object-meta.xml
<CustomObject>
    <description>Resale Process</description>
    <label>Resale Process</label>
    <nameField>
        <displayFormat>RPN-{0000}</displayFormat>
        <label>Resale Process Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resale Process</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Resale_Process__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Resale Process</relationshipLabel>
    <relationshipName>Resale_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resale_Process__c/fields/CRM_Document_Controller__c.field-meta.xml
<CustomField>
    <fullName>CRM_Document_Controller__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CRM Document Controller</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Resale_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resale_Process__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Resale Process</relationshipLabel>
    <relationshipName>Resale_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Resale_Process__c/fields/Type_of_Buyer__c.field-meta.xml
<CustomField>
    <fullName>Type_of_Buyer__c</fullName>
    <label>Type of Buyer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Company</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Resale_Process__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Resale Process</relationshipLabel>
    <relationshipName>Resale_Process</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Booking_Id__c.field-meta.xml
<CustomField>
    <fullName>Booking_Id__c</fullName>
    <formula>Booking__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Booking Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <displayFormat>U - {0000}</displayFormat>
    <label>User Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/resaledocusignhandler.cls
public without sharing class resaledocusignhandler  
{
    @InvocableMethod
    public static void sendEnvelopeMethod(List<Id> resaleIds)
        {
            Id mySourceId = resaleIds[0];
            forForSigningFuture(mySourceId);
        }
    @future(callout=true)
    public static void forForSigningFuture(Id mySourceId) 
    {
        try {
            Map<String,String> emailToRoleMap = new Map<String,String>();
			Resale_Process__c resale = [Select Id, Name, CRM_Document_Controller__r.Name, CRM_Document_Controller__r.Email, Type_of_Buyer__c, Booking__c, Booking__r.name, Booking__r.Unit__r.Name, Booking__r.Tower__c , Booking__r.Cluster__c, Unit__c, Unit__r.Name from  Resale_Process__c Where Id =:mySourceId order by createddate desc Limit 1];
            dfsle.Envelope myEnvelope = dfsle.EnvelopeService.getEmptyEnvelope(new dfsle.Entity(mySourceId));
    		String docName = 'Resale Agreement '+resale.Unit__r.Name+'%';
            System.debug('document Name should be: '+docName);
            List<ContentDocumentLink> docList = [SELECT ContentDocumentId,ContentDocument.title,Id,LinkedEntityId,ShareType 
                                                FROM ContentDocumentLink 
                                                WHERE LinkedEntityId =:mySourceId 
                                                    and ContentDocument.title like :docName
                                                Order by ContentDocument.createdDate desc];

            Id myDocumentId = docList[0].ContentDocumentId; // The ID of a document stored in a Salesforce library
    
            Id myFileId = [SELECT id from ContentVersion where ContentDocumentId =:myDocumentId LIMIT 1].id;
    
            List<Applicant_Details__c> applicants = [Select id,name, Email_Address__c, Applicant_Number__c,Mobile_Number__c,Type_Of_Applicant__c ,Corporate_Stamping_Required__c  From Applicant_Details__c
                                                        Where Booking__c =:resale.Booking__c ORDER BY Applicant_Signing_Order__c ASC];
            Integer applicantsSize = applicants.size();
            Integer i=1;
            Decimal scaleValue;
            Integer yOffset = 0;
            scaleValue = 1.0;
            yOffset = 10;
            Integer j=1;
            List<Buyer__c> buyers = [Select Id, Name, Email__c, Phone_Number__c, Passport_Number__c, Buyer_Type__c  from Buyer__c where Resale_Process__c=:mySourceId];
              
        
            // Add document to the envelope
            myEnvelope = myEnvelope.withDocuments(dfsle.DocumentService.getDocuments(ContentVersion.getSObjectType(), new Set<Id> { myFileId }));
            
            //Docusign For Appllicants
            List<dfsle.Recipient> recipientList = new List<dfsle.Recipient>();
            
            
            //Integer i = 1;
            for (Applicant_Details__c applicant:applicants) {
                emailToRoleMap.put(applicant.Email_Address__c +'_'+i,'Seller');
                
                //SMS authentication phone numbers
                List<String> smsPhoneNumbers = new List<String>();
                String applPhoneNumber = validateAndUpdatePhoneNumber(applicant.Mobile_Number__c);
                smsPhoneNumbers.add(applPhoneNumber);
    
                //Set the authentication
                dfsle.Recipient.Authentication auth = new dfsle.Recipient.Authentication('', false, smsPhoneNumbers );

                String sub = resale.Booking__r.Unit__r.Name +' - '+resale.Booking__r.Cluster__c+' - Seller Email';
                String body = docusignSellerEmailBody();


                dfsle.Recipient.EmailSettings applicantEmailSetting = new dfsle.Recipient.EmailSettings('en','English', sub, body);
    
                String anchorString = 'purchasersig' + String.valueOf(i);
                // Create a Sign Here tab
                List<dfsle.Tab> applicantsTabs = new List<dfsle.Tab>();
                dfsle.Tab mySignHereTab = new dfsle.SignHereTab()
                                                            .withScale(scaleValue) // 1.5 scale
                                                            .withRequired(true) // Signing mandatory
                                                            .withAnchor(new dfsle.Tab.Anchor(
                                                                anchorString, // Anchor string
                                                                false, // Do not allow white space in anchor string
                                                                false, // Anchor string is not case sensitive
                                                                'right', // Horizontal alignment in relation to the anchor text
                                                                true, // Ignore if the anchor text is not present in the document
                                                                true, // Must match the value of the anchor string in its entirety
                                                                'pixels', // Unit of the x and y offset properties
                                                                0, // X offset
                                                                yOffset)); // Y offset 
                applicantsTabs.add(mySignHereTab);
                
                 //If corporate applicant enable stamping for primary
                if (applicant.Applicant_Number__c == 'Primary Applicant' && applicant.Type_Of_Applicant__c == 'Corporate Purchaser') {
                    dfsle.SignHereTab.Stamp corpAppStamp = new dfsle.SignHereTab.Stamp('stamp',null,null,null,null,null,null,null);      
                    dfsle.Tab corpAppStampTab = new dfsle.SignHereTab().withStamp(corpAppStamp)
                                                .withScale(1.0) // 1.5 scale
                                                .withRequired(true) // Signing mandatory
                                                .withAnchor(new dfsle.Tab.Anchor(
                                                                    'sellerstamp', // Anchor string
                                                                    false, // Do not allow white space in anchor string
                                                                    false, // Anchor string is not case sensitive
                                                                    'right', // Horizontal alignment in relation to the anchor text
                                                                    true, // Ignore if the anchor text is not present in the document
                                                                    true, // Must match the value of the anchor string in its entirety
                                                                    'pixels', // Unit of the x and y offset properties
                                                                    0, // X offset
                                                                    0)
                                                            ); // Y offset
                    applicantsTabs.add(corpAppStampTab);
                }

    
                dfsle.Recipient myRecipient = dfsle.Recipient.fromSource(
                                                                applicant.name,
                                                                applicant.Email_Address__c,
                                                                null, 
                                                                applicant.Applicant_Number__c,
                                                                null
                                                            )
                                                            .withTabs(applicantsTabs)
                                                            .withAuthentication(auth)
                                                            .withEmailSettings(applicantEmailSetting);
                
                recipientList.add(myRecipient);
                i = i+1;
            }
    
            //buyers
            for (Buyer__c applicant: buyers) {
                emailToRoleMap.put(applicant.Email__c +'_'+i,'Buyer');
                
                //SMS authentication phone numbers
                List<String> smsPhoneNumbers = new List<String>();
                String applPhoneNumber = resaledocusignUtil.validateAndUpdatePhoneNumber(applicant.Phone_Number__c);
                smsPhoneNumbers.add(applPhoneNumber);
    
                //Set the authentication
                dfsle.Recipient.Authentication auth = new dfsle.Recipient.Authentication('', false, smsPhoneNumbers );

                String sub = resale.Booking__r.Unit__r.Name +' - '+resale.Booking__r.Cluster__c+' - buyer Email';
                String body = docusignBuyerEmailBody();

                dfsle.Recipient.EmailSettings applicantEmailSetting = new dfsle.Recipient.EmailSettings('en','English',sub,body);
    
                String anchorString = 'buyersign' + String.valueOf(j);
                // Create a Sign Here tab
                List<dfsle.Tab> buyerTabs = new List<dfsle.Tab>();
                dfsle.Tab mySignHereTab = new dfsle.SignHereTab()
                                                            .withScale(scaleValue) // 1.5 scale
                                                            .withRequired(true) // Signing mandatory
                                                            .withAnchor(new dfsle.Tab.Anchor(
                                                                anchorString, // Anchor string
                                                                false, // Do not allow white space in anchor string
                                                                false, // Anchor string is not case sensitive
                                                                'right', // Horizontal alignment in relation to the anchor text
                                                                true, // Ignore if the anchor text is not present in the document
                                                                true, // Must match the value of the anchor string in its entirety
                                                                'pixels', // Unit of the x and y offset properties
                                                                0, // X offset
                                                                yOffset)); // Y offset 
                buyerTabs.add(mySignHereTab);
                 //If corporate applicant enable stamping for primary
                if (applicant.Buyer_Type__c  == 'Primary Applicant' && resale.Type_of_Buyer__c == 'Company') {
                    dfsle.SignHereTab.Stamp corpAppStamp = new dfsle.SignHereTab.Stamp('stamp',null,null,null,null,null,null,null);      
                    dfsle.Tab corpAppStampTab = new dfsle.SignHereTab().withStamp(corpAppStamp)
                                                .withScale(1.0) // 1.5 scale
                                                .withRequired(true) // Signing mandatory
                                                .withAnchor(new dfsle.Tab.Anchor(
                                                                    'buyerstamp', // Anchor string
                                                                    false, // Do not allow white space in anchor string
                                                                    false, // Anchor string is not case sensitive
                                                                    'right', // Horizontal alignment in relation to the anchor text
                                                                    true, // Ignore if the anchor text is not present in the document
                                                                    true, // Must match the value of the anchor string in its entirety
                                                                    'pixels', // Unit of the x and y offset properties
                                                                    0, // X offset
                                                                    0)
                                                            ); // Y offset

                    buyerTabs.add(corpAppStampTab);
                }
    
                dfsle.Recipient myRecipient = dfsle.Recipient.fromSource(
                                                                applicant.name,
                                                                applicant.Email__c,
                                                                null, 
                                                                applicant.Phone_Number__c ,
                                                                null
                                                            )
                                                            .withTabs(buyerTabs)
                                                            .withAuthentication(auth)
                                                            .withEmailSettings(applicantEmailSetting);
                
                recipientList.add(myRecipient);
                i = i+1;
                j=j+1;
            }
            
            String CRMOpsSub = 'DocuSign Unit # - '+resale.Booking__r.Unit__r.Name+' Booking ID#'+resale.Booking__r.name+' - for Resale# '+resale.Name;
            String CRMOpsBody = docusignCRMTeamEmailBody(resale.name);

            dfsle.Recipient.EmailSettings crmEmailSetting = new dfsle.Recipient.EmailSettings('en','English', CRMOpsSub, CRMOpsBody);
            String crmApproveAnchor = 'crmopsapprove';
            String crmDeclineAnchor = 'crmopsdecline';
            dfsle.Tab crmApproveTab = new dfsle.ApproveTab()
                                                        .withAnchor(new dfsle.Tab.Anchor(
                                                            crmApproveAnchor, // Anchor string
                                                            false, // Do not allow white space in anchor string
                                                            false, // Anchor string is not case sensitive
                                                            'right', // Horizontal alignment in relation to the anchor text
                                                            true, // Ignore if the anchor text is not present in the document
                                                            true, // Must match the value of the anchor string in its entirety
                                                            'pixels', // Unit of the x and y offset properties
                                                            0, // X offset
                                                            5)); // Y offset
            dfsle.Tab crmDeclineTab = new dfsle.DeclineTab()
                                                        .withAnchor(new dfsle.Tab.Anchor(
                                                            crmDeclineAnchor, // Anchor string
                                                            false, // Do not allow white space in anchor string
                                                            false, // Anchor string is not case sensitive
                                                            'right', // Horizontal alignment in relation to the anchor text
                                                            true, // Ignore if the anchor text is not present in the document
                                                            true, // Must match the value of the anchor string in its entirety
                                                            'pixels', // Unit of the x and y offset properties
                                                            0, // X offset
                                                            5)); // Y offset
            dfsle.Recipient crmops = dfsle.Recipient.fromSource(
                                                                'Resale CRM Ops', 
                                                                Label.Resale_DocuSign_CRM_Ops,
                                                                null,
                                                                null,
                                                                null)
                                                            .withTabs(new List<dfsle.Tab> {
                                                                crmApproveTab,crmDeclineTab
                                                            })
                                                            .withEmailSettings(crmEmailSetting);
                                                            
            recipientList.add(crmops);
            emailToRoleMap.put(Label.Resale_DocuSign_CRM_Ops +'_'+i,'Resale CRM Ops');
            i=i+1;
			
            //Authorized Signatory
            String authsub =resale.Booking__r.Unit__r.Name +' - '+resale.Booking__r.Cluster__c+' - Authorized Signatory Email for Resale# '+resale.Name;
            String authbody = docusignAuthEmailBody(resale.name);
            dfsle.Recipient.EmailSettings authEmailSetting = new dfsle.Recipient.EmailSettings('en','English', authsub,authbody);
            
            String authAnchor = 'authsign';
            // Create a Sign Here tab
            dfsle.Tab authTab = new dfsle.SignHereTab()
                                                .withScale(1.0) // 1.0 scale
                                                .withRequired(true) // Signing mandatory
                                                .withAnchor(new dfsle.Tab.Anchor(
                                                    authAnchor, // Anchor string
                                                    false, // Do not allow white space in anchor string
                                                    false, // Anchor string is not case sensitive
                                                    'right', // Horizontal alignment in relation to the anchor text
                                                    true, // Ignore if the anchor text is not present in the document
                                                    true, // Must match the value of the anchor string in its entirety
                                                    'pixels', // Unit of the x and y offset properties
                                                    0, // X offset
                                                    0)); // Y offset 

            dfsle.Recipient authEmail = dfsle.Recipient.fromSource('Authorized Signatory', Label.Resale_Authorized_Signatory, null, null, null).withTabs(new List<dfsle.Tab> {authTab}).withEmailSettings(authEmailSetting);
            recipientList.add(authEmail);
            emailToRoleMap.put(Label.Resale_Authorized_Signatory +'_'+i,'Authorized Signatory');
            i=i+1;
            //Authorized Siganatory Ends
            
             //CRM Document Controller
                    String docContSub = resale.Booking__r.Unit__r.Name +' - '+resale.Booking__r.Cluster__c+' - CRM Controller - '+resale.Name;
                    String docContBody = docusignDocumentControllerEmailBody(resale.name);
                    dfsle.Recipient.EmailSettings docContEmailSetting = new dfsle.Recipient.EmailSettings('en','English',docContSub,docContBody);
                    dfsle.SignHereTab.Stamp docControllerStamp = new dfsle.SignHereTab.Stamp('stamp',null,null,null,null,null,null,null);      
                    dfsle.Tab docControllerStampTab = new dfsle.SignHereTab().withStamp(docControllerStamp)
                                                                            .withScale(1.0) // 1.5 scale
                                                                            .withRequired(true) // Signing mandatory
                                                                            .withAnchor(new dfsle.Tab.Anchor(
                                                                                'resaledocstamp', // Anchor string
                                                                                false, // Do not allow white space in anchor string
                                                                                false, // Anchor string is not case sensitive
                                                                                'right', // Horizontal alignment in relation to the anchor text
                                                                                true, // Ignore if the anchor text is not present in the document
                                                                                true, // Must match the value of the anchor string in its entirety
                                                                                'pixels', // Unit of the x and y offset properties
                                                                                10, // X offset
                                                                                0));// Y offset
                    emailToRoleMap.put(resale.CRM_Document_Controller__r.Email +'_'+i,'Document Controller');
                    i=i+1;
                    dfsle.Recipient docControllerRecipient = dfsle.Recipient.fromSource(
                                                                                resale.CRM_Document_Controller__r.Name,
                                                                                resale.CRM_Document_Controller__r.Email,
                                                                                null, 
                                                                                null,
                                                                                null)
                                                                                .withTabs(new List<dfsle.Tab> {
                                                                                        docControllerStampTab
                                                                                })
                                                                                .withEmailSettings(docContEmailSetting);
                        														
                    recipientList.add(docControllerRecipient);

            //Add the signers...
            myEnvelope = myEnvelope
                            .withRecipients(recipientList);
                            //.withNotifications(expirySettings );

            //Send the Envelope
            if(!Test.isRunningTest()) {
                myEnvelope = dfsle.EnvelopeService.sendEnvelope(
                    myEnvelope,
                    true
                );
               // String envelopeId = String.valueOf(myEnvelope.docuSignId);
               // Booking__c b = new Booking__c(id=mySourceId, SPA_Docusign_Envelope_Id__c=envelopeId);
               // update b;
            }
                String envelopeId = String.valueOf(myEnvelope.docuSignId);
                System.debug('Envelop Id: '+envelopeId);
            
                Docusign_Result__e event = new Docusign_Result__e();
                event.MessageToDisplay__c = 'Resale document successfully sent for Docusign.';
                event.Booking_Id__c = mySourceId;
                event.User_Id__c = UserInfo.getUserId();
                EventBus.publish(event);
            	docusignPostProcessing(envelopeId, mySourceId, myDocumentId, emailToRoleMap, applicantsSize);
            } 
            
        catch (Exception e) 
            {
                Docusign_Result__e event = new Docusign_Result__e();
                event.MessageToDisplay__c = 'Error sending resale document for Docusign - '+e.getMessage();
                event.Booking_Id__c = mySourceId;
                event.User_Id__c = UserInfo.getUserId();
                EventBus.publish(event);
            } 
    }
        public static String docusignSellerEmailBody() {
            return 
            'Dear Customer \n\n'+
				'Greetings from Sobha Realty! \n\n'+
                'We trust this communication finds you well. \n\n'+
                'Attached to this email is the Assignment Agreement for digital signoff via DocuSign, the link for which is valid for seven days from the day of origination of the email. \n\n'+
                'The instructions for signing the document via DocuSign are as below: \n'+
                '<ol>'+
                '<li>Click on Review document and enter the OTP received on your registered mobile number to procced to sign..</li>'+
                '<li>Click on the Start to initiate the signing.</li> '+
                '<li>Draw the Signature and follow the Docusign flow to sign the Document</li>'+
                '<li>Click on Finish once the document is complete.</li></ol>\n'+
                '<ol>'+
                'Best Regards,\n\n'+
                'CRM Team \n'+
                'Sobha Realty</p>\n';
        }

        public static String docusignBuyerEmailBody() {
            return 
            'Dear Customer \n\n'+
				'Greetings from Sobha Realty! \n\n'+
                'We trust this communication finds you well. \n\n'+
                'Attached to this email is the Assignment Agreement for digital signoff via DocuSign, the link for which is valid for seven days from the day of origination of the email. \n\n'+
                'The instructions for signing the document via DocuSign are as below: \n'+
                '<ol>'+
                '<li>Click on Review document and enter the OTP received on your registered mobile number to procced to sign..</li>'+
                '<li>Click on the Start to initiate the signing.</li> '+
                '<li>Draw the Signature and follow the Docusign flow to sign the Document</li>'+
                '<li>Click on Finish once the document is complete.</li></ol>\n'+
                '<ol>'+
                'Best Regards,\n\n'+
                'CRM Team \n'+
                'Sobha Realty</p>\n';
        }
    	public static String docusignAuthEmailBody(String resale)
    	{	
            return 
                'Dear Authorized Signatory \n\n'+
            	'Please find attached the Assignment Agreement signed off by the customer. Please review the same and sign off.\n'+
                'Resale Reference Number  '+resale+'\n'+
            	'\n'+
            	'\n'+
            	'Best Regards,\n\n'+
                'CRM Team \n'+
                'Sobha Realty</p>\n';      
    	}
    public static String docusignCRMTeamEmailBody(String resale)
    	{	
            return 
                'Dear CRM Team \n\n'+
            	'Please find attached the Assignment Agreement signed off by the customer. Please review the same and Approve or Decline.\n'+
            	'Resale Reference Number  '+resale+'\n'+
                '\n'+
            	'\n'+
            	'Best Regards,\n\n'+
                'Sobha Realty</p>\n';      
    	}
    public static String docusignDocumentControllerEmailBody(String resale)
    	{	
            return 
                'Dear CRM Document Controller \n\n'+
            	'Please find the attached Resale Agreement. Please review the same and sign off.\n'+
                'Resale Reference Number  '+resale+'\n'+
            	'\n'+
            	'\n'+
            	'Best Regards,\n\n'+
                'CRM Team \n'+
                'Sobha Realty</p>\n';      
    	}
    Public static void docusignPostProcessing(String envelopeId, Id resaleId, Id myDocumentId, Map<String,String> emailToRoleMap, Integer applicantsSize)
    	{
           // sleep(50);
        
   	    List<dfsle__EnvelopeStatus__c> docusignStatusList = [Select Id,dfsle__DocuSignId__c, Envelope_Type__c, Envelope_Recipient_Type__c, Resale_Process__c From dfsle__EnvelopeStatus__c Where dfsle__DocuSignId__c=:envelopeId];
		System.debug('docusignPostProcessing'+docusignStatusList+'Time is :'+system.now());
        if (docusignStatusList.size() > 0) 
        {
            dfsle__EnvelopeStatus__c ds = docusignStatusList[0];
            ds.Envelope_Type__c = 'Resale process';
            ds.Resale_Process__c  = resaleId;
            update ds; 

            List<dfsle__RecipientStatus__c> rsToUpdateList = new List<dfsle__RecipientStatus__c>();
            List<dfsle__RecipientStatus__c> docusignReceipentStatusList = [Select id,dfsle__RoutingOrder__c,Booking__c,dfsle__Email__c,Envelope_Type__c, Envelope_Recipient_Type__c, Resale_Process__c From dfsle__RecipientStatus__c Where dfsle__EnvelopeStatus__c=:docusignStatusList[0].id];
            Integer i = 1;
            for (dfsle__RecipientStatus__c rs:docusignReceipentStatusList) 
            {
                String drsKey=rs.dfsle__Email__c+'_'+rs.dfsle__RoutingOrder__c;
                if (emailToRoleMap.containsKey(drsKey)) {
                    rs.Resale_Process__c = resaleId;
                    rs.Envelope_Recipient_Type__c = emailToRoleMap.get(drsKey);
                    rs.Envelope_Type__c = 'Resale process';
                    if (i==applicantsSize) {
                        rs.Last_Applicant__c = true;
                    } else {
                        rs.Last_Applicant__c = false;
                    }
                    rsToUpdateList.add(rs);
                }
                i += 1;
            }                                                        
            update rsToUpdateList;
            system.debug(rsToUpdateList);

        } 
    } 
    
 	Private static String validateAndUpdatePhoneNumber(String phoneNumber) 
        {
        	if (!phoneNumber.startsWith('+')) 
        		{
            		phoneNumber = '+'+phoneNumber;
        		}
        	return phoneNumber;
    	}
    
   /* public static void sleep(Integer secs ) {
        datetime myStartDateTime = datetime.now();
        DateTime newDateTime = myStartDateTime.addSeconds(secs);
        while (datetime.now() < newDateTime ) {
            // sleeping here...sort of
        }
        datetime myEndDateTime = datetime.now();
        System.debug('start:  ' + myStartDateTime ) ;
        System.debug('end:  ' + myEndDateTime) ;
    }  */
    
}