force-app/main/default/objects/Applicant_Details__c/Applicant_Details__c.object-meta.xml
<CustomObject>
    <label>Applicant Details</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApplicantDetails</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant_Details__c/fields/Applicant_Number__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Number__c</fullName>
    <label>Applicant Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Applicant</fullName>
            </value>
            <value>
                <fullName>Second Applicant</fullName>
            </value>
            <value>
                <fullName>Third Applicant</fullName>
            </value>
            <value>
                <fullName>Fourth Applicant</fullName>
            </value>
            <value>
                <fullName>Fifth Applicant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Applicant Details</relationshipLabel>
    <relationshipName>ApplicantDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Applicant_Details__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Details</label>
    <referenceTo>Applicant_Details__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <label>Tower</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demand</label>
    <referenceTo>Demand__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Feature_Flag__mdt/Feature_Flag__mdt.object-meta.xml
<CustomObject>
    <description>This is a feature flag to control features at org-level</description>
    <label>Feature Flag</label>
    <pluralLabel>Feature Flags</pluralLabel>
</CustomObject>

force-app/main/default/objects/Feature_Flag__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 5) OR (1 AND 2 AND 3 AND 4) OR (6 AND 2 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Not_Available_for_Sales__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Unit__c.Allocated_SM__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>notEqual</operation>
            <value>Unreleased</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Allocated_SM__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Hold</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demand</label>
    <referenceTo>Demand__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/Xpedeon_Sync_Delegate__c.object-meta.xml
<CustomObject>
    <label>Xpedeon Sync Delegate</label>
    <nameField>
        <displayFormat>XSD-{0000}</displayFormat>
        <label>Xpedeon Sync Delegate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xpedeon Sync Delegates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Applicant_Details__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Details</label>
    <referenceTo>Applicant_Details__c</referenceTo>
    <relationshipLabel>Xpedeon Sync Delegates</relationshipLabel>
    <relationshipName>Xpedeon_Sync_Delegates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demand</label>
    <referenceTo>Demand__c</referenceTo>
    <relationshipLabel>Xpedeon Sync Delegates</relationshipLabel>
    <relationshipName>Xpedeon_Sync_Delegates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Xpedeon Sync Delegates</relationshipLabel>
    <relationshipName>Xpedeon_Sync_Delegates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Manually Synced</fullName>
            </value>
            <value>
                <fullName>Sync in Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Xpedeon Sync Delegates</relationshipLabel>
    <relationshipName>Xpedeon_Sync_Delegates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Xpedeon Sync Delegates</relationshipLabel>
    <relationshipName>Xpedeon_Sync_Delegates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/X_XSD_Util.cls
public class X_XSD_Util {
    
    //DISPATCHERs
    public static void processInit(Map<Id,SObject> oldMap,Map<Id,SObject> newMap){
        try{
            if(Feature_Flag__mdt.getAll().containsKey('XpedeonSyncDelegateCreation') && Feature_Flag__mdt.getInstance('XpedeonSyncDelegateCreation').Active__c){
                process(oldMap,newMap);
            }
        }catch(Exception ex){
            insert new Error_Log__c(Message__c = 'X_XSD_Util Exception : \n\n ex.getMessage() - '+ex.getMessage()+'\n\n ex.getStackTraceString() - '+ex.getStackTraceString()+'\n\n ex.getTypeName() - '+ex.getTypeName());
        }
    }
    
    public static void forceInit(List<Id> targetRecordIds){
        forceInit(new Set<Id>(targetRecordIds));
    }
    
    public static void forceInit(Set<Id> targetRecordIds){
        if(targetRecordIds == NULL || targetRecordIds.isEmpty()) return;
        
        List<Xpedeon_Sync_Delegate__c> xsds = new List<Xpedeon_Sync_Delegate__c>();
        
        for(Id targetRecordId : targetRecordIds){
            if(targetRecordId.getSObjectType() == Tower__c.SObjectType){
                xsds.add(
                    new Xpedeon_Sync_Delegate__c(
                        Tower__c = targetRecordId,
                        Sync_Status__c = 'Ready',
                        Sequence_Number__c = 1
                    )
                );    
            }
            if(targetRecordId.getSObjectType() == Unit__c.SObjectType){
                xsds.add(
                    new Xpedeon_Sync_Delegate__c(
                        Unit__c = targetRecordId,
                        Sync_Status__c = 'Ready',
                        Sequence_Number__c = 2
                    )
                );
            }
            if(targetRecordId.getSObjectType() == Applicant_Details__c.SObjectType){
                xsds.add(
                    new Xpedeon_Sync_Delegate__c(
                        Applicant_Details__c = targetRecordId,
                        Sync_Status__c = 'Ready',
                        Sequence_Number__c = 3
                    )
                );
            }
            if(targetRecordId.getSObjectType() == Demand__c.SObjectType){
                xsds.add(
                    new Xpedeon_Sync_Delegate__c(
                        Demand__c = targetRecordId,
                        Sync_Status__c = 'Ready',
                        Sequence_Number__c = 4
                    )
                );
            }
            /*
            if(targetRecordId.getSObjectType() == Bank_Receipt__c.SObjectType){
                xsds.add(
                    new Xpedeon_Sync_Delegate__c(
                        Bank_Receipt__c = targetRecordId,
                        Sync_Status__c = 'Ready',
                        Sequence_Number__c = 5
                    )
                );
            }
            */
            if(targetRecordId.getSObjectType() == Receipt__c.SObjectType){
                xsds.add(
                    new Xpedeon_Sync_Delegate__c(
                        Receipt__c = targetRecordId,
                        Sync_Status__c = 'Ready',
                        Sequence_Number__c = 6
                    )
                );
            }
        }
        
        Database.insert(xsds,false);
    }
    
    //HANDLERs
    static void process(Map<Id,SObject> oldMap,Map<Id,SObject> newMap){
        if(newMap == NULL || newMap.isEmpty()) return;
        oldMap = oldMap == NULL ? new Map<Id,SObject>() : oldMap;
        
        if(!isAsyncContext()){
            processFuture(JSON.serialize(oldMap),JSON.serialize(newMap));
            return;
        }
        
        States s = new States(oldMap,newMap);
        
        if(s.sObjType == Tower__c.SObjectType){
            towerProcess(s);
        }
        if(s.sObjType == Unit__c.SObjectType){
            unitProcess(s);
        }
        if(s.sObjType == Applicant_Details__c.SObjectType){
            applicantDetailsProcess(s);
        }
        if(s.sObjType == Demand__c.SObjectType){
            demandProcess(s);
        }
        /*if(s.sObjType == Bank_Receipt__c.SObjectType){
            brcProcess(s);
        }*/
        if(s.sObjType == Receipt__c.SObjectType){
            receiptProcess(s);
        }
        
    }
    
    @future
    static void processFuture(String oldMap,String newMap){
        process((Map<Id,SObject>)JSON.deserialize(oldMap,Map<Id,SObject>.class),(Map<Id,SObject>)JSON.deserialize(newMap,Map<Id,SObject>.class));
    }
    
    //WORKERs
    static void towerProcess(States s){
        if(!s.insertOrUpdate) return;
        Map<Id,Tower__c> oldMap = (Map<Id,Tower__c>) s.oldMap;
        Map<Id,Tower__c> newMap = (Map<Id,Tower__c>) s.newMap;
        List<Xpedeon_Sync_Delegate__c> xsds = new List<Xpedeon_Sync_Delegate__c>();
        for(Tower__c t : newMap.values()){
            //if(t.Project__c == 'a0RTX000008zDTv2AM') continue;//blocking Siniya towers capture
            xsds.add(
                new Xpedeon_Sync_Delegate__c(
                    Tower__c = t.Id,
                    Sync_Status__c = 'Ready',
                    Sequence_Number__c = 1
                )
            );
        }
        Database.insert(xsds,false);
    }
    
    static void unitProcess(States s){
        if(!s.insertOrUpdate) return;
        Map<Id,Unit__c> oldMap = (Map<Id,Unit__c>) s.oldMap;
        Map<Id,Unit__c> newMap = (Map<Id,Unit__c>) s.newMap;
        List<Xpedeon_Sync_Delegate__c> xsds = new List<Xpedeon_Sync_Delegate__c>();
        for(Unit__c u : newMap.values()){
            //if(u.Project__c == 'a0RTX000008zDTv2AM') continue;//blocking Siniya units capture
            xsds.add(
                new Xpedeon_Sync_Delegate__c(
                    Unit__c = u.Id,
                    Sync_Status__c = 'Ready',
                    Sequence_Number__c = 2
                )
            );
        }
        Database.insert(xsds,false);        
    }
    
    static void applicantDetailsProcess(States s){
        Map<Id,Applicant_Details__c> oldMap = (Map<Id,Applicant_Details__c>) s.oldMap;
        Map<Id,Applicant_Details__c> newMap = (Map<Id,Applicant_Details__c>) s.newMap;
        List<Xpedeon_Sync_Delegate__c> xsds = new List<Xpedeon_Sync_Delegate__c>();
        for(Applicant_Details__c ad : newMap.values()){
            if(
                (s.insertOrUpdate && ad.Applicant_Number__c == 'Primary Applicant')
                || (!s.insertOrUpdate && ad.Applicant_Number__c == 'Primary Applicant' && oldMap.containsKey(ad.Id) && oldMap.get(ad.Id).Applicant_Number__c != 'Primary Applicant')
            ){
                xsds.add(
                    new Xpedeon_Sync_Delegate__c(
                        Applicant_Details__c = ad.Id,
                        Sync_Status__c = 'Ready',
                        Sequence_Number__c = 3
                    )
                );
            }
        }
        Database.insert(xsds,false);
    }
    
    static void demandProcess(States s){
        if(!s.insertOrUpdate) return;
        
        Map<Id,Demand__c> oldMap = (Map<Id,Demand__c>) s.oldMap;
        Map<Id,Demand__c> newMap = (Map<Id,Demand__c>) s.newMap;
        List<Xpedeon_Sync_Delegate__c> xsds = new List<Xpedeon_Sync_Delegate__c>();
        for(Demand__c d : newMap.values()){
            //if(d.Project__c == 'a0RTX000008zDTv2AM' || d.Booking__C == 'a062o00001vPdWiAAK' || d.Booking__C == 'a067S000003KShUQAW') continue;
            if(d.Booking__C == 'a062o00001vPdWiAAK' || d.Booking__C == 'a067S000003KShUQAW') continue;
            if(String.isNotBlank(X_Utility.getDemandType(d))){
                xsds.add(
                    new Xpedeon_Sync_Delegate__c(
                        Demand__c = d.Id,
                        Sync_Status__c = 'Ready',
                        Sequence_Number__c = 4
                    )
                );
            }
        }
        Database.insert(xsds,false);
    }
    
    /*
    static void brcProcess(States s){
        if(!s.insertOrUpdate) return;
        
        Map<Id,Bank_Receipt__c> oldMap = (Map<Id,Bank_Receipt__c>) s.oldMap;
        Map<Id,Bank_Receipt__c> newMap = (Map<Id,Bank_Receipt__c>) s.newMap;
        List<Xpedeon_Sync_Delegate__c> xsds = new List<Xpedeon_Sync_Delegate__c>();
        for(Bank_Receipt__c brc : newMap.values()){
            xsds.add(
                new Xpedeon_Sync_Delegate__c(
                    Bank_Receipt__c = brc.Id,
                    Sync_Status__c = 'Ready',
                    Sequence_Number__c = 5
                )
            );
        }
        Database.insert(xsds,false);
    }
    */
    
    static void receiptProcess(States s){
        
        Map<Id,Receipt__c> oldMap = (Map<Id,Receipt__c>) s.oldMap;
        Map<Id,Receipt__c> newMap = (Map<Id,Receipt__c>) s.newMap;
        
        Set<Id> receiptIdsWithExistingXsds = new Set<Id>();
        for(Xpedeon_Sync_Delegate__c existingXsd : [SELECT Receipt__c FROM Xpedeon_Sync_Delegate__c WHERE Receipt__c IN :newMap.keySet()]){
            receiptIdsWithExistingXsds.add(existingXsd.Receipt__c);
        }
        
        List<Xpedeon_Sync_Delegate__c> xsds = new List<Xpedeon_Sync_Delegate__c>();
        for(Receipt__c newR : newMap.values()){
            
            if(receiptIdsWithExistingXsds.contains(newR.Id) || String.isBlank(newR.Payment_Request__c)) continue;
            Boolean isEligible = false;
            
            if(newR.Mode__c == 'Cash' || newR.Mode__c == 'Credit Note'){
                isEligible = false;
            }else if(s.insertOrUpdate){
                isEligible = newR.Receipt_Status__c == 'Cleared';
            }else{
                isEligible = newR.Receipt_Status__c == 'Cleared' && oldMap.containsKey(newR.Id) && oldMap.get(newR.Id).Receipt_Status__c != 'Cleared';
            }
            
            if(isEligible){
                xsds.add(
                    new Xpedeon_Sync_Delegate__c(
                        Receipt__c = newR.Id,
                        Sync_Status__c = 'Ready',
                        Sequence_Number__c = 6
                    )
                );
            }
        }
        Database.insert(xsds,false);
    }
    
    //WRAPPERs
    class States{
        SObjectType sObjType;
        Boolean insertOrUpdate;
        Map<Id,SObject> oldMap;
        Map<Id,Sobject> newMap;
        
        States(Map<Id,SObject> oldMap,Map<Id,SObject> newMap){
            this.insertOrUpdate = (oldMap == NULL || oldMap.isEmpty());
            this.sObjType = newMap.values()[0].Id.getSObjectType();
            
            typeCastMaps(oldMap,newMap);
        }
        
        void typeCastMaps(Map<Id,SObject> oldMap,Map<Id,SObject> newMap){
            
            if(this.sObjType == Tower__c.SobjectType){//Tower
                this.oldMap = new Map<Id,Tower__c>();
                for(sObject s : oldMap.values()) this.oldMap.put(s.Id,(Tower__c) s);
                this.newMap = new Map<Id,Tower__c>();
                for(sObject s : newMap.values()) this.newMap.put(s.Id,(Tower__c) s);
            }
            if(this.sObjType == Unit__c.SobjectType){//Unit
                this.oldMap = new Map<Id,Unit__c>();
                for(sObject s : oldMap.values()) this.oldMap.put(s.Id,(Unit__c) s);
                this.newMap = new Map<Id,Unit__c>();
                for(sObject s : newMap.values()) this.newMap.put(s.Id,(Unit__c) s);
            }
            if(this.sObjType == Applicant_Details__c.SobjectType){//Applicant Details
                this.oldMap = new Map<Id,Applicant_Details__c>();
                for(sObject s : oldMap.values()) this.oldMap.put(s.Id,(Applicant_Details__c) s);
                this.newMap = new Map<Id,Applicant_Details__c>();
                for(sObject s : newMap.values()) this.newMap.put(s.Id,(Applicant_Details__c) s);
            }
            if(this.sObjType == Demand__c.SobjectType){//Demand
                this.oldMap = new Map<Id,Demand__c>();
                for(sObject s : oldMap.values()) this.oldMap.put(s.Id,(Demand__c) s);
                this.newMap = new Map<Id,Demand__c>();
                for(sObject s : newMap.values()) this.newMap.put(s.Id,(Demand__c) s);
            }
            /*
            if(this.sObjType == Bank_Receipt__c.SobjectType){//Bank Receipt
                this.oldMap = new Map<Id,Bank_Receipt__c>();
                for(sObject s : oldMap.values()) this.oldMap.put(s.Id,(Bank_Receipt__c) s);
                this.newMap = new Map<Id,Bank_Receipt__c>();
                for(sObject s : newMap.values()) this.newMap.put(s.Id,(Bank_Receipt__c) s);
            }
            */
            if(this.sObjType == Receipt__c.SobjectType){//Receipt
                this.oldMap = new Map<Id,Receipt__c>();
                for(sObject s : oldMap.values()) this.oldMap.put(s.Id,(Receipt__c) s);
                this.newMap = new Map<Id,Receipt__c>();
                for(sObject s : newMap.values()) this.newMap.put(s.Id,(Receipt__c) s);
            }
        }
    }
    
    //HELPERs
    static Boolean isAsyncContext(){
        return System.isFuture() || System.isScheduled() || System.isQueueable() || System.isBatch();
    }
}