force-app/main/default/objects/Applicant_Details__c/Applicant_Details__c.object-meta.xml
<CustomObject>
    <label>Applicant Details</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApplicantDetails</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant_Details__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Applicant Details</relationshipLabel>
    <relationshipName>ApplicantDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 5) OR (1 AND 2 AND 3 AND 4) OR (6 AND 2 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Not_Available_for_Sales__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Unit__c.Allocated_SM__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>notEqual</operation>
            <value>Unreleased</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Allocated_SM__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Hold</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demand</label>
    <referenceTo>Demand__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/Xpedeon_Sync_Delegate__c.object-meta.xml
<CustomObject>
    <label>Xpedeon Sync Delegate</label>
    <nameField>
        <displayFormat>XSD-{0000}</displayFormat>
        <label>Xpedeon Sync Delegate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Xpedeon Sync Delegates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Applicant_Details__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Details</label>
    <referenceTo>Applicant_Details__c</referenceTo>
    <relationshipLabel>Xpedeon Sync Delegates</relationshipLabel>
    <relationshipName>Xpedeon_Sync_Delegates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demand</label>
    <referenceTo>Demand__c</referenceTo>
    <relationshipLabel>Xpedeon Sync Delegates</relationshipLabel>
    <relationshipName>Xpedeon_Sync_Delegates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Xpedeon Sync Delegates</relationshipLabel>
    <relationshipName>Xpedeon_Sync_Delegates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Xpedeon Sync Delegates</relationshipLabel>
    <relationshipName>Xpedeon_Sync_Delegates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Sequence_Number__c</fullName>
    <label>Sequence Number</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Sync_Status__c.field-meta.xml
<CustomField>
    <fullName>Sync_Status__c</fullName>
    <label>Sync Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Manually Synced</fullName>
            </value>
            <value>
                <fullName>Sync in Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Xpedeon Sync Delegates</relationshipLabel>
    <relationshipName>Xpedeon_Sync_Delegates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Sync_Delegate__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Xpedeon Sync Delegates</relationshipLabel>
    <relationshipName>Xpedeon_Sync_Delegates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/X_SyncBatch.cls
public class X_SyncBatch implements Database.Batchable<SObject>,Database.AllowsCallouts{
    
    static final List<String> STATUS_FOR_SYNC_FILTER = new List<String>{'Ready','Failed','Sync in Progress'};
    
    List<Id> xsdIds;
    Set<Integer> sequenceNumbers;
    
    public X_SyncBatch(){}
    
    public X_SyncBatch(List<Integer> sequenceNumbers){
        this.sequenceNumbers = new Set<Integer>(sequenceNumbers);
    }
    
    public X_SyncBatch(Set<Integer> sequenceNumbers){
        this.sequenceNumbers = sequenceNumbers;
    }
    
    public X_SyncBatch(Set<Id> xsdIds){
        this.xsdIds = new List<Id>(xsdIds);
    }
    
    public X_SyncBatch(List<Id> xsdIds){
        this.xsdIds = xsdIds;
    }
    
    public Database.QueryLocator start(Database.BatchableContext dBC){
        if(this.xsdIds != NULL){
            return Database.getQueryLocator([SELECT id,Name,Sync_Status__c,Sequence_Number__c,Tower__c,Unit__c,Applicant_Details__c,Demand__c,Payment_Request__c,Receipt__c FROM Xpedeon_Sync_Delegate__c WHERE Id IN :this.xsdIds AND Sync_Status__c IN :STATUS_FOR_SYNC_FILTER ORDER BY CreatedDate ASC,Sequence_Number__c ASC]);
        }else if(this.sequenceNumbers != NULL){
            return Database.getQueryLocator([SELECT id,Name,Sync_Status__c,Sequence_Number__c,Tower__c,Unit__c,Applicant_Details__c,Demand__c,Payment_Request__c,Receipt__c FROM Xpedeon_Sync_Delegate__c WHERE Sequence_Number__c IN :this.sequenceNumbers AND  Sync_Status__c IN :STATUS_FOR_SYNC_FILTER ORDER BY CreatedDate ASC,Sequence_Number__c ASC]);
        }else{
        	return Database.getQueryLocator([SELECT id,Name,Sync_Status__c,Sequence_Number__c,Tower__c,Unit__c,Applicant_Details__c,Demand__c,Payment_Request__c,Receipt__c FROM Xpedeon_Sync_Delegate__c WHERE  Sync_Status__c IN :STATUS_FOR_SYNC_FILTER ORDER BY CreatedDate ASC,Sequence_Number__c ASC]);
        }
    }
    
    public void execute(Database.BatchableContext dBC,List<Xpedeon_Sync_Delegate__c> xsds){
        for(Xpedeon_Sync_Delegate__c xsd : xsds){
            
            
            //Id sourceRecordId = String.isNotBlank(xsd.Tower__c) ? xsd.Tower__c : String.isNotBlank(xsd.Unit__c) ? xsd.Unit__c : String.isNotBlank(xsd.Applicant_Details__c) ? xsd.Applicant_Details__c : String.isNotBlank(xsd.Demand__c) ? xsd.Demand__c : String.isNotBlank(xsd.Payment_Request__c) ? xsd.Payment_Request__c : String.isNotBlank(xsd.Receipt__c) ? xsd.Receipt__c : NULL;
            Id sourceRecordId;
            if(String.isNotBlank(xsd.Tower__c)){
                sourceRecordId = xsd.Tower__c;
            }else if(String.isNotBlank(xsd.Unit__c)){
                sourceRecordId = xsd.Unit__c;
            }else if(String.isNotBlank(xsd.Applicant_Details__c)){
                sourceRecordId = xsd.Applicant_Details__c;
            }else if(String.isNotBlank(xsd.Demand__c)){
                sourceRecordId = xsd.Demand__c;
            }else if(String.isNotBlank(xsd.Payment_Request__c)){
                sourceRecordId = xsd.Payment_Request__c;
            }else if(String.isNotBlank(xsd.Receipt__c)){
                sourceRecordId = xsd.Receipt__c;
            }
            
            if(String.isBlank(sourceRecordId)) continue;
            X_Service service = new X_Service(new X_Service.X_APIData(sourceRecordId,'POST',xsd.Id)); 
            X_Service.SyncResult sr = service.sync();
            xsd.Sync_Status__c = sr.success != NULL && sr.success ? 'Synced' : 'Failed';
            if(xsd.Sync_Status__c == 'Failed'){
                xsd.Remarks__c = truncateToFieldSize(xsd.Sync_Status__c+' : '+sr.httpResponseBody,Xpedeon_Sync_Delegate__c.fields.Remarks__c.getDescribe().getLength());
            }
            
        }
        update xsds;
    }
    
    public void finish(Database.BatchableContext dBC){
        
    }

    //UTILITIES
    static String truncateToFieldSize(String str,Integer lengthLimit){
        return String.isNotBlank(str) && str.length() > lengthLimit ? str.substring(0,lengthLimit) : str;
    }
}