force-app/main/default/objects/Applicant_Details__c/Applicant_Details__c.object-meta.xml
<CustomObject>
    <label>Applicant Details</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApplicantDetails</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant_Details__c/fields/Applicant_Number__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Number__c</fullName>
    <label>Applicant Number</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary Applicant</fullName>
            </value>
            <value>
                <fullName>Second Applicant</fullName>
            </value>
            <value>
                <fullName>Third Applicant</fullName>
            </value>
            <value>
                <fullName>Fourth Applicant</fullName>
            </value>
            <value>
                <fullName>Fifth Applicant</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>ApplicantDetails</relationshipLabel>
    <relationshipName>ApplicantDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Applicant Details</relationshipLabel>
    <relationshipName>ApplicantDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Applicant_Details__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Details</label>
    <referenceTo>Applicant_Details__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/BCC_Notice_Sent__c.field-meta.xml
<CustomField>
    <fullName>BCC_Notice_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BCC Notice Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Booking_Approver_Audit__c.field-meta.xml
<CustomField>
    <fullName>Booking_Approver_Audit__c</fullName>
    <label>Audit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted to Audit</fullName>
            </value>
            <value>
                <fullName>Document Verification Not Started</fullName>
            </value>
            <value>
                <fullName>Document Verification Accepted</fullName>
            </value>
            <value>
                <fullName>Document Verification Rejected</fullName>
            </value>
            <value>
                <fullName>Audit Accepted</fullName>
            </value>
            <value>
                <fullName>Audit Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Pre_registration__c.field-meta.xml
<CustomField>
    <fullName>Pre_registration__c</fullName>
    <label>Pre-registration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
                <default>true</default>
                <label>Not Initiated</label>
            </value>
            <value>
                <fullName>Request to Initiate Pre-Registration</fullName>
            </value>
            <value>
                <fullName>Additional Docs required</fullName>
            </value>
            <value>
                <fullName>Customer Docs Required</fullName>
            </value>
            <value>
                <fullName>Under Process - Paid</fullName>
            </value>
            <value>
                <fullName>Submitted To DLD</fullName>
            </value>
            <value>
                <fullName>With Audit</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Email__c</fullName>
    <label>Primary Applicant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name__c</fullName>
    <label>Primary Applicant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/SPA_Executed__c.field-meta.xml
<CustomField>
    <fullName>SPA_Executed__c</fullName>
    <label>SPA Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Blocked Sales</fullName>
                <default>true</default>
                <label>Blocked Sales</label>
            </value>
            <value>
                <fullName>To be Issued</fullName>
            </value>
            <value>
                <fullName>SPA Issued But Not Sent</fullName>
            </value>
            <value>
                <fullName>SPA Sent But Not Returned</fullName>
            </value>
            <value>
                <fullName>SPA Received and sent to Audit for Review</fullName>
                <label>SPA Received and sent to CRM OPS Assurance for Review</label>
            </value>
            <value>
                <fullName>SPA Executed</fullName>
            </value>
            <value>
                <fullName>SPA Particulars Received</fullName>
            </value>
            <value>
                <fullName>Revised SPA Particular Sent</fullName>
            </value>
            <value>
                <fullName>Revised SPA Particular Received - SPA Copy Pending</fullName>
            </value>
            <value>
                <fullName>SPA Issued But Not Sent  - Customer to Collect</fullName>
                <label>SPA Issued But Not Sent - Customer to Collect</label>
            </value>
            <value>
                <fullName>SPA Sent through DocuSign</fullName>
            </value>
            <value>
                <fullName>Executed copy sent through DocuSign</fullName>
            </value>
            <value>
                <fullName>Audit Review completed</fullName>
                <label>CRM OPS Assurance Review completed</label>
            </value>
            <value>
                <fullName>SPA Signed by Seller</fullName>
            </value>
            <value>
                <fullName>SPA is Voided in Docusign</fullName>
            </value>
            <value>
                <fullName>Audit rejected</fullName>
                <label>CRM OPS Assurance rejected</label>
            </value>
            <value>
                <fullName>Issue ? Under discussion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>Booking In Process</fullName>
            </value>
            <value>
                <fullName>Cancellation In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Title_Transfer_Completed__c.field-meta.xml
<CustomField>
    <fullName>Title_Transfer_Completed__c</fullName>
    <label>Title Transfer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Initiated</fullName>
                <default>true</default>
                <label>Not Initiated</label>
            </value>
            <value>
                <fullName>Additional Docs Required</fullName>
            </value>
            <value>
                <fullName>Under Process</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>DSR Received from Customer</fullName>
            </value>
            <value>
                <fullName>DSR Pending with Customer</fullName>
            </value>
            <value>
                <fullName>Sent for accounts/Audit review</fullName>
            </value>
            <value>
                <fullName>Sent for Authorized signatory</fullName>
            </value>
            <value>
                <fullName>Request to initiate Title transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mobile_App__mdt/Mobile_App__mdt.object-meta.xml
<CustomObject>
    <label>Mobile App</label>
    <pluralLabel>Mobile App</pluralLabel>
</CustomObject>

force-app/main/default/objects/Time_Slot_For_Handover__c/Time_Slot_For_Handover__c.object-meta.xml
<CustomObject>
    <label>Time Slot For Handover</label>
    <nameField>
        <displayFormat>HO - {0000}</displayFormat>
        <label>Time Slot For  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slot For Handover</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Time Slot For Handover</relationshipLabel>
    <relationshipName>Time_Slot_For_Handover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/Primary_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name__c</fullName>
    <formula>Booking__r.Primary_Applicant_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Primary Applicant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Unable to contact</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>At the time of Handover</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Planned</fullName>
                <isActive>false</isActive>
                <label>Planned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/recordTypes/HandOver.recordType-meta.xml
<RecordType>
    <fullName>HandOver</fullName>
    <active>true</active>
    <label>HandOver</label>
</RecordType>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Time_Slot_For_Handover__c.field-meta.xml
<CustomField>
    <fullName>Time_Slot_For_Handover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Time Slot For Handover</label>
    <referenceTo>Time_Slot_For_Handover__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BookingTriggerHandler.cls
public class BookingTriggerHandler {
    
    @future(callOut=true)
    Public static void sendToMobileAPI(string newBookingString, string oldBookingString,boolean isInsert){
        Mobile_App__mdt mobile_appmdt = Mobile_App__mdt.getInstance('Mobile_Link');
        String endpoint = mobile_appmdt.End_Point__c;
        String endPointURL = endpoint+'/srprosalesforce/v1/salesforce/bookings';
        string methodType = 'POST';
        list<Booking__c> newList = (list<Booking__c>)JSON.deserialize(newBookingString, list<Booking__c>.Class);
        String errorMessage = '';
        String requestString = '';
        string response = '';
        Integer statusCode;
        String bookingId = '';
        requestBodyWrapper wrap;
        boolean spaExecuted = false;
        boolean spaExecuteddocSign = false;
        String notificationStatus = '';
        Map<Id,Id> unitWithBookingMap = new Map<Id,Id>();
        Map<Id,requestBodyWrapper> wrapMap =  new Map<Id,requestBodyWrapper>();
        List<requestBodyWrapper> wraplst = new List<requestBodyWrapper>();
        Boolean sendAlert = false;
        Boolean sendmessage = false;
        Boolean isApplicantBlank = false;
        try{
            for(Booking__c bk :newList){
                unitWithBookingMap.put(bk.Unit__c, bk.Id);
                wrap = new requestBodyWrapper();
                if(oldBookingString != null){
                    Map<Id,Booking__c> oldMap = (Map<Id,Booking__c>)JSON.deserialize(oldBookingString, Map<Id,Booking__c>.Class);
                    wrap.bookingID = bk.Id;
                    wrap.bookingName = bk.Name;
                    wrap.bookingStatus = bk.Status__c != null ? bk.Status__c : String.ValueOf(oldMap.get(bk.Id).Status__c);
                    wrap.customerName = bk.Primary_Applicant_Name__c != null ? bk.Primary_Applicant_Name__c : String.ValueOf(oldMap.get(bk.Id).Primary_Applicant_Name__c);
                    wrap.customerEmail = bk.Primary_Applicant_Email__c != null ? bk.Primary_Applicant_Email__c : String.ValueOf(oldMap.get(bk.Id).Primary_Applicant_Email__c);
                    wrap.handoverDate = bk.Handover_Date__c != null ? bk.Handover_Date__c : oldMap.get(bk.Id).Handover_Date__c;
                    wrap.sfUnitId = bk.Unit__c;
                    
                    if(bk.SPA_Executed__c != oldMap.get(bk.Id).SPA_Executed__c){
                        
                        if(bk.SPA_Executed__c == 'SPA Sent through Docusign'){ 
                            sendAlert = true;
                            notificationStatus = 'SPA_readiness_customer_signature';
                        }else if (bk.SPA_Executed__c == 'SPA Executed'){ 
                            sendAlert = true;
                            notificationStatus = 'completion_SPA_approval';
                        }
                    }
                    if(bk.Current_Status__c != oldMap.get(bk.Id).Current_Status__c && bk.Current_Status__c == 'Sent to Client'){
                        notificationStatus = 'booking_form_readiness_for_the_customer_signature';
                        sendAlert = true;
                    }
                    if(bk.Booking_Approver_Audit__c != oldMap.get(bk.Id).Booking_Approver_Audit__c && bk.Booking_Approver_Audit__c == 'Accepted'){
                        notificationStatus = 'completion_booking_approval';
                        sendmessage = true;
                    }
                    if(bk.Pre_registration__c != oldMap.get(bk.Id).Pre_registration__c && bk.Pre_registration__c == 'Completed'){
                        notificationStatus = 'document_available_user_after_final_approval';
                        sendmessage = true;
                    }
                    if(bk.Status__c != oldMap.get(bk.Id).Status__c && bk.Status__c == 'Cancelled'){
                        notificationStatus = 'rejection_booking_form_approval';
                        sendAlert = true;
                    }
                    if(bk.BCC_Notice_Sent__c != oldMap.get(bk.Id).BCC_Notice_Sent__c && bk.BCC_Notice_Sent__c == True){
                        notificationStatus = 'building_completion_certificate_document';
                        sendmessage = true;
                    }
                    if(bk.Title_Transfer_Completed__c != oldMap.get(bk.Id).Title_Transfer_Completed__c && bk.Title_Transfer_Completed__c == 'Completed'){
                        notificationStatus = 'readiness_title_deed';
                        sendmessage = true;
                    }
                    
                }else{
                    
                    if(bk.Id != null){
                        wrap.bookingID = bk.Id;
                    }
                    if(bk.name != null){
                        wrap.bookingName = bk.name;
                    }
                    if(bk.Status__c != null){
                        wrap.bookingStatus = bk.Status__c;
                    }
                    if(bk.Primary_Applicant_Name__c != null){
                        wrap.customerName = bk.Primary_Applicant_Name__c;
                    }
                    if(bk.Primary_Applicant_Email__c != null){
                        wrap.customerEmail = bk.Primary_Applicant_Email__c;
                    }
                    else{
                        isApplicantBlank = true;
                    }
                    if(bk.Handover_Date__c != null){
                        wrap.handoverDate = bk.Handover_Date__c;
                    }
                    wrap.actualHandoverDate = null; 
                    if(bk.Unit__c != null){
                        wrap.sfUnitId = bk.Unit__c;
                    }
                }
                wrapMap.put(bk.Id,wrap);
            }
            if(unitWithBookingMap.size() > 0){
                for(Unit__c unitinfo : [select Id, DLP_End_Date__c from Unit__c where id IN :unitWithBookingMap.keySet()]){
                    wrapMap.get(unitWithBookingMap.get(unitinfo.Id)).dlpDate = unitinfo.DLP_End_Date__c != null ? unitinfo.DLP_End_Date__c : null;
                }
                for(Time_Slot_For_Handover__c timeslot : [select Scheduled_Date__c,Booking__c from Time_Slot_For_Handover__c where Booking__c IN :unitWithBookingMap.values() and Status__c = 'Completed' AND RecordType.Name='HandOver']){
                    wrapMap.get(timeslot.Booking__c).actualHandoverDate = timeslot.Scheduled_Date__c != null ? timeslot.Scheduled_Date__c : null;
                }
                if(isApplicantBlank){
                    for(Applicant_Details__c applicantRec : [select id, Name, Booking__c,Email_Address__c from Applicant_Details__c  where Booking__r.id IN :unitWithBookingMap.values() and Applicant_Number__c = 'Primary Applicant']){
                        wrapMap.get(applicantRec.Booking__c).customerEmail = applicantRec.Email_Address__c;
                        wrapMap.get(applicantRec.Booking__c).customerName = applicantRec.Name;
                    }
                }
                for(Id bkgId : wrapMap.keySet()){
                    wraplst.add(wrapMap.get(bkgId));
                }
            }         
            if(wraplst != null){
                String userResponse=null;
                response = callbookingAPI(wraplst, isInsert, sendAlert, sendmessage, notificationStatus);
                
            }
        }catch(Exception e){
            errorMessage = e.getMessage();
            statusCode = 400;
            
        }
        
    }
    
    public static String callbookingAPI(List<requestBodyWrapper> wraplst, Boolean isInsert, Boolean sendAlert, Boolean sendmessage, String notificationStatus){
        String response = '';
        Mobile_App__mdt mobile_appmdt = Mobile_App__mdt.getInstance('Mobile_Link');
        String endpoint = mobile_appmdt.End_Point__c;
        String endPointURL = endpoint+'/srprosalesforce/v1/salesforce/bookings';
        string methodType = 'POST';
        // code added by Roshan
        if(wraplst[0].customerEmail==null && wraplst[0].customerName==null)
        {
            return null;
        }
        //end 
        response = MobileIntegrationCallOutsAPI.callMobileApp(endPointURL,methodType,JSON.serialize(wraplst[0]));
        
        if(response != null && response != '' && isInsert){ 
            ID jobID = System.enqueueJob(new MobileAppQueuable(new List<String>{wraplst[0].bookingID},wraplst[0].customerEmail,'unit_booking_confirmation','message'));
        }else if(response != null && sendAlert){ 
            ID jobID = System.enqueueJob(new MobileAppQueuable(new List<String>{wraplst[0].bookingID},wraplst[0].customerEmail,notificationStatus,'alert'));
        }
        else if(response != null && sendmessage){
            ID jobID = System.enqueueJob(new MobileAppQueuable(new List<String>{wraplst[0].bookingID},wraplst[0].customerEmail,notificationStatus,'message'));
        }
        return response;
    }
    
    
    public class requestBodyWrapper{
        String bookingID;
        String bookingStatus;
        String bookingName;
        String customerName;
        String customerEmail;
        Date handoverDate;
        Date actualHandoverDate;
        String sfUnitId;
        Date dlpDate;
    }
    
}