force-app/main/default/objects/Applicant_Details__c/Applicant_Details__c.object-meta.xml
<CustomObject>
    <label>Applicant Details</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApplicantDetails</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant_Details__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>ApplicantDetails</relationshipLabel>
    <relationshipName>ApplicantDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking Applicant Details</relationshipLabel>
    <relationshipName>ApplicantDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Applicant Details</relationshipLabel>
    <relationshipName>ApplicantDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/BCC_Notice_Sent__c.field-meta.xml
<CustomField>
    <fullName>BCC_Notice_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BCC Notice Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Sub Project</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Due_Payments__c.field-meta.xml
<CustomField>
    <fullName>Due_Payments__c</fullName>
    <formula>IF( Milestone_Due_Till_Date__c &gt;= Total_On_Account_Money_With_Registration__c , 
(Milestone_Due_Till_Date__c -  Total_On_Account_Money_With_Registration__c), 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due Payments</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <formula>Opportunity__r.Lead_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Paid_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Paid_Percentage__c</fullName>
    <formula>If(Agreement_Value__c &gt; 0 &amp;&amp; Total_On_Account_Money__c &gt; 0,
(Total_On_Account_Money_With_Registration__c)/(Agreement_Value__c + Tax_on_Purchase_Price__c),
0)</formula>
    <label>Paid Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/PCC_Approved_By_Audit__c.field-meta.xml
<CustomField>
    <fullName>PCC_Approved_By_Audit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PCC Approved By Audit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <label>Tower</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Related_Document__c/Customer_Related_Document__c.object-meta.xml
<CustomObject>
    <description>This object is used to store the documents and their related document Ids in order to map the correct documents in the system</description>
    <label>Customer Related Document</label>
    <nameField>
        <displayFormat>CRD-{000000}</displayFormat>
        <label>Customer Related Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Related Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Related_Document__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Customer Related Documents</relationshipLabel>
    <relationshipName>Customer_Related_Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <label>Lead Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <label>Lead Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SH-{000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Sold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/Time_Slot_For_Handover__c.object-meta.xml
<CustomObject>
    <label>Time Slot For Handover</label>
    <nameField>
        <displayFormat>HO - {0000}</displayFormat>
        <label>Time Slot For  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slot For Handover</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Time Slot For Handover</relationshipLabel>
    <relationshipName>Time_Slot_For_Handover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/Paid_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Paid_Percentage__c</fullName>
    <formula>Booking__r.Paid_Percentage__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Paid Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <formula>Booking__r.Tower_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tower</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/recordTypes/HandOver.recordType-meta.xml
<RecordType>
    <fullName>HandOver</fullName>
    <active>true</active>
    <label>HandOver</label>
</RecordType>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Mobile_getBookingJourney.cls
@RestResource(urlMapping = '/getBookingJourney')
global class Mobile_getBookingJourney {

    @HttpPost
    global static void getBookingJourney(String bookingId){ 
        RestResponse res = RestContext.response; 
        String responseString = '';
        String errorMessage = '';
        try{ 
            ResponseBodyWrapper bookingJourneyWrapper = new ResponseBodyWrapper();
            List<Milestones> milestoneWrapper = new List<Milestones>();
            List<Mobile_getPaymentPlan.responseBodyWrapper> paymentBreakupList = new List<Mobile_getPaymentPlan.responseBodyWrapper>();
            if(bookingId != null && String.isNotBlank(bookingId)){
                List<Booking__c> bklst = [select id, Quotation__c, name,unit__r.name,unit__r.tower__r.name,unit__r.tower__r.Cluster__r.name,unit__r.Project__r.Name,Opportunity__r.Lead_Id__c,Due_Payments__c,BCC_Notice_Sent__c,PCC_Approved_By_Audit__c,Paid_Percentage__c,Current_Status__c,
                                       Opportunity__r.CreatedDate,Status__c,createddate,SPA_Executed_Date__c,SPA_Executed__c,SPA_Sent_Date__c,Date_of_Pre_registration_Completion__c,Pre_registration__c,Title_Transfer_Completed__c,(select id, name,Registration_Collection_Control_Report__c from Receipts__r)  
                                       from Booking__c where id =:bookingId ];
                //new add for getting applicant details
                List<Applicant_Details__c> applicantlst = [select id, Name from Applicant_Details__c  where Booking__r.id =:bookingId];
                String appNames=''; 
                if(applicantlst.size() > 0){
                    for(Applicant_Details__c applicant : applicantlst ){
                        appNames += applicant.Name + '|'; 
                    }
                    appNames = appNames.removeEnd('|');
                }

                // Title_Transfer_Date__c no field in QA but there is PROD
                if(bklst.size() > 0){
                    Map<String,String> customerDocWithId = getCustomerDocumentMap('Booking__c', bookingId);
                    Booking__c bookingRec = bklst[0];
                    UnitDetails  uwrap = new UnitDetails();
                    uwrap.bookingNumber = bookingRec.Name;
                    uwrap.unitNumber = bookingRec.unit__r.name;
                    uwrap.unitid = bookingRec.unit__r.Id;
                    uwrap.towerName = bookingRec.unit__r.tower__r.name;
                    uwrap.communityName = bookingRec.unit__r.tower__r.Cluster__r.name;
                    uwrap.masterCommunityName = bookingRec.unit__r.Project__r.Name;
                    uwrap.dueAmount = bookingRec.Due_Payments__c;
                    uwrap.applicantNames = appNames;
                    bookingJourneyWrapper.unitDetails = uwrap;   

                 /*   Milestones leadMilestone = new Milestones();
                    leadMilestone.heading = 'Lead';
                    leadMilestone.order = '1';
                    leadMilestone.currentStatus = 'Completed';
                    leadMilestone.statusDate = date.newinstance(bookingRec.Opportunity__r.createddate.year(), bookingRec.Opportunity__r.createddate.month(), bookingRec.Opportunity__r.createddate.day());
                    leadMilestone.documentLink = null;
                    milestoneWrapper.add(leadMilestone);*/

                    Milestones bookingForm = new Milestones();
                    bookingForm.heading = 'Booking Form';
                    bookingForm.order = '2';
                    bookingForm.currentStatus = (bookingRec.Current_Status__c == 'Audit Accepted' && bookingRec.Status__c != 'Cancelled') ? 'Completed' : bookingRec.Status__c == 'Cancelled' ? 'Cancelled' : 'In Progress' ;
                    bookingForm.statusDate = date.newinstance(bookingRec.createddate.year(), bookingRec.createddate.month(), bookingRec.createddate.day());
                    bookingForm.documentLink = customerDocWithId.size() > 0 && customerDocWithId.containsKey('Booking Form') ? customerDocWithId.get('Booking Form') : null;
                    bookingForm.actionLink = null;
                    milestoneWrapper.add(bookingForm);
	
                    Milestones spaDocument = new Milestones(); 
                    spaDocument.heading = 'Sales & Purchase Agreement (SPA)';
                    spaDocument.order = '3';
                    spaDocument.currentStatus = bookingRec.SPA_Executed__c == 'Blocked Sales' || bookingRec.SPA_Executed__c == 'Revised SPA Particular Received - SPA Copy pending.' || bookingRec.SPA_Executed__c == 'SPA Issued But Not Sent' || bookingRec.SPA_Executed__c == 'SPA - issued but not sent to dispatch.' || bookingRec.SPA_Executed__c == 'SPA is Voided in Docusign' || bookingRec.SPA_Executed__c == 'Audit Rejected' || bookingRec.SPA_Executed__c == 'To Be Issued'? null : bookingRec.SPA_Executed__c == 'SPA Executed' || bookingRec.SPA_Executed__c == 'Executed copy send through DocuSign' ? 'Completed' : 'In Progress'; 
                    //spaDocument.statusDate = spaDocument.currentStatus == 'Completed' ? bookingRec.SPA_Executed_Date__c : bookingRec.SPA_Sent_Date__c != null ? bookingRec.SPA_Sent_Date__c : null;
                    spaDocument.statusDate = spaDocument.currentStatus == 'Completed' ? null : bookingRec.SPA_Sent_Date__c != null ? bookingRec.SPA_Sent_Date__c : null;
                    spaDocument.documentLink = customerDocWithId.size() > 0 && customerDocWithId.containsKey('SPA') ? customerDocWithId.get('SPA') : null;
                    spaDocument.actionLink = null;
                    milestoneWrapper.add(spaDocument);

                    Milestones oqood = new Milestones();
                    oqood.heading = 'OQOOD Registration';
                    oqood.order = '4';
                    oqood.currentStatus = bookingRec.Pre_registration__c == 'Not Initiated' || bookingRec.Pre_registration__c == 'Additional Docs required' || bookingRec.Pre_registration__c == null ? null : bookingRec.Pre_registration__c == 'Completed' ? 'Completed' : 'In Progress';
                    oqood.statusDate = bookingRec.Date_of_Pre_registration_Completion__c != null ? date.newinstance(bookingRec.Date_of_Pre_registration_Completion__c.year(), bookingRec.Date_of_Pre_registration_Completion__c.month(), bookingRec.Date_of_Pre_registration_Completion__c.day())  : null;
                    oqood.documentLink = customerDocWithId.size() > 0 && customerDocWithId.containsKey('OQOOD') ? customerDocWithId.get('OQOOD') : null;
                    milestoneWrapper.add(oqood);

                    Milestones payPlan = new Milestones();
                    payPlan.heading = 'Pay as per Payment Plan';
                    payPlan.order = '5';
                    milestoneWrapper.add(payPlan);
                    if(bookingRec.Quotation__c != null){
                        paymentBreakupList = Mobile_getPaymentPlan.getPaymentMilestones(bookingRec.Quotation__c);
                    }
                    
                    // 6. Building Completion Certificate pending discussion
					Milestones bcc = new Milestones();
					bcc.heading = 'Building Completion Certificate'; 
                    bcc.order = '6';
                    bcc.currentStatus = bookingRec.BCC_Notice_Sent__c ? 'Completed' : null;
                    bcc.documentLink = customerDocWithId.size() > 0 && customerDocWithId.containsKey('Building Completion Certificate') ? customerDocWithId.get('Building Completion Certificate') : null;
					milestoneWrapper.add(bcc); 
                    
                    List<Time_Slot_For_Handover__c> homeOrientationRec = [Select id, RecordType.Name, Status__c, Scheduled_Date__c, Timings__c, createddate  from Time_Slot_For_Handover__c where Booking__c = :bookingId and recordType.Name = 'Home Orientation' order by createddate desc];
                    
                    if(homeOrientationRec != null && homeOrientationRec.size() > 0){
                         Milestones homeOrc = new Milestones();
                         homeOrc.heading = 'Home Orientation';
                         homeOrc.order = '7';
                         String tempstatus = '';
                        Date tempDate = null;
                         String timing = '';
                        for(Time_Slot_For_Handover__c homeOrientation : homeOrientationRec ){
                            if(homeOrientation.Status__c == 'Completed'){
                                tempstatus = 'Completed';
                                tempDate = homeOrientation.Scheduled_Date__c;
                                timing = homeOrientation.Timings__c;
                                break;
                            }else if(homeOrientation.Status__c == 'Confirmed'){
                                tempDate = homeOrientation.Scheduled_Date__c;
                                timing = homeOrientation.Timings__c;
                                tempstatus = 'In Progress';
                                break;
                            }else{
                                tempDate = date.newinstance(homeOrientation.createddate.year(), homeOrientation.createddate.month(), homeOrientation.createddate.day());  
                                tempstatus = 'Booking Allowed';                            
                            }
                        }
   							                    
                        homeOrc.currentStatus = tempstatus;
                        homeOrc.statusDate = tempDate;
                       // handover.currentStatus = handoverRec.Status__c == 'Cancelled' ? 'Cancelled' : handoverRec.Status__c == 'Completed' ? 'Completed' : handoverRec.Status__c == 'None' || handoverRec.Status__c == null ? 'Booking Allowed' : 'In Progress';
                       // homeOrc.statusDate = homeOrc.Scheduled_Date__c != null ? homeOrc.Scheduled_Date__c :null;
                        homeOrc.documentLink = timing;
                        milestoneWrapper.add(homeOrc);
                    } else {
                        Milestones homeOrt = new Milestones();
                        homeOrt.heading = 'Home Orientation';
                        homeOrt.order = '7';
                        
                        homeOrt.currentStatus = null;
                        homeOrt.statusDate = null;
                        homeOrt.documentLink = null;
                        milestoneWrapper.add(homeOrt);
                    }
                    
                   // Milestones pcc = new Milestones();
                  //  pcc.heading = 'Payment Completion Certificate';
                  //  pcc.order = '10';
                  //  pcc.currentStatus = bookingRec.Paid_Percentage__c == 100 && bookingRec.PCC_Approved_By_Audit__c  ? 'Completed' : bookingRec.Paid_Percentage__c == 100 && bookingRec.PCC_Approved_By_Audit__c == false ? 'In progress' : null;
                  //  pcc.documentLink = customerDocWithId.size() > 0 && customerDocWithId.containsKey('Payment Completion Certificate') ? customerDocWithId.get('Payment Completion Certificate') : null;
                   // milestoneWrapper.add(pcc);

                    List<Time_Slot_For_Handover__c> handOverRec = [Select id, RecordType.Name, Status__c, Scheduled_Date__c, Timings__c, createddate from Time_Slot_For_Handover__c where Booking__c = :bookingId and recordType.Name = 'HandOver' order by createddate desc];
                    
                    if(handOverRec != null && handOverRec.size() > 0){
                         Milestones handOver = new Milestones();
                         handOver.heading = 'Handover';
                         handOver.order = '9';
                         String tempstatus = '';
                        Date tempDate = null;
                         String timing = '';
                        for(Time_Slot_For_Handover__c handrec : handOverRec ){
                            if(handrec.Status__c == 'Completed'){
                                tempstatus = 'Completed';
                                tempDate = handrec.Scheduled_Date__c;
                                timing = handrec.Timings__c;
                                break;
                            }else if(handrec.Status__c == 'Confirmed'){
                             	tempDate = handrec.Scheduled_Date__c;
                                timing = handrec.Timings__c;
                                tempstatus = 'In progress';
                                break;
                            }else{
                                tempDate = date.newinstance(handrec.createddate.year(), handrec.createddate.month(), handrec.createddate.day());  
                                tempstatus = 'Booking Allowed';                               
                            }
                        }
   							                    
                        handOver.currentStatus = tempstatus;
                        handOver.statusDate = tempDate;
                       // handover.currentStatus = handoverRec.Status__c == 'Cancelled' ? 'Cancelled' : handoverRec.Status__c == 'Completed' ? 'Completed' : handoverRec.Status__c == 'None' || handoverRec.Status__c == null ? 'Booking Allowed' : 'In Progress';
                       // homeOrc.statusDate = homeOrc.Scheduled_Date__c != null ? homeOrc.Scheduled_Date__c :null;
                        handOver.documentLink = timing;
                        milestoneWrapper.add(handOver);
                    } else{
                        Milestones handover = new Milestones();
                        handover.heading = 'Handover';
                        handover.order = '9';
                        handover.currentStatus = null;
                        handover.statusDate = null;
                        handover.documentLink = null;
                        milestoneWrapper.add(handover);
                    }

                    // 8. handover notice is a manual process   
                    Milestones titleDeed = new Milestones();
                    titleDeed.heading = 'Title Deed';
                    titleDeed.order = '11';
                    titleDeed.currentStatus = bookingRec.Title_Transfer_Completed__c == 'Not Initiated' ? null : bookingRec.Title_Transfer_Completed__c == 'Completed' ? 'Completed' : 'In progress';
                    titleDeed.documentLink = customerDocWithId.size() > 0 && customerDocWithId.containsKey('Title Deed') ? customerDocWithId.get('Title Deed') : null;
                    milestoneWrapper.add(titleDeed);
                    bookingJourneyWrapper.milestones = milestoneWrapper;
                    bookingJourneyWrapper.paymentBreakup = paymentBreakupList;
                    //return prepareResponse(bookingJourneyWrapper,'Operation Successfull','Success',200,true);
                    responseString = (prepareResponse(bookingJourneyWrapper,'Operation Successfull','Success',200,true)).toString().replace('"','');
                    res.responseBody = BLOB.valueOf(JSON.serialize(prepareResponse(bookingJourneyWrapper,'Operation Successfull','Success',200,true)));
                    res.statusCode = 200;
                }
                else{
                    // return prepareResponse(null,'No data found','No Data Found',400,false);
                    res.responseBody = BLOB.valueOf(JSON.serialize(prepareResponse(null,'No Data Found','Error',400,false)));
                    res.statusCode = 400;
                }        
            }
         }
        catch(Exception ex){
            errorMessage = ex.getMessage();
            res.responseBody = BLOB.valueOf(JSON.serialize(prepareResponse(null,'Error','Error',400,false)));
            res.statusCode = 400;
        }  
        Mobile_ApiUtility.createMobileAPILogs('getBookingJourney','Mobile_getBookingJourney',bookingId,responseString,errorMessage,res.statusCode);
    }

    global class ResponseBodyWrapper{
        UnitDetails unitDetails;
        List<Milestones> milestones;
        List<Mobile_getPaymentPlan.responseBodyWrapper> paymentBreakup;
    }

    global class UnitDetails{
        String bookingNumber;
        String unitNumber;
        String unitid;
        String towerName;
        String communityName;
        String masterCommunityName;
        Decimal dueAmount;
        String applicantNames;
    }

    public class Milestones{
        public String heading;
        public String order;
        public String currentStatus;
        public Date statusDate;
        public String documentLink;
        public String actionLink;
    }

    public class PaymentBreakup{
        public String name;
        public String description;
        public String amount;
        public Date dueDate;
        public String installment;
        public Decimal chargePercent;
    }

    Public static HttpResponseWrapper prepareResponse(ResponseBodyWrapper rBody,string rMessage,string rStatus,integer rStatusCode,boolean rSuccess){
        HttpResponseWrapper resWrap = new HttpResponseWrapper();
        resWrap.data = rBody; 
        resWrap.message = rMessage;
        resWrap.status = rStatus;
        resWrap.statusCode = rStatusCode;
        resWrap.success = rSuccess;
        return resWrap;
    }

    global class HttpResponseWrapper{
        String status;
        Integer statusCode;
        ResponseBodyWrapper data = new ResponseBodyWrapper();
        boolean success;
        String message;
    }

    public static Map<String,String> getCustomerDocumentMap(String objectName, String relatedId){
        Map<String,String> customerDocWithIdMap = new Map<String,Id>();
        List<Customer_Related_Document__c> customerDocsList = new List<Customer_Related_Document__c>();
        String queryString = 'Select id, Active__c, Booking__c, File_Name__c, DocumentId__c from Customer_Related_Document__c';
        if(objectName != null && relatedId != null){
            queryString += ' Where '+objectName+ ' = :relatedId and Active__c = true';
        }
        customerDocsList = Database.query(queryString);
        if(customerDocsList.size() > 0){
            for(Customer_Related_Document__c custDocRec : customerDocsList){
                customerDocWithIdMap.put(custDocRec.File_Name__c,custDocRec.DocumentId__c);
            }
        }
        return customerDocWithIdMap;
    }

}