force-app/main/default/objects/Business_Process_Step__c/Business_Process_Step__c.object-meta.xml
<CustomObject>
    <label>Business Process Step</label>
    <nameField>
        <label>Business Process Steps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Process Steps</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Process_Step__c/fields/Accepted_Time__c.field-meta.xml
<CustomField>
    <fullName>Accepted_Time__c</fullName>
    <label>Initial Accepted Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Business_Process_Step__c/fields/Aging__c.field-meta.xml
<CustomField>
    <fullName>Aging__c</fullName>
    <label>Aging</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Business_Process_Step__c/fields/Completed_Time__c.field-meta.xml
<CustomField>
    <fullName>Completed_Time__c</fullName>
    <label>Initial Completed Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Business_Process_Step__c/fields/Final_Accepted_Time__c.field-meta.xml
<CustomField>
    <fullName>Final_Accepted_Time__c</fullName>
    <label>Final Accepted Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Business_Process_Step__c/fields/Final_Assigned_Time__c.field-meta.xml
<CustomField>
    <fullName>Final_Assigned_Time__c</fullName>
    <label>Final Assigned Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Business_Process_Step__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Not Actioned</fullName>
                <default>true</default>
                <label>Not Actioned</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BusinessProcessStepAgingUpdateBatch.cls
global class BusinessProcessStepAgingUpdateBatch implements Database.Batchable<sObject>, Database.Stateful {

    global final String query;

    global BusinessProcessStepAgingUpdateBatch(String query) {
        if(query == null){
            query = 'SELECT Accepted_Time__c,Final_Assigned_Time__c,Final_Accepted_Time__c,Completed_Time__c,Status__c,owner.Type,owner.Name,ownerId FROM Business_Process_Step__c WHERE Status__c = \'Open\'';
        }
        this.query = query;
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Business_Process_Step__c> bpsUpdateList = new List<Business_Process_Step__c>();

        for (sObject record : scope) {
            Business_Process_Step__c bps = (Business_Process_Step__c)record;
            if (bps.Final_Assigned_Time__c != null) {
                DateTime workStartTime = DateTime.newInstance(bps.Final_Assigned_Time__c.date(), Time.newInstance(9, 0, 0, 0));
                DateTime workEndTime = DateTime.newInstance(bps.Final_Assigned_Time__c.date(), Time.newInstance(18, 0, 0, 0));
                workStartTime = workStartTime.addHours(4);
                workEndTime = workEndTime.addHours(4);
                String timeGap = HolidayUtility.calculateBusinessHours(bps.Final_Assigned_Time__c.addHours(4), System.now().addHours(4), workStartTime, workEndTime);
                bps.Aging__c = Decimal.valueOf(timeGap);
                bpsUpdateList.add(bps);
            }
        }

        if (bpsUpdateList.size() > 0) {
            update bpsUpdateList;
        }
    }

    global void finish(Database.BatchableContext BC) {
        // Your finish logic, if any
    }
}