force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/Call_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Call_Attempt_Status__c</fullName>
    <label>Call Attempt Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
            </value>
            <value>
                <fullName>Not Actioned</fullName>
            </value>
            <value>
                <fullName>Visit confirmed</fullName>
            </value>
            <value>
                <fullName>Visit proposed</fullName>
            </value>
            <value>
                <fullName>Junk Lead</fullName>
            </value>
            <value>
                <fullName>Invalid Enquiry</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Not Actioned - No Shuffle</fullName>
            </value>
            <value>
                <fullName>Not Shuffle</fullName>
            </value>
            <value>
                <fullName>Recycled Lead</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Follow up - email</fullName>
            </value>
            <value>
                <fullName>Follow up - social</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Last_Call_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Call_Attempt_Status__c</fullName>
    <defaultValue>&quot;Not Actioned&quot;</defaultValue>
    <label>Presales Last Call Attempt Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <displayFormat>{000000}</displayFormat>
    <externalId>true</externalId>
    <label>Lead Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Last_call_attempt_status__c.field-meta.xml
<CustomField>
    <fullName>Last_call_attempt_status__c</fullName>
    <label>Presales Last Call Attempt Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Id__c.field-meta.xml
<CustomField>
    <fullName>Lead_Id__c</fullName>
    <label>Lead Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
/* Handler Class for Opportunity trigger */
public class OpportunityTriggerHandler {
    
    /* Update back Parent Lead - Datahash */
    public static void updateLeadAttemptStatus(List<Opportunity> opportunities){
        try {
            Set<Id> leadIdsToUpdate = new Set<Id>();
            List<Lead> updatedLeads = new List<Lead>();
            Set<Id> opportunityIds = new Set<Id>();
            Map<String,Opportunity> opportunityMap = new Map<String,Opportunity>();
            
            for (Opportunity opp : opportunities) {
                opportunityMap.put(opp.Id, opp);
            }
            
            List<Lead> parentLeadList = [SELECT Id, Last_Call_Attempt_Status__c,
                                         convertedOpportunityId, Lead_Id__c
                                         FROM Lead 
                                         WHERE convertedOpportunityId IN :opportunityMap.KeySet()];
            for(Lead parentLead: parentLeadList) {
                Lead updatedLead = New Lead(Id = parentLead.id);
                Opportunity convertedOpp = opportunityMap.containsKey(parentLead.ConvertedOpportunityId) ? opportunityMap.get(parentLead.ConvertedOpportunityId) : null;
                if(convertedOpp != null) {
                    updatedLead.Last_Call_Attempt_Status__c = convertedOpp.Last_Call_Attempt_Status__c;
                    updatedLead.Call_Attempt_Status__c = convertedOpp.Last_Call_Attempt_Status__c;
                    updatedLeads.add(updatedLead);
                }
            }
            
            // Perform the update on Leads
            if (updatedLeads.size() > 0) {
                Database.update(updatedLeads, FALSE); 
            }
        }
        catch(Exception ex) {
            Error_Log__c trackErrorRec = new Error_Log__c(Class__c = 'OpportunityTriggerhandler -- updateLeadAttemptStatus',Message__c = ex.getmessage());
            database.insert(trackErrorRec, false);
        }
    }
}