force-app/main/default/objects/Direct_Sales_Managers__c/Direct_Sales_Managers__c.object-meta.xml
<CustomObject>
    <label>Direct Sales Managers</label>
    <nameField>
        <displayFormat>DSM-{0000}</displayFormat>
        <label>Direct Sales Managers Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Sales Managers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Direct_Sales_Managers__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Direct_Sales_Managers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/getdirectsalesmanagersTest.cls
@isTest
public class getdirectsalesmanagersTest {
    

	 @isTest static void testmethod1() 
     {
        Direct_Sales_Managers__c dsms = new Direct_Sales_Managers__c();
        dsms.Sales_Manager__c=userinfo.getuserid();
        dsms.Availability_Status__c=true;
        insert dsms;
        Test.startTest();
         getdirectsalesmanagers gdsm = new getdirectsalesmanagers();
         getdirectsalesmanagers.getsalesmanagers();
        Test.stopTest();
     }


}