force-app/main/default/objects/Interim_Payments__c/Interim_Payments__c.object-meta.xml
<CustomObject>
    <label>Interim Payments Received</label>
    <nameField>
        <displayFormat>IPC-{YY}-{MM}-{0000}</displayFormat>
        <label>Interim Payments Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interim Payments Received</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Interim_Payments__c/fields/Amount_Interim__c.field-meta.xml
<CustomField>
    <fullName>Amount_Interim__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Interim_Payments__c/fields/Application_Booking_Interim__c.field-meta.xml
<CustomField>
    <fullName>Application_Booking_Interim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application / Booking</label>
    <referenceTo>PropStrength__Application_Booking__c</referenceTo>
    <relationshipName>Interim_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interim_Payments__c/fields/Approval_Status_Interim__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status_Interim__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>PDC</fullName>
            </value>
            <value>
                <fullName>Cheque Dishonoured</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Submitted for Cheque Hold</fullName>
            </value>
            <value>
                <fullName>Cheque Hold Approved</fullName>
            </value>
            <value>
                <fullName>Submitted for Cheque Replacement</fullName>
            </value>
            <value>
                <fullName>Cheque Replacement Approved</fullName>
            </value>
            <value>
                <fullName>Auto-Rejected - Payment not made</fullName>
                <isActive>false</isActive>
                <label>Auto-Rejected - Payment not made</label>
            </value>
            <value>
                <fullName>Hold</fullName>
                <isActive>false</isActive>
                <label>Hold</label>
            </value>
            <value>
                <fullName>Sent for Banking</fullName>
                <isActive>false</isActive>
                <label>Sent for Banking</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interim_Payments__c/fields/Payment_Mode_Interim__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode_Interim__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>OTC Deposits(Cash counter)</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>CDM Cash (Cash Deposit in Machine)</fullName>
            </value>
            <value>
                <fullName>CDM Cheque (Cheque Deposit in Machine)</fullName>
            </value>
            <value>
                <fullName>IWT(International)</fullName>
            </value>
            <value>
                <fullName>DWT(Domestic)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interim_Payments__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Interim Payments Received</relationshipLabel>
    <relationshipName>Interim_Payments_Received</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mobile_App_Log__c/Mobile_App_Log__c.object-meta.xml
<CustomObject>
    <label>Mobile App Log</label>
    <nameField>
        <displayFormat>Log-{YY}-{MM}-{0000000}</displayFormat>
        <label>Mobile App Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile App Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mobile_App_Log__c/fields/Application_Booking__c.field-meta.xml
<CustomField>
    <fullName>Application_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application / Booking</label>
    <referenceTo>PropStrength__Application_Booking__c</referenceTo>
    <relationshipLabel>Mobile App Logs</relationshipLabel>
    <relationshipName>Mobile_App_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mobile_App_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Application_Booking__c.field-meta.xml
<CustomField>
    <fullName>Application_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application / Booking</label>
    <referenceTo>PropStrength__Application_Booking__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTC Deposits</fullName>
                <label>OTC Deposit(Cash counter)</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>CDM Cash</fullName>
                <label>CDM Cash (Cash Deposit in Machine)</label>
            </value>
            <value>
                <fullName>CDM Cheque</fullName>
                <label>CDM Cheque (Cheque Deposit in Machine)</label>
            </value>
            <value>
                <fullName>International Wire Transfer</fullName>
                <label>IWT(International)</label>
            </value>
            <value>
                <fullName>Domestic Wire Transfer</fullName>
                <label>DWT(Domestic)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Accounts Approval</fullName>
            </value>
            <value>
                <fullName>Approved by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by Accounts</fullName>
            </value>
            <value>
                <fullName>Pending for Sales Ops Approval</fullName>
            </value>
            <value>
                <fullName>Rejected by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Resubmitted to SM/SD</fullName>
            </value>
            <value>
                <fullName>Approved by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Submitted to Accounts for Amount Confirmation</fullName>
            </value>
            <value>
                <fullName>Amount Confirmed by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by System</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Payment Link sent to Customer</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>PR was Approved- Booking is cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 5) OR (1 AND 2 AND 3 AND 4) OR (6 AND 2 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Not_Available_for_Sales__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Unit__c.Allocated_SM__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>notEqual</operation>
            <value>Unreleased</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Allocated_SM__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Hold</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PSGetPaymentReceiptsMobileHelper.cls
global class PSGetPaymentReceiptsMobileHelper {
    global Static String GetPaymentReceiptsMobile(RestRequest request) {
        String responce = '';
        if (request != null && 
            request.requestBody != null) {
                JSONGenerator gen = JSON.createGenerator(true);
                String jsonString = request.requestBody.toString();
                try {                    
                    PSGetApplicantDetailMobilePOJO allApplicantDetail = (PSGetApplicantDetailMobilePOJO) JSON.deserialize(jsonString, PSGetApplicantDetailMobilePOJO.class);
                    if(allApplicantDetail != null) {
                        if(!String.isBlank(allApplicantDetail.bookingId)) {
                            List<PropStrength__Received_Payment__c> appList = [SELECT Id,Receipt_Status__c,Name,PropStrength__Amount__c,Receipt_Number__c,PropStrength__Payment_Type__c,
                                                                               createdDate,PropStrength__Application_Booking__r.PropStrength__Project__r.Name,
                                                                               PropStrength__Application_Booking__r.PropStrength__Property__r.PropStrength__House_Unit_No__c
                                                                               FROM PropStrength__Received_Payment__c
                                                                               WHERE PropStrength__Application_Booking__c =: allApplicantDetail.bookingId
                                                                               AND Recordtype.Name =: 'Payment Received'];
                            List<Payment_Request__c> payRequestList = [SELECT Id,Name,Status__c,Mode__c,Total_Amount__c,Unit__r.Name,createddate,
                                                                       Application_Booking__r.PropStrength__Project__r.Name,Amount__c,Application_Booking__r.PropStrength__Property__r.PropStrength__House_Unit_No__c
                                                                       FROM Payment_Request__c
                                                                       WHERE Application_Booking__c =: allApplicantDetail.bookingId];
                            List<Interim_Payments__c> interimList = [SELECT Id,Name,createddate,Approval_Status_Interim__c,Payment_Request__r.Name,
                                                                     Application_Booking_Interim__r.PropStrength__Project__r.Name,Payment_Mode_Interim__c,
                                                                     Amount_Interim__c,Application_Booking_Interim__r.PropStrength__Property__r.PropStrength__House_Unit_No__c
                                                                     FROM Interim_Payments__c
                                                                     WHERE Application_Booking_Interim__c =: allApplicantDetail.bookingId];
                            if(!appList.isEmpty()) {
                                gen.writeStartObject();     
                                gen.writeBooleanField('success', true);
                                gen.writeNumberField('statusCode', 200);
                                gen.writeStringField('status', 'Success');
                                gen.writeStringField('Message', 'Operation Successfull');
                                gen.writeFieldName('data');
                                gen.writeStartArray();
                            } else if(appList.isEmpty() && !payRequestList.isEmpty()) {
                                gen.writeStartObject();     
                                gen.writeBooleanField('success', true);
                                gen.writeNumberField('statusCode', 200);
                                gen.writeStringField('status', 'Success');
                                gen.writeStringField('Message', 'Operation Successfull');
                                gen.writeFieldName('data');
                                gen.writeStartArray();
                            }
                            if(!appList.isEmpty()) {
                                for(PropStrength__Received_Payment__c appDetail : appList) {
                                    gen.writeStartObject();
                                    gen.writeStringField('id', appDetail.Id);
                                    gen.writeStringField('name', !String.isBlank(appDetail.Name) ? appDetail.Name : '');
                                    gen.writeStringField('mode', !String.isBlank(appDetail.PropStrength__Payment_Type__c) ? appDetail.PropStrength__Payment_Type__c : '');
                                    gen.writeStringField('receiptNumber', appDetail.Name != null ? appDetail.Name : '');
                                    gen.writeStringField('totalamount', appDetail.PropStrength__Amount__c != null ? String.valueOf(appDetail.PropStrength__Amount__c) : '');
                                    gen.writeStringField('createdDate', String.valueOf(Date.newinstance(appDetail.createddate.year(), appDetail.createddate.month(), appDetail.createddate.day())));
                                    gen.writeStringField('unitName', appDetail.PropStrength__Application_Booking__r.PropStrength__Property__r.PropStrength__House_Unit_No__c != null ? appDetail.PropStrength__Application_Booking__r.PropStrength__Property__r.PropStrength__House_Unit_No__c : '');
                                    gen.writeStringField('projectName', appDetail.PropStrength__Application_Booking__r.PropStrength__Project__r.Name != null ? appDetail.PropStrength__Application_Booking__r.PropStrength__Project__r.Name : '');
                                    gen.writeStringField('prstatus', 'Completed');
                                    //gen.writeStringField('prstatus', appDetail.Receipt_Status__c != null ? appDetail.Receipt_Status__c : '');
                                    gen.writeEndObject();
                                }
                            }
                            if(!payRequestList.isEmpty()) {
                                for(Payment_Request__c appDetail : payRequestList) {
                                    if (!appDetail.Status__c.contains('Approved')) { // && !appDetail.Status__c.contains('Rejected')
                                        gen.writeStartObject();
                                        gen.writeStringField('id', appDetail.Id);
                                        gen.writeStringField('name', !String.isBlank(appDetail.Name) ? appDetail.Name : '');
                                        gen.writeStringField('mode', !String.isBlank(appDetail.Mode__c) ? appDetail.Mode__c : '');
                                        gen.writeStringField('receiptNumber', appDetail.name != null ? appDetail.name : '');
                                        gen.writeStringField('totalamount', appDetail.Amount__c != null ? String.valueOf(appDetail.Amount__c) : '');
                                        gen.writeStringField('createdDate', String.valueOf(Date.newinstance(appDetail.createddate.year(), appDetail.createddate.month(), appDetail.createddate.day())));
                                        //gen.writeStringField('unitName', appDetail.Unit__r.Name != null ? appDetail.Unit__r.Name : '');
                                        gen.writeStringField('unitName', appDetail.Application_Booking__r.PropStrength__Property__r.PropStrength__House_Unit_No__c != null ? appDetail.Application_Booking__r.PropStrength__Property__r.PropStrength__House_Unit_No__c : '');
                                        gen.writeStringField('projectName', appDetail.Application_Booking__r.PropStrength__Project__r.Name != null ? appDetail.Application_Booking__r.PropStrength__Project__r.Name : '');
                                        gen.writeStringField('prstatus', 'In Progress');
                                        gen.writeEndObject();
                                    }
                                }
                            }
                            if(!interimList.isEmpty()) {
                                for(Interim_Payments__c appDetail: interimList) {
                                    if (!appDetail.Approval_Status_Interim__c.contains('Approved')) { // && !appDetail.Status__c.contains('Rejected')
                                        gen.writeStartObject();
                                        gen.writeStringField('id', appDetail.Id);
                                        gen.writeStringField('name', !String.isBlank(appDetail.Payment_Request__r.Name) ? appDetail.Payment_Request__r.Name : '');
                                        gen.writeStringField('mode', !String.isBlank(appDetail.Payment_Mode_Interim__c) ? appDetail.Payment_Mode_Interim__c : '');
                                        gen.writeStringField('receiptNumber', appDetail.name != null ? appDetail.name : '');
                                        gen.writeStringField('totalamount', appDetail.Amount_Interim__c != null ? String.valueOf(appDetail.Amount_Interim__c) : '');
                                        gen.writeStringField('createdDate', String.valueOf(Date.newinstance(appDetail.createddate.year(), appDetail.createddate.month(), appDetail.createddate.day())));
                                        //gen.writeStringField('unitName', appDetail.Unit__r.Name != null ? appDetail.Unit__r.Name : '');
                                        gen.writeStringField('unitName', appDetail.Application_Booking_Interim__r.PropStrength__Property__r.PropStrength__House_Unit_No__c != null ? appDetail.Application_Booking_Interim__r.PropStrength__Property__r.PropStrength__House_Unit_No__c : '');
                                        gen.writeStringField('projectName', appDetail.Application_Booking_Interim__r.PropStrength__Project__r.Name != null ? appDetail.Application_Booking_Interim__r.PropStrength__Project__r.Name : '');
                                        gen.writeStringField('prstatus', 'In Progress');
                                        gen.writeEndObject();
                                    }
                                }
                            }
                            gen.writeEndArray();
                            gen.writeEndObject();
                            responce = gen.getAsString();
                            if(!appList.isEmpty() || !payRequestList.isEmpty()) {
                                Mobile_App_Log__c logError = new Mobile_App_Log__c();
                                logError.Response_Body__c = responce;
                                logError.Class_Name__c = 'PSGetPaymentReceiptsMobileHelper';
                                logError.API_Name__c = '/services/apexrest/getPaymentReceipts/';
                                logError.Status__c = '200';
                                logError.Request_Body__c = JSON.serialize(jsonString);
                                insert logError;
                            } else {
                                gen.writeStartObject();     
                                gen.writeBooleanField('success', false);
                                gen.writeNumberField('statusCode', 400);
                                gen.writeStringField('status', 'Error');
                                gen.writeStringField('Message', 'No data found');
                                gen.writeFieldName('data');
                                gen.writeStartArray();
                                gen.writeEndArray();
                                gen.writeEndObject();
                                responce = gen.getAsString();
                                
                                Mobile_App_Log__c logError = new Mobile_App_Log__c();
                                logError.Response_Body__c = responce;
                                logError.Class_Name__c = 'PSGetPaymentReceiptsMobileHelper';
                                logError.API_Name__c = '/services/apexrest/getPaymentReceipts/';
                                logError.Status__c = '400';
                                logError.Request_Body__c = JSON.serialize(jsonString);
                                insert logError;
                            }
                        } else {
                            gen.writeStartObject();     
                            gen.writeBooleanField('success', false);
                            gen.writeNumberField('statusCode', 400);
                            gen.writeStringField('status', 'Error');
                            gen.writeStringField('Message', 'Bookind Id is Required.');
                            gen.writeFieldName('data');
                            gen.writeStartArray();
                            gen.writeEndArray();
                            gen.writeEndObject();
                            responce = gen.getAsString();
                            
                            Mobile_App_Log__c logError = new Mobile_App_Log__c();
                            logError.Response_Body__c = responce;
                            logError.Class_Name__c = 'PSGetPaymentReceiptsMobileHelper';
                            logError.API_Name__c = '/services/apexrest/getPaymentReceipts/';
                            logError.Status__c = '400';
                            logError.Request_Body__c = JSON.serialize(jsonString);
                            insert logError;
                        }
                    }
                } catch(Exception e) {
                    gen.writeStartObject();     
                    gen.writeBooleanField('success', false);
                    gen.writeNumberField('statusCode', 400);
                    gen.writeStringField('status', 'Error');
                    gen.writeStringField('Message', String.valueOf(e.getMessage()));
                    gen.writeFieldName('data');
                    gen.writeStartArray();
                    gen.writeEndArray();
                    gen.writeEndObject();
                    responce = gen.getAsString();
                    
                    Mobile_App_Log__c logError = new Mobile_App_Log__c();
                    logError.Response_Body__c = responce;
                    logError.Class_Name__c = 'PSGetPaymentReceiptsMobileHelper';
                    logError.API_Name__c = '/services/apexrest/getPaymentReceipts/';
                    logError.Status__c = '400';
                    logError.Request_Body__c = JSON.serialize(jsonString);
                    insert logError;
                    System.debug('Catch:-'+ e.getMessage() + 'Line Num:- '+e.getLineNumber());
                }
            }
        return responce;
    }
}