force-app/main/default/objects/Attempt_Tracking__c/Attempt_Tracking__c.object-meta.xml
<CustomObject>
    <label>Attempt Tracking</label>
    <nameField>
        <label>Attempt Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attempt Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attempt_Tracking__c/fields/Attempt_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Attempt_Sequence__c</fullName>
    <label>Attempt Sequence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attempt_Tracking__c/fields/Attempted_By__c.field-meta.xml
<CustomField>
    <fullName>Attempted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attempt Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Attempt_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attempt_Tracking__c/fields/Day_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Day_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Day Tracking</label>
    <referenceTo>Day_Tracking__c</referenceTo>
    <relationshipLabel>Attempt Trackings</relationshipLabel>
    <relationshipName>Attempt_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attempt_Tracking__c/fields/Last_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Attempt_Status__c</fullName>
    <formula>TEXT( Day_Tracking__r.Lead__r.Last_Attempt_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Attempt Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attempt_Tracking__c/recordTypes/WhatsApp.recordType-meta.xml
<RecordType>
    <fullName>WhatsApp</fullName>
    <active>true</active>
    <label>WhatsApp</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Last_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Attempt_Status__c</fullName>
    <label>Last Attempt Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Contact - Follow-up</fullName>
            </value>
            <value>
                <fullName>Sobha Landline - Contacted</fullName>
            </value>
            <value>
                <fullName>WhatsApp - Contacted</fullName>
            </value>
            <value>
                <fullName>Email - Contacted</fullName>
            </value>
            <value>
                <fullName>Official Mobile - Contacted</fullName>
            </value>
            <value>
                <fullName>Official Landline - Contacted</fullName>
            </value>
            <value>
                <fullName>WhatsApp Not Available</fullName>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Call_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Call_Attempt_Status__c</fullName>
    <label>Presales Last Call Attempt Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Day_Tracking__c/Day_Tracking__c.object-meta.xml
<CustomObject>
    <label>Day Tracking</label>
    <nameField>
        <label>Days Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Day_Tracking__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Day Trackings</relationshipLabel>
    <relationshipName>Day_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Last_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Attempt_Status__c</fullName>
    <label>Last Attempt Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Contact - Follow-up</fullName>
            </value>
            <value>
                <fullName>Sobha Landline - Contacted</fullName>
            </value>
            <value>
                <fullName>WhatsApp - Contacted</fullName>
            </value>
            <value>
                <fullName>Email - Contacted</fullName>
            </value>
            <value>
                <fullName>Official Mobile - Contacted</fullName>
            </value>
            <value>
                <fullName>Official Landline - Contacted</fullName>
            </value>
            <value>
                <fullName>WhatsApp Not Available</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
                <isActive>false</isActive>
                <label>Actioned</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
                <isActive>false</isActive>
                <label>Contacted</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
                <isActive>false</isActive>
                <label>Invalid Number</label>
            </value>
            <value>
                <fullName>Junk Lead</fullName>
                <isActive>false</isActive>
                <label>Junk Lead</label>
            </value>
            <value>
                <fullName>No Contact</fullName>
                <isActive>false</isActive>
                <label>No Contact</label>
            </value>
            <value>
                <fullName>Not Actioned</fullName>
                <isActive>false</isActive>
                <label>Not Actioned</label>
            </value>
            <value>
                <fullName>Not Interested</fullName>
                <isActive>false</isActive>
                <label>Not Interested</label>
            </value>
            <value>
                <fullName>Tele-Meeting Fixed</fullName>
                <isActive>false</isActive>
                <label>Tele-Meeting Fixed</label>
            </value>
            <value>
                <fullName>Visit Proposed</fullName>
                <isActive>false</isActive>
                <label>Visit Proposed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Last_Call_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Call_Attempt_Status__c</fullName>
    <defaultValue>&quot;Not Actioned&quot;</defaultValue>
    <label>Presales Last Call Attempt Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Temp_CreatedDate__c.field-meta.xml
<CustomField>
    <fullName>Temp_CreatedDate__c</fullName>
    <label>Temp CreatedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/WhatsApp_Not_Available__c.field-meta.xml
<CustomField>
    <fullName>WhatsApp_Not_Available__c</fullName>
    <defaultValue>false</defaultValue>
    <label>WhatsApp Not Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead_Nurturing__mdt/Lead_Nurturing__mdt.object-meta.xml
<CustomObject>
    <label>Lead Nurturing</label>
    <pluralLabel>Lead Nurturing</pluralLabel>
</CustomObject>

force-app/main/default/classes/CreateLeadDailyTrackingBatch.cls
global class CreateLeadDailyTrackingBatch implements Database.Batchable<sObject>, Schedulable {
    global list<string> statusList = new list<string>();
    global list<string> presalesLastCallAttemptStatusList = new list<string>();
    global list<string> invalidStatusList = new list<string>();
    
    global void execute(SchedulableContext SC) {
        Database.executebatch(new CreateLeadDailyTrackingBatch(),50);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        statusList.add('No Contact - Follow-up'); // configure metadata  
        presalesLastCallAttemptStatusList.add('Not Actioned');
        invalidStatusList.add('Junk Lead');
        invalidStatusList.add('junk lead');
        invalidStatusList.add('junk Lead');
        invalidStatusList.add('Junk lead');
        invalidStatusList.add('junk');
        invalidStatusList.add('Junklead');
        invalidStatusList.add('JUNK LEAD');
        
        String query = 'SELECT Id, CreatedDate, Last_Attempt_Status__c FROM Lead WHERE Last_Attempt_Status__c IN: statusList AND Last_Call_Attempt_Status__c NOT IN : invalidStatusList';
        //Below query is only for UAT
        //String query = 'SELECT Id, CreatedDate, Last_Attempt_Status__c, Temp_CreatedDate__c FROM Lead WHERE Last_Attempt_Status__c IN: statusList and Temp_CreatedDate__c != null';
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Lead> leadList) {
        map<string,string> leadShuffleConfigs = LeadNurturingController.getLeadNurturingConfigs();
        list<Day_Tracking__c> dayTrackingsToCreate = new list<Day_Tracking__c>();
        Date tdy = system.today();
        string skipDays = string.valueOf(leadShuffleConfigs.get('SkipDays'));
        list<integer> skipDaysList = new list<integer>();
        for(String day : skipDays.split(',')){
            day = day.trim();
            skipDaysList.add(Integer.valueOf(day));
        }
        list<lead> toBeCloseLeadList = new list<lead>();
        for(Lead l : leadList){
            Integer leadAge = (tdy.daysBetween(l.CreatedDate.Date()))*(-1)+1;
            //Below line is only for UAT
            //Integer leadAge = (tdy.daysBetween(l.Temp_CreatedDate__c.Date()))*(-1)+1;
            if(leadAge<21 && !skipDaysList.contains(leadAge)){ // configure 21
                Day_Tracking__c d = new Day_Tracking__c();
                d.Name = 'Day '+leadAge;
                d.Lead__c = l.Id;
                dayTrackingsToCreate.add(d);
            }
            if(leadAge==21){
                l.Status = 'Closed';
                toBeCloseLeadList.add(l);
            }
        }
        if(dayTrackingsToCreate.size()>0){
            insert dayTrackingsToCreate;
            list<Attempt_Tracking__c> atToInsert = new list<Attempt_Tracking__c>();
            map<string,string> dayToAttempts = new map<string,string>();
            List<Lead_Nurturing__mdt> days = [select Label, Value__c from Lead_Nurturing__mdt where DeveloperName LIKE 'Day_%'];
            for(Lead_Nurturing__mdt d : days){
                dayToAttempts.put(d.Label,d.Value__c);
            }
            map<string,string> recordTypeNameToId = new map<string,string>();
            for(RecordType recType : [select id,name from RecordType where sObjectType='Attempt_Tracking__c']){
                recordTypeNameToId.put(recType.name,recType.id);
            }
            for(Day_Tracking__c dT : [select Id, Name, Lead__r.OwnerId, Lead__r.WhatsApp_Not_Available__c from Day_Tracking__c where Id IN : dayTrackingsToCreate]){
                string ownerId = dT.Lead__r.OwnerId;
                string allAttempts = dayToAttempts.get(dT.Name);
                string attempt = allAttempts.split(',')[0];
                Attempt_Tracking__c a = new Attempt_Tracking__c();
                if(attempt=='WhatsApp' && dT.Lead__r.WhatsApp_Not_Available__c){
                    attempt = allAttempts.split(',')[1];
                    a.Attempt_Sequence__c = '2';
                }
                else{
                    a.Attempt_Sequence__c = '1';
                }
                a.Day_Tracking__c = dT.Id;
                a.Name = attempt;
                a.Attempted_By__c = (ownerId!=null && ownerId.startsWith('005'))?ownerId:null;
                a.RecordTypeId = recordTypeNameToId.get(attempt);
                atToInsert.add(a);
            }
            if(atToInsert.size()>0){
                insert atToInsert;
            }
        }
        if(toBeCloseLeadList.size()>0){
            try{
            	update toBeCloseLeadList;
            }
            catch(Exception e){
                
            }
        }
    }
    global void finish(Database.BatchableContext BC) {
        
    }
}