force-app/main/default/objects/Attempt_Tracking__c/Attempt_Tracking__c.object-meta.xml
<CustomObject>
    <label>Attempt Tracking</label>
    <nameField>
        <label>Attempt Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attempt Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attempt_Tracking__c/fields/Attempt_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Attempt_Sequence__c</fullName>
    <label>Attempt Sequence</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attempt_Tracking__c/fields/Attempted_By__c.field-meta.xml
<CustomField>
    <fullName>Attempted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attempt Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Attempt_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attempt_Tracking__c/fields/Day_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Day_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Day Tracking</label>
    <referenceTo>Day_Tracking__c</referenceTo>
    <relationshipLabel>Attempt Trackings</relationshipLabel>
    <relationshipName>Attempt_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attempt_Tracking__c/fields/Last_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Attempt_Status__c</fullName>
    <formula>TEXT( Day_Tracking__r.Lead__r.Last_Attempt_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Attempt Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Attempt_Tracking__c/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

force-app/main/default/objects/Campaign/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <label>Campaign Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Last_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Attempt_Status__c</fullName>
    <label>Last Attempt Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Contact - Follow-up</fullName>
            </value>
            <value>
                <fullName>Sobha Landline - Contacted</fullName>
            </value>
            <value>
                <fullName>WhatsApp - Contacted</fullName>
            </value>
            <value>
                <fullName>Email - Contacted</fullName>
            </value>
            <value>
                <fullName>Official Mobile - Contacted</fullName>
            </value>
            <value>
                <fullName>Official Landline - Contacted</fullName>
            </value>
            <value>
                <fullName>WhatsApp Not Available</fullName>
            </value>
            <value>
                <fullName>Follow Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Day_Tracking__c/Day_Tracking__c.object-meta.xml
<CustomObject>
    <label>Day Tracking</label>
    <nameField>
        <label>Days Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Day_Tracking__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Day Trackings</relationshipLabel>
    <relationshipName>Day_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Day_Tracking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Contact - Follow-up</fullName>
            </value>
            <value>
                <fullName>Sobha Landline - Contacted</fullName>
            </value>
            <value>
                <fullName>WhatsApp - Contacted</fullName>
            </value>
            <value>
                <fullName>Email - Contacted</fullName>
            </value>
            <value>
                <fullName>Official Mobile - Contacted</fullName>
            </value>
            <value>
                <fullName>Official Landline - Contacted</fullName>
            </value>
            <value>
                <fullName>WhatsApp Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <label>Campaign Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Last_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Attempt_Status__c</fullName>
    <label>Last Attempt Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No Contact - Follow-up</fullName>
            </value>
            <value>
                <fullName>Sobha Landline - Contacted</fullName>
            </value>
            <value>
                <fullName>WhatsApp - Contacted</fullName>
            </value>
            <value>
                <fullName>Email - Contacted</fullName>
            </value>
            <value>
                <fullName>Official Mobile - Contacted</fullName>
            </value>
            <value>
                <fullName>Official Landline - Contacted</fullName>
            </value>
            <value>
                <fullName>WhatsApp Not Available</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
                <isActive>false</isActive>
                <label>Actioned</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
                <isActive>false</isActive>
                <label>Cancelled</label>
            </value>
            <value>
                <fullName>Contacted</fullName>
                <isActive>false</isActive>
                <label>Contacted</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
                <isActive>false</isActive>
                <label>Invalid Number</label>
            </value>
            <value>
                <fullName>Junk Lead</fullName>
                <isActive>false</isActive>
                <label>Junk Lead</label>
            </value>
            <value>
                <fullName>No Contact</fullName>
                <isActive>false</isActive>
                <label>No Contact</label>
            </value>
            <value>
                <fullName>Not Actioned</fullName>
                <isActive>false</isActive>
                <label>Not Actioned</label>
            </value>
            <value>
                <fullName>Not Interested</fullName>
                <isActive>false</isActive>
                <label>Not Interested</label>
            </value>
            <value>
                <fullName>Tele-Meeting Fixed</fullName>
                <isActive>false</isActive>
                <label>Tele-Meeting Fixed</label>
            </value>
            <value>
                <fullName>Visit Proposed</fullName>
                <isActive>false</isActive>
                <label>Visit Proposed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/RDS_Country__c.field-meta.xml
<CustomField>
    <fullName>RDS_Country__c</fullName>
    <label>Dialing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United Arab Emirates</fullName>
                <default>true</default>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Cote D&apos;Ivoire</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Ghana</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Israel</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/LeadNurturingControllerTest.cls
@isTest
public class LeadNurturingControllerTest {
	@isTest
    public static void testLeadNurturingController(){
        Map<String, Id> recordMap = TestDataFactory.createMasterProject('Test Project');
        Id oppId  =   recordMap.get('OPPORTUNITY');
        Id unitId = recordMap.get('UNIT');
        Id projectId = recordMap.get('PROJECT');
        Id projCharges = recordMap.get('BASIC');
        Id towerId = recordMap.get('TOWER');
        Lead l = new Lead();
        l.lastname='Test1';
        l.email='test@test.com';
        l.MobilePhone = '1234567891';
        l.Project__c =projectId;
        l.RDS_Country__c ='Test India';
        l.Campaign_Code__c='Test Campaign';
        l.ownerId = UserInfo.getUserId();
        l.Last_Attempt_Status__c='No Contact - Follow-up';
        insert l;
        LeadNurturingController.getLeadNurturingConfigs();
        Day_Tracking__c d = new Day_Tracking__c();
        d.Name = 'Day 1';
        d.Lead__c = l.Id;
        insert d;
        Attempt_Tracking__c a = new Attempt_Tracking__c();
        a.Day_Tracking__c = d.Id;
        a.Attempted_By__c = UserInfo.getUserId();
        a.Name = 'Email';
        a.Attempt_Sequence__c = '1';
        insert a;
        LeadNurturingController.loadEmailTemplate(d.Id);
        LeadNurturingController.sendEmailToCustomer(d.Id);
        Database.executeBatch(new CreateLeadDailyTrackingBatch());
        Attempt_Tracking__c a1 = new Attempt_Tracking__c();
        a1.Day_Tracking__c = d.Id;
        a1.Attempted_By__c = UserInfo.getUserId();
        a1.Name = 'Official Mobile';
        a1.Attempt_Sequence__c = '3';
        insert a1;
        a1.Status__c = 'No Contact - Follow-up';
        update a1;
    }
}