force-app/main/default/objects/Attempt_Tracking__c/Attempt_Tracking__c.object-meta.xml
<CustomObject>
    <label>Attempt Tracking</label>
    <nameField>
        <label>Attempt Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attempt Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attempt_Tracking__c/fields/Attempted_By__c.field-meta.xml
<CustomField>
    <fullName>Attempted_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attempt Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Attempt_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attempt_Tracking__c/fields/Day_Tracking__c.field-meta.xml
<CustomField>
    <fullName>Day_Tracking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Day Tracking</label>
    <referenceTo>Day_Tracking__c</referenceTo>
    <relationshipLabel>Attempt Trackings</relationshipLabel>
    <relationshipName>Attempt_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attempt_Tracking__c/recordTypes/Email.recordType-meta.xml
<RecordType>
    <fullName>Email</fullName>
    <active>true</active>
    <label>Email</label>
</RecordType>

force-app/main/default/objects/Day_Tracking__c/Day_Tracking__c.object-meta.xml
<CustomObject>
    <label>Day Tracking</label>
    <nameField>
        <label>Days Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Day Trackings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Day_Tracking__c/fields/Enquiry__c.field-meta.xml
<CustomField>
    <fullName>Enquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enquiry</label>
    <referenceTo>PropStrength__Request__c</referenceTo>
    <relationshipLabel>Day Trackings</relationshipLabel>
    <relationshipName>Day_Trackings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Day_Tracking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>No Contact - Follow-up</fullName>
            </value>
            <value>
                <fullName>Sobha Landline - Contacted</fullName>
            </value>
            <value>
                <fullName>WhatsApp - Contacted</fullName>
            </value>
            <value>
                <fullName>Email - Contacted</fullName>
            </value>
            <value>
                <fullName>Official Mobile - Contacted</fullName>
            </value>
            <value>
                <fullName>Official Landline - Contacted</fullName>
            </value>
            <value>
                <fullName>WhatsApp Not Available</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVAILABLE</fullName>
                <label>Available</label>
            </value>
            <value>
                <fullName>BUSY</fullName>
                <label>Busy</label>
            </value>
            <value>
                <fullName>BREAK</fullName>
                <label>Break</label>
            </value>
            <value>
                <fullName>OUTCALL</fullName>
                <label>OutCall</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnquiryNurturingController.cls
public class EnquiryNurturingController {    
    @AuraEnabled
    public static string loadEmailTemplate(String dayTrackingId) {
        List<Attempt_Tracking__c> attemptList = new List<Attempt_Tracking__c>();
        List<EmailTemplate> emailTemplate = new List<EmailTemplate>();
        String templateName = '';
        String emailBody = '';
        attemptList = [SELECT Id, Status__c, Day_Tracking__r.Name, 
                        Attempted_By__r.Name 
                        FROM Attempt_Tracking__c 
                        WHERE Day_Tracking__c =: dayTrackingId AND 
                            Name = 'Email' LIMIT 1];
        if(!attemptList.isEmpty() && attemptList.size()>0) {
            templateName = attemptList[0].Day_Tracking__r.Name;
            templateName = templateName.replace(' ','_');
            templateName = 'Enquiry_Follow_up_Email_Customer_' + templateName;
        }
        if(!String.isBlank(templateName)) {
            emailTemplate = [SELECT Id, Subject, Description, HtmlValue, 
                                DeveloperName, Body 
                                FROM EmailTemplate 
                                WHERE DeveloperName =: templateName LIMIT 1];
        }
        if(!emailTemplate.isEmpty() && emailTemplate.size()>0 && 
            !attemptList.isEmpty() && attemptList.size()>0) {
            emailBody = emailTemplate[0].Body;
            emailBody = emailBody.replace('#AGENT_NAME#', UserInfo.getName());
        }
        return emailBody;
    }
    @AuraEnabled
    public static void sendEmailToCustomer(string dayTrackingId) {
        List<Attempt_Tracking__c> attemptList = new List<Attempt_Tracking__c>();
        List<EmailTemplate> emailTemplate = new List<EmailTemplate>();
        String templateName = '';
        attemptList = [SELECT Id, Status__c, Day_Tracking__r.Enquiry__r.PropStrength__Email_Address__c, 
                       Day_Tracking__r.Enquiry__r.PropStrength__Primary_Contact__r.email,
                        Day_Tracking__r.Name, Attempted_By__r.Name 
                        FROM Attempt_Tracking__c 
                        WHERE Day_Tracking__c =: dayTrackingId AND 
                            Name = 'Email' LIMIT 1];
        if(!attemptList.isEmpty() && attemptList.size()>0) {
            templateName = attemptList[0].Day_Tracking__r.Name;
            templateName = templateName.replace(' ','_');
            templateName = 'Enquiry_Follow_up_Email_Customer_' + templateName;
        }
        System.debug('templateName/***--'+templateName);
        if(!String.isBlank(templateName)) {
            emailTemplate = [SELECT Id, Subject, Description, HtmlValue, 
                                DeveloperName, Body 
                                FROM EmailTemplate 
                                WHERE DeveloperName =: templateName LIMIT 1];
        }
        if(!emailTemplate.isEmpty() && emailTemplate.size()>0 && 
            emailTemplate[0].Subject != null && 
            !attemptList.isEmpty() && attemptList.size()>0 && 
            attemptList[0].Day_Tracking__r.Enquiry__r.PropStrength__Email_Address__c != null) { 
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] {attemptList[0].Day_Tracking__r.Enquiry__r.PropStrength__Primary_Contact__r.email};
            mail.setToAddresses(toAddresses);
            mail.setSubject(emailTemplate[0].Subject);
            String emailBody = emailTemplate[0].HtmlValue;
            emailBody = emailBody.replace('#AGENT_NAME#', UserInfo.getName());
            mail.setHtmlBody(emailBody);
            mail.setReplyTo(UserInfo.getUserEmail());
            mail.setSenderDisplayName(UserInfo.getName()); 
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            attemptList[0].Status__c = 'No Contact - Follow-up';
            update attemptList[0];
        }
    }
}