force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Car_Park_Count_1__c.field-meta.xml
<CustomField>
    <fullName>Car_Park_Count_1__c</fullName>
    <label>Car Park Count 1</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Car_Park_Type_1__c.field-meta.xml
<CustomField>
    <fullName>Car_Park_Type_1__c</fullName>
    <label>Car Park Type 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Stack</fullName>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Tandem</fullName>
            </value>
            <value>
                <fullName>2 Wheeler</fullName>
            </value>
            <value>
                <fullName>Covered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Chargeable_Area__c.field-meta.xml
<CustomField>
    <fullName>Chargeable_Area__c</fullName>
    <label>Chargeable Area</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/DLD_Building_Number__c.field-meta.xml
<CustomField>
    <fullName>DLD_Building_Number__c</fullName>
    <formula>Tower__r.Building_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DLD Building Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Floor_No_to_print__c.field-meta.xml
<CustomField>
    <fullName>Floor_No_to_print__c</fullName>
    <label>Floor No. to print</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/No_of_Bedroom__c.field-meta.xml
<CustomField>
    <fullName>No_of_Bedroom__c</fullName>
    <label>No. of Bedroom</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Not_Available_for_Sales__c.field-meta.xml
<CustomField>
    <fullName>Not_Available_for_Sales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not Available for Sales</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Parking_Bay_Allocation_No__c.field-meta.xml
<CustomField>
    <fullName>Parking_Bay_Allocation_No__c</fullName>
    <label>Parking Bay Allocation No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Permitted_Use__c.field-meta.xml
<CustomField>
    <fullName>Permitted_Use__c</fullName>
    <label>Permitted Use</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Plot_Area__c.field-meta.xml
<CustomField>
    <fullName>Plot_Area__c</fullName>
    <label>Plot Area (For Villas)</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project_Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Property_Type__c</fullName>
    <label>Project Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Puchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Puchase_Price__c</fullName>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/RERA_Chargeable_Area_Sq_Ft__c.field-meta.xml
<CustomField>
    <fullName>RERA_Chargeable_Area_Sq_Ft__c</fullName>
    <label>RERA Chargeable Area (Sq. Ft.)</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestUnitTriggerHandler.cls
@isTest
public class TestUnitTriggerHandler {

    @isTest
    static void testSendToMobileAPI() {
        
        Mobile_TestUtil.createBooking();
        
        Map<Id,Unit__c> unitsMap = new Map<Id,Unit__c>();
        Unit__c u = [Select id,Permitted_Use__c ,Parking_Bay_Allocation_No__c ,RERA_Chargeable_Area_Sq_Ft__c,Plot_Area__c,Chargeable_Area__c ,Car_Park_Count_1__c,Car_Park_Type_1__c ,Project_Property_Type__c,name,Floor_No_to_print__c,Unit_Type__c,No_of_Bedroom__c,Puchase_Price__c,DLD_Building_Number__c From Unit__c limit 1];
        unitsMap.put(u.id,u); 
        
        List<Unit__c> updatedUnits = new List<Unit__c>();
        u.name = 'UnitChanged';
        u.Floor_No_to_print__c = 'flr';
        u.Unit_Type__c  = 'Villa';
        u.Puchase_Price__c = 1234567;
        u.No_of_Bedroom__c = '3';
        u.Not_Available_for_Sales__c = true;
      //  u.DLD_Building_Number__c = '12345';
        u.Permitted_Use__c = 'Residential';
        u.Project_Property_Type__c = 'Residential';
        u.Car_Park_Count_1__c = 1;
        u.Car_Park_Type_1__c  = 'Open';
        u.Chargeable_Area__c = 1323.12;
        u.Plot_Area__c = 2343.34;
        u.RERA_Chargeable_Area_Sq_Ft__c = 1234.12;
        u.Parking_Bay_Allocation_No__c = '23423';
        update u;
        
        Unit__c uUpdated = [Select id,name,Permitted_Use__c ,Parking_Bay_Allocation_No__c ,RERA_Chargeable_Area_Sq_Ft__c,Plot_Area__c,Chargeable_Area__c ,Car_Park_Count_1__c,Car_Park_Type_1__c ,Project_Property_Type__c,Floor_No_to_print__c,Unit_Type__c,No_of_Bedroom__c,Puchase_Price__c,DLD_Building_Number__c From Unit__c where id=:u.id];
		List<Unit__c> updatedList = new List<Unit__c>();
        updatedList.add(uUpdated);
        // Serialize newUnitList to JSON
        String newUnitString = JSON.serialize(updatedList);

        // Call the future method
        Test.startTest();
        UnitTriggerHandler.sendToMobileAPI(newUnitString, JSON.serialize(unitsMap));
        UnitTriggerHandler.sendToMobileAPI(newUnitString, null);
        Test.stopTest();
    }
    
    @isTest
    static void testSendToMobileAPI2() {
        
        Mobile_TestUtil.createBooking();
        
        Map<Id,Unit__c> unitsMap = new Map<Id,Unit__c>();
        Unit__c u = [Select id,Permitted_Use__c ,Parking_Bay_Allocation_No__c ,RERA_Chargeable_Area_Sq_Ft__c,Plot_Area__c,Chargeable_Area__c ,Car_Park_Count_1__c,Car_Park_Type_1__c ,Project_Property_Type__c,name,Floor_No_to_print__c,Unit_Type__c,No_of_Bedroom__c,Puchase_Price__c,DLD_Building_Number__c From Unit__c limit 1];
        unitsMap.put(u.id,u); 
        String oldMapString = JSON.serialize(unitsMap);
        
        List<Unit__c> updatedUnits = new List<Unit__c>();
        u.name = 'UnitChanged';
        u.Floor_No_to_print__c = 'flr';
        u.Unit_Type__c  = 'Villa';
        u.Puchase_Price__c = 1234567;
        u.No_of_Bedroom__c = '3';
        u.Not_Available_for_Sales__c = true;
       // u.DLD_Building_Number__c = '12345';
        u.Permitted_Use__c = 'Residential';
        u.Project_Property_Type__c = 'Residential';
        u.Car_Park_Count_1__c = 1;
        u.Car_Park_Type_1__c  = 'Open';
        u.Chargeable_Area__c = 1323.12;
        u.Plot_Area__c = 2343.34;
        u.RERA_Chargeable_Area_Sq_Ft__c = 1234.12;
        u.Parking_Bay_Allocation_No__c = '23423';
        update u;
        
        Unit__c uUpdated = [Select id,name,Permitted_Use__c ,Parking_Bay_Allocation_No__c ,RERA_Chargeable_Area_Sq_Ft__c,Plot_Area__c,Chargeable_Area__c ,Car_Park_Count_1__c,Car_Park_Type_1__c ,Project_Property_Type__c,Floor_No_to_print__c,Unit_Type__c,No_of_Bedroom__c,Puchase_Price__c,DLD_Building_Number__c From Unit__c where id=:u.id];
		List<Unit__c> updatedList = new List<Unit__c>();
        updatedList.add(uUpdated);
        // Serialize newUnitList to JSON
        String newUnitString = JSON.serialize(updatedList);

        // Call the future method
        Test.startTest();
        UnitTriggerHandler.sendToMobileAPI(newUnitString, oldMapString);
        Test.stopTest();
    }
}