force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <label>Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Events3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/City_Country__c.field-meta.xml
<CustomField>
    <fullName>City_Country__c</fullName>
    <label>City (Enter Full Name Correctly)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Abuja</fullName>
            </value>
            <value>
                <fullName>Addis Ababa</fullName>
            </value>
            <value>
                <fullName>Agra</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Al Ain</fullName>
            </value>
            <value>
                <fullName>Alger</fullName>
            </value>
            <value>
                <fullName>Almaty</fullName>
                <label>ALMATY</label>
            </value>
            <value>
                <fullName>Amsterdam</fullName>
                <label>AMSTERDAM</label>
            </value>
            <value>
                <fullName>Ankara</fullName>
            </value>
            <value>
                <fullName>Astana</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>Baghdad</fullName>
                <label>BAGHDAD</label>
            </value>
            <value>
                <fullName>Baku</fullName>
            </value>
            <value>
                <fullName>bandar abbas</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
                <label>BANGALORE</label>
            </value>
            <value>
                <fullName>Bangkok</fullName>
            </value>
            <value>
                <fullName>Basel</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>BEIRUT</fullName>
            </value>
            <value>
                <fullName>Belgrade</fullName>
                <label>BELGRADE</label>
            </value>
            <value>
                <fullName>BERLIN</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Bishkek</fullName>
            </value>
            <value>
                <fullName>Bradford</fullName>
            </value>
            <value>
                <fullName>Brighton</fullName>
            </value>
            <value>
                <fullName>Brussels</fullName>
            </value>
            <value>
                <fullName>Bucharest</fullName>
                <label>BUCHAREST</label>
            </value>
            <value>
                <fullName>Bursa</fullName>
            </value>
            <value>
                <fullName>Cairo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Confirmed_No_of_Meeting__c.field-meta.xml
<CustomField>
    <fullName>Confirmed_No_of_Meeting__c</fullName>
    <label>Confirmed No. of Meeting</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
                <label>AUSTRALIA</label>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Cameroon</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
                <label>CANADA</label>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>Czech Republic</fullName>
            </value>
            <value>
                <fullName>Democratic Republic of Congo</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>egypt</fullName>
                <label>Egypt</label>
            </value>
            <value>
                <fullName>Ethiopia</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
                <label>GERMANY</label>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
                <label>HONG KONG</label>
            </value>
            <value>
                <fullName>India</fullName>
                <label>INDIA</label>
            </value>
            <value>
                <fullName>Indonesia</fullName>
                <label>INDONESIA</label>
            </value>
            <value>
                <fullName>Iran</fullName>
            </value>
            <value>
                <fullName>Iraq</fullName>
                <label>IRAQ</label>
            </value>
            <value>
                <fullName>Israel</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>Kazakhstan</fullName>
            </value>
            <value>
                <fullName>Kenya</fullName>
            </value>
            <value>
                <fullName>Korea</fullName>
            </value>
            <value>
                <fullName>KSA</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Kyrgyzstan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Date_Of_Event__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Event__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Date_of_Proposal__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Proposal__c</fullName>
    <formula>CreatedDate</formula>
    <label>Date Of Proposal</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/End_Date_Of_Event__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Of_Event__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/End_Time_of_the_Event__c.field-meta.xml
<CustomField>
    <fullName>End_Time_of_the_Event__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Start_Time_of_the_Event__c.field-meta.xml
<CustomField>
    <fullName>Start_Time_of_the_Event__c</fullName>
    <label>Start time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/classes/ConfirmNoOfMeetingBatch.cls
global class ConfirmNoOfMeetingBatch Implements Schedulable {
    global void execute(SchedulableContext sc)
    {
        findEvents();   
    }
    
    public void findEvents(){
        DateTime days15DateTime = System.today().addDays(15);
        Date days15Date = Date.newInstance(days15DateTime.year(), days15DateTime.month(), days15DateTime.day());
        List<Events__c> listOfEvents = [select Id,Name,Date_of_Proposal__c,Date_Of_Event__c,End_Date_Of_Event__c,City_Country__c,Country__c,Start_Time_of_the_Event__c,End_Time_of_the_Event__c,Confirmed_No_of_Meeting__c,Channel_Relationship_Manager__c,Channel_Relationship_Manager__r.Email from Events__c where Date_Of_Event__c =: days15Date]; 
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        for(Events__c e : listOfEvents){
            if(e.Channel_Relationship_Manager__c != null){
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();  
                email.setSubject('Reminder to update Confirmed No. Of Meeting');
                email.setToAddresses(new List<string>{e.Channel_Relationship_Manager__r.Email});
                
                string dateOfProposal = (e.Date_of_Proposal__c!=null)?e.Date_of_Proposal__c.format():'';
                string startDate = (e.Date_Of_Event__c!=null)?e.Date_Of_Event__c.format():'';
                string endDate = (e.End_Date_Of_Event__c!=null)?e.End_Date_Of_Event__c.format():'';
                
                string htmlBody = 'Kind Attention,<br/><br/>';
                htmlBody = htmlBody + 'Following event is due in 15 days, please update Confirmed No. Of Meeting on priority.<br/><br/>';
                htmlBody = htmlBody + '<table border="1" style="border-collapse: collapse">';
                htmlBody = htmlBody + '<tr><td>' + 'Event Name' + '</td><td>' + e.Name + '</td></tr>';
                htmlBody = htmlBody + '<tr><td>' + 'Date of Proposal' + '</td><td>' + dateOfProposal + '</td></tr>';
                htmlBody = htmlBody + '<tr><td>' + 'Start Date of the Event' + '</td><td>' + startDate + '</td></tr>';
                htmlBody = htmlBody + '<tr><td>' + 'End Date of the Event' + '</td><td>' + endDate + '</td></tr>';
                htmlBody = htmlBody + '<tr><td>' + 'Start Time of the Event' + '</td><td>' + e.Start_Time_of_the_Event__c + '</td></tr>';
                htmlBody = htmlBody + '<tr><td>' + 'End Time of the Event' + '</td><td>' + e.End_Time_of_the_Event__c + '</td></tr>';
                htmlBody = htmlBody + '<tr><td>' + 'City & Country' + '</td><td>' + e.City_Country__c + ', ' + e.Country__c + '</td></tr>';
                htmlBody += '</table><br/><br/>';
                htmlBody += 'Regards,<br/>';
                htmlBody += 'Salesforce Team.';
                
                email.setHtmlBody(htmlBody);
                emails.add(email);
            }
        }
        if(emails.size()>0){
            Messaging.sendEmail(emails);
        }
    }
}