force-app/main/default/objects/Amenity__c/Amenity__c.object-meta.xml
<CustomObject>
    <label>Amenities</label>
    <nameField>
        <label>Amenity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aminities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Amenity__c/fields/Master_Project__c.field-meta.xml
<CustomField>
    <fullName>Master_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Project</label>
    <referenceTo>Master_Project__c</referenceTo>
    <relationshipLabel>Amenities</relationshipLabel>
    <relationshipName>Aminities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Amenity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Amenity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GYM</fullName>
            </value>
            <value>
                <fullName>Swimming Pool</fullName>
            </value>
            <value>
                <fullName>Garden</fullName>
            </value>
            <value>
                <fullName>Kids Play Area</fullName>
            </value>
            <value>
                <fullName>Retail Spaces</fullName>
            </value>
            <value>
                <fullName>Rooftop Terrace</fullName>
            </value>
            <value>
                <fullName>Health Club</fullName>
            </value>
            <value>
                <fullName>Event Space</fullName>
            </value>
            <value>
                <fullName>Spin Studio</fullName>
            </value>
            <value>
                <fullName>Yoga Zone</fullName>
            </value>
            <value>
                <fullName>Pentanque Boules Lawn</fullName>
            </value>
            <value>
                <fullName>Tai Chi Terrace</fullName>
            </value>
            <value>
                <fullName>Terrace</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Tennis</fullName>
            </value>
            <value>
                <fullName>Paddle</fullName>
            </value>
            <value>
                <fullName>Theatre</fullName>
            </value>
            <value>
                <fullName>Basketball Court</fullName>
            </value>
            <value>
                <fullName>Walking and Jogging Track</fullName>
            </value>
            <value>
                <fullName>Sky Garden</fullName>
            </value>
            <value>
                <fullName>Barbeque Area</fullName>
            </value>
            <value>
                <fullName>Outdoor Games Area</fullName>
            </value>
            <value>
                <fullName>Outdoor Cinema</fullName>
            </value>
            <value>
                <fullName>Zen Garden</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Sauna</fullName>
            </value>
            <value>
                <fullName>Infinity Pool</fullName>
            </value>
            <value>
                <fullName>Swimming Pool Cabana</fullName>
            </value>
            <value>
                <fullName>Sky Deck</fullName>
            </value>
            <value>
                <fullName>Open Amphitheater</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attractions__c/Attractions__c.object-meta.xml
<CustomObject>
    <label>Attractions</label>
    <nameField>
        <label>Attraction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attractions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attractions__c/fields/Attraction_Type__c.field-meta.xml
<CustomField>
    <fullName>Attraction_Type__c</fullName>
    <label>Attraction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mall</fullName>
            </value>
            <value>
                <fullName>Bus Station</fullName>
            </value>
            <value>
                <fullName>Cinemas</fullName>
            </value>
            <value>
                <fullName>Schools</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Hospitals</fullName>
            </value>
            <value>
                <fullName>Clinics</fullName>
            </value>
            <value>
                <fullName>River</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Ferris Wheel</fullName>
            </value>
            <value>
                <fullName>Ice Rink</fullName>
            </value>
            <value>
                <fullName>Island</fullName>
            </value>
            <value>
                <fullName>Harbour</fullName>
            </value>
            <value>
                <fullName>Play Area</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attractions__c/fields/Master_Project__c.field-meta.xml
<CustomField>
    <fullName>Master_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Project</label>
    <referenceTo>Master_Project__c</referenceTo>
    <relationshipLabel>Attractions</relationshipLabel>
    <relationshipName>Attractions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Project__c/Master_Project__c.object-meta.xml
<CustomObject>
    <label>Master Project</label>
    <nameField>
        <label>Master Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Project__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>Thailand</fullName>
            </value>
            <value>
                <fullName>Hongkong</fullName>
            </value>
            <value>
                <fullName>Malaysia</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Project__c/fields/latitude__c.field-meta.xml
<CustomField>
    <fullName>latitude__c</fullName>
    <label>latitude</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Project__c/fields/longitude__c.field-meta.xml
<CustomField>
    <fullName>longitude__c</fullName>
    <label>longitude</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Project__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/ Province</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Master_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Construction Complete</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Construction Not Started</fullName>
            </value>
            <value>
                <fullName>Pre-launch</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Project__c/fields/Type_Of_Project__c.field-meta.xml
<CustomField>
    <fullName>Type_Of_Project__c</fullName>
    <label>Type Of Project</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial + Residential</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Multi Use</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Master_Project__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/ Postal Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/masterProjectTriggerHelper_test.cls
@isTest
public class masterProjectTriggerHelper_test {
    
    @testSetup
    Static void makeData(){
        Master_Project__c project = new Master_Project__c(
            Name = 'Test Project',
            Street__c = '123 Test St',
            City__c = 'Test City',
            State_Province__c = 'TS',
            Zip_Postal_Code__c = '12345',
            Country__c = 'india',
            Max_Budget__c = 100000,
            Min_Budget__c = 50000,
            longitude__c = '123.456',
            latitude__c = '78.910',
            Status__c = 'On Hold',
            Type_of_Project__c = 'Retail'
        );
       
        insert project;
    }

    @isTest
    static void testSendToMobileMasterProject_Update() {
        
        List<Master_Project__c> mpList = [select id, name from Master_Project__c ];
        for(Master_Project__c mp : mpList){
			mp.name = mp.name + 'testUpdate';
        }
        
        Amenity__c amt = new Amenity__c(Name ='TestAMT', Type__c='Swimming Pool', Master_Project__c = mpList[0].Id);
        insert amt;
        
        Attractions__c attr = new Attractions__c(Name ='TestAMT', Attraction_Type__c='Cinemas', Master_Project__c = mpList[0].Id);
 		insert attr;
        update mpList;
    }
    
    @isTest
    static void testSendToMobileMasterProject_Insert() {
        // Setup test data

        
        Master_Project__c project = new Master_Project__c(
            Name = 'Test Project',
            Street__c = '123 Test St',
            City__c = 'Test City',
            State_Province__c = 'TS',
            Zip_Postal_Code__c = '12345',
            Country__c = 'india',
            Max_Budget__c = 100000,
            Min_Budget__c = 50000,
            longitude__c = '123.456',
            latitude__c = '78.910',
            Status__c = 'On Hold',
            Type_of_Project__c = 'Retail'
        );
        
        Test.startTest();
        
        // Insert record
        insert project;
        // for exception Coveraage
        project.Name = 'Test Project';
        update project;
        // Trigger should call the method
        Test.stopTest();

    }
    
    

    @isTest
    static void testSendToMobileMasterProject_TriggerFlagFalse() {
        // Setup test data
     
        Master_Project__c project = new Master_Project__c(
            Name = 'Test Project',
            Street__c = '123 Test St',
            City__c = 'Test City',
            State_Province__c = 'TS',
            Zip_Postal_Code__c = '12345',
            Country__c = 'india',
            Max_Budget__c = 100000,
            Min_Budget__c = 50000,
            longitude__c = '123.456',
            latitude__c = '78.910',
            Status__c = 'On Hold',
            Type_of_Project__c = 'Retail'
        );
        
        Test.startTest();
        insert project;
        Test.stopTest();
        
 
    }

    @isTest
    static void testSendToMobileAPIMasterProject() {
        // Setup test data
     
        Master_Project__c project = new Master_Project__c(
            Name = 'Test Project',
            Street__c = '123 Test St',
            City__c = 'Test City',
            State_Province__c = 'TS',
            Zip_Postal_Code__c = '12345',
            Country__c = 'india',
            Max_Budget__c = 100000,
            Min_Budget__c = 50000,
            longitude__c = '123.456',
            latitude__c = '78.910',
            Status__c = 'On Hold',
            Type_of_Project__c = 'Retail'
        );
         
        insert project;
        Test.startTest();
        masterProjectTriggerHelper.sendToMobileAPIMasterProject(new Set<Id>{project.Id});
        Test.stopTest();
 
    }
}