force-app/main/default/objects/Amenity__c/Amenity__c.object-meta.xml
<CustomObject>
    <label>Amenities</label>
    <nameField>
        <label>Amenity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aminities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Amenity__c/fields/Master_Project__c.field-meta.xml
<CustomField>
    <fullName>Master_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Project</label>
    <referenceTo>Master_Project__c</referenceTo>
    <relationshipLabel>Amenities</relationshipLabel>
    <relationshipName>Aminities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Amenity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Amenities</relationshipLabel>
    <relationshipName>Amenities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Amenity__c/fields/Project_PS__c.field-meta.xml
<CustomField>
    <fullName>Project_PS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>PropStrength__Projects__c</referenceTo>
    <relationshipLabel>Amenities</relationshipLabel>
    <relationshipName>Aminities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Amenity__c/fields/Tower_PS__c.field-meta.xml
<CustomField>
    <fullName>Tower_PS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>PropStrength__Tower__c</referenceTo>
    <relationshipLabel>Amenities</relationshipLabel>
    <relationshipName>Aminities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Amenity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Amenity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GYM</fullName>
            </value>
            <value>
                <fullName>Swimming Pool</fullName>
            </value>
            <value>
                <fullName>Garden</fullName>
            </value>
            <value>
                <fullName>Kids Play Area</fullName>
            </value>
            <value>
                <fullName>Retail Spaces</fullName>
            </value>
            <value>
                <fullName>Rooftop Terrace</fullName>
            </value>
            <value>
                <fullName>Health Club</fullName>
            </value>
            <value>
                <fullName>Event Space</fullName>
            </value>
            <value>
                <fullName>Spin Studio</fullName>
            </value>
            <value>
                <fullName>Yoga Zone</fullName>
            </value>
            <value>
                <fullName>Pentanque Boules Lawn</fullName>
            </value>
            <value>
                <fullName>Tai Chi Terrace</fullName>
            </value>
            <value>
                <fullName>Terrace</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Tennis</fullName>
            </value>
            <value>
                <fullName>Paddle</fullName>
            </value>
            <value>
                <fullName>Theatre</fullName>
            </value>
            <value>
                <fullName>Basketball Court</fullName>
            </value>
            <value>
                <fullName>Walking and Jogging Track</fullName>
            </value>
            <value>
                <fullName>Sky Garden</fullName>
            </value>
            <value>
                <fullName>Barbeque Area</fullName>
            </value>
            <value>
                <fullName>Outdoor Games Area</fullName>
            </value>
            <value>
                <fullName>Outdoor Cinema</fullName>
            </value>
            <value>
                <fullName>Zen Garden</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Sauna</fullName>
            </value>
            <value>
                <fullName>Infinity Pool</fullName>
            </value>
            <value>
                <fullName>Swimming Pool Cabana</fullName>
            </value>
            <value>
                <fullName>Sky Deck</fullName>
            </value>
            <value>
                <fullName>Open Amphitheater</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attractions__c/Attractions__c.object-meta.xml
<CustomObject>
    <label>Attractions</label>
    <nameField>
        <label>Attraction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attractions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attractions__c/fields/Attraction_Type__c.field-meta.xml
<CustomField>
    <fullName>Attraction_Type__c</fullName>
    <label>Attraction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mall</fullName>
            </value>
            <value>
                <fullName>Bus Station</fullName>
            </value>
            <value>
                <fullName>Cinemas</fullName>
            </value>
            <value>
                <fullName>Schools</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Hospitals</fullName>
            </value>
            <value>
                <fullName>Clinics</fullName>
            </value>
            <value>
                <fullName>River</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Ferris Wheel</fullName>
            </value>
            <value>
                <fullName>Ice Rink</fullName>
            </value>
            <value>
                <fullName>Island</fullName>
            </value>
            <value>
                <fullName>Harbour</fullName>
            </value>
            <value>
                <fullName>Play Area</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attractions__c/fields/Master_Project__c.field-meta.xml
<CustomField>
    <fullName>Master_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Project</label>
    <referenceTo>Master_Project__c</referenceTo>
    <relationshipLabel>Attractions</relationshipLabel>
    <relationshipName>Attractions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attractions__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Attractions</relationshipLabel>
    <relationshipName>Attractions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attractions__c/fields/Project_PS__c.field-meta.xml
<CustomField>
    <fullName>Project_PS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>PropStrength__Projects__c</referenceTo>
    <relationshipLabel>Attractions</relationshipLabel>
    <relationshipName>Attractions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attractions__c/fields/Tower_PS__c.field-meta.xml
<CustomField>
    <fullName>Tower_PS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>PropStrength__Tower__c</referenceTo>
    <relationshipLabel>Attractions</relationshipLabel>
    <relationshipName>Attractions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Project__c/Master_Project__c.object-meta.xml
<CustomObject>
    <label>Master Project</label>
    <nameField>
        <label>Master Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Master_Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Under Construction</fullName>
            </value>
            <value>
                <fullName>Construction Complete</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Construction Not Started</fullName>
            </value>
            <value>
                <fullName>Pre-launch</fullName>
            </value>
            <value>
                <fullName>Launch</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
                <isActive>false</isActive>
                <label>Inactive</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mobile_App__mdt/Mobile_App__mdt.object-meta.xml
<CustomObject>
    <label>Mobile App</label>
    <pluralLabel>Mobile App</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mobile_App__mdt/fields/Communities_endpoint__c.field-meta.xml
<CustomField>
    <fullName>Communities_endpoint__c</fullName>
    <label>Communities endpoint</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Mobile_App__mdt/fields/Project_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Project_Trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Project Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mobile_App__mdt/fields/sf_Token__c.field-meta.xml
<CustomField>
    <fullName>sf_Token__c</fullName>
    <label>sf-Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mobile_App__mdt/fields/Subscription_Key__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Key__c</fullName>
    <label>Subscription-Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mobile_App_Log__c/Mobile_App_Log__c.object-meta.xml
<CustomObject>
    <label>Mobile App Log</label>
    <nameField>
        <displayFormat>Log-{YY}-{MM}-{0000000}</displayFormat>
        <label>Mobile App Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mobile App Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mobile_App_Log__c/fields/Master_Project__c.field-meta.xml
<CustomField>
    <fullName>Master_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Project</label>
    <referenceTo>Master_Project__c</referenceTo>
    <relationshipLabel>Mobile App Logs</relationshipLabel>
    <relationshipName>Mobile_App_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mobile_App_Log__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>PropStrength__Projects__c</referenceTo>
    <relationshipLabel>Mobile App Logs</relationshipLabel>
    <relationshipName>Mobile_App_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mobile_App_Log__c/fields/Response_Body__c.field-meta.xml
<CustomField>
    <fullName>Response_Body__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectTriggerHelper.cls
public class ProjectTriggerHelper {
    public static void sendToMobile(List<PropStrength__Projects__c> newList,map<Id,PropStrength__Projects__c> oldMap) {
        Mobile_App__mdt mobile_appmdt = Mobile_App__mdt.getInstance('Mobile_Link');
        boolean trgFlg = mobile_appmdt.Project_Trigger__c;
        set<Id> projectIds = new Set<Id>();
        if(trgFlg || test.IsRunningtest()) {
            for(PropStrength__Projects__c pr : newList) {
                if(trigger.isInsert) {
                    if(pr.Name != null || pr.Master_Project__c != null || pr.Min_Area__c != null || pr.Max_Area__c != null || pr.PropStrength__Description__c != null) {
                           projectIds.add(pr.Id);
                       }
                } else if(trigger.isUpdate) {
                    if(pr.Name != oldMap.get(pr.Id).Name ||
                      pr.Master_Project__c != oldMap.get(pr.Id).Master_Project__c ||
                      pr.Min_Area__c != oldMap.get(pr.Id).Min_Area__c ||
                      pr.Max_Area__c != oldMap.get(pr.Id).Max_Area__c ||
                      pr.PropStrength__Description__c != oldMap.get(pr.Id).PropStrength__Description__c) {
                           projectIds.add(pr.Id);
                       }
                }
            }
            system.debug('projectIds::'+projectIds);
            if(!projectIds.isEmpty() && !System.IsBatch() && !System.isFuture()) {
                ProjectTriggerHelper.sendToMobileAPI(projectIds);
            }
        }
    }
    
    public static void convertRichTextToText(List<PropStrength__Projects__c> newList, map<Id,PropStrength__Projects__c> oldMap) {
        
        for(PropStrength__Projects__c pr : newList) {
         if(pr.Booking_Form_T_C__c != null) {
                pr.Booking_Form_T_C_Text__c = pr.Booking_Form_T_C__c.stripHtmlTags();
            System.debug('pr.Booking_Form_T_C_Text__c*-----'+pr.Booking_Form_T_C_Text__c);
         }
        }            
        
    }
    
    @future(callOut=true)
    Public static void sendToMobileAPI(set<Id> projectIds) {
        if(!projectIds.isEmpty()) {
            Mobile_App__mdt mobile_appmdt = Mobile_App__mdt.getInstance('Mobile_Link');
            String endPointURL = mobile_appmdt.Communities_endpoint__c;
            List<Mobile_App_Log__c> insertList = new List<Mobile_App_Log__c>();
            List<requestBodyWrapper> wraplst = new List<requestBodyWrapper>();
            List<PropStrength__Projects__c> projectList = [SELECT Id,Name,PropStrength__Description__c,Min_Area__c,Max_Area__c,
                                                           Master_Project__c,
                                                           (SELECT Id,Name,Type__c,Project_PS__c,Tower_PS__c FROM Aminities__r),
                                                           (SELECT Id,Name,Attraction_Type__c,Project_PS__c,Tower_PS__c FROM Attractions__r)
                                                           FROM PropStrength__Projects__c
                                                           WHERE Id IN: projectIds];
            if(!projectList.isEmpty()) {
                try{
                    String sftoken = mobile_appmdt.sf_Token__c;
                    String Subscription_Key = mobile_appmdt.Subscription_Key__c;
                    for(PropStrength__Projects__c pr : projectList) {
                        requestBodyWrapper wrap = new requestBodyWrapper();
                        wrap.sfCommunityId = pr.Id;
                        wrap.sfMasterCommunityId = pr.Master_Project__c;
                        wrap.name = (!String.isBlank(pr.Name) ? pr.Name : '');
                        wrap.minArea = (pr.Min_Area__c != null ? pr.Min_Area__c : 0);
                        wrap.maxArea  = (pr.Max_Area__c != null ? pr.Max_Area__c : 0);
                        wrap.description = (!String.isBlank(pr.PropStrength__Description__c) ? pr.PropStrength__Description__c : '');
                        if(pr.Aminities__r.size() > 0){
                            for(Amenity__c ame : pr.Aminities__r) {
                                amenities amenitywrap = new amenities();
                                amenitywrap.sfAmenityId = ame.Id;
                                amenitywrap.Name = ame.Name;
                                amenitywrap.type = ame.Type__c;
                                wrap.amenities.add(amenitywrap);
                            }
                        }
                        if(pr.Attractions__r.size() > 0){
                            for(Attractions__c attract  : pr.Attractions__r) {
                                attractions attractwrap = new attractions();
                                attractwrap.sfAttractionId = attract.Id;
                                attractwrap.Name = attract.Name;
                                attractwrap.type = attract.Attraction_Type__c;
                                wrap.attractions.add(attractwrap);
                            }
                        }
                        wraplst.add(wrap);
                    }
                    system.debug('wraplst::'+JSON.serialize(wraplst[0]));
                    if(wraplst != null){
                        String response = MobileIntegrationCallOutsAPI_PS.callMobileApp(endPointURL,'POST',JSON.serialize(wraplst[0]));
                        system.debug('response::'+response);
                        if(!String.isBlank(response)) {
                            for(PropStrength__Projects__c pr : projectList) {
                                Mobile_App_Log__c appLog = new Mobile_App_Log__c();
                                appLog.Project__c = pr.Id;
                                appLog.Request_Body__c = JSON.serialize(wraplst[0]);
                                appLog.API_Name__c = endPointURL;
                                appLog.Response_Body__c = response;
                                if(response.contains('Success')){
                                    appLog.Status__c = 'Success';
                                }else
                                    appLog.Status__c = 'Error';
                                insertList.add(appLog);
                            }
                            if(!insertList.isEmpty()) {
                                insert insertList;
                            }
                        }
                    }
                } catch(Exception e) {
                    for(PropStrength__Projects__c pr : projectList) {
                        Mobile_App_Log__c appLog = new Mobile_App_Log__c();
                        appLog.Project__c = pr.Id;
                        appLog.Status__c = 'Exception';
                        appLog.API_Name__c = endPointURL;
                        appLog.Request_Body__c = JSON.serialize(wraplst[0]);
                        appLog.Response_Body__c = String.valueOf(e.getStackTraceString());
                        insertList.add(appLog);
                    }
                    if(!insertList.isEmpty()) {
                        insert insertList;
                    }
                    system.debug('~~~~~Error: '+e.getStackTraceString());
                }
            }
        }
    }
    
    public class requestBodyWrapper{
        //string name;
        string name;
        string description;
        Decimal minArea;
        Decimal maxArea;
        String sfCommunityId;
        String sfMasterCommunityId;
        
        List<amenities> amenities = new List<amenities>();
        List<attractions> attractions = new List<attractions>();
    }
    
    public class amenities{
        String sfAmenityId;
        String name;
        String type;
    }
    
    public class attractions{
        String sfAttractionId;
        String name;
        String type;
    }
}