force-app/main/default/objects/Amenity__c/Amenity__c.object-meta.xml
<CustomObject>
    <label>Amenities</label>
    <nameField>
        <label>Amenity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aminities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Amenity__c/fields/Amenity_Name__c.field-meta.xml
<CustomField>
    <fullName>Amenity_Name__c</fullName>
    <label>Amenity Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Amenity__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Aminities</relationshipLabel>
    <relationshipName>Aminities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Amenity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Amenity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GYM</fullName>
            </value>
            <value>
                <fullName>Swimming Pool</fullName>
            </value>
            <value>
                <fullName>Garden</fullName>
            </value>
            <value>
                <fullName>Kids Play Area</fullName>
            </value>
            <value>
                <fullName>Retail Spaces</fullName>
            </value>
            <value>
                <fullName>Rooftop Terrace</fullName>
            </value>
            <value>
                <fullName>Health Club</fullName>
            </value>
            <value>
                <fullName>Event Space</fullName>
            </value>
            <value>
                <fullName>Spin Studio</fullName>
            </value>
            <value>
                <fullName>Yoga Zone</fullName>
            </value>
            <value>
                <fullName>Pentanque Boules Lawn</fullName>
            </value>
            <value>
                <fullName>Tai Chi Terrace</fullName>
            </value>
            <value>
                <fullName>Terrace</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Tennis</fullName>
            </value>
            <value>
                <fullName>Paddle</fullName>
            </value>
            <value>
                <fullName>Theatre</fullName>
            </value>
            <value>
                <fullName>Basketball Court</fullName>
            </value>
            <value>
                <fullName>Walking and Jogging Track</fullName>
            </value>
            <value>
                <fullName>Sky Garden</fullName>
            </value>
            <value>
                <fullName>Barbeque Area</fullName>
            </value>
            <value>
                <fullName>Outdoor Games Area</fullName>
            </value>
            <value>
                <fullName>Outdoor Cinema</fullName>
            </value>
            <value>
                <fullName>Zen Garden</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Sauna</fullName>
            </value>
            <value>
                <fullName>Infinity Pool</fullName>
            </value>
            <value>
                <fullName>Swimming Pool Cabana</fullName>
            </value>
            <value>
                <fullName>Sky Deck</fullName>
            </value>
            <value>
                <fullName>Open Amphitheater</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attractions__c/Attractions__c.object-meta.xml
<CustomObject>
    <label>Attractions</label>
    <nameField>
        <label>Attraction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attractions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attractions__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tower</label>
    <referenceTo>Tower__c</referenceTo>
    <relationshipLabel>Attractions</relationshipLabel>
    <relationshipName>Attractions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Completion_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Completion_Percentage__c</fullName>
    <label>Completion Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/Under_Construction__c.field-meta.xml
<CustomField>
    <fullName>Under_Construction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Under Construction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TowerTriggerHandlerTest.cls
@isTest
public class TowerTriggerHandlerTest {

    @isTest
    static void testSendToMobileAPI() {
        // Create test data
        Tower__c testTower = new Tower__c();
            testTower.Name = 'Test Tower';
            testTower.Under_Construction__c = false;
            testTower.Completion_Percentage__c = 10;
            // Add other required fields
        
        insert testTower;

        Tower__c testTower1 = new Tower__c();
            testTower.Name = 'Test Tower1';
            testTower.Under_Construction__c = true;
            testTower.Completion_Percentage__c = 9;
        testTower1.Id = testTower.Id;
        
        Amenity__c am = new Amenity__c();
        am.Name = 'test';
        am.Amenity_Name__c = 'Test';
        am.Type__c = 'Theatre';
        am.Tower__c = testTower.Id;
        insert am;
        
        Attractions__c att = new Attractions__c();
        att.Name = 'Twst';
        att.Tower__c = testTower.Id;
        insert att;
        

        
        Map<id,Tower__c> oldMap = new Map<id,Tower__c>();
        oldMap.put(testTower1.id,testTower1);
        // Call the future method
        
        Test.startTest();
        TowerTriggerHandler.sendToMobileAPI(JSON.serialize(new List<Tower__C>{ testTower }), JSON.serialize(oldMap));
        TowerTriggerHandler.sendToMobileAPI(JSON.serialize(new List<Tower__C>{ testTower }), null);
        Test.stopTest();

        // Add assertions based on your expected behavior
        // For example, check if the callout was made successfully and the response is as expected
        // assert...

        // Optionally, add more test cases for different scenarios
    }
}