force-app/main/default/objects/Amenity__c/Amenity__c.object-meta.xml
<CustomObject>
    <label>Amenities</label>
    <nameField>
        <label>Amenity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aminities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Amenity__c/fields/Sub_Project__c.field-meta.xml
<CustomField>
    <fullName>Sub_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Aminities</relationshipLabel>
    <relationshipName>Aminities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Amenity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Amenity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GYM</fullName>
            </value>
            <value>
                <fullName>Swimming Pool</fullName>
            </value>
            <value>
                <fullName>Garden</fullName>
            </value>
            <value>
                <fullName>Kids Play Area</fullName>
            </value>
            <value>
                <fullName>Retail Spaces</fullName>
            </value>
            <value>
                <fullName>Rooftop Terrace</fullName>
            </value>
            <value>
                <fullName>Health Club</fullName>
            </value>
            <value>
                <fullName>Event Space</fullName>
            </value>
            <value>
                <fullName>Spin Studio</fullName>
            </value>
            <value>
                <fullName>Yoga Zone</fullName>
            </value>
            <value>
                <fullName>Pentanque Boules Lawn</fullName>
            </value>
            <value>
                <fullName>Tai Chi Terrace</fullName>
            </value>
            <value>
                <fullName>Terrace</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Tennis</fullName>
            </value>
            <value>
                <fullName>Paddle</fullName>
            </value>
            <value>
                <fullName>Theatre</fullName>
            </value>
            <value>
                <fullName>Basketball Court</fullName>
            </value>
            <value>
                <fullName>Walking and Jogging Track</fullName>
            </value>
            <value>
                <fullName>Sky Garden</fullName>
            </value>
            <value>
                <fullName>Barbeque Area</fullName>
            </value>
            <value>
                <fullName>Outdoor Games Area</fullName>
            </value>
            <value>
                <fullName>Outdoor Cinema</fullName>
            </value>
            <value>
                <fullName>Zen Garden</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Sauna</fullName>
            </value>
            <value>
                <fullName>Infinity Pool</fullName>
            </value>
            <value>
                <fullName>Swimming Pool Cabana</fullName>
            </value>
            <value>
                <fullName>Sky Deck</fullName>
            </value>
            <value>
                <fullName>Open Amphitheater</fullName>
            </value>
            <value>
                <fullName>Mall</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attractions__c/Attractions__c.object-meta.xml
<CustomObject>
    <label>Attractions</label>
    <nameField>
        <label>Attraction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attractions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attractions__c/fields/Attraction_Type__c.field-meta.xml
<CustomField>
    <fullName>Attraction_Type__c</fullName>
    <label>Attraction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mall</fullName>
            </value>
            <value>
                <fullName>Bus Station</fullName>
            </value>
            <value>
                <fullName>Cinemas</fullName>
            </value>
            <value>
                <fullName>Schools</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Hospitals</fullName>
            </value>
            <value>
                <fullName>Clinics</fullName>
            </value>
            <value>
                <fullName>River</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Ferris Wheel</fullName>
            </value>
            <value>
                <fullName>Ice Rink</fullName>
            </value>
            <value>
                <fullName>Island</fullName>
            </value>
            <value>
                <fullName>Harbour</fullName>
            </value>
            <value>
                <fullName>Play Area</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attractions__c/fields/Sub_Project__c.field-meta.xml
<CustomField>
    <fullName>Sub_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Attractions</relationshipLabel>
    <relationshipName>Attractions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <label>Sub Project</label>
    <nameField>
        <label>Sub Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster__c/fields/Max_Area__c.field-meta.xml
<CustomField>
    <fullName>Max_Area__c</fullName>
    <label>Max Area</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Cluster__c/fields/Min_Area__c.field-meta.xml
<CustomField>
    <fullName>Min_Area__c</fullName>
    <label>Min Area</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_MB_clusTriggerHandler.cls
@isTest
public class Test_MB_clusTriggerHandler {
	
    @TestSetup
    static void testSetup(){
        List<Cluster__c> clusterList = new List<Cluster__c>();
        for(Integer i=0; i<6; i++){
            Cluster__c clus = new Cluster__c();
            if(i==1){
               clus = new Cluster__c( Name='PROJ'+i, Description__c='Ready to Move in (RTMI)',
                                     Min_Area__c = 100,
            						Max_Area__c = 200
                                     ); 
            } else {
            	clus = new Cluster__c( Name='PROJ'+i, Description__c='Ready to Move in (RTMI)',
                                     Min_Area__c = 100,
            						Max_Area__c = 200);
            }
            clusterList.add(clus);
        }
        insert clusterList;
        List<Amenity__c> ametiryList = new List<Amenity__c>();
        for(Integer i=0; i<5; i++){
            Amenity__c amt = new Amenity__c(Name ='TestAMT'+i, Type__c='PlayGround', Sub_Project__c=clusterList[i].Id);
            ametiryList.add(amt);
        }
        insert ametiryList;
        
        list<Attractions__c> attractionList = new List<Attractions__c>();
        for(Integer i=0; i<5; i++){
            Attractions__c attr = new Attractions__c(Name ='TestAMT'+i, Attraction_Type__c='Mall', Sub_Project__c=clusterList[i].Id);
            attractionList.add(attr);
        }
        insert attractionList;
    }
    
    @isTest
    static void testInsertMethod(){
        Map<Id, Cluster__c> oldMapData = new Map<Id, Cluster__c>();
    	List<Cluster__c> clusList = [SELECT Id, Name, Min_Area__c,Max_Area__c,  
                                        Description__c
                                       FROM Cluster__c];
       	system.debug('~~~~N: '+clusList);
        Test_MB_MockupClass.responseBodyWrapper wrap = new Test_MB_MockupClass.responseBodyWrapper();
        wrap.result = 'Success';
        Test.startTest();
        	Test.setMock(HttpCalloutMock.class, new Test_MB_MockupClass(JSON.serialize(wrap), 200, 'OK'));
        	clusTriggerHandler.sendToMobileAPI(JSON.serialize(clusList), null);
       	Test.stopTest();
    }
    
    @isTest
    static void testUpdateMethod(){
        Map<Id, Cluster__c> projectMap = new Map<Id, Cluster__c>([SELECT Id,Name, Min_Area__c,Max_Area__c,  
                                        Description__c
                                       FROM Cluster__c]);
        
        List<Cluster__c> projectList2 = [SELECT Id,Name, Min_Area__c,Max_Area__c,  
                                        Description__c
                                       FROM Cluster__c];
        
        List<Cluster__c> projectList3 = new List<Cluster__c>();
        Integer k=6;
        
        for(Cluster__c prj : projectList2){
            if(k!=6){
                prj.name = 'TestProjectPR'+k;
                prj.Min_Area__c = 600;
                prj.Max_Area__c = 700;
                prj.Description__c = 'desc'+k;
            }
            if(k==8){
            	prj.name = null;
                prj.Min_Area__c = 600;
                prj.Max_Area__c = 700;
                prj.Description__c = 'desc'+k;
            }
            k++;
            projectList3.add(prj);
        }
        update projectList3;
        Test_MB_MockupClass.responseBodyWrapper wrap = new Test_MB_MockupClass.responseBodyWrapper();
        wrap.result = 'Success';
        Test.startTest(); 
       		Test.setMock(HttpCalloutMock.class, new Test_MB_MockupClass(JSON.serialize(wrap), 200, 'OK'));
        	clusTriggerHandler.sendToMobileAPI(JSON.serialize(projectList3), JSON.serialize(projectMap));
        Test.stopTest();
    }
}