force-app/main/default/objects/Amenity__c/Amenity__c.object-meta.xml
<CustomObject>
    <label>Amenities</label>
    <nameField>
        <label>Amenity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aminities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Amenity__c/fields/Master_Project__c.field-meta.xml
<CustomField>
    <fullName>Master_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Project</label>
    <referenceTo>Master_Project__c</referenceTo>
    <relationshipLabel>Amenities</relationshipLabel>
    <relationshipName>Aminities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Amenity__c/fields/Project_PS__c.field-meta.xml
<CustomField>
    <fullName>Project_PS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>PropStrength__Projects__c</referenceTo>
    <relationshipLabel>Amenities</relationshipLabel>
    <relationshipName>Aminities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Amenity__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Amenity Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GYM</fullName>
            </value>
            <value>
                <fullName>Swimming Pool</fullName>
            </value>
            <value>
                <fullName>Garden</fullName>
            </value>
            <value>
                <fullName>Kids Play Area</fullName>
            </value>
            <value>
                <fullName>Retail Spaces</fullName>
            </value>
            <value>
                <fullName>Rooftop Terrace</fullName>
            </value>
            <value>
                <fullName>Health Club</fullName>
            </value>
            <value>
                <fullName>Event Space</fullName>
            </value>
            <value>
                <fullName>Spin Studio</fullName>
            </value>
            <value>
                <fullName>Yoga Zone</fullName>
            </value>
            <value>
                <fullName>Pentanque Boules Lawn</fullName>
            </value>
            <value>
                <fullName>Tai Chi Terrace</fullName>
            </value>
            <value>
                <fullName>Terrace</fullName>
            </value>
            <value>
                <fullName>Club House</fullName>
            </value>
            <value>
                <fullName>Tennis</fullName>
            </value>
            <value>
                <fullName>Paddle</fullName>
            </value>
            <value>
                <fullName>Theatre</fullName>
            </value>
            <value>
                <fullName>Basketball Court</fullName>
            </value>
            <value>
                <fullName>Walking and Jogging Track</fullName>
            </value>
            <value>
                <fullName>Sky Garden</fullName>
            </value>
            <value>
                <fullName>Barbeque Area</fullName>
            </value>
            <value>
                <fullName>Outdoor Games Area</fullName>
            </value>
            <value>
                <fullName>Outdoor Cinema</fullName>
            </value>
            <value>
                <fullName>Zen Garden</fullName>
            </value>
            <value>
                <fullName>Steam</fullName>
            </value>
            <value>
                <fullName>Sauna</fullName>
            </value>
            <value>
                <fullName>Infinity Pool</fullName>
            </value>
            <value>
                <fullName>Swimming Pool Cabana</fullName>
            </value>
            <value>
                <fullName>Sky Deck</fullName>
            </value>
            <value>
                <fullName>Open Amphitheater</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attractions__c/Attractions__c.object-meta.xml
<CustomObject>
    <label>Attractions</label>
    <nameField>
        <label>Attraction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attractions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Attractions__c/fields/Attraction_Type__c.field-meta.xml
<CustomField>
    <fullName>Attraction_Type__c</fullName>
    <label>Attraction Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mall</fullName>
            </value>
            <value>
                <fullName>Bus Station</fullName>
            </value>
            <value>
                <fullName>Cinemas</fullName>
            </value>
            <value>
                <fullName>Schools</fullName>
            </value>
            <value>
                <fullName>Shopping</fullName>
            </value>
            <value>
                <fullName>Hospitals</fullName>
            </value>
            <value>
                <fullName>Clinics</fullName>
            </value>
            <value>
                <fullName>River</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Ferris Wheel</fullName>
            </value>
            <value>
                <fullName>Ice Rink</fullName>
            </value>
            <value>
                <fullName>Island</fullName>
            </value>
            <value>
                <fullName>Harbour</fullName>
            </value>
            <value>
                <fullName>Play Area</fullName>
            </value>
            <value>
                <fullName>Residential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Attractions__c/fields/Master_Project__c.field-meta.xml
<CustomField>
    <fullName>Master_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Master Project</label>
    <referenceTo>Master_Project__c</referenceTo>
    <relationshipLabel>Attractions</relationshipLabel>
    <relationshipName>Attractions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Attractions__c/fields/Project_PS__c.field-meta.xml
<CustomField>
    <fullName>Project_PS__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>PropStrength__Projects__c</referenceTo>
    <relationshipLabel>Attractions</relationshipLabel>
    <relationshipName>Attractions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Master_Project__c/Master_Project__c.object-meta.xml
<CustomObject>
    <label>Master Project</label>
    <nameField>
        <label>Master Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Master Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectTriggerHelper_Test.cls
@isTest
public class ProjectTriggerHelper_Test {
    @TestSetup
    static void setup(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
    }
    
    @isTest
    static void Test1(){
        PropStrength__Projects__c project = new PropStrength__Projects__c();
        project.Name = 'Test Project 1'+String.valueOf(Math.random()).substring(0,5);
        project.Master_Project__c = null;
        project.Min_Area__c = null;
        project.Max_Area__c = null;
        project.PropStrength__Description__c = 'Description';
        insert project;
        
        Amenity__c amenity = new Amenity__c();
        amenity.Name = 'Test Amenity' ;
        amenity.Type__c = 'GYM' ;
        amenity.Project_PS__c = project.Id;
        insert amenity;
        
        Attractions__c attract = new Attractions__c();
        attract.Name = 'Test Attraction';
        attract.Attraction_Type__c = 'Cinemas';
        attract.Project_PS__c = project.Id;
        insert attract;
        
        project.Name = 'Test Project 2';
        update project;
        
    }
}