force-app/main/default/objects/Dashboard_Field_Configuration__mdt/Dashboard_Field_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>This is to store information on what all fields will be deisplayed on Audit Dashboard.</description>
    <label>Dashboard Field Configuration</label>
    <pluralLabel>DashboardFieldConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Dashboard_Field_Configuration__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <label>Field API Name</label>
    <length>144</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dashboard_Field_Configuration__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <label>Field Label</label>
    <length>144</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dashboard_Field_Configuration__mdt/fields/Order_Of_Column__c.field-meta.xml
<CustomField>
    <fullName>Order_Of_Column__c</fullName>
    <description>Order of the Column on Reciept Dashboard.</description>
    <label>Order Of Column</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Dashboard_Field_Configuration__mdt/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <label>Screen</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audit</fullName>
                <default>true</default>
                <label>Audit</label>
            </value>
            <value>
                <fullName>Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Final_Approver__c.field-meta.xml
<CustomField>
    <fullName>Final_Approver__c</fullName>
    <label>Final Approver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Audit_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Audit_Approval_Status__c</fullName>
    <label>Audit Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Under Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Legacy Record</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Audit_Approver_s_Comments__c.field-meta.xml
<CustomField>
    <fullName>Audit_Approver_s_Comments__c</fullName>
    <description>Audit Approver Comments.</description>
    <label>Audit Approver’s Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReceiptController.cls
public without sharing class ReceiptController {
    
    // Method to retrieve field configuration from Custom Metadata Type
    @AuraEnabled(cacheable=true)
    public static List<Dashboard_Field_Configuration__mdt> getDashboardFieldConfiguration(String screenType) {
        return [SELECT Field_API_Name__c, Field_Label__c FROM Dashboard_Field_Configuration__mdt WHERE Screen__c = :screenType ORDER by Order_Of_Column__c ];
    }
    
    // Method to fetch receipts with Cleared status and Under Approval
    @AuraEnabled(cacheable=false)
    public static List<SObject> getReceipts(String status) {
        List<Dashboard_Field_Configuration__mdt> fieldConfigs = getDashboardFieldConfiguration('Audit');
        String queryFields = generateQueryFields(fieldConfigs);
        queryFields += ',Payment_Request__r.Name ';
        String query = 'SELECT id, ' + queryFields + ' FROM Receipt__c WHERE Audit_Approval_Status__c = :status And Payment_Request__c != null ORDER BY CreatedDate ASC LIMIT 300';// ORDER BY and LIMIT added fir Page-Load issue fix
        System.debug('--------query------'+query);
        // return Database.query(query);
        List<Receipt__c> rs = Database.query(query);
        System.debug('--------qwerty------'+rs);
        Map<Id,Id> idFinalIdMap = new Map<Id,Id>();
        if(rs != null && rs.size()>0){
            for(Receipt__c r: rs){
                idFinalIdMap.put(r.id,r.Payment_Request__r.Final_Approver__c);
            }
            Map<id,User> userMap = new Map<id,User>();
            if(idFinalIdMap.values() != null && idFinalIdMap.values().size()>0){
                userMap = new Map<Id, User>([Select Name from User where id IN :idFinalIdMap.values()]);
                
                for(Receipt__c r: rs){
                    if (userMap != null && !userMap.isEmpty() && userMap.containsKey(idFinalIdMap.get(r.id)) && userMap.get(idFinalIdMap.get(r.id)) != null && userMap.get(idFinalIdMap.get(r.id)).Name != null) {
                        
                        r.Payment_Request__r.Final_Approver__c = userMap.get(idFinalIdMap.get(r.id)).Name;
                    }
                }
            }
        }
        System.debug('----------'+rs);
        for(Receipt__c r : rs){
            System.debug('Deepanshu : '+r.Name+' -> '+r.Payment_Request__r.Final_Approver__c);
        }
        return rs;
    }
    
    // Generate query fields based on field configuration
    private static String generateQueryFields(List<Dashboard_Field_Configuration__mdt> fieldConfigs) {
        List<String> fields = new List<String>();
        for (Dashboard_Field_Configuration__mdt config : fieldConfigs) {
            fields.add(config.Field_API_Name__c);
        }
        return String.join(fields, ', ');
    }
    
    
    @AuraEnabled     
    public static void updateReceiptStatus(String receiptId, String action, String comment) 
    {        
        System.debug('receiptId, action, comment - '+receiptId + ' : '+action+' : '+comment);
        Receipt__c receiptToUpdate = [SELECT Id, Audit_Approval_Status__c, Audit_Approver_s_Comments__c FROM Receipt__c WHERE Id = :receiptId LIMIT 1];                  
        // Check if the receipt is found         
        if (receiptToUpdate != null) 
        {             // Update receipt fields based on action             
            if (action.containsIgnoreCase('Approve')) 
            {                 
                receiptToUpdate.Audit_Approval_Status__c = 'Approved';             
            } 
            else if (action.containsIgnoreCase('Reject')) 
            {                 
                receiptToUpdate.Audit_Approval_Status__c = 'Rejected';                 
                receiptToUpdate.Audit_Approver_s_Comments__c = comment;
            }
            else if (action.containsIgnoreCase('Under')) 
            {                 
                receiptToUpdate.Audit_Approval_Status__c = 'Under Approval';                 
                receiptToUpdate.Audit_Submitter_s_Comments__c = comment;
            }// Perform the update             
            try {                 
                update receiptToUpdate;
           }catch (Exception e) {// Handle update error                 
                System.debug('Error updating receipt: ' + e.getMessage());                 
                throw new AuraHandledException('Error updating receipt: ' + e.getMessage());             
            }
        } 
        else 
        {             // Handle receipt not found error             
            throw new AuraHandledException('Receipt not found with ID: ' + receiptId);        
        }     
    }
    
}