force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Notification__c/fields/CP_SC_ID__c.field-meta.xml
<CustomField>
    <fullName>CP_SC_ID__c</fullName>
    <label>CP/SC ID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sobha_Event__c/Sobha_Event__c.object-meta.xml
<CustomObject>
    <label>Sobha Event</label>
    <nameField>
        <label>Sobha Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sobha Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SobhaEventTriggerHelper_Test.cls
@isTest
public class SobhaEventTriggerHelper_Test {
	@isTest
    static void testMethod1() {
        Sobha_Event__c shobaEvt = new Sobha_Event__c();
        shobaEvt.Name = 'Shoba Event';
        shobaEvt.IsActive__c = true;
        insert shobaEvt;
        
        shobaEvt.IsActive__c = false;
        update shobaEvt;
        
        Notification__c ntRec = new Notification__c();
        ntRec.Object_Type__c = 'Gallery';
        ntRec.CP_SC_ID__c = shobaEvt.Id;
        insert ntRec;
    }
}