force-app/main/default/objects/Xpedeon_API_Metadata__mdt/Xpedeon_API_Metadata__mdt.object-meta.xml
<CustomObject>
    <label>Xpedeon API Metadata</label>
    <pluralLabel>Xpedeon API Metadata</pluralLabel>
</CustomObject>

force-app/main/default/objects/Xpedeon_Metadata_Headers__mdt/Xpedeon_Metadata_Headers__mdt.object-meta.xml
<CustomObject>
    <label>Xpedeon Metadata Headers</label>
    <pluralLabel>Xpedeon Metadata Headers</pluralLabel>
</CustomObject>

force-app/main/default/objects/Xpedeon_Metadata_Headers__mdt/fields/Xpedeon_API_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Xpedeon_API_Metadata__c</fullName>
    <label>Xpedeon API Metadata</label>
    <referenceTo>Xpedeon_API_Metadata__mdt</referenceTo>
    <relationshipLabel>Xpedeon Metadata Headers</relationshipLabel>
    <relationshipName>Xpedeon_Metadata_Headers</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Static_Data__mdt/Xpedeon_Static_Data__mdt.object-meta.xml
<CustomObject>
    <label>Xpedeon Static Data</label>
    <pluralLabel>Xpedeon Static Data</pluralLabel>
</CustomObject>

force-app/main/default/objects/Xpedeon_Static_Data__mdt/fields/Xpedeon_API_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Xpedeon_API_Metadata__c</fullName>
    <label>Xpedeon API Metadata</label>
    <referenceTo>Xpedeon_API_Metadata__mdt</referenceTo>
    <relationshipLabel>Xpedeon Static Data</relationshipLabel>
    <relationshipName>Xpedeon_Static_Data</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Xpedeon_Static_Value_Mapping__mdt/Xpedeon_Static_Value_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>To Save value based payload mapping</description>
    <label>Xpedeon Static Value Mapping</label>
    <pluralLabel>Xpedeon Static Value Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Xpedeon_Static_Value_Mapping__mdt/fields/Xpedeon_API_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Xpedeon_API_Metadata__c</fullName>
    <label>Xpedeon API Metadata</label>
    <referenceTo>Xpedeon_API_Metadata__mdt</referenceTo>
    <relationshipLabel>Xpedeon Static Value Mappings</relationshipLabel>
    <relationshipName>Xpedeon_Static_Value_Mappings</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/classes/X_RequestMetadata.cls
public class X_RequestMetadata {
    public Xpedeon_API_Metadata__mdt metadataAPI{get; private set;}
    public List<Xpedeon_Metadata_Headers__mdt> metadataHeaders{get;private set;}
    public List<Xpedeon_Static_Data__mdt> staticMetadata{get;private set;}
     public List<Xpedeon_Static_Value_Mapping__mdt> staticValueMetadata{get;private set;}
    
    public X_RequestMetadata(String requestName){
        this.metadataAPI = Xpedeon_API_Metadata__mdt.getInstance(requestName);
        this.metadataHeaders = getMetadataHeaders(this.metadataAPI.Id);
        this.staticMetadata = getMetadataStaticData(this.metadataAPI.Id);
        this.staticValueMetadata = getmetadataStaticValueData(this.metadataAPI.Id);
    }
    
    static List<Xpedeon_Metadata_Headers__mdt> getMetadataHeaders(String parentId){
        List<Xpedeon_Metadata_Headers__mdt> retValues = new List<Xpedeon_Metadata_Headers__mdt>();
        
        for(Xpedeon_Metadata_Headers__mdt header : Xpedeon_Metadata_Headers__mdt.getAll().values()){
            if(header.Xpedeon_API_Metadata__c == parentId){
                retValues.add(header);
            }
        }
        
        return retValues;
    }
    
    static List<Xpedeon_Static_Data__mdt> getMetadataStaticData(String parentId){
        List<Xpedeon_Static_Data__mdt> retValues = new List<Xpedeon_Static_Data__mdt>();
        
        for(Xpedeon_Static_Data__mdt header : Xpedeon_Static_Data__mdt.getAll().values()){
            if(header.Xpedeon_API_Metadata__c == parentId){
                retValues.add(header);
            }
        }
        
        return retValues;
    }
    
    static List<Xpedeon_Static_Value_Mapping__mdt> getmetadataStaticValueData(String parentId){
        List<Xpedeon_Static_Value_Mapping__mdt> retValues = new List<Xpedeon_Static_Value_Mapping__mdt>();
        
        for(Xpedeon_Static_Value_Mapping__mdt header : Xpedeon_Static_Value_Mapping__mdt.getAll().values()){
            if(header.Xpedeon_API_Metadata__c == parentId){
                retValues.add(header);
            }
        }
        
        return retValues;
    }
    
}