force-app/main/default/objects/External_Reference_Register__c/External_Reference_Register__c.object-meta.xml
<CustomObject>
    <description>This object is to be used to prevent IDOR while generating and managing links to the internal documents to be shared over the public/guest user sites.</description>
    <label>External Reference Register</label>
    <nameField>
        <displayFormat>ERR #{0}</displayFormat>
        <label>External Reference Register Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>External Reference Registers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/External_Reference_Register__c/fields/Entry_Expiration_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Entry_Expiration_DateTime__c</fullName>
    <label>Entry Expiration DateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ScheduledBatchERR_Deletion.cls
//Test class : TestSRCustomer
public class ScheduledBatchERR_Deletion implements Schedulable,Database.Batchable<sObject>{

    //Schedulable
    public void execute(SchedulableContext sc){
        Database.executeBatch(new ScheduledBatchERR_Deletion(),2000);
    }
    
    //Batchable
    public Database.QueryLocator start(Database.BatchableContext bc){
        DateTime dtNow = System.now();
        return Database.getQueryLocator('SELECT id FROM External_Reference_Register__c WHERE Entry_Expiration_DateTime__c <= :dtNow');
    }
    
    public void execute(Database.BatchableContext bc, List<External_Reference_Register__c> errs){Database.delete(errs,false);}
    
    public void finish(Database.BatchableContext bc){}
}