force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Channel_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <label>Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <formula>Text(Date_Of_Event__c)+&apos;/&apos;+TEXT(City_Country__c)+&apos;/&apos;+ RecordType.Name +&apos;/&apos;+IF( Channel_Partner__c !=null,Channel_Partner__r.Name,Sobha_Connect__r.Name)</formula>
    <label>Campaign Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Channel_Partner__c.Black_listed_user__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/City_Country__c.field-meta.xml
<CustomField>
    <fullName>City_Country__c</fullName>
    <label>City (Enter Full Name Correctly)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Abuja</fullName>
            </value>
            <value>
                <fullName>Addis Ababa</fullName>
            </value>
            <value>
                <fullName>Agra</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Al Ain</fullName>
            </value>
            <value>
                <fullName>Alger</fullName>
            </value>
            <value>
                <fullName>Almaty</fullName>
                <label>ALMATY</label>
            </value>
            <value>
                <fullName>Amsterdam</fullName>
                <label>AMSTERDAM</label>
            </value>
            <value>
                <fullName>Ankara</fullName>
            </value>
            <value>
                <fullName>Astana</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>Baghdad</fullName>
                <label>BAGHDAD</label>
            </value>
            <value>
                <fullName>Baku</fullName>
            </value>
            <value>
                <fullName>bandar abbas</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
                <label>BANGALORE</label>
            </value>
            <value>
                <fullName>Bangkok</fullName>
            </value>
            <value>
                <fullName>Basel</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>BEIRUT</fullName>
            </value>
            <value>
                <fullName>Belgrade</fullName>
                <label>BELGRADE</label>
            </value>
            <value>
                <fullName>BERLIN</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Bishkek</fullName>
            </value>
            <value>
                <fullName>Bradford</fullName>
            </value>
            <value>
                <fullName>Brighton</fullName>
            </value>
            <value>
                <fullName>Brussels</fullName>
            </value>
            <value>
                <fullName>Bucharest</fullName>
                <label>BUCHAREST</label>
            </value>
            <value>
                <fullName>Bursa</fullName>
            </value>
            <value>
                <fullName>Cairo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Date_Of_Event__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Event__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/End_Date_Of_Event__c.field-meta.xml
<CustomField>
    <fullName>End_Date_Of_Event__c</fullName>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Sales Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Events1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <label>Campaign Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Channel_Partner__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Capture__c/Lead_Capture__c.object-meta.xml
<CustomObject>
    <label>Lead Capture</label>
    <nameField>
        <displayFormat>LC-{0000000}</displayFormat>
        <label>Lead Capture Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lead Captures</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Capture__c/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <label>Campaign Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Location__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>2024-08-31/SINGAPORE/Road Shows/FOOT PRINT REAL ESTATE BROKER</fullName>
            </value>
            <value>
                <fullName>2024-08-31/London/Road Shows/LUXURY LIVING HOMES INTERNATIONAL LTD</fullName>
            </value>
            <value>
                <fullName>2024-08-31/Hyderabad/Road Shows/NEST HUNTERS REAL ESTATE LLC</fullName>
            </value>
            <value>
                <fullName>2024-08-31/Baku/Road Shows/H J REAL ESTATES</fullName>
            </value>
            <value>
                <fullName>2024-09-01/Birmingham/Road Shows/ELAN REAL ESTATE</fullName>
            </value>
            <value>
                <fullName>2024-08-25/Pune/Business Trip/SQUAREA GULF REAL ESTATE L.L.C</fullName>
            </value>
            <value>
                <fullName>2024-09-05/Bogota/Road Shows/J A Z REAL ESTATE</fullName>
            </value>
            <value>
                <fullName>2024-09-07/Delhi/Road Shows/CASA REGAL PROPERTIES L.L.C</fullName>
            </value>
            <value>
                <fullName>2024-09-07/Lagos/Road Shows/EMPIRE HILLS REAL ESTATE L.L.C</fullName>
            </value>
            <value>
                <fullName>2024-09-07/Hamburg/Road Shows/FOOT PRINT REAL ESTATE BROKER</fullName>
            </value>
            <value>
                <fullName>2024-09-07/Ludhiana/Road Shows/GREHA PRAVESH REAL ESTATE L.L.C</fullName>
            </value>
            <value>
                <fullName>2024-09-07/Cochin/Road Shows/FIFTY SIX REALTY L.L.C</fullName>
            </value>
            <value>
                <fullName>2024-09-07/Baghdad/Road Shows/VILA L.L.C-FZ</fullName>
            </value>
            <value>
                <fullName>2024-09-07/Chicago/Road Shows/PROVIDENT REAL ESTATE BROKER L.L.C</fullName>
            </value>
            <value>
                <fullName>2024-09-07/Colombo/Road Shows/BENCHMARK PROPERTIES</fullName>
            </value>
            <value>
                <fullName>2024-09-13/Abuja/Road Shows/SPRING FIELD REAL ESTATE</fullName>
            </value>
            <value>
                <fullName>2024-09-14/Hong Kong/Road Shows/KNIGHTSBRIDGE &amp; PARTNERS (HK) LIMITED</fullName>
            </value>
            <value>
                <fullName>2024-09-14/Dallas/Road Shows/FOOT PRINT REAL ESTATE BROKER</fullName>
            </value>
            <value>
                <fullName>2024-09-14/Zurich/Road Shows/M G L REALESTATE L.L.C</fullName>
            </value>
            <value>
                <fullName>2024-09-14/Houston/Road Shows/RAYNA PROPERTIES</fullName>
            </value>
            <value>
                <fullName>2024-09-14/Miami/Road Shows/JAPSONS REALTY L.L.C</fullName>
            </value>
            <value>
                <fullName>2024-09-14/CAPETOWN/Road Shows/RANGE INTERNATIONAL PROPERTY INVESTMENT ONE PERSON COMPANY L.L.C</fullName>
            </value>
            <value>
                <fullName>2024-09-14/Frankfurt/Road Shows/KREDIUM TECHNOLOGIES L L C - DUBAI BRANCH</fullName>
            </value>
            <value>
                <fullName>2024-09-21/Coimbatore/Road Shows/THE G O A T REAL ESTATE L.L.C</fullName>
            </value>
            <value>
                <fullName>2024-09-21/Hyderabad/Road Shows/HOMES 4 LIFE REAL ESTATE BROKER (LLC)</fullName>
            </value>
            <value>
                <fullName>2024-09-21/London/Road Shows/AEON TRISL INVESTMENTS LIMITED</fullName>
            </value>
            <value>
                <fullName>2024-09-21/Manchester/Road Shows/ELEVATION INTERNATIONAL REAL ESTATE L.L.C</fullName>
            </value>
            <value>
                <fullName>2024-09-21/Mumbai/Road Shows/FOOT PRINT REAL ESTATE BROKER</fullName>
            </value>
            <value>
                <fullName>2024-09-21/SINGAPORE/Road Shows/FOOT PRINT REAL ESTATE BROKER</fullName>
            </value>
            <value>
                <fullName>2024-09-21/Stuttgart/Road Shows/ALLEGIANCE REAL ESTATE L.L.C</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Capture__c/fields/Events__c.field-meta.xml
<CustomField>
    <fullName>Events__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Events</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Lead Captures</relationshipLabel>
    <relationshipName>Lead_Captures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Capture__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Lead_Captures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadCaptureTest.cls
@isTest
public class LeadCaptureTest {
    @isTest
    static void testLeadCaptEventDateValidation() {
        // Create test Channel Partner record
        Channel_Partner__c testChannelPartner = new Channel_Partner__c(
            Name = 'Test Channel Partner'
        );
        insert testChannelPartner;
        
        // Create test Event__c record with a Channel Partner
        Events__c testEventWithChannelPartner = new Events__c(
            Name = 'Test Event with Channel Partner',
            Date_Of_Event__c = Date.today().addDays(2),
            End_Date_Of_Event__c = Date.today().addDays(3),
            Channel_Partner__c = testChannelPartner.Id,
         //   City_Country__c = 'Test City, Test Country',
            sales_manager__c = UserInfo.getUserId()
        );
        insert testEventWithChannelPartner;
        
        Events__c thisEvents = [SELECT id,Campaign_Code__c from Events__c LIMIT 1];
        String campaignCodeDynamic = thisEvents.Campaign_Code__c;
        
        // Create test Lead_Capture__c record related to the test Event with Channel Partner
		List<Lead_Capture__C> testLeadCaptures = new List<Lead_Capture__c>();
        Lead_Capture__c testLeadCapture = new Lead_Capture__c(
            Name__c = 'Test Lead Capture',
            Mobile_Number__c ='1212121212',
            Campaign_Code__c = '2024-08-31/SINGAPORE/Road Shows/FOOT PRINT REAL ESTATE BROKER',
            Broker_Name__c ='FOOT PRINT REAL ESTATE BROKER'
        );
        testLeadCaptures.add(testLeadCapture);
        
        Lead_Capture__c testLeadCapture1 = new Lead_Capture__c(
            Name__c = 'Test Lead Capture1',
            Mobile_Number__c ='1313131313',
            Campaign_Code__c =  '2024-08-31/SINGAPORE/Road Shows/FOOT PRINT REAL ESTATE BROKER',
            Broker_Name__c ='FOOT PRINT REAL ESTATE BROKER'
        );
        testLeadCaptures.add(testLeadCapture1);
        
        Test.startTest();
        insert testLeadCaptures;
        Test.stopTest();
        
        // Verify that no error was added to the Lead_Capture__c record
        System.assertEquals(1, [SELECT count() FROM Lead_Capture__c WHERE Id = :testLeadCapture.Id AND IsDeleted = false]);
         }
}