force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>International Broker - New</fullName>
            </value>
            <value>
                <fullName>International Broker - Old</fullName>
            </value>
            <value>
                <fullName>Broker - UAE</fullName>
            </value>
            <value>
                <fullName>Broker - Intnl</fullName>
            </value>
            <value>
                <fullName>Broker - RERA</fullName>
            </value>
            <value>
                <fullName>Broker - China</fullName>
                <isActive>false</isActive>
                <label>Broker - China</label>
            </value>
            <value>
                <fullName>Broker - India</fullName>
                <isActive>false</isActive>
                <label>Broker - India</label>
            </value>
            <value>
                <fullName>Broker - Intl</fullName>
                <isActive>false</isActive>
                <label>Broker - Intl</label>
            </value>
            <value>
                <fullName>Broker - KSA</fullName>
                <isActive>false</isActive>
                <label>Broker - KSA</label>
            </value>
            <value>
                <fullName>Broker - Others</fullName>
                <isActive>false</isActive>
                <label>Broker - Others</label>
            </value>
            <value>
                <fullName>Broker - UK</fullName>
                <isActive>false</isActive>
                <label>Broker - UK</label>
            </value>
            <value>
                <fullName>SC - China</fullName>
                <isActive>false</isActive>
                <label>SC - China</label>
            </value>
            <value>
                <fullName>SC - India</fullName>
                <isActive>false</isActive>
                <label>SC - India</label>
            </value>
            <value>
                <fullName>SC - KSA</fullName>
                <isActive>false</isActive>
                <label>SC - KSA</label>
            </value>
            <value>
                <fullName>SC - Others</fullName>
                <isActive>false</isActive>
                <label>SC - Others</label>
            </value>
            <value>
                <fullName>SC - UAE</fullName>
                <isActive>false</isActive>
                <label>SC - UAE</label>
            </value>
            <value>
                <fullName>SC - UK</fullName>
                <isActive>false</isActive>
                <label>SC - UK</label>
            </value>
            <value>
                <fullName>Sobha Connect - Intl</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect - Intl</label>
            </value>
            <value>
                <fullName>Sobha Connect - UAE</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect - UAE</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Channel_Partner_Id__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner_Id__c</fullName>
    <displayFormat>CP - {0000}</displayFormat>
    <externalId>true</externalId>
    <label>Channel Partner Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Channel_Relationship_Head__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relations Team Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Channel_Partners3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Channel_Partners2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Geography_Head__c.field-meta.xml
<CustomField>
    <fullName>Geography_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Geography Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Channel_Partners5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Geography_Manager__c.field-meta.xml
<CustomField>
    <fullName>Geography_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Geography Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Channel_Partners4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/New_Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>New_Channel_Partner__c</fullName>
    <formula>HYPERLINK(&quot;https://cs58.salesforce.com/a07/e?retURL=%2Fa07%3Ffcf%3D00B0l000000Qde0&amp;_CONFIRMATIONTOKEN=VmpFPSxNakF4TnkweE1TMHpNRlF4TVRveE16bzFNaTQyTkRkYSxHMzBmNHM0a0RIY3N2eGNQYVhDWC1lLE5UVTFPREps&amp;common.udd.actions.ActionsUtilORIG_URI=%2Fa07%2Fe&quot;, &quot;New Channel Partner&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>New Channel Partner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/No_of_Broker_Trainings__c.field-meta.xml
<CustomField>
    <fullName>No_of_Broker_Trainings__c</fullName>
    <label>No.of Broker Trainings</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/No_of_Open_Houses__c.field-meta.xml
<CustomField>
    <fullName>No_of_Open_Houses__c</fullName>
    <label>No.of Open Houses</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Qualified_Sales_Value__c.field-meta.xml
<CustomField>
    <fullName>Qualified_Sales_Value__c</fullName>
    <label>Qualified Sales Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Renewal_New_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Renewal_New_Expiry__c</fullName>
    <label>Renewal - New Expiry</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/RERA_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>RERA_Registration_No__c</fullName>
    <externalId>true</externalId>
    <label>RERA Registration No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Channel_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/Sobha_Connect__c.object-meta.xml
<CustomObject>
    <label>Sobha Connect</label>
    <nameField>
        <displayFormat>SC - {0000}</displayFormat>
        <label>Sobha Connect Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sobha Connect</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sobha_Connect__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>International Broker - New</fullName>
            </value>
            <value>
                <fullName>International Broker - Old</fullName>
            </value>
            <value>
                <fullName>Broker - UAE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Channel_Relationship_Head__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sobha_Connect1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sobha_Connect</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Contact_Person__c.field-meta.xml
<CustomField>
    <fullName>Contact_Person__c</fullName>
    <label>Contact Person</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <label>Email Id</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Geography_Head__c.field-meta.xml
<CustomField>
    <fullName>Geography_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Geography Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sobha_Connect6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Geography_Manager__c.field-meta.xml
<CustomField>
    <fullName>Geography_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Geography Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sobha_Connect5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_No__c</fullName>
    <label>Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Qualified_Sales_Value__c.field-meta.xml
<CustomField>
    <fullName>Qualified_Sales_Value__c</fullName>
    <label>Qualified Sales Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Renewal_New_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Renewal_New_Expiry__c</fullName>
    <label>Renewal - New Expiry</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sobha_Connect2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SobhaTokenAPI.cls
/**
*  --------------------------------------------------------------------------------------------------------------------------------------
* @Who   : CEPTES Software Pvt.Ltd.
* @What  : Fetch records for Token System
* @Why   : To expose Sobha Connect and Channel Partner records data to third party.
* @When  : 06-Jan-2021
*  -------------------------------------------------------------------------------------------------------------------------------------
**/
@RestResource(urlMapping='/sobhatokensystem/')
global with sharing class SobhaTokenAPI {
    /**
* @Method       : doGet
* @Invoke       : When any third party hit the API
* @Description  : This API is used to expose the Sobha connect and Channel Partner Data
* @Return       : Records for Sobha Connect and Channel Partner for token system
* @Params       : Search String
**/
    @HttpGet
    global static SobhaTokenAPIWrapper doGet() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String nameString;
        if (Test.isRunningTest()) {
            nameString = 'test';
        } else {
            nameString = req.params.get('search_string');
        }
        List<List<SObject>> searchList = new List<List<SObject>>();
        List<Sobha_Connect__c> sobhaConnect = new List<Sobha_Connect__c>();
        List<Channel_Partner__c> channelPartner = new List<Channel_Partner__c>();
        
        //Fetch unit data from unit object
        try{

            //String searchquery='FIND\''+nameString+'*\'IN NAME FIELDS RETURNING Sobha_Connect__c(id,name,Channel_Relationship_Head__c,Channel_Relationship_Manager__c,Contact_Person__c,Creation_Date__c,Email_Id__c,Expiry_Date__c,Geography_Head__c,Geography_Manager__c,Mobile_No__c,Name__c,Renewal_New_Expiry__c,Registration_Date__c),Channel_Partner__c(Id,Name,Approval_Status__c,Category__c,Channel_Partner_Id__c,Channel_Relationship_Head__c,Channel_Relationship_Manager__c,Contact_Person__c,New_Channel_Partner__c,No_of_Broker_Trainings__c,No_of_Open_Houses__c,Qualified_Sales_Value__c,Registration_Date__c,Renewal_New_Expiry__c,RERA_Registration_No__c,Sales_Manager__c)'; 
            //searchList = search.query(searchquery);
            String searchStringVal= '%'+nameString+'%';
            sobhaConnect = [Select id,
                                    name,
                                    Channel_Relationship_Head__c,
                                    Channel_Relationship_Head__r.Name,
                                    Channel_Relationship_Manager__c,
                                    Channel_Relationship_Manager__r.Name,
                                    Contact_Person__c,
                                    Creation_Date__c,
                                    Email_Id__c,
                                    Expiry_Date__c,
                                    Geography_Head__c,
                                    Geography_Manager__c,
                                    Geography_Manager__r.Name,
                                    Mobile_No__c,
                                    Name__c,
                                    Renewal_New_Expiry__c,
                                    Registration_Date__c
                                From Sobha_Connect__c
                                Where Name__c like :searchStringVal];
            
            channelPartner = [Select Id,
                                    Name,
                                    Approval_Status__c,
                                    Category__c,
                                    Channel_Partner_Id__c,
                                    Channel_Relationship_Head__c,
                                    Channel_Relationship_Head__r.Name,
                                    Channel_Relationship_Manager__c,
                                    Channel_Relationship_Manager__r.Name,
                                    Contact_Person__c,
                                    No_of_Broker_Trainings__c,
                                    No_of_Open_Houses__c,
                                    Qualified_Sales_Value__c,
                                    Registration_Date__c,
                                    Renewal_New_Expiry__c,
                                    RERA_Registration_No__c,
                                    Sales_Manager__c,
                                    Sales_Manager__r.Name
                                From Channel_Partner__c
                                Where name LIKE :searchStringVal];
            
            //If any issue in fetching the unit records   
        }catch(Exception e) {
            System.debug('Your exception message here....'+e.getMessage());
            SobhaTokenAPIWrapper exposeData = new SobhaTokenAPIWrapper();
            exposeData.success = false;
            exposeData.statusCode = 500;
            exposeData.message = 'INTERNAL_SERVER_ERROR!!';           
            return exposeData;
        }
        
        //If unitdata is not empty 
        if((sobhaConnect.size() > 0) || ( channelPartner!=null && !channelPartner.isEmpty())) {
            SobhaTokenAPIWrapper exposeData = new SobhaTokenAPIWrapper();
            exposeData.success = true;
            exposeData.statusCode = 200;
            //if (sobhaConnect!=null && !searchList.isEmpty()) {
                exposeData.sobhaConnectData = sobhaConnect;
            //if (channelPartner!=null && !channelPartner.isEmpty()) {
                exposeData.channelPartnerData = channelPartner;

            
            //exposeData.channelPartnerData = channelPartner;
            //If unitdata is empty
            return exposeData;
        }else{
                SobhaTokenAPIWrapper exposeData = new SobhaTokenAPIWrapper();
                exposeData.success = true;
                exposeData.statusCode = 200;
                exposeData.message = 'No matching records found!!';            
                return exposeData;
        	 }        
    }
    
    global with sharing class SobhaTokenAPIWrapper{
        Public Boolean success;
        public Integer statusCode;
        public String message='';
        //public List<List<SObject>> responseData;
        public List<Channel_Partner__c> channelPartnerData;
        public List<Sobha_Connect__c> sobhaConnectData;
        
    }
}