force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Registration__c/Customer_Registration__c.object-meta.xml
<CustomObject>
    <label>Site Visit Form</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>Customer Registration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visit Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Customer_Registration__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Channel_Partner__c.Black_listed_user__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Customer Registration Forms</relationshipLabel>
    <relationshipName>Customer_Registration_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Customer_Registration__c/fields/Sobha_Connect__c.field-meta.xml
<CustomField>
    <fullName>Sobha_Connect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sobha Connect</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sobha_Connect__c.Black_listed_user__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Sobha_Connect__c</referenceTo>
    <relationshipLabel>Site Visit Forms</relationshipLabel>
    <relationshipName>Site_Visit_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Info__c/Integration_Info__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Integration Info</label>
</CustomObject>

force-app/main/default/objects/Sobha_Connect__c/Sobha_Connect__c.object-meta.xml
<CustomObject>
    <label>Sobha Connect</label>
    <nameField>
        <displayFormat>SC - {0000}</displayFormat>
        <label>Sobha Connect Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sobha Connect</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CustomerRegistrationHandlerTest.cls
@isTest
public class CustomerRegistrationHandlerTest {

    @isTest
    public static void beforeInsertTest(){
        List<Customer_Registration__c> crList = DataUtility.getSiteVisitForms();
        List<Sobha_Connect__c> scList = DataUtility.getSobhaConnect();
        List<Channel_Partner__c> cpList = DataUtility.getChannelPartner();
        List<Integration_Info__c> cfiList = DataUtility.getCustomer_Registration();
        crList[0].Alternate_Mobile_Number__c = '1111111123';
        crList[0].Sobha_Connect__c = scList[0].Id;
        crList[0].Channel_Partner__c = cpList[0].Id;
        update crList;
    }
    
    @isTest
    public static void testAPI(){
        List<Customer_Registration__c> crList = DataUtility.getSiteVisitForms();
        List<Sobha_Connect__c> scList = DataUtility.getSobhaConnect();
        List<Channel_Partner__c> cpList = DataUtility.getChannelPartner();
        List<Integration_Info__c> cfiList = DataUtility.getCustomer_Registration();
        crList[0].Alternate_Mobile_Number__c = '1111111123';
        crList[0].Sobha_Connect__c = scList[0].Id;
        crList[0].Channel_Partner__c = cpList[0].Id;
        update crList;
        customerregistrationhandler.sendToTokenAPI(crList[0].Id);
    }
}