force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EOI_Form__c/EOI_Form__c.object-meta.xml
<CustomObject>
    <label>EOI Form</label>
    <nameField>
        <displayFormat>EOI-{0000}</displayFormat>
        <label>EOI Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EOI Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/EOI_Form__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>EOI Forms</relationshipLabel>
    <relationshipName>EOI_Forms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EOI_Form__c/fields/Source_of_EOI__c.field-meta.xml
<CustomField>
    <fullName>Source_of_EOI__c</fullName>
    <label>Source of EOI</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Channel Partner</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Sobha Connect</fullName>
            </value>
            <value>
                <fullName>Management Reference</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Digital</fullName>
            </value>
            <value>
                <fullName>Retention</fullName>
            </value>
            <value>
                <fullName>Sales-Initiative</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EOI_Form__c/fields/Unit_Number__c.field-meta.xml
<CustomField>
    <fullName>Unit_Number__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit Number</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1</booleanFilter>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>EOI Forms</relationshipLabel>
    <relationshipName>EOI_Forms</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>Requested For EOI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testEOIformController.cls
@isTest
private class testEOIformController {

    @IsTest	
    private static  void testEOIformController(){
             
        Unit__c u =new Unit__c();
        u.Name='Test';
        U.Unit_Status__c ='Available';
        insert u;
        
         Channel_Partner__c CP = New Channel_Partner__c();
        CP.Name ='FAST WAY REAL ESTATE BROKER';
        insert CP;
              
        EOI_Form__c EOI =new EOI_Form__c();
        EOI.Unit_Number__c= u.Id;
        //EOI.CurrencyIsoCode = 'AED - UAE Dirham';
       EOI.Source_of_EOI__c ='Channel Partner';
        EOI.Channel_Partner__c = CP.id;
        Insert EOI;
        
       /* Unit__c u1 =new Unit__c();
        u1.Name='Test1';
        u1.Unit_Status__c ='Available';
        insert u1;
        
        Channel_Partner__c CP = New Channel_Partner__c();
        CP.Name ='FAST WAY REAL ESTATE BROKER';
        insert CP;
                
        EOI_Form__c EOI1 =new EOI_Form__c();
        EOI1.Unit_Number__c= u1.Id;
        //EOI.CurrencyIsoCode = 'AED - UAE Dirham';
        EOI1.Channel_Partner__c =CP.Id;
        EOI1.Source_of_EOI__c = 'Channel Partner'
        Insert EOI1; */
        
  
    PageReference pRef1 = Page.EOIform;
        Test.setCurrentPage(pRef1);          
        ApexPages.currentPage().getParameters().put('id', EOI.id);
        EOIformController spa = new EOIformController();        
       }   
   
    
}