force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Channel_Partners2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Email_ID_1__c.field-meta.xml
<CustomField>
    <fullName>Email_ID_1__c</fullName>
    <label>Email ID 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Channel_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <label>Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Channel_Partner__c.Black_listed_user__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Events3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Date_Of_Event__c.field-meta.xml
<CustomField>
    <fullName>Date_Of_Event__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Approved_status__c.field-meta.xml
<CustomField>
    <fullName>Event_Approved_status__c</fullName>
    <label>Event approval status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>The event has been Submitted for the Invoice Raise Approval</fullName>
            </value>
            <value>
                <fullName>The event has been Approved for the Invoice Raise</fullName>
            </value>
            <value>
                <fullName>The event has been Rejected before the Invoice Raise</fullName>
            </value>
            <value>
                <fullName>The event has been Submitted for the after Invoice Raise Approval to CP Head</fullName>
            </value>
            <value>
                <fullName>After Invoice Raise Approved by CP Head</fullName>
            </value>
            <value>
                <fullName>The event has been Submitted for the after Invoice Raise Rejected by CP Head</fullName>
            </value>
            <value>
                <fullName>The event has been Submitted for the after Invoice Raise Approval  for CSO</fullName>
            </value>
            <value>
                <fullName>The event has been approved by Manish Goenka</fullName>
            </value>
            <value>
                <fullName>The event has been rejected by Manish Goenka</fullName>
            </value>
            <value>
                <fullName>The event has been approved by Sales Director</fullName>
            </value>
            <value>
                <fullName>The event has been rejected by Sales Director</fullName>
            </value>
            <value>
                <fullName>The event has been approved by Channel Relationship Manager</fullName>
                <label>The event has been approved by CHRM manager</label>
            </value>
            <value>
                <fullName>The event has been rejected by Channel Relationship Manager</fullName>
                <label>The event has been rejected by CHRM manager</label>
            </value>
            <value>
                <fullName>The event has been approved by Channel Relationship Head</fullName>
                <label>The event has been approved by CHRM manager TL</label>
            </value>
            <value>
                <fullName>The event has been rejected by Channel Relationship Head</fullName>
                <label>The event has been rejected by CHRM manager TL</label>
            </value>
            <value>
                <fullName>The event has been approved by Avin Anil</fullName>
                <label>The event has been approved by Maria</label>
            </value>
            <value>
                <fullName>The event has been rejected by Avin Anil</fullName>
                <label>The event has been rejected by Maria</label>
            </value>
            <value>
                <fullName>The event has been approved by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>The event has been rejected by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>The event has been approved by GM Hospitality</fullName>
            </value>
            <value>
                <fullName>The event has been rejected by GM Hospitality</fullName>
            </value>
            <value>
                <fullName>This event has been submitted by GM after invoice approval</fullName>
            </value>
            <value>
                <fullName>The event has been approved by CRM OPs after Invoice Approval</fullName>
            </value>
            <value>
                <fullName>Pending With Sales Director</fullName>
            </value>
            <value>
                <fullName>Pending With VP</fullName>
            </value>
            <value>
                <fullName>Pending With CHRM manager</fullName>
            </value>
            <value>
                <fullName>Pending With CHRM manager TL</fullName>
            </value>
            <value>
                <fullName>Pending With Avin Anil</fullName>
                <label>Pending With Maria</label>
            </value>
            <value>
                <fullName>Pending With Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Pending With Manish Goenka</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>contains</operation>
            <value>Sales Manager</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Events1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Stay_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Stay_Start_Date__c</fullName>
    <label>Stay Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ConfirmNoOfMeetingBatchTest.cls
@isTest public class ConfirmNoOfMeetingBatchTest {
    static testMethod void testConfirmNoOfMeetingBatch() {
        User u = [select id from user where userrole.name like '%Sales Manager%' limit 1];
        Channel_Partner__c chPartner = new Channel_Partner__c();
        chPartner.Name = 'Test Channel Partner';
        chPartner.Expiry_Date__c = System.today();
        chPartner.Channel_Relationship_Manager__c = UserInfo.getUserId();
        chPartner.Email_ID_1__c='test@test.com';
        insert chPartner;
        
        List<Events__c> evntlst = new List<Events__c>();
        Events__c evnt = new Events__c();
        evnt.Sales_Manager__c = u.id;
        evnt.Name = 'Video Shoot';
        evnt.Date_Of_Event__c = System.today().addDays(15);
        evnt.Stay_Start_Date__c = System.today().addDays(16);
        Id devRecordTypeId1 = Schema.SObjectType.Events__c.getRecordTypeInfosByName().get('Video Shoot').getRecordTypeId();
        evnt.RecordTypeId = devRecordTypeId1;
        evnt.Channel_Partner__c = chPartner.id;
        evnt.Event_Approved_status__c = 'The event has been approved by Sales Director';
        evntlst.add(evnt);
        insert evntlst;
        
        Test.startTest();
        ConfirmNoOfMeetingBatch ob = new ConfirmNoOfMeetingBatch();
        ob.execute(null);
        Test.stopTest();
    }
}