force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>United Arab Emirates</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>Iraq</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>Gabon</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>Kuwait</fullName>
            </value>
            <value>
                <fullName>Tajikistan</fullName>
            </value>
            <value>
                <fullName>Republic of Congo</fullName>
            </value>
            <value>
                <fullName>Ivory Coast (Cote D`Ivoire)</fullName>
            </value>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Nigeria</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Lebanon</fullName>
            </value>
            <value>
                <fullName>Kazakhstan</fullName>
            </value>
            <value>
                <fullName>Kenya</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
            <value>
                <fullName>Ukraine</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Pakistan</fullName>
            </value>
            <value>
                <fullName>Ethiopia</fullName>
            </value>
            <value>
                <fullName>Portugal</fullName>
            </value>
            <value>
                <fullName>Uganda</fullName>
            </value>
            <value>
                <fullName>Zimbabwe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <label>Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Campaign_Code__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Code__c</fullName>
    <formula>Text(Date_Of_Event__c)+&apos;/&apos;+TEXT(City_Country__c)+&apos;/&apos;+ RecordType.Name +&apos;/&apos;+IF( Channel_Partner__c !=null,Channel_Partner__r.Name,Sobha_Connect__r.Name)</formula>
    <label>Campaign Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/City_Country__c.field-meta.xml
<CustomField>
    <fullName>City_Country__c</fullName>
    <label>City (Enter Full Name Correctly)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abu Dhabi</fullName>
            </value>
            <value>
                <fullName>Abuja</fullName>
            </value>
            <value>
                <fullName>Addis Ababa</fullName>
            </value>
            <value>
                <fullName>Agra</fullName>
            </value>
            <value>
                <fullName>Ahmedabad</fullName>
            </value>
            <value>
                <fullName>Al Ain</fullName>
            </value>
            <value>
                <fullName>Alger</fullName>
            </value>
            <value>
                <fullName>Almaty</fullName>
                <label>ALMATY</label>
            </value>
            <value>
                <fullName>Amsterdam</fullName>
                <label>AMSTERDAM</label>
            </value>
            <value>
                <fullName>Ankara</fullName>
            </value>
            <value>
                <fullName>Astana</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>Baghdad</fullName>
                <label>BAGHDAD</label>
            </value>
            <value>
                <fullName>Baku</fullName>
            </value>
            <value>
                <fullName>bandar abbas</fullName>
            </value>
            <value>
                <fullName>Bangalore</fullName>
                <label>BANGALORE</label>
            </value>
            <value>
                <fullName>Bangkok</fullName>
            </value>
            <value>
                <fullName>Basel</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>BEIRUT</fullName>
            </value>
            <value>
                <fullName>Belgrade</fullName>
                <label>BELGRADE</label>
            </value>
            <value>
                <fullName>BERLIN</fullName>
            </value>
            <value>
                <fullName>Birmingham</fullName>
            </value>
            <value>
                <fullName>Bishkek</fullName>
            </value>
            <value>
                <fullName>Bradford</fullName>
            </value>
            <value>
                <fullName>Brighton</fullName>
            </value>
            <value>
                <fullName>Brussels</fullName>
            </value>
            <value>
                <fullName>Bucharest</fullName>
                <label>BUCHAREST</label>
            </value>
            <value>
                <fullName>Bursa</fullName>
            </value>
            <value>
                <fullName>Cairo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Email_Last_Triggered_Time__c.field-meta.xml
<CustomField>
    <fullName>Email_Last_Triggered_Time__c</fullName>
    <label>Email Last Triggered Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/End_Time_of_the_Event__c.field-meta.xml
<CustomField>
    <fullName>End_Time_of_the_Event__c</fullName>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Event_Approved_status__c.field-meta.xml
<CustomField>
    <fullName>Event_Approved_status__c</fullName>
    <label>Event approval status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>The event has been Submitted for the Invoice Raise Approval</fullName>
            </value>
            <value>
                <fullName>The event has been Approved for the Invoice Raise</fullName>
            </value>
            <value>
                <fullName>The event has been Rejected before the Invoice Raise</fullName>
            </value>
            <value>
                <fullName>The event has been Submitted for the after Invoice Raise Approval to CP Head</fullName>
            </value>
            <value>
                <fullName>After Invoice Raise Approved by CP Head</fullName>
            </value>
            <value>
                <fullName>The event has been Submitted for the after Invoice Raise Rejected by CP Head</fullName>
            </value>
            <value>
                <fullName>The event has been Submitted for the after Invoice Raise Approval  for CSO</fullName>
            </value>
            <value>
                <fullName>The event has been approved by Manish Goenka</fullName>
            </value>
            <value>
                <fullName>The event has been rejected by Manish Goenka</fullName>
            </value>
            <value>
                <fullName>The event has been approved by Sales Director</fullName>
            </value>
            <value>
                <fullName>The event has been rejected by Sales Director</fullName>
            </value>
            <value>
                <fullName>The event has been approved by Channel Relationship Manager</fullName>
                <label>The event has been approved by CHRM manager</label>
            </value>
            <value>
                <fullName>The event has been rejected by Channel Relationship Manager</fullName>
                <label>The event has been rejected by CHRM manager</label>
            </value>
            <value>
                <fullName>The event has been approved by Channel Relationship Head</fullName>
                <label>The event has been approved by CHRM manager TL</label>
            </value>
            <value>
                <fullName>The event has been rejected by Channel Relationship Head</fullName>
                <label>The event has been rejected by CHRM manager TL</label>
            </value>
            <value>
                <fullName>The event has been approved by Avin Anil</fullName>
                <label>The event has been approved by Maria</label>
            </value>
            <value>
                <fullName>The event has been rejected by Avin Anil</fullName>
                <label>The event has been rejected by Maria</label>
            </value>
            <value>
                <fullName>The event has been approved by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>The event has been rejected by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>The event has been approved by GM Hospitality</fullName>
            </value>
            <value>
                <fullName>The event has been rejected by GM Hospitality</fullName>
            </value>
            <value>
                <fullName>This event has been submitted by GM after invoice approval</fullName>
            </value>
            <value>
                <fullName>The event has been approved by CRM OPs after Invoice Approval</fullName>
            </value>
            <value>
                <fullName>Pending With Sales Director</fullName>
            </value>
            <value>
                <fullName>Pending With VP</fullName>
            </value>
            <value>
                <fullName>Pending With CHRM manager</fullName>
            </value>
            <value>
                <fullName>Pending With CHRM manager TL</fullName>
            </value>
            <value>
                <fullName>Pending With Avin Anil</fullName>
                <label>Pending With Maria</label>
            </value>
            <value>
                <fullName>Pending With Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Pending With Manish Goenka</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Events__c/fields/Next_Approver__c.field-meta.xml
<CustomField>
    <fullName>Next_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Next Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Events9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/No_Of_Pax_Attending__c.field-meta.xml
<CustomField>
    <fullName>No_Of_Pax_Attending__c</fullName>
    <description>only for video shoot</description>
    <label>No. Of Pax. Attending</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Start_Time_of_the_Event__c.field-meta.xml
<CustomField>
    <fullName>Start_Time_of_the_Event__c</fullName>
    <label>Start time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/User_1__c.field-meta.xml
<CustomField>
    <fullName>User_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant 1</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Eventsp6Pb</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/User_2__c.field-meta.xml
<CustomField>
    <fullName>User_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant 2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Eventsp6Pl</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/User_3__c.field-meta.xml
<CustomField>
    <fullName>User_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Participant 3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Eventsp6Pv</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Venue_Video_Shoot__c.field-meta.xml
<CustomField>
    <fullName>Venue_Video_Shoot__c</fullName>
    <label>Venue</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Show Apartment</fullName>
            </value>
            <value>
                <fullName>Sales Gallery</fullName>
            </value>
            <value>
                <fullName>Event Hall</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApprovalEmailForEventsController.cls
public  class ApprovalEmailForEventsController {
    public static Id currentId {get;set;}
    public static integer numberOfHoursElapsed {get;set;}
    public static boolean escalationEmail {get;set;}
	public static String getCurrentUserName(){
        return UserInfo.getFirstName()+' '+UserInfo.getLastName();
    }

	public static Events__c getrelatedTo() {
        Events__c evt =  [Select id,campaign_code__c,Event_Approved_status__c,start_time_of_the_event__C,end_time_of_the_event__C,Venue_Video_Shoot__c,No_Of_Pax_Attending__c,User_1__r.Name,User_2__r.Name,User_3__r.Name,Email_Last_Triggered_Time__c,Name,Next_Approver__c,Next_Approver__r.name,City_Country__c,Country__c,createdby.name,approval_request_submitted_time__c,Date_Of_Event__c,Sales_VP__r.name,Sales_Director__r.name,Owner.Name,Remaining_Days_in_Event__c,Channel_Relationship_Manager__r.name,Channel_Relationship_Head__r.name,Marketing_Support_Required_Brochures_etc__c,Channel_Partner__c,Channel_Partner__r.name,End_Date_Of_Event__c,Type_Of_road_show__c,
        recordtypeId,recordtype.name,
        (SELECT Id, LastActor.Name FROM ProcessInstances order by createddate desc limit 1)
         FROM EVENTS__c where id=:currentId]; 
        
         if(evt.approval_request_submitted_time__c != null){
         numberOfHoursElapsed = (evt.approval_request_submitted_time__c.date()).daysbetween((system.today()));
         numberOfHoursElapsed = numberOfHoursElapsed*24;
         }
        return evt;
    }
    public static String getLastApprovarName() {
        List<ProcessInstanceStep> steps = new List<ProcessInstanceStep>([
            SELECT Actor.Name
            FROM ProcessInstanceStep
            WHERE ProcessInstance.TargetObjectId = :currentId
            ORDER BY SystemModStamp DESC
            LIMIT 1
        ]);
        return ( steps.size() > 0 ) ? steps[0].Actor.Name : null;
    }
    
    public static List<ApprovalHistory_Control.eventWrap> getApprovalHistory(){
        return  ApprovalHistory_Control.ApprovalHistoryRecords(currentId,'Approved');
    }
    public static List<ApprovalHistory_Control.eventWrap> getApprovalHistoryRejection(){
        return  ApprovalHistory_Control.ApprovalHistoryRecords(currentId,'Rejected');
    }
}