force-app/main/default/objects/Eztap_Device__mdt/Eztap_Device__mdt.object-meta.xml
<CustomObject>
    <label>Eztap Device</label>
    <pluralLabel>Eztap Devices</pluralLabel>
</CustomObject>

force-app/main/default/objects/Eztap_Device__mdt/fields/Device_Id__c.field-meta.xml
<CustomField>
    <fullName>Device_Id__c</fullName>
    <label>Device Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTC Deposits</fullName>
                <label>OTC Deposit(Cash counter)</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>CDM Cash</fullName>
                <label>CDM Cash (Cash Deposit in Machine)</label>
            </value>
            <value>
                <fullName>CDM Cheque</fullName>
                <label>CDM Cheque (Cheque Deposit in Machine)</label>
            </value>
            <value>
                <fullName>International Wire Transfer</fullName>
                <label>IWT(International)</label>
            </value>
            <value>
                <fullName>Domestic Wire Transfer</fullName>
                <label>DWT(Domestic)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/Payment_Request_POP_Transactions__c.object-meta.xml
<CustomObject>
    <label>Payment Request POP Transactions</label>
    <nameField>
        <displayFormat>POP-{00000000}</displayFormat>
        <label>Payment Request POP Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Request POP Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/amount__c.field-meta.xml
<CustomField>
    <fullName>amount__c</fullName>
    <label>amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/P2PRequestId__c.field-meta.xml
<CustomField>
    <fullName>P2PRequestId__c</fullName>
    <label>P2PRequestId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Request POP Transactions</relationshipLabel>
    <relationshipName>Payment_Request_POP_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request_POP_Transactions__c/fields/username__c.field-meta.xml
<CustomField>
    <fullName>username__c</fullName>
    <label>username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InitiateEztapControllerTest.cls
@isTest
public class InitiateEztapControllerTest {
    
	@isTest
    public static void getAllEztapDevices_test(){
    	Test.startTest();
        InitiateEztapController.getAllEztapDevices();
        Test.stopTest();
    }
    
    @isTest
    public static void checkExistingRequest_test(){
        Payment_Request__c pr = new Payment_Request__c();
        pr.Mode__c = 'Credit Card';
        insert pr;
    	Test.startTest();
        InitiateEztapController.checkExistingRequest(pr.Id);
        Test.stopTest();
    }
    
    @isTest
    public static void startEztap_test(){
        Payment_Request__c pr = new Payment_Request__c();
        pr.Mode__c = 'Credit Card';
        pr.Amount__c = 100;
        insert pr;
    	Test.startTest();
        Eztap_Device__mdt device = [select Id, 
                                    MasterLabel, 
                                    DeveloperName, 
                                    Device_Id__c, Location__c, Username__c 
                                    from Eztap_Device__mdt 
                                    LIMIT 1];
        Test.setMock(HttpCalloutMock.class, new EzetapStartCalloutMock()); 
        InitiateEztapController.startEztap(device.Id,pr.Id);
        Test.stopTest();
    }
    
    @isTest
    public static void eztapCancelTransaction_test(){
        Payment_Request__c pr = new Payment_Request__c();
        pr.Mode__c = 'Credit Card';
        pr.Amount__c = 100;
        insert pr;
        Payment_Request_POP_Transactions__c txn = new Payment_Request_POP_Transactions__c();
        txn.Payment_Request__c = pr.Id;
        txn.P2PRequestId__c = '230103090Test';
        insert txn;
    	Test.startTest();
        Test.setMock(HttpCalloutMock.class, new EzetapCancelCalloutMock()); 
        InitiateEztapController.eztapCancelTransaction(pr.Id); 
        Test.stopTest();
    }
    
    @isTest
    public static void eztapStatusCheck_test(){
        Payment_Request__c pr = new Payment_Request__c();
        pr.Mode__c = 'Credit Card';
        pr.Amount__c = 100;
        insert pr;
        Payment_Request_POP_Transactions__c txn = new Payment_Request_POP_Transactions__c();
        txn.Payment_Request__c = pr.Id;
        txn.P2PRequestId__c = '230103090Test';
        insert txn;
    	Test.startTest();
        Test.setMock(HttpCalloutMock.class, new EzetapStatusCalloutMock()); 
        InitiateEztapController.eztapStatusCheck(pr.Id);
        Test.stopTest();
    }
    
    @isTest
    public static void eztapStatusCheckBatch_test(){
        Payment_Request__c pr = new Payment_Request__c();
        pr.Mode__c = 'Credit Card';
        pr.Amount__c = 100;
        insert pr;
        Payment_Request_POP_Transactions__c txn = new Payment_Request_POP_Transactions__c();
        txn.Payment_Request__c = pr.Id;
        txn.P2PRequestId__c = '230103090Test';
        insert txn;
    	Test.startTest();
        Test.setMock(HttpCalloutMock.class, new EzetapStatusCalloutMock()); 
        EztapStatusCheck ob = new EztapStatusCheck(txn.Id);
        Database.executeBatch(ob);
        Test.stopTest();
    }
}