force-app/main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <label>Issue</label>
    <nameField>
        <displayFormat>I-{000}</displayFormat>
        <label>Issue Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue__c/fields/Analysis_Description__c.field-meta.xml
<CustomField>
    <fullName>Analysis_Description__c</fullName>
    <label>Analysis Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Analysis_Submitted_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Analysis_Submitted_Date_Time__c</fullName>
    <label>Analysis Submitted Date &amp; Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Estimated_Effort_Person_Days__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Effort_Person_Days__c</fullName>
    <label>Estimated Effort (Person Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Under Analysis</fullName>
            </value>
            <value>
                <fullName>Analysis Done &amp; Submitted</fullName>
            </value>
            <value>
                <fullName>Go-ahead start of dev</fullName>
            </value>
            <value>
                <fullName>Under Development</fullName>
            </value>
            <value>
                <fullName>UAT</fullName>
            </value>
            <value>
                <fullName>Go-ahead migration to prod</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>ReOpen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IssueManagementVR.cls
public class IssueManagementVR {

            public static void requiredField()
    {
        for(Issue__c issueNew:(List<Issue__c>)trigger.new)
        {
            if(trigger.isInsert)
            if(issueNew.Status__c == 'Analysis Done & Submitted' && (issueNew.Analysis_Description__c == null
              || issueNew.Analysis_Submitted_Date_Time__c == null 
              || issueNew.Estimated_Effort_Person_Days__c == null))
            issueNew.addError('As you have selected Status "Analysis Done & Submitted" you must have to enter following fields >Analysis Submitted Date & Time  >Analysis Description >Estimated Effort (Person Days)');
            
            if(trigger.isUpdate)
            for(Issue__c issueOld :(List<Issue__c>)trigger.old)
            {
            if(issueNew.Status__c == 'Analysis Done & Submitted' && (issueNew.Analysis_Description__c == null
              || issueNew.Analysis_Submitted_Date_Time__c == null 
              || issueNew.Estimated_Effort_Person_Days__c == null))
            issueNew.addError('As you have selected Status  "Analysis Done & Submitted" you must have to enter following fields >Analysis Submitted Date & Time> >Analysis Description >Estimated Effort (Person Days)');    
            }
            
         }
     }

}