force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <label>Booking Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Date_of_Signing_by_Sobha_Signatory__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Signing_by_Sobha_Signatory__c</fullName>
    <label>Date of Signing by Sobha Signatory</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Paid_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Paid_Percentage__c</fullName>
    <formula>If(Agreement_Value__c &gt; 0 &amp;&amp; Total_On_Account_Money__c &gt; 0,
(Total_On_Account_Money_With_Registration__c)/(Agreement_Value__c + Tax_on_Purchase_Price__c),
0)</formula>
    <label>Paid Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/PCC_Approved_By_Audit__c.field-meta.xml
<CustomField>
    <fullName>PCC_Approved_By_Audit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PCC Approved By Audit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Email__c</fullName>
    <label>Primary Applicant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name__c</fullName>
    <label>Primary Applicant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/PrimaryMobileNumber__c.field-meta.xml
<CustomField>
    <fullName>PrimaryMobileNumber__c</fullName>
    <label>Primary Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Purchase_Price_Only__c.field-meta.xml
<CustomField>
    <fullName>Purchase_Price_Only__c</fullName>
    <label>Purchase Price Only</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/SPA_Executed_Date__c.field-meta.xml
<CustomField>
    <fullName>SPA_Executed_Date__c</fullName>
    <label>SPA Executed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/SPA_Issue_Date__c.field-meta.xml
<CustomField>
    <fullName>SPA_Issue_Date__c</fullName>
    <label>SPA Issue Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tax_on_Purchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Tax_on_Purchase_Price__c</fullName>
    <formula>Quotation__r.CGST_on_Total_Agreement_Value_Bucket__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT on Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_On_Account_Money_With_Registration__c.field-meta.xml
<CustomField>
    <fullName>Total_On_Account_Money_With_Registration__c</fullName>
    <formula>Total_On_Account_Money__c -  Registration_Amount_Paid__c - Credit_Card_Charges_Colleceted__c -VAT_Reduction_From_PPP__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total On Account Money</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/TotalAmountPaid__c.field-meta.xml
<CustomField>
    <fullName>TotalAmountPaid__c</fullName>
    <label>Total Amount Paid</label>
    <summarizedField>Demand__c.Total_Amount_Paid__c</summarizedField>
    <summaryFilterItems>
        <field>Demand__c.Demand_Status__c</field>
        <operation>notEqual</operation>
        <value>Reversed</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Demand__c.Debit_Type__c</field>
        <operation>notEqual</operation>
        <value>Credit Note Reversal</value>
    </summaryFilterItems>
    <summaryForeignKey>Demand__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <label>Tower</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Legal_Entity__c/Legal_Entity__c.object-meta.xml
<CustomObject>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Other_Applicants_Email__c.field-meta.xml
<CustomField>
    <fullName>Other_Applicants_Email__c</fullName>
    <label>Other Applicants Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Other_Applicants_Name__c.field-meta.xml
<CustomField>
    <fullName>Other_Applicants_Name__c</fullName>
    <label>Other Applicants Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Permanent_Address__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address__c</fullName>
    <label>Permanent Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <label>Primary Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Property_Type__c</fullName>
    <label>Project Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/RDS_Company_Code__c.field-meta.xml
<CustomField>
    <fullName>RDS_Company_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Chargeable_Area__c.field-meta.xml
<CustomField>
    <fullName>Chargeable_Area__c</fullName>
    <label>Chargeable Area</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Project_Property_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Property_Type__c</fullName>
    <label>Project Property Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Residential only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PCC.cls
public class PCC {
    public Date demandDate{get; set;}
    public Booking__c booking{get; set;} 
    public Date topDate{get; set;} 
    public Decimal result{get; set;} 
    public List<ProcessInstance> PList{get; set;} 
    public Id bookingId ;
    public String currencyInWord {get;set;}
    public Set<string> towerexception = new Set<string>();
    public PCC(){
        bookingId = (Id) ApexPages.currentPage().getParameters().get('bookingId');
        demandDate = System.today();
        booking = [SELECT Id,Primary_Applicant_Name__c,Opportunity__r.Other_Applicants_Name__c, Opportunity__r.Other_Applicants_Email__c,Opportunity__r.Primary_Email__c,
                            Opportunity__r.Permanent_Address__c,Primary_Applicant_Email__c, PrimaryMobileNumber__c,Unit__r.Name,Unit__r.Project_Property_Type__c,Unit__r.Tower__r.Name,PCC_Approved_By_Audit__c,Unit__r.Tower__r.RDS_Company_Code__r.Name,Unit__r.Tower__r.RDS_Company_Code__r.Account_Number_Flat_Cost__c,Unit__r.Tower__r.RDS_Company_Code__r.MICR_Code_Flat_Cost__c,Unit__r.Tower__r.RDS_Company_Code__r.Bank_Name_Flat_Cost__c,Unit__r.Tower__r.RDS_Company_Code__r.Favouring__c,Unit__r.Tower__r.RDS_Company_Code__r.IBAN__c,Unit__r.Tower__r.Address__c, Unit__r.Project__r.Name, Unit__r.Chargeable_Area__c,
                            Booking_Date__c,Total_On_Account_Money_With_Registration__c, Agreement_Value__c,Purchase_Price_Only__c,Unit__r.Project__r.Address__c,SPA_Executed_Date__c,Tax_on_Purchase_Price__c,SPA_Issue_Date__c,Unit__r.Tower__r.RDS_Company_Code__r.RDS_Address1__c ,TotalAmountPaid__c,Paid_Percentage__c,Date_of_Signing_by_Sobha_Signatory__c
                            FROM Booking__c WHERE Id = :bookingId];

        PList = [ SELECT CompletedDate,CreatedById,CreatedDate,ElapsedTimeInDays,ElapsedTimeInHours,ElapsedTimeInMinutes,Id,IsDeleted,LastActorId,LastModifiedById,LastModifiedDate,ProcessDefinitionId,Status,SubmittedById,SystemModstamp,TargetObjectId FROM ProcessInstance WHERE TargetObjectId =:bookingId  ORDER BY CreatedDate DESC LIMIT 1 ];
        if(PList.size() > 0){
            topDate = date.newinstance(PList[0].LastModifiedDate.year(), PList[0].LastModifiedDate.month(), PList[0].LastModifiedDate.day());
        }
        result = booking.Agreement_Value__c.setScale(2);
        // currencyInWord = S_NumberToWord.convertNumbertoWords(result).remove('Rupees ');
        S_NumberToWord S_N = new S_NumberToWord();
        currencyInWord = S_NumberToWord.CurrencyToWordsFormatAED(result);
    }

}