force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Email__c</fullName>
    <label>Primary Applicant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name__c</fullName>
    <label>Primary Applicant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Receipts__c.field-meta.xml
<CustomField>
    <fullName>Receipts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Receipt__c.Project_Unit__c</field>
            <operation>equals</operation>
            <valueField>$Source.Unit__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Sales_Head__c.field-meta.xml
<CustomField>
    <fullName>Sales_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Sales_Managers__c.field-meta.xml
<CustomField>
    <fullName>Sales_Managers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <label>Tower</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Head__c.field-meta.xml
<CustomField>
    <fullName>Sales_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Head</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mode__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/New_Sale_Approval__c.field-meta.xml
<CustomField>
    <fullName>New_Sale_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Sale Approval</label>
    <referenceTo>unit_hold_request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/New_Sale_Approval__c.field-meta.xml
<CustomField>
    <fullName>New_Sale_Approval__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Sale Approval</label>
    <referenceTo>unit_hold_request__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Project_Unit__c.field-meta.xml
<CustomField>
    <fullName>Project_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_No__c.field-meta.xml
<CustomField>
    <fullName>Receipt_No__c</fullName>
    <displayFormat>{0000}</displayFormat>
    <label>Receipt No</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Requester__c/Requester__c.object-meta.xml
<CustomObject>
    <label>Requester</label>
    <nameField>
        <displayFormat>RQ-{0000}</displayFormat>
        <label>Requester Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requester</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Requester__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Requester</relationshipLabel>
    <relationshipName>Requester</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Requester__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>Australian Dollar</fullName>
            </value>
            <value>
                <fullName>Bahrain Dinar</fullName>
            </value>
            <value>
                <fullName>Canadian Dollar</fullName>
            </value>
            <value>
                <fullName>Chinese Yuan</fullName>
            </value>
            <value>
                <fullName>European Euro</fullName>
            </value>
            <value>
                <fullName>Hong Kong Dollar</fullName>
            </value>
            <value>
                <fullName>Indian Rupee</fullName>
            </value>
            <value>
                <fullName>Japanese Yen</fullName>
            </value>
            <value>
                <fullName>Kuwaiti Dinar</fullName>
            </value>
            <value>
                <fullName>Saudi Riyal</fullName>
            </value>
            <value>
                <fullName>Singapore Dollar</fullName>
            </value>
            <value>
                <fullName>UK Pound</fullName>
            </value>
            <value>
                <fullName>US Dollar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Requester__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <formula>Booking__r.Unit__r.Tower__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tower</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/unit_hold_request__c/unit_hold_request__c.object-meta.xml
<CustomObject>
    <label>New Sale Approval</label>
    <nameField>
        <displayFormat>N-{0000}</displayFormat>
        <label>New Sale Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>New Sale Approvals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/unit_hold_request__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>New Sale Approvals</relationshipLabel>
    <relationshipName>New_Sale_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/unit_hold_request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>https://ceptessobha.atlassian.net/browse/SOB-133</description>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>New Sale Approvals</relationshipLabel>
    <relationshipName>New_Sale_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/unit_hold_request__c/fields/Sales_Head__c.field-meta.xml
<CustomField>
    <fullName>Sales_Head__c</fullName>
    <formula>Units_Hold_Request_Form__r.Channel_Partner__r.Sales_Manager_s_Line_Manager__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Head</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ReceiptCreationQueueable.cls
global class ReceiptCreationQueueable implements Queueable, Database.AllowsCallouts { 
    global List<String> receiptIds = new List<String>();
    global ReceiptCreationQueueable(List<String> receiptIdList){
        receiptIds = new list<String>(receiptIdList);
    }
    
    global void execute(QueueableContext context) { 
        List<Receipt__c> receiptList = [SELECT name,id,Project_Unit__r.Name,Total_Amount__c,Receipt_No__c,New_Sale_Approval__c,
                                         Currency__c,Booking__r.Tower__c,Booking__r.Name,Booking__r.Primary_Applicant_Name__c,
                                         New_Sale_Approval__r.Owner.email,New_Sale_Approval__r.Payment_Request__r.Name__c,
                                         New_Sale_Approval__r.Payment_Request__r.Email__c,GL_Date__c,Project__c,Payment_Request__c,
                                         Booking__r.Primary_Applicant_Email__c,Booking__r.Sales_Head__c,
                                         Booking__r.Secondary_Sales_Manager_VP__c,Booking__r.Sales_Head__r.Manager.Email,
                                         Booking__r.Secondary_Sales_Head__r.Manager.Email,
                                         Booking__r.Secondary_Sales_Manager_VP__r.email,Booking__r.Sales_Head__r.email,
                                         Booking__r.Sales_Managers__r.email,Booking__r.Secondary_Sales_Manager__r.email,
                                         Booking__r.Secondary_Sales_Head__r.email 
                                        FROM Receipt__c 
                                        WHERE Id IN : receiptIds];
        List<Messaging.SingleEmailMessage> emailsList = new  List<Messaging.SingleEmailMessage>();
        for(Receipt__c receipt : receiptList){
            //Changes to attach Receipt to Requester
            PageReference page = new PageReference('/apex/PrintReceiptSobhaDubai?id='+receipt.Id+'&letterhead=0');
            Blob pdf;
            String name = '';
            String descr = 'Receipt';
            try{              
                pdf = page.getContentAsPDF();
            }catch(Exception e){
                pdf = Blob.valueOf(e.getMessage());
                descr = e.getMessage();
            }
            
            Attachment att = new Attachment();
            att.Body = pdf;
            att.Name = receipt.name+'.pdf';
            att.IsPrivate = false;
            att.ParentId = receipt.New_Sale_Approval__c;
            att.Description = descr;
            insert att;
            //End ---
            
            System.debug('I am recordidyamini-->'+receipt.Id);
            String fileName;
            
            User usr = [SELECT Id, Email,Name FROM User WHERE Id = :UserInfo.getUserId()]; 
            if((receipt.New_Sale_Approval__r.Owner.email != null && receipt.New_Sale_Approval__r.Owner.email  != '') || Test.isRunningTest()){   
                
                PageReference pref = new PageReference('/apex/PrintReceiptSobhaDubai');
                pref.getParameters().put('id', receipt.Id);
                Blob b;
                if(!Test.isRunningTest()){
                    b = pref.getContent();   
                } else {
                    b = Blob.valueOf('Test123');
                }                           
                
                fileName = receipt.Name;
                Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();                                
                attach.setBody(b);
                attach.setFileName(fileName+'.pdf');  
                
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();              
                email.setSubject('Receipt for ' +receipt.Booking__r.Name+' '+receipt.Project_Unit__r.Name+' '+ receipt.Booking__r.Primary_Applicant_Name__c);
                List <String> lststringtoaddress = new List<String>();
                List <String> lstStringccaddress = new List <String>();
                List <String> lstStringbccaddress = new List <String>();
                
                String body =  'Dear ' + receipt.New_Sale_Approval__r.Payment_Request__r.Name__c+ ',<br/><br/>' +                        
                    
                    'Greetings, <br/><br/>'+
                    'Thank you for your payment towards your property'+' ' +receipt.Booking__r.Tower__c+' '+receipt.Project_Unit__r.Name +
                    '.Please find attached receipt of amount'+' '+receipt.Currency__c+' '+receipt.Total_Amount__c +'.<br/><br/>'+                
                    'Best Regards,<br/>'+
                    usr.Name;
                
                if(receipt.New_Sale_Approval__r.Payment_Request__r.Email__c !=null && receipt.New_Sale_Approval__r.Payment_Request__r.Email__c != ''){
                    lststringtoaddress.add(receipt.New_Sale_Approval__r.Payment_Request__r.Email__c); //Commented to block direct communication with client and added booking owner  
                    System.debug('lststringtoaddress -->'+ lststringtoaddress);          
                }
                
                if(receipt.Booking__r.Primary_Applicant_Email__c != null && receipt.Booking__r.Primary_Applicant_Email__c != ''){
                    lststringtoaddress.add(receipt.Booking__r.Primary_Applicant_Email__c);
                }
                SYSTEM.DEBUG('I AM EMAIL'+receipt.Booking__r.sales_Head__r.email);
                if(receipt.Booking__r.Sales_Head__c != null){
                    if(receipt.Booking__r.Sales_Head__r.email != null)
                    	lstStringccaddress.add(receipt.Booking__r.Sales_Head__r.email);
                    if(receipt.Booking__r.Sales_Head__r.Manager != null && receipt.Booking__r.Sales_Head__r.Manager.Email != null)
                    	lstStringccaddress.add(receipt.Booking__r.Sales_Head__r.Manager.Email);
                    SYSTEM.DEBUG('I AM EMAIL'+receipt.Booking__r.sales_Head__r.email);
                }
                if(receipt.Booking__r.Secondary_Sales_Head__c!=null){
                    if(receipt.Booking__r.Secondary_Sales_Head__r.Manager != null && receipt.Booking__r.Secondary_Sales_Head__r.Manager.Email != null)
                    	lstStringccaddress.add(receipt.Booking__r.Secondary_Sales_Head__r.Manager.Email);
                }
                if(receipt.Booking__r.Sales_Managers__c!=null && receipt.Booking__r.Sales_Managers__r.email != null){
                    lstStringccaddress.add(receipt.Booking__r.Sales_Managers__r.email);
                }
                if(receipt.Booking__r.Secondary_Sales_Manager__c!=null && receipt.Booking__r.Secondary_Sales_Manager__r.email != null){
                    lstStringccaddress.add(receipt.Booking__r.Secondary_Sales_Manager__r.email);
                }
                if(receipt.Booking__r.Secondary_Sales_Head__c!=null && receipt.Booking__r.Secondary_Sales_Head__r.email != null){
                    lstStringccaddress.add(receipt.Booking__r.Secondary_Sales_Head__r.email);
                }
                
                lstStringccaddress.add('salesops@sobharealty.com'); 
                lstStringccaddress.add(System.label.SF_Notifications);  
                
                email.setToAddresses(lststringtoaddress);
                email.setccAddresses(lstStringccaddress);
                email.setbccAddresses(lstStringbccaddress);
                email.setHtmlBody('<span style="font-family:Tahoma;font-size:14px;" >'+body+'</span>');
                email.setFileAttachments(new Messaging.EmailFileAttachment[] {attach});   
                emailsList.add(email);
                
                
                //ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Confirm,'A mail has been sent to customer on email Id: ' + receiptdetails.Requester__r.Owner.email)); 
            } else 
            {
                //ApexPages.addMessage(new ApexPages.message(ApexPages.severity.Warning,'Customer Email Id is blank'));     
            }  
        }
        Messaging.sendEmail(emailsList);
    }
    
}