force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>Booking In Process</fullName>
            </value>
            <value>
                <fullName>Cancellation In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CDR__c/CDR__c.object-meta.xml
<CustomObject>
    <label>CDR</label>
    <nameField>
        <displayFormat>CDR-{0000}</displayFormat>
        <label>CDR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CDRS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CDR__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CDRS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CDR__c/fields/Call_Recording__c.field-meta.xml
<CustomField>
    <fullName>Call_Recording__c</fullName>
    <label>Call Recording</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CDR__c/fields/Extension__c.field-meta.xml
<CustomField>
    <fullName>Extension__c</fullName>
    <label>Extension</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CDR__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>CDRS</relationshipLabel>
    <relationshipName>CDRS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CDR__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AGENT BUSY</fullName>
            </value>
            <value>
                <fullName>ANSWERED</fullName>
            </value>
            <value>
                <fullName>BUSY</fullName>
            </value>
            <value>
                <fullName>CANCEL</fullName>
            </value>
            <value>
                <fullName>DISCONNECTED</fullName>
            </value>
            <value>
                <fullName>FAILD</fullName>
            </value>
            <value>
                <fullName>IVR TIMEOUT</fullName>
            </value>
            <value>
                <fullName>NO AGENTS</fullName>
            </value>
            <value>
                <fullName>NO ANSWER</fullName>
            </value>
            <value>
                <fullName>QUEUE TIMEOUT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Call_Duration__c.field-meta.xml
<CustomField>
    <fullName>Call_Duration__c</fullName>
    <label>Call Duration</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Call_Hold_Duration__c.field-meta.xml
<CustomField>
    <fullName>Call_Hold_Duration__c</fullName>
    <description>In seconds</description>
    <label>Call Hold Duration</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Call_Recording_Url__c.field-meta.xml
<CustomField>
    <fullName>Call_Recording_Url__c</fullName>
    <label>Recording Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Call_Status__c.field-meta.xml
<CustomField>
    <fullName>Call_Status__c</fullName>
    <label>Call Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Calling_Agent__c.field-meta.xml
<CustomField>
    <fullName>Calling_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent Details</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/CTI_Unique_Id__c.field-meta.xml
<CustomField>
    <fullName>CTI_Unique_Id__c</fullName>
    <externalId>true</externalId>
    <label>CTI Unique Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Disposition__c.field-meta.xml
<CustomField>
    <fullName>Disposition__c</fullName>
    <inlineHelpText>In Seconds</inlineHelpText>
    <label>Disposition</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Last_Contacted_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Contacted_Date__c</fullName>
    <label>Last Contacted Date</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Manual_Dial__c.field-meta.xml
<CustomField>
    <fullName>Manual_Dial__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Manual Dial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVAILABLE</fullName>
                <label>Available</label>
            </value>
            <value>
                <fullName>BUSY</fullName>
                <label>Busy</label>
            </value>
            <value>
                <fullName>BREAK</fullName>
                <label>Break</label>
            </value>
            <value>
                <fullName>OUTCALL</fullName>
                <label>OutCall</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TeleSalesCTICDRAPI.cls
@RestResource(urlMapping='/sobhatelesalescticdrpush/')
global with sharing class TeleSalesCTICDRAPI {
    @HttpPost
    global static CTICDRAPIWrapper doPost() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        try{	
            CTICDRAPIWrapper exposeData = new CTICDRAPIWrapper();
            DooCTICDRParser result;
            if (Test.isRunningTest()) {
                result = testParseObj();
            } else {
                if (req.requestBody == null){exposeData.success = false;exposeData.statusCode = 400;exposeData.message = 'No CDR body!!';TeleSalesUtil.createTeleSalesAPILogs('sobhatelesalescticdrpush','TeleSalesCTICDRAPI','',JSON.serialize(exposeData),'',''); return exposeData;}
                result = (DooCTICDRParser)JSON.deserialize(req.requestBody.toString(),DooCTICDRParser.class);
            }
            
            String phoneNumber = result.phone_number;
            String agentExtension = result.extension_no;
            String uniqueId = result.uniqueId;
            String did = result.did;
            String recordId = result.recordId;
            
            if(Test.isRunningTest())
                phoneNumber='971502083945';
            
            if(recordId!=null && recordId!='' && recordId.startsWith('a06')){
                
                //Query user for the extension
                List<User> usersList = [SELECT id FROM User WHERE Extension =: agentExtension];
                
                if (usersList.size() == 0) {exposeData.success = false; exposeData.statusCode = 400; exposeData.message = 'No agent with extension - '+agentExtension;  return exposeData; }
                
                if (usersList.size() > 1) {exposeData.success = false;exposeData.statusCode = 400;exposeData.message = 'Multiple agents with extension - '+agentExtension; return exposeData;}
                
                List<Task__c> taskCreatedByAgent = [SELECT id,
                                                    Call_Duration__c,
                                                    Call_Hold_Duration__c,
                                                    Call_Recording_Url__c,
                                                    Call_Status__c ,
                                                    Manual_Dial__c
                                                    FROM Task__c 
                                                    WHERE createdById =: usersList[0].id 
                                                    AND Booking__c =: recordId
                                                    AND createdDate = TODAY
                                                    AND Manual_Dial__c = false
                                                    ORDER BY createdDate desc];
                Task__c latestTask;
                
                if (taskCreatedByAgent.size() < 1) { Task__c newTask = new Task__c(); latestTask = newTask; List<Booking__c> bookingList = [SELECT id FROM Booking__c WHERE Id =: recordId]; if (bookingList.size() > 0) { latestTask.booking__c = bookingList[0].id; } } 
                else { latestTask = taskCreatedByAgent[0]; }
                
                if (latestTask != null) { latestTask.Call_Duration__c  = result.After_Call_Work_Duration; latestTask.Call_Hold_Duration__c= result.Hold_Duration; latestTask.Call_Status__c= result.Call_Status; latestTask.Call_Recording_Url__c= result.Call_Recording_Link_Url; latestTask.CTI_Unique_Id__c = result.uniqueid; latestTask.Disposition__c = result.After_Call_Work_Duration; latestTask.Last_Contacted_Date__c = result.Date_And_Time_Of_Call; latestTask.Calling_Agent__c = usersList[0].id; upsert latestTask; exposeData.success = true; exposeData.statusCode = 200; exposeData.message = 'CDR updated successfully'; }
                
                return exposeData;
            }
            else{
                List<Lead> leadList = [Select Id,OwnerId
                                       From Lead 
                                       where MobilePhone=:phoneNumber order by CreatedDate desc];
                
                List<User> usersList = [Select Id,Extension From User where Extension =:agentExtension and isActive=true LIMIT 1];
                
                CDR__c cdr = new CDR__c();
                cdr.Call_Recording__c = result.Call_Recording_Link_Url;
                cdr.Date_Time__c = ((result.Date_And_Time_Of_Call != null) && (result.Date_And_Time_Of_Call != '')) ? DateTime.valueOf(result.Date_And_Time_Of_Call) : System.Now();
                cdr.Duration__c = String.valueOf(result.Talk_Time_Duration);
                cdr.Lead__c = (leadList.size()>0)?leadList[0].Id:null;
                cdr.Status__c = result.Call_Status;
                cdr.Agent__c = (usersList.size()>0)?usersList[0].Id:null;
                cdr.Extension__c = (usersList.size()>0)?usersList[0].Extension:'';
                if(Test.isRunningTest())
                    cdr.Lead__c = leadList[0].Id;
                insert cdr;
                
                exposeData.success = true;
                exposeData.statusCode = 200;
                exposeData.message = 'CDR updated successfully.';
                if(!Test.isRunningTest()) TeleSalesUtil.createTeleSalesAPILogs('sobhatelesalescticdrpush','TeleSalesCTICDRAPI',req.requestBody.toString(),JSON.serialize(exposeData),'','');
                return exposeData;
            }
        }catch(Exception e) {
            System.debug('Your exception message here....'+e.getMessage());
            CTICDRAPIWrapper exposeData = new CTICDRAPIWrapper();
            exposeData.success = false;
            exposeData.statusCode = 400;
            exposeData.message = e.getMessage();
            if(!Test.isRunningTest()) TeleSalesUtil.createTeleSalesAPILogs('sobhatelesalescticdrpush','TeleSalesCTICDRAPI',req.requestBody.toString(),JSON.serialize(exposeData),e.getMessage(),e.getStackTraceString());
            return exposeData;
        }
    }
    
    global with sharing class CTICDRAPIWrapper{
        Public Boolean success;
        public Integer statusCode;
        public String message='';
    }
    
    public static DooCTICDRParser testParseObj() {
        String json = '{'+
            '  \"phone_number\": \"00919900000001\",'+
            '  \"extension_no\": \"2002\",'+
            '  \"uniqueid\": \"1649938730.602\",'+
            '  \"Call_Status\": \"ANSWER\",'+
            '  \"Talk_Time_Duration\": 7,'+
            '  \"After_Call_Work_Duration\": 120,'+
            '  \"Queue_Duration\": 4,'+
            '  \"Hold_Duration\": 0,'+
            '  \"Date_And_Time_Of_Call\": \"2022-04-14 16:18:49\",'+
            '  \"Call_Recording_Link_Url\": \"https://cti.sobhaapps.com/webphone/login/monitor/20220414/IN-2002-0502083945-20220414-161850-1649938730.601.wav\",'+
            '  \"Queue\": \"801\"'+
            '}';
        DooCTICDRParser obj = DooCTICDRParser.parse(json);
        return obj;
    }
}