force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <label>Booking Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <formula>Quotation__r.Payment_Plan__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Plan</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>Booking In Process</fullName>
            </value>
            <value>
                <fullName>Cancellation In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Legacy_Booking_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Booking_Id__c</fullName>
    <label>Legacy Booking Id</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AEDToUSDConversionRate</label>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Plan__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Valid</fullName>
                <default>true</default>
                <label>Not Valid</label>
            </value>
            <value>
                <fullName>Valid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SH-{000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>Payment_Plan__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/Time_Slot_For_Handover__c.object-meta.xml
<CustomObject>
    <label>Time Slot For Handover</label>
    <nameField>
        <displayFormat>HO - {0000}</displayFormat>
        <label>Time Slot For  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slot For Handover</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Time Slot For Handover</relationshipLabel>
    <relationshipName>Time_Slot_For_Handover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/CRM_Excutive__c.field-meta.xml
<CustomField>
    <fullName>CRM_Excutive__c</fullName>
    <label>CRM Executive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sunny Pradhan</fullName>
            </value>
            <value>
                <fullName>Ahmed Yossry</fullName>
            </value>
            <value>
                <fullName>Nisha Krishnan</fullName>
            </value>
            <value>
                <fullName>Racha Dannaoui</fullName>
            </value>
            <value>
                <fullName>Usman Sheikh</fullName>
            </value>
            <value>
                <fullName>Ali Yousuf Abdulla Qassem Alemadi</fullName>
            </value>
            <value>
                <fullName>Priyanka Binil</fullName>
            </value>
            <value>
                <fullName>Sahar Sultan</fullName>
            </value>
            <value>
                <fullName>Laila Nadeer</fullName>
            </value>
            <value>
                <fullName>Abdelrahman Salim Rashid Alzumr Al-Ali</fullName>
            </value>
            <value>
                <fullName>Deeksha Poral Lakshminarayana</fullName>
            </value>
            <value>
                <fullName>Hadi osama hussain mohamed ghanem</fullName>
            </value>
            <value>
                <fullName>Malak Saleh</fullName>
            </value>
            <value>
                <fullName>Juma Khalfan Juma Humaid Al-Ali</fullName>
            </value>
            <value>
                <fullName>Ummer Farhan</fullName>
            </value>
            <value>
                <fullName>Roopa Nataraj</fullName>
            </value>
            <value>
                <fullName>Divya Shanthigrama Keshava</fullName>
            </value>
            <value>
                <fullName>Priya Rathi</fullName>
            </value>
            <value>
                <fullName>Aruna</fullName>
            </value>
            <value>
                <fullName>Davood Sheikh</fullName>
            </value>
            <value>
                <fullName>Aswathi Kumar</fullName>
            </value>
            <value>
                <fullName>Vivek Sharma</fullName>
            </value>
            <value>
                <fullName>Ruvaid Vani</fullName>
            </value>
            <value>
                <fullName>Pratyush Kumar Nayak</fullName>
            </value>
            <value>
                <fullName>Araba Aln’airat</fullName>
            </value>
            <value>
                <fullName>Mariia Aleksandrovskaia</fullName>
            </value>
            <value>
                <fullName>Yugeshkumar Sureshkumar</fullName>
            </value>
            <value>
                <fullName>Qingqin Yang</fullName>
            </value>
            <value>
                <fullName>Abdeldjalil Kamel Bensenada</fullName>
            </value>
            <value>
                <fullName>Kaisar Sabraimov</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/Proposed_Scheduled_Date__c.field-meta.xml
<CustomField>
    <fullName>Proposed_Scheduled_Date__c</fullName>
    <label>Proposed Scheduled Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/QT_Keepout_Date__c.field-meta.xml
<CustomField>
    <fullName>QT_Keepout_Date__c</fullName>
    <label>QT Keepout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Unable to contact</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>At the time of Handover</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Planned</fullName>
                <isActive>false</isActive>
                <label>Planned</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/Third_party_snagging__c.field-meta.xml
<CustomField>
    <fullName>Third_party_snagging__c</fullName>
    <label>Third party snagging</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/Timings__c.field-meta.xml
<CustomField>
    <fullName>Timings__c</fullName>
    <label>Timings</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10 AM-11 AM</fullName>
            </value>
            <value>
                <fullName>11 AM-12 PM</fullName>
            </value>
            <value>
                <fullName>12 PM- 1 PM</fullName>
            </value>
            <value>
                <fullName>1 PM - 2 PM</fullName>
            </value>
            <value>
                <fullName>2 PM - 3 PM</fullName>
            </value>
            <value>
                <fullName>3 PM- 4 PM</fullName>
            </value>
            <value>
                <fullName>4 PM -5 PM</fullName>
            </value>
            <value>
                <fullName>5 PM - 6 PM</fullName>
            </value>
            <value>
                <fullName>6 PM - 7 PM</fullName>
            </value>
            <value>
                <fullName>7PM - 8 PM</fullName>
            </value>
            <value>
                <fullName>12:30 PM -2:30 PM</fullName>
                <isActive>false</isActive>
                <label>12:30 PM -2:30 PM</label>
            </value>
            <value>
                <fullName>4:00 PM - 6:00 PM</fullName>
                <isActive>false</isActive>
                <label>4:00 PM - 6:00 PM</label>
            </value>
            <value>
                <fullName>9 AM-11 AM</fullName>
                <isActive>false</isActive>
                <label>9 AM-11 AM</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/recordTypes/HandOver.recordType-meta.xml
<RecordType>
    <fullName>HandOver</fullName>
    <active>true</active>
    <label>HandOver</label>
</RecordType>

force-app/main/default/classes/PSM_HO_Handover_Batch_Test.cls
@isTest
private class PSM_HO_Handover_Batch_Test {
    
    @testSetup
    static void setup() {
        // Create sample Booking__c records
        Map<String,Id> projectMap=TestDataFactory.createMasterProject('Test');
        Quotation__c quote=new Quotation__c();
        quote.Opportunity__c=projectMap.get('OPPORTUNITY');
        quote.Payment_Plan__c=projectMap.get('PLAN');
        insert quote;
        Booking__c bookg= New Booking__c();
        bookg.Quotation__c=quote.Id;
        bookg.Booking_Date__c = System.today();
        insert bookg;
        List<Booking__c>bookingRecords = new List<Booking__c>();
        bookingRecords.add(bookg);
        
        Time_Slot_For_Handover__c tsh1 = new Time_Slot_For_Handover__c();
        tsh1.recordTypeId = Schema.SObjectType.Time_Slot_For_Handover__c.getRecordTypeInfosByName().get('Home Orientation').getRecordTypeId();
        tsh1.Booking__c = bookg.Id;
        tsh1.QT_Keepout_Date__c = Date.valueOf('2023-09-09'); 
        insert tsh1;
        
        Time_Slot_For_Handover__c tsh2 = new Time_Slot_For_Handover__c();
        tsh2.recordTypeId = Schema.SObjectType.Time_Slot_For_Handover__c.getRecordTypeInfosByName().get('HandOver').getRecordTypeId();
        tsh2.Booking__c = bookg.Id;
        tsh2.QT_Keepout_Date__c = Date.valueOf('2023-09-09'); 
        insert tsh2;
        
        // Create corresponding PropStrength__Application_Booking__c records
        List<PropStrength__Application_Booking__c> appBookingRecords = new List<PropStrength__Application_Booking__c>();
        PropStrength__Projects__c proj = new PropStrength__Projects__c(Booking_Form_T_C__c = 'Testing Form', DLD_Executive__c=UserInfo.getUserId(), Name = 'Test Project', PropStrength__Active__c = true, T_link_Demand_Days__c = 1);
        Insert proj;
        for (Booking__c booking : bookingRecords) {
            appBookingRecords.add(new PropStrength__Application_Booking__c(
                Legacy_Booking_Id__c = booking.Id,PropStrength__Project__c = proj.Id, PropStrength__Booking_Date__c = system.today()
            ));
        }
        insert appBookingRecords;
    }
    
    @isTest
    static void testBatchExecution() {
        // Instantiate the batch class
        PSM_HO_Handover_Batch batch = new PSM_HO_Handover_Batch('select Id,Name,RecordTypeId,RecordType.Name,CRM_Excutive__c,Proposed_Scheduled_Date__c,Booking__c,Scheduled_Date__c,Status__c,Remarks__c,QT_Keepout_Date__c,Third_party_snagging__c, Timings__c from Time_Slot_For_Handover__c WHERE Booking__c != NULL');
        
        // Execute the batch
        Test.startTest();
        ID batchId = Database.executeBatch(batch);
        Test.stopTest();
        
    }
}