force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Slot_For_Handover__c/Time_Slot_For_Handover__c.object-meta.xml
<CustomObject>
    <label>Time Slot For Handover</label>
    <nameField>
        <displayFormat>HO - {0000}</displayFormat>
        <label>Time Slot For  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Slot For Handover</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Time Slot For Handover</relationshipLabel>
    <relationshipName>Time_Slot_For_Handover</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/fields/QT_Keepout_Date__c.field-meta.xml
<CustomField>
    <fullName>QT_Keepout_Date__c</fullName>
    <label>QT Keepout Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Slot_For_Handover__c/recordTypes/HandOver.recordType-meta.xml
<RecordType>
    <fullName>HandOver</fullName>
    <active>true</active>
    <label>HandOver</label>
</RecordType>

force-app/main/default/classes/Test_Mb_getBookingJourney.cls
@isTest
public class Test_Mb_getBookingJourney {
    
    @testSetup
    static void setupTestData() {
        Mobile_TestUtil.createBooking();
    }
    
    @isTest
    static void testGetBookingListWithRecords() {
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        
        request.requestURI = '/services/apexrest/getBookingJourney';
        request.httpMethod = 'POST';
        
        RestContext.request = request;
        RestContext.response = response;
        
        List<booking__c> book = [select id, name from booking__c];

        Test.startTest();
        Mobile_getBookingJourney.getBookingJourney(book[0].Id);
        Test.stopTest();
        
        System.assertEquals(200, response.statusCode);
    }
    
    @isTest
    static void testGetBookingListWithRecords2() {
         RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        
        request.requestURI = '/services/apexrest/getBookingJourney';
        request.httpMethod = 'POST';
        
        RestContext.request = request;
        RestContext.response = response;
        
        List<booking__c> book = [select id, name from booking__c];
        
        

        Time_Slot_For_Handover__c tsh = new Time_Slot_For_Handover__c();
        tsh.recordTypeId = Schema.SObjectType.Time_Slot_For_Handover__c.getRecordTypeInfosByName().get('Home Orientation').getRecordTypeId();
        tsh.Booking__c = book[0].Id;
        tsh.QT_Keepout_Date__c = Date.valueOf('2023-09-09'); 
        insert tsh;
        
        Test.startTest();
        Mobile_getBookingJourney.getBookingJourney(book[0].Id);
        Test.stopTest();
        
        System.assertEquals(200, response.statusCode);
        
    }
    
    @isTest
    static void testGetBookingListWithRecords3() {
        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
        
        request.requestURI = '/services/apexrest/getBookingJourney';
        request.httpMethod = 'POST';
        
        RestContext.request = request;
        RestContext.response = response;
        
        List<booking__c> book = [select id, name from booking__c];
        
        

        Time_Slot_For_Handover__c tsh = new Time_Slot_For_Handover__c();
        tsh.recordTypeId = Schema.SObjectType.Time_Slot_For_Handover__c.getRecordTypeInfosByName().get('HandOver').getRecordTypeId();
        tsh.Booking__c = book[0].Id;
        tsh.QT_Keepout_Date__c = Date.valueOf('2023-09-09'); 
        insert tsh;
        
        Test.startTest();
        Mobile_getBookingJourney.getBookingJourney(book[0].Id);
        Test.stopTest();
        
        System.assertEquals(200, response.statusCode);
    }

}