force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Credit_Card_Charges_Colleceted__c.field-meta.xml
<CustomField>
    <fullName>Credit_Card_Charges_Colleceted__c</fullName>
    <label>Other Charges Collected Rollup</label>
    <summarizedField>Receipt__c.Credit_Card_Charges__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt__c.Receipt_Status__c</field>
        <operation>equals</operation>
        <value>Cleared</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt__c.Other_Charges_Type__c</field>
        <operation>notEqual</operation>
        <value>Late Payment Charges</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/DLD_Amount__c.field-meta.xml
<CustomField>
    <fullName>DLD_Amount__c</fullName>
    <formula>((4 / 100) *  Quotation__r.Total_Agreement_Value_Bucket__c ) + 1150</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DLD Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Payment_Milestones__c.field-meta.xml
<CustomField>
    <fullName>Payment_Milestones__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Milestones</label>
    <referenceTo>Payment_Milestones__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Registration_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Registration_Amount_Paid__c</fullName>
    <label>Registration Amount Paid (RollUp)</label>
    <summarizedField>Receipt__c.Registration_Collection_Control_Report__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt__c.Receipt_Status__c</field>
        <operation>equals</operation>
        <value>Cleared</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt__c.Is_Reversed_Receipt__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt__c.Other_Charges_Type__c</field>
        <operation>equals</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_On_Account_Money__c.field-meta.xml
<CustomField>
    <fullName>Total_On_Account_Money__c</fullName>
    <label>Total On Account Money With Registration</label>
    <summarizedField>Receipt__c.Amount_Rs__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt__c.Receipt_Status__c</field>
        <operation>equals</operation>
        <value>Cleared</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt__c.Consider_for_Paid_Percentage__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt__c.Is_Reversed_Receipt__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/VAT_Reduction_From_PPP__c.field-meta.xml
<CustomField>
    <fullName>VAT_Reduction_From_PPP__c</fullName>
    <defaultValue>0</defaultValue>
    <label>VAT Reduction From PPP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Debit_Type__c.field-meta.xml
<CustomField>
    <fullName>Debit_Type__c</fullName>
    <label>Debit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cheque Bounce</fullName>
            </value>
            <value>
                <fullName>Brokerage Reversal</fullName>
            </value>
            <value>
                <fullName>Interior Charges</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>Interest Charges</fullName>
            </value>
            <value>
                <fullName>DLD Charges</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Credit Card Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Demand_Status__c.field-meta.xml
<CustomField>
    <fullName>Demand_Status__c</fullName>
    <label>Demand Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Raised</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demand__c/fields/GL_Date__c.field-meta.xml
<CustomField>
    <fullName>GL_Date__c</fullName>
    <label>GL Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Installment__c.field-meta.xml
<CustomField>
    <fullName>Installment__c</fullName>
    <formula>If(NOT(ISNULL(Payment_Milestones__c)), Payment_Milestones__r.Installment__c,   Milestone_Name__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Installment</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Milestone_Name__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Name__c</fullName>
    <label>Milestone Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Payment_Milestones__c.field-meta.xml
<CustomField>
    <fullName>Payment_Milestones__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Milestones</label>
    <referenceTo>Payment_Milestones__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Amount_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Tax_Demanded__c.field-meta.xml
<CustomField>
    <fullName>Total_Tax_Demanded__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total VAT Demanded</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Error_Log__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demand</label>
    <referenceTo>Demand__c</referenceTo>
    <relationshipLabel>Error Log</relationshipLabel>
    <relationshipName>Error_Log</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Payment Milestones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Milestones__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Milestones__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <formula>Project_Construction_Stages__r.Planned_date_of_completion__c +  Number_Of_Days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Milestones__c/fields/Installment__c.field-meta.xml
<CustomField>
    <fullName>Installment__c</fullName>
    <label>Installment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Name__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Name__c</fullName>
    <label>Milestone Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Amount_Rs__c.field-meta.xml
<CustomField>
    <fullName>Amount_Rs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount (AED)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Cheque_DD_Date__c.field-meta.xml
<CustomField>
    <fullName>Cheque_DD_Date__c</fullName>
    <label>Cheque Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demand</label>
    <referenceTo>Demand__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Number__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Number__c</fullName>
    <formula>IF( Advance_Receipt__c  = true, IF( Tax_Receipt__c = true, (Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Project_Unit__r.Tower__r.Name ,2) &amp; &apos;-&apos; &amp; Project_Unit__r.Name &amp; &apos;/&apos; &amp; TEXT(Receipt_Date__c) &amp; &apos;/&apos; &amp; &apos;AdvTax-&apos; &amp; Name,(Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Project_Unit__r.Tower__r.Name ,2) &amp; &apos;-&apos; &amp; Project_Unit__r.Name &amp; &apos;/&apos; &amp; TEXT(Receipt_Date__c) &amp; &apos;/&apos; &amp; &apos;Adv-&apos; &amp; Name), 
(Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Project_Unit__r.Tower__r.Name ,2) &amp; &apos;-&apos; &amp; Project_Unit__r.Name &amp; &apos;/&apos; &amp; TEXT(Receipt_Date__c) &amp; &apos;/&apos; &amp; Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Receipt Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Mobile_getStatementOfAccount.cls
@RestResource(urlMapping = '/getStatementOfAccount')
global class Mobile_getStatementOfAccount{

    @HttpPost
    global static HttpResponseWrapper getStatementOfAccount(String bookingId){
        ResponseBodyWrapper statementOfAccountWrapper = new ResponseBodyWrapper();
        try {

            List<Booking__c> bookingList = [Select id, Agreement_Value__c,Total_On_Account_Money__c,Registration_Amount_Paid__c,DLD_Amount__c,Credit_Card_Charges_Colleceted__c, VAT_Reduction_From_PPP__c from Booking__c where id= :bookingId LIMIT 1];
            if(bookingList.size() > 0){
                statementOfAccountWrapper.purchasePrice = bookingList[0].Agreement_Value__c != null ? bookingList[0].Agreement_Value__c.setScale(2, RoundingMode.HALF_UP) : 0;
                statementOfAccountWrapper.regAmountPaid = bookingList[0].Registration_Amount_Paid__c != null ? bookingList[0].Registration_Amount_Paid__c.setScale(2, RoundingMode.HALF_UP) : 0;
                statementOfAccountWrapper.totalAmount = statementOfAccountWrapper.purchasePrice + (bookingList[0].DLD_Amount__c != null ? bookingList[0].DLD_Amount__c.setScale(2, RoundingMode.HALF_UP) : 0);
                statementOfAccountWrapper.paidAmount = bookingList[0].Total_On_Account_Money__c != null ? bookingList[0].Total_On_Account_Money__c.setScale(2, RoundingMode.HALF_UP) : 0;
                List<PayWrapper> demandWrapperList = new List<PayWrapper>();
                List<PayWrapper> receiptWrapperList = new List<PayWrapper>();
                for(Demand__c demandRec : [SELECT Id, Name, Total_Amount_Demanded__c, Demand_Status__c, Milestone_Name__c, GL_Date__c, Due_Date__c, Invoice_Date__c, Debit_Type__c, Payment_Milestones__c, Total_Tax_Demanded__c,Installment__c 
                                            FROM Demand__c WHERE Debit_Type__c != 'DLD Charges' and Booking__c = :bookingId ORDER BY GL_Date__c]){
                    PayWrapper demandWrapRec = new PayWrapper();
                    demandWrapRec.name = demandRec.Name;
                    demandWrapRec.createdDate = demandRec.Invoice_Date__c;
                    demandWrapRec.dueDate = demandRec.Due_Date__c;
                    demandWrapRec.isReversed = demandRec.Demand_Status__c != null ? true : false ;
                    if(demandRec.Total_Amount_Demanded__c != null && demandRec.Total_Tax_Demanded__c != null) { 
                        demandWrapRec.amount = (Decimal)demandRec.Total_Amount_Demanded__c + (Decimal)demandRec.Total_Tax_Demanded__c;
                    }
                    demandWrapRec.installment = demandRec.Installment__c != null && String.isNotBlank(demandRec.Installment__c) ? demandRec.Installment__c : null;
                    demandWrapRec.milesstoneName = demandRec.Milestone_Name__c != null && String.isNotBlank(demandRec.Milestone_Name__c) ? demandRec.Milestone_Name__c : null;
                    demandWrapRec.debitType = demandRec.Debit_Type__c != null && String.isNotBlank(demandRec.Debit_Type__c) ? demandRec.Debit_Type__c : null;
                    
                    demandWrapperList.add(demandWrapRec);
                }
                if(demandWrapperList.size() > 0){
                    statementOfAccountWrapper.demandList = demandWrapperList;
                }
                for(Receipt__c receiptRec : [SELECT Id, Name, CreatedDate, Mode__c, Cheque_DD_Date__c, GL_Date__c, Cheque_DD__c, DraweeBank__c,Currency__c, Amount_Rs__c, Receipt_Number__c, Receipt_Status__c, Demand__c, Demand__r.Name, Description__c,Registration_Collection_Control_Report__c,Debit_Account__r.Name FROM Receipt__c 
                                    WHERE Booking__c = :bookingId AND Receipt_Status__c IN('Cleared') AND (Mode__c !='Credit Note' or Debit_Account__r.Name in ('Commission Adjustment Credit','Credit Card Transactions','Discount/rebate credit note','Receipt transfer credit (swap)','RECEIVABLE/PAYABLE ADJUSTMENT','Unearned Revenue','Interest charges','Broker underwriting adjustment','Cheque Dishonored charges (Miscellaneous Income)','DIB–AED–ES–CV–Main A/c–SLLC - 001582194865001')) ORDER BY GL_Date__c]){
                    PayWrapper receiptWrapRec = new PayWrapper();  
                    receiptWrapRec.name = receiptRec.Name;   
                    receiptWrapRec.createdDate = Date.newInstance(receiptRec.CreatedDate.year(), receiptRec.CreatedDate.month(), receiptRec.CreatedDate.day());
                    receiptWrapRec.amount = receiptRec.Amount_Rs__c != null ? receiptRec.Amount_Rs__c.setScale(2, RoundingMode.HALF_UP) : 0;
                    receiptWrapperList.add(receiptWrapRec);
                }
                if(receiptWrapperList.size() > 0){
                    statementOfAccountWrapper.receiptList = receiptWrapperList;
                }

                return prepareResponse(statementOfAccountWrapper,'Operation Successfull','Success',200,true);             
            }

            return prepareResponse(null,'No data found','No Data Found',400,false);
        } catch (Exception ex) {
            Error_Log__c logError = new Error_Log__c(Message__c = ex.getMessage());
            logError.class__c = 'Mobile_getStatementOfAccount';
            insert logError;
            return prepareResponse(null,ex.getMessage(),'Error',400,false);
        }

    }

    public static HttpResponseWrapper prepareResponse(ResponseBodyWrapper rBody,string rMessage,string rStatus,integer rStatusCode,boolean rSuccess){
        HttpResponseWrapper resWrap = new HttpResponseWrapper();
        resWrap.data = rBody;
        resWrap.Message = rMessage;
        resWrap.status = rStatus;
        resWrap.statusCode = rStatusCode;
        resWrap.success = rSuccess;
        return resWrap;
    }
    
    public class ResponseBodyWrapper{
        public Decimal purchasePrice;
        public Decimal regAmountPaid;
        public Decimal totalAmount;
        public Decimal paidAmount;
        public List<PayWrapper> demandList;
        public List<PayWrapper> receiptList;
    }

    public class PayWrapper{
        public String name;
        public Date createdDate;
        public Date dueDate;
        public Decimal amount;
        public String milesstoneName;
        public String installment;
        public Boolean isReversed;
        public String debitType;
    }
    
    global class HttpResponseWrapper{
        public String status;
        public Integer statusCode;
        public ResponseBodyWrapper data;
        public Boolean success;
        public String Message;
    }

}