force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted to Audit</fullName>
            </value>
            <value>
                <fullName>Document Verification Not Started</fullName>
            </value>
            <value>
                <fullName>Document Verification Accepted</fullName>
            </value>
            <value>
                <fullName>Document Verification Rejected</fullName>
            </value>
            <value>
                <fullName>Audit Accepted</fullName>
            </value>
            <value>
                <fullName>Audit Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Milestone_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Due_Date__c</fullName>
    <label>Milestone Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Payment_Milestones__c.field-meta.xml
<CustomField>
    <fullName>Payment_Milestones__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Milestones</label>
    <referenceTo>Payment_Milestones__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Stage_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Stage_of_Booking__c</fullName>
    <label>Stage of Booking</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>Booking In Process</fullName>
            </value>
            <value>
                <fullName>Cancellation In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <label>Tower</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Under_cancellation__c.field-meta.xml
<CustomField>
    <fullName>Under_cancellation__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox will be used to bypass demand generation for payment milestones with selected related bookings</description>
    <label>Under cancellation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Milestones__c/Payment_Milestones__c.object-meta.xml
<CustomObject>
    <label>Payment Milestones</label>
    <nameField>
        <displayFormat>PM-{0000000}</displayFormat>
        <label>Payment Milestones Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Milestones__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Milestones__c/fields/is_demand_raised__c.field-meta.xml
<CustomField>
    <fullName>is_demand_raised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is demand raised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Milestones__c/fields/Milestone_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Due_Date__c</fullName>
    <label>Milestone Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Milestones__c/fields/Quotation__c.field-meta.xml
<CustomField>
    <fullName>Quotation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quotation</label>
    <referenceTo>Quotation__c</referenceTo>
    <relationshipLabel>Payment Milestones</relationshipLabel>
    <relationshipName>Payment_Milestones</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Milestones__c/fields/Raise_Demand_Tracker_Created__c.field-meta.xml
<CustomField>
    <fullName>Raise_Demand_Tracker_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Raise Demand Tracker Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Milestones__c/fields/Stage_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Stage_of_Booking__c</fullName>
    <formula>TEXT(Quotation__r.Booking__r.Stage_of_Booking__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stage of Booking</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Milestones__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <formula>Quotation__r.Unit__r.Tower__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tower</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SH-{000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Sold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Raise_Demand_Tracker__c/Raise_Demand_Tracker__c.object-meta.xml
<CustomObject>
    <label>Raise Demand Tracker</label>
    <nameField>
        <displayFormat>RDT-{000000000}</displayFormat>
        <label>Raise Demand Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Raise Demand Tracker</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Raise_Demand_Tracker__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Raise Demand Tracker</relationshipLabel>
    <relationshipName>Raise_Demand_Tracker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Raise_Demand_Tracker__c/fields/Is_Demand_Raised__c.field-meta.xml
<CustomField>
    <fullName>Is_Demand_Raised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Demand Raised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Raise_Demand_Tracker__c/fields/Milestone_Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Due_Date__c</fullName>
    <formula>Payment_Milestones__r.Milestone_Due_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Milestone Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Raise_Demand_Tracker__c/fields/Payment_Milestones__c.field-meta.xml
<CustomField>
    <fullName>Payment_Milestones__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Milestones</label>
    <referenceTo>Payment_Milestones__c</referenceTo>
    <relationshipLabel>Raise Demand Tracker</relationshipLabel>
    <relationshipName>Raise_Demand_Tracker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Raise_Demand_Tracker__c/fields/Raise_Demand_Date__c.field-meta.xml
<CustomField>
    <fullName>Raise_Demand_Date__c</fullName>
    <label>Raise Demand Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Raise_Demand_Tracker__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <formula>Booking__r.Tower_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tower</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Stage_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Stage_of_Booking__c</fullName>
    <formula>TEXT(Booking__r.Stage_of_Booking__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stage of Booking</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RaiseDemandTrackerSchedular.cls
global class RaiseDemandTrackerSchedular implements Schedulable {
    public void execute(SchedulableContext sc) {
        list<Raise_Demand_Tracker__c> trackerList = new list<Raise_Demand_Tracker__c>();
        String query = 'Select Id, Quotation__r.Unit__c, Quotation__r.Booking__c ' +
            ' from Payment_Milestones__c ' +
            ' where Quotation__c != null ' +
            ' and Quotation__r.Unit__c != null ' +
            ' and Quotation__r.Booking__c != null ' +
            ' and Quotation__r.Booking__r.Current_Status__c = \'Audit Accepted\' ' +
            ' and Quotation__r.Booking__r.Status__c = \'Processed\' '+
            ' and Quotation__r.Booking__r.Stage_of_Booking__c != \'EOI\' '+
            ' and is_demand_raised__c = false '+  
            ' and Quotation__r.Booking__r.Under_cancellation__c = false '+  
            ' and Raise_Demand_Tracker_Created__c = false '+
            ' and Milestone_Due_Date__c != null and Milestone_Due_Date__c <= NEXT_N_DAYS:25';
        list<Payment_Milestones__c> pmList = Database.query(query);
        Map<String, String> Qoutation_PM_Map = new Map<String, String>();
        Map<String, String> ValidQuotation_Map = new Map<String, String>();
        for (Payment_Milestones__c pm : pmList) {
            Qoutation_PM_Map.put(pm.Id,pm.Quotation__c);
        }
        
        System.debug(' Qoutation_PM_Map -> '+Qoutation_PM_Map);
        System.debug(' Qoutation_PM_Map -> '+Qoutation_PM_Map.size());
        for (Booking__c booking : [ SELECT Id,Name,Quotation__c,Unit__r.Name,Unit__r.Tower__r.Name FROM Booking__c WHERE Quotation__c IN : Qoutation_PM_Map.values() AND Unit__r.Tower__r.ByPass_Demand_Generation__c = False ]) {
            ValidQuotation_Map.put(booking.Id,booking.Quotation__c);
        }
        for(Payment_Milestones__c pm : pmList){
            Raise_Demand_Tracker__c tracker = new Raise_Demand_Tracker__c();
            tracker.Booking__c = pm.Quotation__r.Booking__c;
            tracker.Payment_Milestones__c = pm.Id;
            tracker.Raise_Demand_Date__c = System.today();
            if(ValidQuotation_Map.values().contains(pm.Quotation__c)){
                trackerList.add(tracker);
                pm.Raise_Demand_Tracker_Created__c = true;
            }
        }
        System.debug(' ValidQuotation_Map -> '+ValidQuotation_Map);
        System.debug(' ValidQuotation_Map -> '+ValidQuotation_Map.size());
        if(trackerList.size()>0)
            Database.insert(trackerList,false);
        if(pmList.size()>0)
            Database.update(pmList,false);
    }
}