force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Payments</fullName>
            </value>
            <value>
                <fullName>Advance Payments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Email__c</fullName>
    <label>Primary Applicant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name__c</fullName>
    <label>Primary Applicant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_On_Account_Money__c.field-meta.xml
<CustomField>
    <fullName>Total_On_Account_Money__c</fullName>
    <label>Total On Account Money With Registration</label>
    <summarizedField>Receipt__c.Amount_Rs__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt__c.Receipt_Status__c</field>
        <operation>equals</operation>
        <value>Cleared</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt__c.Consider_for_Paid_Percentage__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt__c.Is_Reversed_Receipt__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Amount_To_Be_Paid_After_Discount__c.field-meta.xml
<CustomField>
    <fullName>Amount_To_Be_Paid_After_Discount__c</fullName>
    <label>Amount To Be Paid After Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Amount_To_Be_Paid_In_Advance__c.field-meta.xml
<CustomField>
    <fullName>Amount_To_Be_Paid_In_Advance__c</fullName>
    <label>Amount To Be Paid In Advance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Booking_Balance__c.field-meta.xml
<CustomField>
    <fullName>Booking_Balance__c</fullName>
    <label>Booking Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Booking_Project__c.field-meta.xml
<CustomField>
    <fullName>Booking_Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Booking_Sale_Value__c.field-meta.xml
<CustomField>
    <fullName>Booking_Sale_Value__c</fullName>
    <label>Booking Sale Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Booking_Unit__c.field-meta.xml
<CustomField>
    <fullName>Booking_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PTP</fullName>
            </value>
            <value>
                <fullName>No Contact / Unable to Reach</fullName>
            </value>
            <value>
                <fullName>Raise for Cancellation</fullName>
            </value>
            <value>
                <fullName>Adjustment Pending / Rebate Pending</fullName>
            </value>
            <value>
                <fullName>Paid But Not Realized</fullName>
            </value>
            <value>
                <fullName>Regular Follow Up</fullName>
            </value>
            <value>
                <fullName>Mortgage</fullName>
            </value>
            <value>
                <fullName>Unable to Pay</fullName>
            </value>
            <value>
                <fullName>SPA / DLD Not Done</fullName>
            </value>
            <value>
                <fullName>Swap / Upgrade</fullName>
            </value>
            <value>
                <fullName>Not Pitched</fullName>
            </value>
            <value>
                <fullName>Customer Interested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Expected_Date_Of_The_Payment__c.field-meta.xml
<CustomField>
    <fullName>Expected_Date_Of_The_Payment__c</fullName>
    <label>Expected Date Of The Payment</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CustomTaskController.cls
public class CustomTaskController {
    //@InvocableVariable(label='Id' required=true)
    public static Id Idtask;
    public Task__c taskData {get;set;}
    /*public CustomTaskController(){
        
        system.debug('constructor:'+ApexPages.currentPage().getParameters().get('id'));
        Idtask = ApexPages.currentPage().getParameters().get('id');
        taskData = new Task__c();
        
        
    }*/
    @InvocableMethod(label='Send Email from Task')
    public static void sendEmail(List<Id> taskId) {
        
    Idtask =  taskId[0];
        system.debug('CustomTaskController'+taskId);
        
        Task__c taskData = [SELECT Amount_To_Be_Paid_After_Discount__c, Amount_To_Be_Paid_In_Advance__c,Bank_Name__c,Booking__c,
                    Booking_Balance__c,Booking_Project__c,Booking_Sale_Value__c,Booking_Unit__c,
                    Discount_Amount__c, Expected_Date_Of_The_Payment__c,Category__c,
                            Booking_Project__r.Name,Booking_Unit__r.Name,Booking__r.Primary_Applicant_Email__c,
                            Booking__r.Project__r.Name,Booking__r.Unit__r.name,Booking__r.Primary_Applicant_Name__c,
                            Booking__r.Agreement_Value__c,Booking__r.Total_On_Account_Money__c
                    FROM Task__c 
                    WHERE id =: taskId[0] 
                    LIMIT 1];
        
        system.debug('taskData'+taskData);
        
        EmailTemplate e = [select id, HtmlValue, subject from EmailTemplate where DeveloperName ='Send_Email_From_Task'];
        string body = e.HtmlValue;
        body = body.replace('#customer#', taskData.Booking__r.Primary_Applicant_Name__c);
        body = body.replace('#Unit#', taskData.Booking__r.Unit__r.name);
        body = body.replace('#SaleValue#', String.valueOf(taskData.Booking__r.Agreement_Value__c.format()));
        body = body.replace('#AmountToBePaidInAdvance#',String.valueOf(taskData.Amount_To_Be_Paid_In_Advance__c.format()));
        body = body.replace('#DiscountAmount#', String.valueOf(taskData.Discount_Amount__c.format()));
        body = body.replace('#AmountAfterDiscount#', String.valueOf(taskData.Amount_To_Be_Paid_After_Discount__c.format()));
        date myDate = date.newInstance(taskData.Expected_Date_Of_The_Payment__c.year(),taskData.Expected_Date_Of_The_Payment__c.month(),taskData.Expected_Date_Of_The_Payment__c.day());
		String dayString = myDate.format();
        body = body.replace('#ExpectedDate#', dayString);
        body = body.replace('#PaidTillDate#', String.valueOf(taskData.Booking__r.Total_On_Account_Money__c.format()));
             
        string subject = e.subject;
        subject = subject.replace('#Unit#', taskData.Booking__r.Unit__r.name);
        subject = subject.replace('#project#', taskData.Booking__r.Project__r.Name);
        
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 
        mail.setSubject(subject); 
        mail.setHtmlBody(body);
        list<string> toaddress = new List<string>();
         //SOB-336 start
         String emailAddressFromBooking = BookingUtilityClass.getEmailOfApplicants(taskData.Booking__c);
         if(!string.isblank(emailAddressFromBooking)){
             for(String s : emailAddressFromBooking.split(',')){
                 if(!s.containsIgnoreCase('null')){
                    toaddress.add(s);
                 }
             }
         }
        //SOB-336 end
        toaddress.add(taskData.Booking__r.Primary_Applicant_Email__c);
        list<string> ccAddress = new list<string>();
        ccAddress.add(System.label.SobhaHelpdesk);
        mail.setToAddresses(toaddress);
        mail.setCcAddresses(ccAddress);
        mail.setSaveAsActivity(false); 
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        
    }

}