force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Cancellation_Date__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Date__c</fullName>
    <description>When booking status is unprocessed for more than 7 days, Signed status is null and the Booking date is after june 1st then system cancel the booking automatically</description>
    <inlineHelpText>This field holds the value of cancellation date which is cancelled through system</inlineHelpText>
    <label>Cancellation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Cancellation_In_Progress__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_In_Progress__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cancellation In Progress</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/IS_SO__c.field-meta.xml
<CustomField>
    <fullName>IS_SO__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IS SO</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Reason_For_Cancellation_D__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Cancellation_D__c</fullName>
    <label>Reason For Cancellation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>15 days - 0%</fullName>
            </value>
            <value>
                <fullName>30 days - unit not qualified</fullName>
            </value>
            <value>
                <fullName>Auto cancellation (7 days policy)</fullName>
            </value>
            <value>
                <fullName>Cancel &amp; Rebook</fullName>
            </value>
            <value>
                <fullName>Cancel &amp; Swap</fullName>
            </value>
            <value>
                <fullName>Cancellation &amp; Transfer</fullName>
            </value>
            <value>
                <fullName>Cancelled by CRM</fullName>
            </value>
            <value>
                <fullName>Client request for cancellation</fullName>
            </value>
            <value>
                <fullName>Low Funds</fullName>
            </value>
            <value>
                <fullName>Management Instruction</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>PR rejected due to non-submission of NSA</fullName>
            </value>
            <value>
                <fullName>Auto cancellation (14 days policy)</fullName>
            </value>
            <value>
                <fullName>15 days - 2%</fullName>
            </value>
            <value>
                <fullName>14Days - Not Qualified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>Booking In Process</fullName>
            </value>
            <value>
                <fullName>Cancellation In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AEDToUSDConversionRate</label>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/N_CancelBookingSOController.cls
public class N_CancelBookingSOController{
    
    public String bookId;
    public Booking__c book;
    public boolean isError {get;set;}
    
    public N_CancelBookingSOController(){       
        if(ApexPages.currentPage().getParameters().get('Id') != null && ApexPages.currentPage().getParameters().get('Id') != ''){
            bookId = ApexPages.currentPage().getParameters().get('Id');
        }
        if(String.isNotBlank(bookId)){           
            book = [SELECT Status__c, Cancellation_In_Progress__c FROM Booking__c WHERE Id = :bookId]; 
            if(book.Status__c != 'Cancelled' && book.Status__c != 'Cancellation In Progress'){
                isError = false;    
            } else {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Unable to process your request. Selected booking is already cancelled or cancellation is in process.'));
                isError = true;    
            }                  
        } else {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Unable to process your request. Invalid booking id'));
            isError = true;                
        }
       system.debug('error::: ' + isError); 
    } 
    
    public PageReference updateBookingStatus(){
        /* Trigger fires when boking status changes from Cancellation to Progress to Cancelled */
        List<Booking__c> cancelledBookingList = new List<Booking__c>();
        book = [SELECT Name,Status__c,Unit__c,Opportunity__c,Cancellation_In_Progress__c,Reason_For_Cancellation_D__c FROM Booking__c WHERE Id = :bookId]; 
        if (book.Reason_For_Cancellation_D__c == null || book.Reason_For_Cancellation_D__c == '')
        {
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,' Please update Reason for Cancellation on Booking before cancelling the Booking.'));
            //isError = true;
            return null;
        }   
        book.Cancellation_In_Progress__c = true;
        book.Status__c = 'Cancellation In Progress';
        book.IS_SO__c = true;
        update book;
        
        book.Status__c = 'Cancelled';
        book.Cancellation_Date__c = System.now();
        update book;
        cancelledBookingList.add(book);
        trgBookinghandler.bookingCancellation(cancelledBookingList);
        trgBookinghandler.updatePaymentRequestStatus(new Set<String>{book.Name});
        BookingTriggerHandlerCtr.sendEmailOnBookingCancellation(cancelledBookingList);
        PageReference pr = new PageReference('/'+book.Id);
        return pr;
    }
    
    public PageReference cancel(){
        PageReference pr = new PageReference('/'+bookId);
        return pr;
    }
}