force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Receipts__c.field-meta.xml
<CustomField>
    <fullName>Receipts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Receipt__c.Project_Unit__c</field>
            <operation>equals</operation>
            <valueField>$Source.Unit__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>Booking In Process</fullName>
            </value>
            <value>
                <fullName>Cancellation In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTC Deposits</fullName>
                <label>OTC Deposit(Cash counter)</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>CDM Cash</fullName>
                <label>CDM Cash (Cash Deposit in Machine)</label>
            </value>
            <value>
                <fullName>CDM Cheque</fullName>
                <label>CDM Cheque (Cheque Deposit in Machine)</label>
            </value>
            <value>
                <fullName>International Wire Transfer</fullName>
                <label>IWT(International)</label>
            </value>
            <value>
                <fullName>Domestic Wire Transfer</fullName>
                <label>DWT(Domestic)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Receipt_Created__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Receipt Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Accounts Approval</fullName>
            </value>
            <value>
                <fullName>Approved by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by Accounts</fullName>
            </value>
            <value>
                <fullName>Pending for Sales Ops Approval</fullName>
            </value>
            <value>
                <fullName>Rejected by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Resubmitted to SM/SD</fullName>
            </value>
            <value>
                <fullName>Approved by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Submitted to Accounts for Amount Confirmation</fullName>
            </value>
            <value>
                <fullName>Amount Confirmed by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by System</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Payment Link sent to Customer</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>PR was Approved- Booking is cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 5) OR (1 AND 2 AND 3 AND 4) OR (6 AND 2 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Not_Available_for_Sales__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Unit__c.Allocated_SM__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>notEqual</operation>
            <value>Unreleased</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Allocated_SM__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Hold</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Number__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Number__c</fullName>
    <formula>IF( Advance_Receipt__c  = true, IF( Tax_Receipt__c = true, (Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Project_Unit__r.Tower__r.Name ,2) &amp; &apos;-&apos; &amp; Project_Unit__r.Name &amp; &apos;/&apos; &amp; TEXT(Receipt_Date__c) &amp; &apos;/&apos; &amp; &apos;AdvTax-&apos; &amp; Name,(Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Project_Unit__r.Tower__r.Name ,2) &amp; &apos;-&apos; &amp; Project_Unit__r.Name &amp; &apos;/&apos; &amp; TEXT(Receipt_Date__c) &amp; &apos;/&apos; &amp; &apos;Adv-&apos; &amp; Name), 
(Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Project_Unit__r.Tower__r.Name ,2) &amp; &apos;-&apos; &amp; Project_Unit__r.Name &amp; &apos;/&apos; &amp; TEXT(Receipt_Date__c) &amp; &apos;/&apos; &amp; Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Receipt Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Status__c</fullName>
    <label>Receipt Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cheque Hold</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Dishonored</fullName>
            </value>
            <value>
                <fullName>PDC</fullName>
            </value>
            <value>
                <fullName>Physical Verification Rejected</fullName>
            </value>
            <value>
                <fullName>Processed-Sent for Banking</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
                <default>true</default>
                <label>UnProcessed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Mobile_PaymentReceipts.cls
@RestResource(urlMapping = '/getPaymentReceipts')
global class Mobile_PaymentReceipts{
    @HttpPost
    global static void getPaymentReceipts(String bookingId){
        List<ResponseBodyWrapper> paymentReceiptsWrapper = new List<ResponseBodyWrapper>();
        RestResponse res = RestContext.response; 
        String responseString = '';
        String errorMessage = '';
        try{
           /* if(bookingId != null && String.isNotBlank(bookingId)){
                
                 List<Payment_Request__c> PaymentReqList = [select id,name,Mode__c,Amount__c, createddate,Booking__r.Unit__r.Name,booking__r.Project__r.Name  from Payment_Request__c  where Booking__c = :bookingId  and Receipt_Created__c = false ]; 
                  if(PaymentReqList.size() > 0){
                    for(Payment_Request__c paymentRec : PaymentReqList){
                        ResponseBodyWrapper payReceipt = new ResponseBodyWrapper();   
                    	payReceipt.id = paymentRec.Id;
                        payReceipt.name = paymentRec.name;
                        payReceipt.mode = paymentRec.Mode__c;
                        payReceipt.receiptNumber = paymentRec.name;
                        payReceipt.totalAmount = paymentRec.Amount__c;
                        payReceipt.createddate = date.newinstance(paymentRec.createddate.year(), paymentRec.createddate.month(), paymentRec.createddate.day());
                        payReceipt.unitName = paymentRec.Booking__r.Unit__r.Name;
                        payReceipt.projectName = paymentRec.Booking__r.Project__r.Name;
                        payReceipt.prstatus = 'In Progress';
                        paymentReceiptsWrapper.add(payReceipt);
                    }
                  }
                List<Receipt__c> receiptRecList = [select id,name,Mode__c,Receipt_Number__c,Total_Amount__c,createddate,Booking__r.Unit__r.Name,booking__r.Project__r.Name  from Receipt__c where Booking__c = :bookingId and Receipt_Status__c  ='Cleared' ];//include the clear status in the where condition, get confirmation from Abdul
                if(receiptRecList.size() > 0){
                    for(Receipt__c receiptRec : receiptRecList){
                        ResponseBodyWrapper payReceipt = new ResponseBodyWrapper();   
                    	payReceipt.id = receiptRec.Id;
                        payReceipt.name = receiptRec.name;
                        payReceipt.mode = receiptRec.Mode__c;
                        payReceipt.receiptNumber = receiptRec.Receipt_Number__c;
                        payReceipt.totalAmount = receiptRec.Total_Amount__c;
                        payReceipt.createddate = date.newinstance(receiptRec.createddate.year(), receiptRec.createddate.month(), receiptRec.createddate.day());
                        payReceipt.unitName = receiptRec.Booking__r.Unit__r.Name;
                        payReceipt.projectName = receiptRec.Booking__r.Project__r.Name;
                        payReceipt.prstatus = 'Completed';
                        paymentReceiptsWrapper.add(payReceipt);
                    }                
                    // return prepareResponse(paymentReceiptsWrapper,'Operation Successfull','Success',200,true);
                    responseString = (prepareResponse(paymentReceiptsWrapper,'Operation Successfull','Success',200,true)).toString().replace('"','');
                    res.responseBody = BLOB.valueOf(JSON.serialize(prepareResponse(paymentReceiptsWrapper,'Operation Successfull','Success',200,true)));
                    res.statusCode = 200;  
                }
                else{
                    res.responseBody = BLOB.valueOf(JSON.serialize(prepareResponse(null,'No Data Found','Error',400,false)));
                    res.statusCode = 400;
                }
            }
            else{
                res.responseBody = BLOB.valueOf(JSON.serialize(prepareResponse(null,'No Data Found','Error',400,false)));
                res.statusCode = 400;
            }
        	// return prepareResponse(null,'No data found','No Data Found',400,false);
        	// 
        */
            
        if(bookingId != null && String.isNotBlank(bookingId)){
            Datetime halfHourBack = Datetime.now().addMinutes(-30);
	
              List<Payment_Request__c> PaymentReqList = [select id,name,Mode__c,Amount__c, createddate,Booking__r.Unit__r.Name,booking__r.Project__r.Name, Status__c  from Payment_Request__c  where Booking__c = :bookingId  and Receipt_Created__c = false ]; 
                  if(PaymentReqList.size() > 0){
                    for(Payment_Request__c paymentRec : PaymentReqList){
                        if(paymentRec.mode__c == 'Website' && paymentRec.createddate < halfHourBack) {
                            CONTINUE;
                        }
                        ResponseBodyWrapper payReceipt = new ResponseBodyWrapper();   
                    	payReceipt.id = paymentRec.Id;
                        payReceipt.name = paymentRec.name;
                        payReceipt.mode = paymentRec.Mode__c;
                        payReceipt.receiptNumber = paymentRec.name;
                        payReceipt.totalAmount = paymentRec.Amount__c;
                        payReceipt.createddate = date.newinstance(paymentRec.createddate.year(), paymentRec.createddate.month(), paymentRec.createddate.day());
                        payReceipt.unitName = paymentRec.Booking__r.Unit__r.Name;
                        payReceipt.projectName = paymentRec.Booking__r.Project__r.Name;
                        payReceipt.prstatus = paymentRec.Status__c == 'Rejected by System' || paymentRec.Status__c == 'Rejected by Accounts' || paymentRec.Status__c =='Rejected by Sales Ops' ? 'Rejected' : 'In Progress'; // include the Rejected status here - Aravindan
                        paymentReceiptsWrapper.add(payReceipt);
                    }
                  }
            
             List<Receipt__c> receiptRecList = [select id,name,Mode__c,Receipt_Number__c,Total_Amount__c,createddate,Booking__r.Unit__r.Name,booking__r.Project__r.Name  from Receipt__c where Booking__c = :bookingId and Receipt_Status__c  ='Cleared' ];//include the clear status in the where condition, get confirmation from Abdul
                if(receiptRecList.size() > 0){
                    for(Receipt__c receiptRec : receiptRecList){
                        ResponseBodyWrapper payReceipt = new ResponseBodyWrapper();   
                    	payReceipt.id = receiptRec.Id;
                        payReceipt.name = receiptRec.name;
                        payReceipt.mode = receiptRec.Mode__c;
                        payReceipt.receiptNumber = receiptRec.Receipt_Number__c;
                        payReceipt.totalAmount = receiptRec.Total_Amount__c;
                        payReceipt.createddate = date.newinstance(receiptRec.createddate.year(), receiptRec.createddate.month(), receiptRec.createddate.day());
                        payReceipt.unitName = receiptRec.Booking__r.Unit__r.Name;
                        payReceipt.projectName = receiptRec.Booking__r.Project__r.Name;
                        payReceipt.prstatus = 'Completed';
                        paymentReceiptsWrapper.add(payReceipt);
                    }  
                }
            
            if(receiptRecList.size() > 0 || PaymentReqList.size() > 0){
                responseString = (prepareResponse(paymentReceiptsWrapper,'Operation Successfull','Success',200,true)).toString().replace('"','');
                    res.responseBody = BLOB.valueOf(JSON.serialize(prepareResponse(paymentReceiptsWrapper,'Operation Successfull','Success',200,true)));
                    res.statusCode = 200; 
            }else{
                    res.responseBody = BLOB.valueOf(JSON.serialize(prepareResponse(null,'No Data Found','Error',400,false)));
                    res.statusCode = 400;
                }            		
            
        }
        } catch (Exception ex) {
            errorMessage = ex.getMessage();
            res.responseBody = BLOB.valueOf(JSON.serialize(prepareResponse(null,'Error','Error',400,false)));
            res.statusCode = 400;
        }  
        Mobile_ApiUtility.createMobileAPILogs('getPaymentReceipts','Mobile_getPaymentReceipts',bookingId,responseString,errorMessage,res.statusCode);
    }
    
    public static HttpResponseWrapper prepareResponse(list<responseBodyWrapper> rBody,string rMessage,string rStatus,integer rStatusCode,boolean rSuccess){
        HttpResponseWrapper resWrap = new HttpResponseWrapper();
        resWrap.data = rBody;
        resWrap.Message = rMessage;
        resWrap.status = rStatus;
        resWrap.statusCode = rStatusCode;
        resWrap.success = rSuccess;
        return resWrap;
    }
    
    public class ResponseBodyWrapper{
        public String id;
        public String name;
        public String mode;
        public String receiptNumber;
        public Decimal totalamount;
        public Date createdDate;
        public String unitName;
        public String projectName;
        public string prstatus;
    }
    
    global class HttpResponseWrapper{
        public String status;
        public Integer statusCode;
        public List<responseBodyWrapper> data = new list<responseBodyWrapper>();
        public Boolean success;
        public String Message;
    }
}