force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Sub Project</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/DLD_Fees__c.field-meta.xml
<CustomField>
    <fullName>DLD_Fees__c</fullName>
    <formula>(Agreement_Value__c * (4/100))+ 1150</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>DLD Fees</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Address__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Address__c</fullName>
    <label>Primary Applicant Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Email__c</fullName>
    <label>Primary Applicant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name__c</fullName>
    <label>Primary Applicant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/PrimaryMobileNumber__c.field-meta.xml
<CustomField>
    <fullName>PrimaryMobileNumber__c</fullName>
    <label>Primary Mobile Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Registration_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Registration_Amount_Paid__c</fullName>
    <label>Registration Amount Paid (RollUp)</label>
    <summarizedField>Receipt__c.Registration_Collection_Control_Report__c</summarizedField>
    <summaryFilterItems>
        <field>Receipt__c.Receipt_Status__c</field>
        <operation>equals</operation>
        <value>Cleared</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt__c.Is_Reversed_Receipt__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>Receipt__c.Other_Charges_Type__c</field>
        <operation>equals</operation>
        <value></value>
    </summaryFilterItems>
    <summaryForeignKey>Receipt__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <label>Tower</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <formula>Unit__r.Sub_project_tower__c</formula>
    <label>Tower Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/welcomeLetterController.cls
public class welcomeLetterController {
   
    public String bookId;
    public String applicantName {get; set;}
    public String applicantAddress {get; set;}
    public String applicantMobileNumber {get; set;}
    public String applicantEmail{get; set;}
    
    public Booking__c Customer {get; set;}
    public Date todayDate {get;set;}
    public Integer purchaseValue {get;set;}
    public Integer dldfeeswithoutfee {get;set;}
    public Integer total  {get;set;}
    
    public welcomeLetterController(){
        	todayDate = System.Today();
             if(ApexPages.currentPage().getParameters().get('id') != null && ApexPages.currentPage().getParameters().get('id') != '')
             bookId = ApexPages.currentPage().getParameters().get('id');
             if(bookId != null && bookId != ''){   
             Customer = [SELECT id, Name, Tower_Name__c,Unit__r.Name,Unit__r.Project__r.Name, Unit__r.Tower__r.Cluster__r.Name, Primary_Applicant_Name__c,Primary_Applicant_Email__c, PrimaryMobileNumber__c,                                                   
                        Agreement_Value__c,Registration_Amount_Paid__c, Primary_Applicant_Address__c,Project__r.Name, DLD_Fees__c  FROM Booking__c WHERE id = :bookId];  
              	 Decimal roundedDLD = Math.ceil(Customer.DLD_Fees__c);
                 dldfeeswithoutfee=Integer.ValueOf(roundedDLD)-1150;
                 purchaseValue = Math.round(Customer.Agreement_Value__c);
                 purchaseValue = Math.ceil(Customer.Agreement_Value__c).intValue();
                 total= Integer.ValueOf(Math.ceil(Customer.DLD_Fees__c));
             }
         // Retrieve the custom parameters
        applicantName = ApexPages.currentPage().getParameters().get('applicantName');
        applicantAddress = ApexPages.currentPage().getParameters().get('applicantAddress');
        applicantMobileNumber = ApexPages.currentPage().getParameters().get('applicantMobileNumber');
        applicantEmail = ApexPages.currentPage().getParameters().get('applicantEmail');
    }
}