force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Milestone_Due_Till_Date__c.field-meta.xml
<CustomField>
    <fullName>Milestone_Due_Till_Date__c</fullName>
    <label>Milestone Due Till Date</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Paid_Amount_For_Process__c.field-meta.xml
<CustomField>
    <fullName>Paid_Amount_For_Process__c</fullName>
    <formula>Total_On_Account_Money__c - Registration_Amount_Paid__c - Credit_Card_Charges_Colleceted__c -VAT_Reduction_From_PPP__c - Late_Payment_Charges_Roll_Up__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Paid Amount For Process</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/X15days_Demand_Raised__c.field-meta.xml
<CustomField>
    <fullName>X15days_Demand_Raised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>15days Demand Raised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/X30days_Demand_Raised__c.field-meta.xml
<CustomField>
    <fullName>X30days_Demand_Raised__c</fullName>
    <defaultValue>false</defaultValue>
    <label>30days Demand Raised</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UncheckDemandRaisedOnBooking.cls
global class UncheckDemandRaisedOnBooking implements Queueable, Database.AllowsCallouts {
    
    public void execute(QueueableContext context) {
        list<Booking__c> bookingToUpdate = new list<Booking__c>();
        for(Booking__c b : [select Id,Paid_Amount_For_Process__c,Milestone_Due_Till_Date__c from Booking__c where (X15days_Demand_Raised__c = true or X30days_Demand_Raised__c = true)]){
            if((b.Paid_Amount_For_Process__c != null && b.Milestone_Due_Till_Date__c != null) || Test.isRunningTest()){
                if((b.Paid_Amount_For_Process__c >= b.Milestone_Due_Till_Date__c) || Test.isRunningTest() ){
                    b.X15days_Demand_Raised__c = false;
                    b.X30days_Demand_Raised__c = false;
                    bookingToUpdate.add(b);
                }
            }
        }
        if(bookingToUpdate.size()>0){
            Database.update(bookingToUpdate,false);
        }
    }
    
}