force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>Booking In Process</fullName>
            </value>
            <value>
                <fullName>Cancellation In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTC Deposits</fullName>
                <label>OTC Deposit(Cash counter)</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>CDM Cash</fullName>
                <label>CDM Cash (Cash Deposit in Machine)</label>
            </value>
            <value>
                <fullName>CDM Cheque</fullName>
                <label>CDM Cheque (Cheque Deposit in Machine)</label>
            </value>
            <value>
                <fullName>International Wire Transfer</fullName>
                <label>IWT(International)</label>
            </value>
            <value>
                <fullName>Domestic Wire Transfer</fullName>
                <label>DWT(Domestic)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request_Wrapper__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request_Wrapper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request Wrapper</label>
    <referenceTo>Payment_Request_Wrapper__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Accounts Approval</fullName>
            </value>
            <value>
                <fullName>Approved by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by Accounts</fullName>
            </value>
            <value>
                <fullName>Pending for Sales Ops Approval</fullName>
            </value>
            <value>
                <fullName>Rejected by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Resubmitted to SM/SD</fullName>
            </value>
            <value>
                <fullName>Approved by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Submitted to Accounts for Amount Confirmation</fullName>
            </value>
            <value>
                <fullName>Amount Confirmed by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by System</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Payment Link sent to Customer</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>PR was Approved- Booking is cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 5) OR (1 AND 2 AND 3 AND 4) OR (6 AND 2 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Not_Available_for_Sales__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Unit__c.Allocated_SM__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>notEqual</operation>
            <value>Unreleased</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Allocated_SM__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Hold</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request_Wrapper__c/Payment_Request_Wrapper__c.object-meta.xml
<CustomObject>
    <label>Payment Request Wrapper</label>
    <nameField>
        <displayFormat>PRW-{0000000000}</displayFormat>
        <label>Payment  Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Request Wrapper</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request_Wrapper__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OTC Deposits</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>CDM Cash</fullName>
            </value>
            <value>
                <fullName>International Wire Transfer</fullName>
            </value>
            <value>
                <fullName>CDM Cheque</fullName>
            </value>
            <value>
                <fullName>Domestic Wire Transfer</fullName>
            </value>
            <value>
                <fullName>CDM Cash (Cash Deposit in Machine)</fullName>
                <isActive>false</isActive>
                <label>CDM Cash (Cash Deposit in Machine)</label>
            </value>
            <value>
                <fullName>CDM Cheque (Cheque Deposit in Machine)</fullName>
                <isActive>false</isActive>
                <label>CDM Cheque (Cheque Deposit in Machine)</label>
            </value>
            <value>
                <fullName>DWT(Domestic)</fullName>
                <isActive>false</isActive>
                <label>DWT(Domestic)</label>
            </value>
            <value>
                <fullName>IWT(International)</fullName>
                <isActive>false</isActive>
                <label>IWT(International)</label>
            </value>
            <value>
                <fullName>OTC Deposit(Cash counter)</fullName>
                <isActive>false</isActive>
                <label>OTC Deposit(Cash counter)</label>
            </value>
            <value>
                <fullName>OTC Deposits(Cash counter)</fullName>
                <isActive>false</isActive>
                <label>OTC Deposits(Cash counter)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PaymentRequestForm.cls
public class PaymentRequestForm {
    @InvocableMethod (label='Reject Payment Requests')
    public static void rejectPaymentRequests (List<Id> prList){
        list<Id> unitIds = new list<Id>();
        list<string> websiteParentIds = new list<string>();
        list<string> parentPRIds = new list<string>();
        
        list<Payment_Request__c> prRecords = [select Id, Unit__c, Payment_Request__c from Payment_Request__c where Id IN: prList];
        for(Payment_Request__c pr : prRecords){ 
            unitIds.add(pr.Unit__c); 
            parentPRIds.add(pr.Payment_Request__c);
        }
        
        list<Id> prIds = new list<Id>();
        
        list<string> rejectStatusToConsider = new list<string>();
        rejectStatusToConsider.add('Pending for Accounts Approval');
        rejectStatusToConsider.add('Pending for Sales Ops Approval');
        rejectStatusToConsider.add('Payment Link sent to Customer');
        rejectStatusToConsider.add('Partially Approved');
        
        
        list<Payment_Request__c> prToReject = [select Id, Mode__c, Payment_Request_Wrapper__c from Payment_Request__c where Unit__c IN: unitIds and Booking__c = null and Status__c IN: rejectStatusToConsider and Id NOT IN: prList and Id NOT IN: parentPRIds];
        for(Payment_Request__c p : prToReject){
            if(p.Mode__c == 'Website'){ websiteParentIds.add(p.Payment_Request_Wrapper__c); }
            else { prIds.add(p.Id); }
        }
        
        prToReject = [select Id, Status__c from Payment_Request__c where Id IN: prIds and Id NOT IN: prList];
        
        PaymentRequestFormController.rejectWebsiteRequests(websiteParentIds);
        
        if(prToReject.size()>0){
            List<ProcessInstance> pendingAprrovalProcessList = [Select Id, TargetObjectId, Status From ProcessInstance Where Status='Pending' and TargetObjectId IN : prToReject];
            List<Id> processInstanceIDs = new List<Id>();
            for(ProcessInstance processIns : pendingAprrovalProcessList){
                processInstanceIDs.add(processIns.Id);
            }
            
            List<ProcessInstanceWorkitem> workItems = [SELECT Id, ProcessInstanceId  FROM ProcessInstanceWorkitem WHERE ProcessInstanceId IN :processInstanceIDs ];
            List<Approval.ProcessWorkitemRequest> allReq = new List<Approval.ProcessWorkitemRequest>(); 
            for(ProcessInstanceWorkitem work : workItems){
                Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
                req.setComments('Rejected by System'); 
                req.setAction('Reject');
                req.setWorkitemId(work.id);
                allReq.add(req);
            }
            Approval.ProcessResult[] result =  Approval.process(allReq);
            for(Payment_Request__c p : prToReject){
                p.Status__c = 'Rejected by System';
            }
            update prToReject;
        }
    }
    
    public static void unlockRecords(){
        list<Payment_Request__c> approvedPRs = [select Id from Payment_Request__c where Status__c = 'Approved'];
        list<Id> recordsToUnlock = new list<Id>();
        for(Payment_Request__c pr : approvedPRs){
            if(Approval.isLocked(pr.Id)){
                recordsToUnlock.add(pr.Id);
            }
        }
        system.debug('recordsToUnlock size: '+recordsToUnlock.size());
        if(recordsToUnlock.size()>0){
            Approval.unlock(recordsToUnlock);
        }
    }
}