force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due Payments</fullName>
            </value>
            <value>
                <fullName>Advance Payments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Department__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AC Cooling - Common Area</fullName>
            </value>
            <value>
                <fullName>AC Cooling - Inside Units</fullName>
            </value>
            <value>
                <fullName>Alterations</fullName>
            </value>
            <value>
                <fullName>Amenity Reservations</fullName>
            </value>
            <value>
                <fullName>Appliances</fullName>
            </value>
            <value>
                <fullName>Blockage</fullName>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>Booking related</fullName>
            </value>
            <value>
                <fullName>Broken Glass</fullName>
            </value>
            <value>
                <fullName>Building Information</fullName>
            </value>
            <value>
                <fullName>Call Back Request</fullName>
            </value>
            <value>
                <fullName>Channel Relations</fullName>
            </value>
            <value>
                <fullName>Cheque Bounce</fullName>
            </value>
            <value>
                <fullName>Cheque Deposit/Realization</fullName>
            </value>
            <value>
                <fullName>Chilled Water Charges</fullName>
            </value>
            <value>
                <fullName>Chilled Water Charges/Coolings</fullName>
            </value>
            <value>
                <fullName>Civil</fullName>
            </value>
            <value>
                <fullName>Civil Works</fullName>
            </value>
            <value>
                <fullName>Collections/ Payments</fullName>
            </value>
            <value>
                <fullName>Common Area Doors</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Community Access Cards</fullName>
            </value>
            <value>
                <fullName>Community Amenities Access</fullName>
            </value>
            <value>
                <fullName>Community Developments</fullName>
            </value>
            <value>
                <fullName>Community Improvements</fullName>
            </value>
            <value>
                <fullName>Community Rules Violation</fullName>
            </value>
            <value>
                <fullName>Community Service Fees</fullName>
            </value>
            <value>
                <fullName>Community Staff Behavior</fullName>
            </value>
            <value>
                <fullName>PCC</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Collections</fullName>
            </value>
            <value>
                <fullName>Community Management</fullName>
            </value>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>DLP</fullName>
                <label>CCC</label>
            </value>
            <value>
                <fullName>DLD</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>SPAM</fullName>
            </value>
            <value>
                <fullName>TEST</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Unregistered Email Id</fullName>
            </value>
            <value>
                <fullName>Channel Relations</fullName>
            </value>
            <value>
                <fullName>HR</fullName>
            </value>
            <value>
                <fullName>Accounts</fullName>
                <isActive>false</isActive>
                <label>Accounts</label>
            </value>
            <value>
                <fullName>Audit</fullName>
                <isActive>false</isActive>
                <label>Audit</label>
            </value>
            <value>
                <fullName>Finalized SCM</fullName>
                <isActive>false</isActive>
                <label>Finalized SCM</label>
            </value>
            <value>
                <fullName>Handover</fullName>
                <isActive>false</isActive>
                <label>Handover</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Collection.recordType-meta.xml
<RecordType>
    <fullName>Collection</fullName>
    <active>true</active>
    <businessProcess>Collection Support Process</businessProcess>
    <label>Collection</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/CRM.recordType-meta.xml
<RecordType>
    <fullName>CRM</fullName>
    <active>true</active>
    <businessProcess>CRM Support Process</businessProcess>
    <label>CRM</label>
</RecordType>

force-app/main/default/objects/Mobile_App_Case_Mapping__mdt/Mobile_App_Case_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Mobile App Case Mapping</label>
    <pluralLabel>Mobile App Case Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mobile_App_Case_Mapping__mdt/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collections</fullName>
                <default>true</default>
                <label>Collections</label>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mobile_App_Case_Mapping__mdt/fields/Queue_Id__c.field-meta.xml
<CustomField>
    <fullName>Queue_Id__c</fullName>
    <label>Queue Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Mobile_createRequest.cls
@RestResource(urlMapping='/createRequest')
global class Mobile_createRequest{
    @HttpPost 
    global static void doCreateCase(){
        RestResponse res = RestContext.response;
        RestRequest request = RestContext.request;
        String responseString = '';
        String errorMessage = '';
        CaseRequestWrapper objcase = (CaseRequestWrapper)System.JSON.deserialize(request.requestBody.toString(),CaseRequestWrapper.class);
        String crmRecordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('CRM').getRecordTypeId();
        String collecRecordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Collection').getRecordTypeId();
            Set<String> collectionTypes = new Set<String>{'PCC','SOA'};
        try {
            if(objcase != null){
                
                List<Mobile_App_Case_Mapping__mdt> caseMetadata = [Select id, Department__c, Queue_Id__c from Mobile_App_Case_Mapping__mdt where MasterLabel = :objcase.requestType LIMIT 1];
                Case newCase = new Case();
                newCase.SuppliedEmail = objcase.email;
                newCase.SuppliedPhone = objcase.mobile;
                newCase.description = objcase.description;
                //newCase.Department__c = caseMetadata.Department__c;
                if(objcase.requestType != null && objcase.requestType != '') {
                    newCase.Department__c = caseMetadata.size() > 0 ? caseMetadata[0].Department__c : 'CRM';
                }
                else {
                    newCase.Department__c = 'CRM';
                }
                newCase.Booking__c = objcase.bookingId != null ? objcase.bookingId : '';
                newCase.Origin = 'Mobile App';
                newCase.Category__c = 'Other';
                newCase.recordTypeId = collectionTypes.contains(objcase.requestType) ? collecRecordTypeID : crmRecordTypeID;
                insert newCase;
                responseString = (Mobile_Case.prepareResponse(new List<Case>{newCase},'Operation Successfull','Success',200,true)).toString().replace('"','');
                res.responseBody =  Blob.valueOf(JSON.serialize(Mobile_Case.prepareResponse(new List<Case>{newCase},'Operation Successfull','Success',200,true)));
                res.statusCode = 200;
                
            }
            else{
                res.responseBody =  Blob.valueOf(JSON.serialize(Mobile_Case.prepareResponse(null,'No data found','No data found',400,false)));
                res.statusCode = 400;
            }
        } catch (Exception ex) {
            errorMessage = ex.getMessage();
            res.responseBody = BLOB.valueOf(JSON.serialize(Mobile_Case.prepareResponse(null,'Error','Error',400,false)));
            res.statusCode = 400;
        }  
        Mobile_ApiUtility.createMobileAPILogs('createRequest','Mobile_createRequest',request.requestBody.toString(),responseString,errorMessage,res.statusCode);        
    }

    public class CaseRequestWrapper{
        public String email;
        public String mobile;
        public String description;
        public String requestType;
        public String bookingId;
    }
}