force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Sub Project</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Dewa_Number__c.field-meta.xml
<CustomField>
    <fullName>Dewa_Number__c</fullName>
    <label>Dewa Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Email__c</fullName>
    <label>Primary Applicant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <label>Tower</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower_Name__c.field-meta.xml
<CustomField>
    <fullName>Tower_Name__c</fullName>
    <formula>Unit__r.Sub_project_tower__c</formula>
    <label>Tower Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <label>Sub Project</label>
    <nameField>
        <label>Sub Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Clusters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/handoverDate__mdt/handoverDate__mdt.object-meta.xml
<CustomObject>
    <label>handoverDate</label>
    <pluralLabel>handoverDates</pluralLabel>
</CustomObject>

force-app/main/default/objects/handoverDate__mdt/fields/ReminderDate__c.field-meta.xml
<CustomField>
    <fullName>ReminderDate__c</fullName>
    <label>ReminderDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Legal_Entity__c/Legal_Entity__c.object-meta.xml
<CustomObject>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Entity__c/fields/RDS_Company_Code__c.field-meta.xml
<CustomField>
    <fullName>RDS_Company_Code__c</fullName>
    <label>Company Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Other_Applicants_Name__c.field-meta.xml
<CustomField>
    <fullName>Other_Applicants_Name__c</fullName>
    <label>Other Applicants Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Permanent_Address__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Address__c</fullName>
    <label>Permanent Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email__c</fullName>
    <label>Primary Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Name__c</fullName>
    <label>Primary Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Phone__c.field-meta.xml
<CustomField>
    <fullName>Primary_Phone__c</fullName>
    <label>Primary Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AEDToUSDConversionRate</label>
</CustomObject>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/RDS_Company_Code__c.field-meta.xml
<CustomField>
    <fullName>RDS_Company_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RunHandover_BookingID__mdt/RunHandover_BookingID__mdt.object-meta.xml
<CustomObject>
    <description>To run Handover notice on specific bookings</description>
    <label>RunHandover_BookingID</label>
    <pluralLabel>RunHandover_BookingIDs</pluralLabel>
</CustomObject>

force-app/main/default/objects/RunHandover_BookingID__mdt/fields/RunPerBooking__c.field-meta.xml
<CustomField>
    <fullName>RunPerBooking__c</fullName>
    <label>RunPerBooking</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/Date_of_Completion__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Completion__c</fullName>
    <label>Date of Completion</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/RDS_Company_Code__c.field-meta.xml
<CustomField>
    <fullName>RDS_Company_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TowerName__mdt/TowerName__mdt.object-meta.xml
<CustomObject>
    <label>TowerName</label>
    <pluralLabel>TowerNames</pluralLabel>
</CustomObject>

force-app/main/default/objects/TowerName__mdt/fields/TowerName__c.field-meta.xml
<CustomField>
    <fullName>TowerName__c</fullName>
    <label>TowerName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SendHandoverReminderBatch.cls
public class SendHandoverReminderBatch implements Database.Batchable<sObject>,Database.stateful {
    public Integer successRec = 0; 
    public Integer failedRec = 0; 
    public Integer totalRec = 0;
    String pdfBody = '';
    public string towerValue;
    public Database.QueryLocator start(Database.BatchableContext BC){
        Date reminderDate  = handoverDate__mdt.getInstance('handoverDate').ReminderDate__c;
        towerValue = TowerName__mdt.getInstance('Tower').TowerName__c;
        System.debug('reminderDate:'+reminderDate);
        System.debug('towerValue:'+towerValue);
        String query = 'select id,Tower_Name__c,Cluster__c, Reminder_Date__c, Dewa_Number__c, Unit__c, Primary_Applicant_Email__c,Unit__r.Name, Owner.Name,Owner.Email,Unit__r.Tower__r.Name,Project__r.name, Unit__r.Tower__r.RDS_Company_Code__r.Name, Unit__r.Tower__r.Date_of_Completion__c,Opportunity__c, Opportunity__r.Other_Applicants_Name__c, Opportunity__r.Primary_Name__c, Opportunity__r.Permanent_Address__c, Opportunity__r.Primary_Phone__c, Opportunity__r.Primary_Email__c,Opportunity__r.AccountId  from Booking__c where  ';
        String runPerBooking = RunHandover_BookingID__mdt.getInstance('bookingName').RunPerBooking__c;
       // if(runPerBooking <> null && !test.isRunningTest()){
        //    List<String> runperbookingList = runPerBooking.split(';');
           // query += 'name in :runperbookingList ';
       // } else{
       query += ' Reminder_Date__c = :reminderDate and Tower__c = :towerValue and Reminder_Date__c != Null and Tower__c != Null';
       
            
       // }
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<Booking__c> bookingList){
        system.debug('bookingList' + bookingList);
        List<Messaging.SingleEmailMessage> mailsList = new List<Messaging.SingleEmailMessage>();
        OrgWideEmailAddress[] owea = [select Id from OrgWideEmailAddress where Address =: system.label.handoverNoticeSender];
        if(bookingList.size() > 0){
            for(Booking__c book : bookingList){
                Blob b;
                PageReference pref = new PageReference('/apex/HandoverReminderVFpage');
                pref.getParameters().put('Id', book.Opportunity__c);
                if(!Test.isRunningTest()){
                    b = pref.getContent();  
                } else {
                    b = Blob.valueOf('Test123');
                }                           
                List<Messaging.Emailfileattachment> fileAttachments = new List<Messaging.Emailfileattachment>();
                Messaging.EmailFileAttachment attach = new Messaging.EmailFileAttachment();                                
                attach.setBody(b);
                attach.setFileName('Handover Reminder.pdf');
                fileAttachments.add(attach);
                
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();              
                
                List <String> lststringtoaddress = new List<String>();
                List <String> lstStringccaddress = new List <String>();
                
                EmailTemplate emailTemplate =[Select Id,Subject,Description,
                                              HtmlValue,DeveloperName,Body
                                              from EmailTemplate where name =
                                              'HandoverReminderEmailTemplate'];
                
                lststringtoaddress.add(book.Primary_Applicant_Email__c); //Commented to block direct communication with client and added booking owner  
               // lstStringccaddress.add('helpdesk@sobharealty.com');
               String handOverNoticeCCList = System.Label.HandOverNoticeCCList;
              // lstStringccaddress.add(HandOverNoticeCCList);
                
                if(owea.size() > 0){
                    email.setOrgWideEmailAddressId( owea.get(0).Id);
                }              
                email.setTemplateID(emailTemplate.Id);
                email.setWhatId(book.Id);
                email.setTargetObjectId(System.Label.HandoverContactId);
                email.setTreatTargetObjectAsRecipient(false);
                email.setSaveAsActivity(false);
                String emailAddressFromBooking = BookingUtilityClass.getEmailOfApplicants(book.id);
                if(!string.isblank(emailAddressFromBooking)){
                    for(String s : emailAddressFromBooking.split(',')){
                        if(!s.containsIgnoreCase('null')){
                            lststringtoaddress.add(s);
                        }
                    }
                }
                
               // String emailAddressFromBooking = BookingUtilityClass.getEmailOfApplicants(book.id);
                if(!string.isblank(handOverNoticeCCList)){
                    for(String s : handOverNoticeCCList.split(',')){
                        if(!s.containsIgnoreCase('null')){
                            lstStringccaddress.add(s);
                        }
                    }
                }
                //SOB-336 end
                email.setToAddresses(lststringtoaddress);
                email.setccAddresses(lstStringccaddress);
                email.setFileAttachments(fileAttachments);    
                mailsList.add(email);       
            }
            Messaging.sendEmail(mailsList);
            
        }
    }   
    
    public void finish(Database.BatchableContext BC){
        
    }
}