force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>Booked_Date__c</fullName>
    <label>Booked Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Collection_Report__c/Collection_Report__c.object-meta.xml
<CustomObject>
    <label>Collection Report</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Collection Report Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collection Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Collection_Report__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Collection_Report__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <label>Total Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Collection_Report__c/fields/Total_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_Amount__c</fullName>
    <label>Total Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBTR__c/SBTR__c.object-meta.xml
<CustomObject>
    <description>Thiis object is created to manage sales booking tracking</description>
    <label>SBTR</label>
    <nameField>
        <displayFormat>SBTR-{00}</displayFormat>
        <label>SBTR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SBTRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SBTR__c/fields/Booked_Date__c.field-meta.xml
<CustomField>
    <fullName>Booked_Date__c</fullName>
    <description>We will pick from NSA (Booked Date)</description>
    <label>Booked Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBTR__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>SBTRs</relationshipLabel>
    <relationshipName>SBTRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBTR__c/fields/Collection_Report__c.field-meta.xml
<CustomField>
    <fullName>Collection_Report__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collection Report</label>
    <referenceTo>Collection_Report__c</referenceTo>
    <relationshipLabel>SBTRs</relationshipLabel>
    <relationshipName>SBTRs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SBTRTriggerHandlerTest.cls
@istest
public class SBTRTriggerHandlerTest{
    @isTest
    private static void updateSBTR(){
        Test.startTest();
        Collection_Report__c cr = new Collection_Report__c();
        cr.Total_Amount__c = 909822.6;
        cr.Total_Paid_Amount__c = 913321;
        insert cr;
        Mobile_TestUtil.createBooking();
        Booking__c b = [Select id  From Booking__c limit 1];
        SBTR__c sbtrRec = new SBTR__c(Booking__c = b.Id);
        insert sbtrRec;

        sbtrRec.Booked_Date__c = System.today();
        sbtrRec.Collection_Report__c = cr.id;
        update sbtrRec;
        Test.stopTest();
    }
}