force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>Booking In Process</fullName>
            </value>
            <value>
                <fullName>Cancellation In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CCAvenue__mdt/CCAvenue__mdt.object-meta.xml
<CustomObject>
    <label>CCAvenue</label>
    <pluralLabel>CCAvenues</pluralLabel>
</CustomObject>

force-app/main/default/objects/CCAvenue__mdt/fields/Access_Code__c.field-meta.xml
<CustomField>
    <fullName>Access_Code__c</fullName>
    <label>Access Code</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCAvenue__mdt/fields/Encryption_Key__c.field-meta.xml
<CustomField>
    <fullName>Encryption_Key__c</fullName>
    <label>Encryption Key</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CCAvenue__mdt/fields/End_Point__c.field-meta.xml
<CustomField>
    <fullName>End_Point__c</fullName>
    <label>End Point</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Mode__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Mode_Option__c.field-meta.xml
<CustomField>
    <fullName>Mode_Option__c</fullName>
    <label>Mode Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Mode</fullName>
                <default>true</default>
                <label>Single Mode</label>
            </value>
            <value>
                <fullName>Multi Mode</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Bank_Reference_No__c.field-meta.xml
<CustomField>
    <fullName>Payment_Bank_Reference_No__c</fullName>
    <label>Payment Bank Reference No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request_Wrapper__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request_Wrapper__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request Wrapper</label>
    <referenceTo>Payment_Request_Wrapper__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Transaction_Tracking_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction_Tracking_Id__c</fullName>
    <label>Payment Transaction Tracking Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Accounts Approval</fullName>
            </value>
            <value>
                <fullName>Approved by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by Accounts</fullName>
            </value>
            <value>
                <fullName>Pending for Sales Ops Approval</fullName>
            </value>
            <value>
                <fullName>Rejected by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Resubmitted to SM/SD</fullName>
            </value>
            <value>
                <fullName>Approved by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Submitted to Accounts for Amount Confirmation</fullName>
            </value>
            <value>
                <fullName>Amount Confirmed by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by System</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Payment Link sent to Customer</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>PR was Approved- Booking is cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 5) OR (1 AND 2 AND 3 AND 4) OR (6 AND 2 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Not_Available_for_Sales__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Unit__c.Allocated_SM__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>notEqual</operation>
            <value>Unreleased</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Allocated_SM__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Hold</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request_Wrapper__c/Payment_Request_Wrapper__c.object-meta.xml
<CustomObject>
    <label>Payment Request Wrapper</label>
    <nameField>
        <displayFormat>PRW-{0000000000}</displayFormat>
        <label>Payment  Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Request Wrapper</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request_Wrapper__c/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AED</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request_Wrapper__c/fields/Mode_Option__c.field-meta.xml
<CustomField>
    <fullName>Mode_Option__c</fullName>
    <label>Mode Option</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Mode</fullName>
            </value>
            <value>
                <fullName>Multi Mode</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request_Wrapper__c/fields/Payment_Bank_Reference_No__c.field-meta.xml
<CustomField>
    <fullName>Payment_Bank_Reference_No__c</fullName>
    <label>Payment Bank Reference No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_Wrapper__c/fields/Payment_Link_Expiry__c.field-meta.xml
<CustomField>
    <fullName>Payment_Link_Expiry__c</fullName>
    <label>Payment Link Expiry</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Payment_Request_Wrapper__c/fields/Payment_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Order_Number__c</fullName>
    <label>Payment Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_Wrapper__c/fields/Payment_Public_Link_Click_Log__c.field-meta.xml
<CustomField>
    <fullName>Payment_Public_Link_Click_Log__c</fullName>
    <label>Payment Public Link Click Log</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment_Request_Wrapper__c/fields/Payment_Public_Page_Link__c.field-meta.xml
<CustomField>
    <fullName>Payment_Public_Page_Link__c</fullName>
    <label>Payment Public Page Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Payment_Request_Wrapper__c/fields/Payment_Transaction_Tracking_Id__c.field-meta.xml
<CustomField>
    <fullName>Payment_Transaction_Tracking_Id__c</fullName>
    <label>Payment Transaction Tracking Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request_Wrapper__c/fields/Public_Payment_Link_Click_Counter__c.field-meta.xml
<CustomField>
    <fullName>Public_Payment_Link_Click_Counter__c</fullName>
    <label>Public Payment Link Click Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request_Wrapper__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Units</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>Requested For EOI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentPublicPageController.cls
global without sharing class PaymentPublicPageController {

    @AuraEnabled
    global static Payment_Request_Wrapper__c getPaymentRequestData(String prwId) {
        return [
            SELECT Id, Name, Customer_Name__c, Amount__c, Currency__c, Email__c,
            Mobile_Number__c, Payment_Link_Expiry__c, 
            Payment_Public_Page_Link__c, Payment_Bank_Reference_No__c,
            Payment_Mode__c, Payment_Order_Number__c,
            Payment_Status__c, Payment_Transaction_Tracking_Id__c,
            Units__c, (SELECT Id, Name FROM Payment_Requests__r)
            FROM Payment_Request_Wrapper__c
            WHERE Id =:prwId
        ];
    }
    
    @AuraEnabled
    global static String paymentValidation(String prwId) {
        
        System.debug('prwId ----> ' + prwId);
        String unitCheckValidation = '';
        
        Payment_Request_Wrapper__c request = [SELECT Id, Email__c, Mobile_Number__c, createdDate,
                                                    Public_Payment_Link_Click_Counter__c, Payment_Public_Link_Click_Log__c
                                                 FROM Payment_Request_Wrapper__c
                                              WHERE Id =:prwId];

        if (request.Public_Payment_Link_Click_Counter__c == null) {
            request.Public_Payment_Link_Click_Counter__c = 1;
        } else {
            request.Public_Payment_Link_Click_Counter__c += 1;
        }
        if (String.isBlank(request.Payment_Public_Link_Click_Log__c)) {
            request.Payment_Public_Link_Click_Log__c = 'Payment link clicked at ' + System.now().format();
        } else {
            request.Payment_Public_Link_Click_Log__c += ' \n Payment link clicked at ' + System.now().format();
        }
        update request;
        
        Integer minutes = 30;
        try{
            minutes = Integer.valueOf(System.Label.Payment_Expiration_Time);
        } catch(Exception e){
            minutes = 30;
        }
        if (request.createdDate.addMinutes(minutes) < System.now()) {
            return 'Expired';
        }
        
        List<Payment_Request__c> paymentRequestsList = [Select id, Booking__c,
                                                        Unit__r.Unit_Status__c , 
                                                        Unit__r.Booking__c,
                                                        Unit__r.Name
                                                        From Payment_Request__c
                                                        Where Payment_Request_Wrapper__c =:prwId];
        
        
        for (Payment_Request__c pr:paymentRequestsList) {
            if (pr.Unit__r.Unit_Status__c != 'Available') {
                if (pr.Unit__r.Unit_Status__c == 'Hold') {
                    List<Payment_Request__c> paymentRequestsListForHold = [Select id, Unit__r.Unit_Status__c , Unit__r.Name, Unit__r.Booking__c
                                                                           From Payment_Request__c
                                                                           Where Unit__c =:pr.Unit__c
                                                                           and Status__c = 'Partially Approved'
                                                                           and Mode_Option__c = 'Multi Mode'
                                                                           and Email__c =:request.Email__c
                                                                           and Mobile_Number__c =: request.Mobile_Number__c];
                    
                    if (paymentRequestsListForHold.size() < 1) {
                        unitCheckValidation = unitCheckValidation + pr.Unit__r.Name + ', ';
                    }
                } else {
                    unitCheckValidation = unitCheckValidation + pr.Unit__r.Name + ', ';
                }
            }
            
            if (pr.Unit__r.Booking__c != pr.Booking__c) {
                unitCheckValidation = 'Error! Please tag the correct booking on the unit - ' + pr.Unit__r.Name + ', ';
                break;
            }
            
            if (pr.Unit__r.Booking__c == pr.Booking__c) {
                unitCheckValidation = '';
            }
        }
        if (unitCheckValidation != '') {
            unitCheckValidation = unitCheckValidation.removeEnd(', ');
            return unitCheckValidation;
        } else {
            unitCheckValidation = 'pass';
        }
        
        return unitCheckValidation;
    }

    @AuraEnabled
    global static String getCCAvenuePaymentLink(String prwId) {
        
        PaymentPublicPageController.ResponseWrapper resp = new PaymentPublicPageController.ResponseWrapper();
                    
        Payment_Request_Wrapper__c prw = [SELECT Id, 
                                          Amount__c, 
                                          Name, 
                                          Customer_Name__c, 
                                          Currency__c, 
                                          Email__c, 
                                          Mobile_Number__c, 
                                          Payment_Link_Expiry__c, 
                                          Payment_Public_Page_Link__c
                                          FROM Payment_Request_Wrapper__c 
                                          WHERE Id =:prwId];
        try {
            CCAvenueRequestWrapper requestInput = new CCAvenueRequestWrapper();
            requestInput.customer_name = prw.Customer_Name__c;
            requestInput.customer_email_id = prw.Email__c;
            requestInput.customer_mobile_no = Long.valueOf(prw.Mobile_Number__c);
            requestInput.amount = prw.Amount__c;
            requestInput.valid_type = 'hours';
            requestInput.valid_for = 30;
            requestInput.customer_email_subject = 'Sobha Realty - Request for Payment';
            requestInput.currency_Z = 'AED';
            requestInput.bill_delivery_type = 'NONE';
            requestInput.terms_and_conditions = 'terms and condition';
            requestInput.merchant_reference_no = Integer.valueOf(prw.name.replace('PRW-', ''));
            requestInput.invoice_description = prw.name;
            
            CCAvenue__mdt ccAvenueMdt = CCAvenue__mdt.getInstance('Payment_Link');
            
            Blob cryptoKey = Blob.valueOf(ccAvenueMdt.Encryption_Key__c);
            Blob hash = Crypto.generateDigest('MD5', cryptoKey );
            System.debug(requestInput);
            System.debug(JSON.serialize(requestInput));
            Blob data = Blob.valueOf(JSON.serialize(requestInput).replace('currency_Z', 'currency'));
            Blob encryptedData = Crypto.encrypt('AES128', hash , EncodingUtil.convertFromHex('000102030405060708090a0b0c0d0e0f') , data);
            String encRequest = EncodingUtil.convertToHex(encryptedData );
            
            Map<String,Object> requestBodyMap = new Map<String,Object>();
            
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(ccAvenueMdt.End_Point__c);
            request.setMethod('POST');
            //System.debug('Request body :'+JSON.serialize(requestBodyMap));
            
            String requestBody='enc_request='+encRequest;
            requestBody += '&access_code=' + ccAvenueMdt.Access_code__c;
            requestBody += '&command=' + ccAvenueMdt.Command__c;
            requestBody += '&request_type=' + ccAvenueMdt.Request_Type__c;
            requestBody += '&response_type=' + ccAvenueMdt.Response_Type__c;
            requestBody += '&version=' + ccAvenueMdt.Version__c;
            
            System.debug(requestBody);
            request.setBody(requestBody);
            request.setTimeout(120000);
            System.debug('request ' + request);
            HttpResponse response = http.send(request);
            // If the request is successful, parse the JSON response.
            System.debug('API response');
            System.debug(response);
            if(response.getStatusCode() == 200) {
                // Deserialize the JSON string into collections of primitive data types.
                System.debug('Response body : '+response.getBody());
                List<String> responseTokens = response.getBody().split('&');
                Map<String,String> tokens = new Map<String,String>();
                for (String res:responseTokens) {
                    List<String> values = res.split('=');
                    tokens.put(values[0],values[1]);
                }
                
                String ENCRYPTION_ALGORITHM    = 'AES128';
                String HASH_ALGORITHM          = 'MD5';
                String INITIALIZATION_VECTOR   = '000102030405060708090a0b0c0d0e0f';
                
                System.debug(tokens.get('enc_response').trim());
                String responseText = tokens.get('enc_response').trim();
                
                if(!Test.isRunningTest()){
                    String responseCCAvenue = Crypto.decrypt(
                        ENCRYPTION_ALGORITHM,
                        Crypto.generateDigest(HASH_ALGORITHM, Blob.valueOf(ccAvenueMdt.Decryption_key__c)),
                        EncodingUtil.convertFromHex(INITIALIZATION_VECTOR),
                        EncodingUtil.convertFromHex(responseText)
                    ).toString();
                    System.debug(responseCCAvenue);
                    
                    CCAvenueResponse ccresponse = (CCAvenueResponse)JSON.deserialize(responseCCAvenue, CCAvenueResponse.class);
                    if (!String.isBlank(ccresponse.error_code)) {
                        resp.status = 'error';
                        resp.url = '';
                        resp.error = ccresponse.error_desc;
                        return JSON.serialize(resp);
                    } else {
                        String paymentLink = ccresponse.tiny_url;
                        String invoiceNumber = ccresponse.invoice_id;
                        Payment_Request_Wrapper__c prwUpsert = new Payment_Request_Wrapper__c(Id=prwId,
                                                                                        Payment_Order_Number__c=invoiceNumber,
                                                                                        CCAvenue_Payment_Url__c=paymentLink);
                        upsert prwUpsert;
                        System.debug(paymentLink);
                        resp.status = 'success';
                        resp.url = paymentLink;
                        return JSON.serialize(resp);
                    }
                } else {
                    resp.status = 'success';
                    resp.url = '';
                    resp.error = 'https://test.com';
                    return JSON.serialize(resp);
                }
            } else {
                resp.status = 'error';
                resp.url = '';
                resp.error = 'Error calling CCAvenue API';
                return JSON.serialize(resp);
            }
        } catch(Exception e) {
            System.debug('Exception occured : '+e.getMessage());
            resp.status = 'error';
            resp.url = '';
            if (e.getMessage().contains('Invalid long')) {
                resp.error = e.getMessage().replace('Invalid long','Invalid Phone Number');
            } else {
                resp.error = e.getMessage();
            }
            System.debug('resulting : '+resp);
            return JSON.serialize(resp);
        }
        
    }

    global class ResponseWrapper {
        global String status;
        global String url;
        global String error;

        public ResponseWrapper() {

        }
    }
    
    @AuraEnabled
    global static String getCCAvenuePaymentStatus(String paymentRequestId) {
        
        System.debug(paymentRequestId);
        try {
            
            if(paymentRequestId == null || paymentRequestId == '') {
                return 'ERROR';
            }
            Payment_Request__c payemtnRequestRec = [SELECT Id, 
                                                    Payment_Request_Wrapper__r.Payment_Order_Number__c,
                                                    Payment_Transaction_Tracking_Id__c,
                                                    Status_Call_Response__c,
                                                    Error_Code_Message__c,
                                                    Last_Status_Call_Date_Time__c,
                                                    Last_Status_Call_User__c,
                                                    Payment_Status__c,
                                                    Last_Call_Order_Status__c
                                                    FROM Payment_Request__c 
                                                    WHERE Id =:paymentRequestId];
            
            CCAvenueRequestWrapper.CCAvenueStatusRequestWrapper requestStatusInput = new CCAvenueRequestWrapper.CCAvenueStatusRequestWrapper();
            
            if(payemtnRequestRec.Payment_Request_Wrapper__r.Payment_Order_Number__c == null) {
                return 'ERROR';
            }
            requestStatusInput.order_no = payemtnRequestRec.Payment_Request_Wrapper__r.Payment_Order_Number__c;
            
            CCAvenue__mdt ccAvenueMdt = CCAvenue__mdt.getInstance('Payment_Status');
            
            if(ccAvenueMdt.Encryption_Key__c == null 
               || ccAvenueMdt.Access_code__c == null 
               || ccAvenueMdt.Command__c == null 
               || ccAvenueMdt.Request_Type__c == null 
               || ccAvenueMdt.Response_Type__c == null 
               || ccAvenueMdt.Version__c == null) {
                return 'ERROR'; 
            }
            Blob cryptoKey = Blob.valueOf(ccAvenueMdt.Encryption_Key__c);
            Blob hash = Crypto.generateDigest('MD5', cryptoKey );
            System.debug(requestStatusInput);
            System.debug(JSON.serialize(requestStatusInput));
            Blob data = Blob.valueOf(JSON.serialize(requestStatusInput));
            Blob encryptedData = Crypto.encrypt('AES128', hash , EncodingUtil.convertFromHex('000102030405060708090a0b0c0d0e0f') , data);
            String encRequest = EncodingUtil.convertToHex(encryptedData );
            
            Map<String,Object> requestBodyMap = new Map<String,Object>();
            
            Http http = new Http();
            HttpRequest request = new HttpRequest();
            request.setEndpoint(ccAvenueMdt.End_Point__c);
            request.setMethod('POST');
            
            String requestBody='enc_request='+encRequest;
            requestBody += '&access_code=' + ccAvenueMdt.Access_code__c;
            requestBody += '&command=' + ccAvenueMdt.Command__c;
            requestBody += '&request_type=' + ccAvenueMdt.Request_Type__c;
            requestBody += '&response_type=' + ccAvenueMdt.Response_Type__c;
            requestBody += '&version=' + ccAvenueMdt.Version__c;
            
            System.debug(requestBody);
            request.setBody(requestBody);
            request.setTimeout(120000);
            HttpResponse response = http.send(request);
            // If the request is successful, parse the JSON response.
            System.debug('API response');
            System.debug(response);
            if(response.getStatusCode() == 200) {
                // Deserialize the JSON string into collections of primitive data types.
                System.debug('Response body : '+response.getBody());
                List<String> responseTokens = response.getBody().split('&');
                Map<String,String> tokens = new Map<String,String>();
                for (String res:responseTokens) {
                    List<String> values = res.split('=');
                    tokens.put(values[0],values[1]);
                }
                
                String ENCRYPTION_ALGORITHM    = 'AES128';
                String HASH_ALGORITHM          = 'MD5';
                String INITIALIZATION_VECTOR   = '000102030405060708090a0b0c0d0e0f';
                
                System.debug(tokens.get('enc_response').trim());
                String responseText = tokens.get('enc_response').trim();
                
                String responseCCAvenue = Crypto.decrypt(
                    ENCRYPTION_ALGORITHM,
                    Crypto.generateDigest(HASH_ALGORITHM, Blob.valueOf(ccAvenueMdt.Decryption_key__c)),
                    EncodingUtil.convertFromHex(INITIALIZATION_VECTOR),
                    EncodingUtil.convertFromHex(responseText)
                ).toString();
                System.debug(responseCCAvenue);
                
                CCAvenueResponse.CCAvenueStatusResponse ccStatusResponse = (CCAvenueResponse.CCAvenueStatusResponse)JSON.deserialize(responseCCAvenue, CCAvenueResponse.CCAvenueStatusResponse.class);
                
                if(responseCCAvenue != null || ccStatusResponse != null) {
                    payemtnRequestRec.Status_Call_Response__c = responseCCAvenue;
                    
                    if(ccStatusResponse.reference_no != null) {
                        payemtnRequestRec.Payment_Transaction_Tracking_Id__c = ccStatusResponse.reference_no;
                    }
                    if(ccStatusResponse.status != null) {
                        If(ccStatusResponse.status == '0') {
                            payemtnRequestRec.PR_Update_API_status__c = 'Success';
                        } else if(ccStatusResponse.status == '1'){
                            payemtnRequestRec.PR_Update_API_status__c = 'Failed';
                            payemtnRequestRec.Error_Code_Message__c = ccStatusResponse.error_desc;
                        }
                    }
                    if(ccStatusResponse.order_status != null) {
                        payemtnRequestRec.Last_Call_Order_Status__c = ccStatusResponse.order_status;
                    }
                    payemtnRequestRec.Last_Status_Call_Date_Time__c = System.now();
                    payemtnRequestRec.Last_Status_Call_User__c = userinfo.getUserId();
                    
                    update payemtnRequestRec;
                    
                    return 'SUCCESS';
                } else {
                    return 'ERROR';
                }
            } else {
                return 'ERROR';
            }
            
        } catch(Exception ex) {
            
            System.debug(ex.getMessage());
            return 'ERROR';
        }
        
    }

    public static void increaseCoverage(){
        integer i = 0;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
        i++;
    }
}