force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>Booking In Process</fullName>
            </value>
            <value>
                <fullName>Cancellation In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Business_Unit_Code__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Code__c</fullName>
    <label>Business Unit Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Corporate_Collection_Control_Report__c.field-meta.xml
<CustomField>
    <fullName>Corporate_Collection_Control_Report__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Corporate Collection Control Report</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Payment_Towards__c.field-meta.xml
<CustomField>
    <fullName>Payment_Towards__c</fullName>
    <label>Payment Towards</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Account</fullName>
                <default>true</default>
                <label>Corporate Account</label>
            </value>
            <value>
                <fullName>ESCROW Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>VAT Rate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Tax_Rates</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/Quotation__c.object-meta.xml
<CustomObject>
    <label>Quotation</label>
    <nameField>
        <displayFormat>SH-{000}</displayFormat>
        <label>Quotation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quotation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quotation__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Sold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Quotations</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Amount_Rs__c.field-meta.xml
<CustomField>
    <fullName>Amount_Rs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount (AED)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Business_Unit_Code__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit_Code__c</fullName>
    <label>Business Unit Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Credit_Account__c.field-meta.xml
<CustomField>
    <fullName>Credit_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Credit Account</label>
    <referenceTo>Account_Master__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Debit_Account__c.field-meta.xml
<CustomField>
    <fullName>Debit_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Debit Account</label>
    <referenceTo>Account_Master__c</referenceTo>
    <relationshipLabel>Receipts (Debit Account)</relationshipLabel>
    <relationshipName>Receipts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Is_Reversed_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Is_Reversed_Receipt__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Reversed Receipt</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Project_Unit__c.field-meta.xml
<CustomField>
    <fullName>Project_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Number__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Number__c</fullName>
    <formula>IF( Advance_Receipt__c  = true, IF( Tax_Receipt__c = true, (Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Project_Unit__r.Tower__r.Name ,2) &amp; &apos;-&apos; &amp; Project_Unit__r.Name &amp; &apos;/&apos; &amp; TEXT(Receipt_Date__c) &amp; &apos;/&apos; &amp; &apos;AdvTax-&apos; &amp; Name,(Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Project_Unit__r.Tower__r.Name ,2) &amp; &apos;-&apos; &amp; Project_Unit__r.Name &amp; &apos;/&apos; &amp; TEXT(Receipt_Date__c) &amp; &apos;/&apos; &amp; &apos;Adv-&apos; &amp; Name), 
(Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Project_Unit__r.Tower__r.Name ,2) &amp; &apos;-&apos; &amp; Project_Unit__r.Name &amp; &apos;/&apos; &amp; TEXT(Receipt_Date__c) &amp; &apos;/&apos; &amp; Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Receipt Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Status__c</fullName>
    <label>Receipt Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cheque Hold</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Dishonored</fullName>
            </value>
            <value>
                <fullName>PDC</fullName>
            </value>
            <value>
                <fullName>Physical Verification Rejected</fullName>
            </value>
            <value>
                <fullName>Processed-Sent for Banking</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
                <default>true</default>
                <label>UnProcessed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Tax_Debit_Account__c.field-meta.xml
<CustomField>
    <fullName>Tax_Debit_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VAT Debit Account</label>
    <referenceTo>Account_Master__c</referenceTo>
    <relationshipLabel>Receipts (VAT Debit Account)</relationshipLabel>
    <relationshipName>Receipts2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/Receipt_Details__c.object-meta.xml
<CustomObject>
    <label>Receipt Details</label>
    <nameField>
        <displayFormat>RD-{00000}</displayFormat>
        <label>Receipt Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt_Details__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Receipt Details</relationshipLabel>
    <relationshipName>Receipt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Valid</fullName>
                <default>true</default>
                <label>Valid</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/N_ReceiptActionController.cls
public class N_ReceiptActionController{    
    String rId;
    public Receipt__c rcpt {get; set;}
    List<Receipt_Details__c> lstRctDetails;
    public String selectedRadioOption {get;set;}

    public N_ReceiptActionController(){   
        lstRctDetails = new List<Receipt_Details__c>();
        rcpt = new Receipt__c();     
        if (Apexpages.Currentpage().getParameters().get('id') != null && Apexpages.Currentpage().getParameters().get('id') != '')
            rId = Apexpages.Currentpage().getParameters().get('id');
    
        if(String.isNotBlank(rId) && rId != null){
            rcpt = [SELECT Id, Name, Project__c, Project_Unit__c, Credit_Account__c, Debit_Account__c, Booking__c, Mode__c, Tax_Debit_Account__c,
                    Business_Unit_Code__c, Business_Unit__c, Amount_Rs__c, Description__c, Is_Reversed_Receipt__c, Tax_Rate__c, Corporate_Collection_Control_Report__c,
                    Receipt_Number__c, Payment_Towards__c, Receipt_Status__c, Credit_Note_Amount__c, Tax_Amount__c, Total_Money_Apportioned__c, Cancellation_Reason__c,
                    Registration_Collection_Control_Report__c, Booking__r.Quotation__c FROM Receipt__c WHERE Id = :rId];
            lstRctDetails = [Select Id, Name, Receipts__c, Status__c from Receipt_Details__c where Receipts__c =: rId];        
        }
    }
    
    public PageReference cancel(){
        return new PageReference('/'+rId);
    }
    
    public PageReference save(){
        if(selectedRadioOption != null && selectedRadioOption == 'reverseCreditNote'){
            if(rcpt.Is_Reversed_Receipt__c != null && rcpt.Is_Reversed_Receipt__c){
             ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, 'This receipt is already reversed'));
             return null;           
            }
        }
        if(selectedRadioOption != null && selectedRadioOption == 'voidReceipt'){
            if(rcpt.Total_Money_Apportioned__c != null && rcpt.Total_Money_Apportioned__c > 0){
             ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, 'You cannot make this receipt void. Please unapportion this receipt first'));
             return null;
            }
            else if( 'Cheque'.equals(rcpt.Mode__c) && String.isBlank( rcpt.Cancellation_Reason__c) ) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL, 'Please enter Cancellation Reason from the receipt record before voiding the receipt.'));
                return null;
            }
        }
        if(selectedRadioOption != null && selectedRadioOption == 'reverseCreditNote')
            reverseCreditNote();
        else if(selectedRadioOption != null && selectedRadioOption == 'unapportionReceipt')    
            unapportionReceipt();
        else if(selectedRadioOption != null && selectedRadioOption == 'voidReceipt')
            voidReceipt();  
        return new PageReference('/'+ rcpt.Id); 
    }

///// Credit Note is reversed by creating debit note and updating RD status to 'Cancelled'   
///// Receipt cannot be reversed 
///// Reversed Credit Note can be adjusted by this Debit note only
    public PageReference reverseCreditNote(){                                 
            if(!lstRctDetails.isEmpty() && lstRctDetails.size() > 0) {
                for(Receipt_Details__c rd : lstRctDetails) {
                    rd.Status__c = 'Cancelled';
                }
                update lstRctDetails; 
            }            
            
            Demand__c d = new Demand__c();
            d.Remarks__c = 'Debit Note for Credit Note Rejection: '+ rcpt.Receipt_Number__c;
            d.Milestone_Name__c = 'Debit Note for Credit Note Rejection: '+ rcpt.Receipt_Number__c;       
            d.Debit_Demanded__c = rcpt.Credit_Note_Amount__c;
            d.Debit_CGST__c = rcpt.Tax_Amount__c;
            d.Tax_Rate__c = rcpt.Tax_Rate__c;
            d.Invoice_Date__c = System.Today();
            d.GL_Date__c = System.Today();
            d.Due_Date__c = System.Today();
            d.Project__c = rcpt.Project__c;
            d.Booking__c = rcpt.Booking__c;
            d.Unit__c = rcpt.Project_Unit__c;
            d.Total_Amount_Account__c = rcpt.Debit_Account__c;
            d.Total_Amount_with_Tax_Account__c = rcpt.Credit_Account__c;           
            d.Total_Tax_Account__c = rcpt.Tax_Debit_Account__c;
            d.Receipt__c = rcpt.Id;
            d.Quotation__c = rcpt.Booking__r.Quotation__c ;
            d.Business_Unit__c = rcpt.Business_Unit__c;
            d.Business_Unit_Code__c = rcpt.Business_Unit_Code__c; 
            d.Corporate_Collection_Control_Report__c = rcpt.Corporate_Collection_Control_Report__c; 
            d.Registration_Collection_Control_Report__c = rcpt.Registration_Collection_Control_Report__c;
            d.Payment_Towards__c = rcpt.Payment_Towards__c ;
            d.Debit_Type__c = 'Credit Note Reversal';
            insert d;
           
            rcpt.Description__c = 'Reversed from Actions';
            rcpt.Is_Reversed_Receipt__c = true;            
            update rcpt;  
            return null;      
    }

////while unapportioning, we are not creating DN and this receipt can be adjusted against any demand    
    public PageReference unapportionReceipt(){              
            if(!lstRctDetails.isEmpty() && lstRctDetails.size() > 0) {
                for(Receipt_Details__c rd : lstRctDetails) {
                    rd.Status__c = 'Cancelled';
                }
                update lstRctDetails;
            }
            return null;                           
    }

////// Receipt is cancelled. We can cancel receipt only if Total Money Apportioned = 0 
    public PageReference voidReceipt(){                         
            rcpt.Receipt_Status__c = 'Cancelled'; 
            update rcpt; 
            return null;                          
    }
}