force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Audit_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Audit_Approval_Date__c</fullName>
    <label>Audit Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Booking_Approver_Audit__c.field-meta.xml
<CustomField>
    <fullName>Booking_Approver_Audit__c</fullName>
    <label>Audit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Sub Project</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Comment_Audit__c.field-meta.xml
<CustomField>
    <fullName>Comment_Audit__c</fullName>
    <label>Comment Audit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Current_Status__c.field-meta.xml
<CustomField>
    <fullName>Current_Status__c</fullName>
    <label>Current Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Submitted to Audit</fullName>
            </value>
            <value>
                <fullName>Document Verification Not Started</fullName>
            </value>
            <value>
                <fullName>Document Verification Accepted</fullName>
            </value>
            <value>
                <fullName>Document Verification Rejected</fullName>
            </value>
            <value>
                <fullName>Audit Accepted</fullName>
            </value>
            <value>
                <fullName>Audit Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Flat_No__c.field-meta.xml
<CustomField>
    <fullName>Flat_No__c</fullName>
    <label>Flat No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Flat_Typology__c.field-meta.xml
<CustomField>
    <fullName>Flat_Typology__c</fullName>
    <label>Flat Typology</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name__c</fullName>
    <label>Primary Applicant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Sales_Managers__c.field-meta.xml
<CustomField>
    <fullName>Sales_Managers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Sales_Operations__c.field-meta.xml
<CustomField>
    <fullName>Sales_Operations__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Operations</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Booking (Sales Operations)</relationshipLabel>
    <relationshipName>Booking6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Select_All_Audit__c.field-meta.xml
<CustomField>
    <fullName>Select_All_Audit__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Select All Audit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>Booking In Process</fullName>
            </value>
            <value>
                <fullName>Cancellation In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <label>Tower</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Verification_status__c.field-meta.xml
<CustomField>
    <fullName>Verification_status__c</fullName>
    <label>Document Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <label>Sub Project</label>
    <nameField>
        <label>Sub Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Agreement_Value__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <formula>TEXT(Unit__r.Unit_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>Requested For EOI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVAILABLE</fullName>
                <label>Available</label>
            </value>
            <value>
                <fullName>BUSY</fullName>
                <label>Busy</label>
            </value>
            <value>
                <fullName>BREAK</fullName>
                <label>Break</label>
            </value>
            <value>
                <fullName>OUTCALL</fullName>
                <label>OutCall</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/N_BookingApproverAuditController.cls
public class N_BookingApproverAuditController{
    public List <rMainWrapper> rwList {get; set;}
    public List <Booking__c> lstBooking {get; set;}
    public List <Unit__c> lstUnit {get; set;}
    public List <Opportunity> lstOpty {get; set;}
    
    public N_BookingApproverAuditController(){
        getBookingList();
    }
    
    public void getBookingList(){
        
        rwList = new List<rMainWrapper>();
        lstBooking = [SELECT Id, Name, Primary_Applicant_Name__c, Booking_Approver_Audit__c, Comment_Audit__c, Select_All_Audit__c, Flat_No__c,
                      Tower__c, Sales_Managers__r.Name, Flat_Typology__c, CreatedDate, Agreement_Value__c, Audit_Approval_Date__c, Unit__c,
                      Status__c, Verification_status__c, Sales_Operations__r.Name, Cluster__c, Opportunity__r.StageName, Unit__r.Unit_Status__c, 
                      Current_Status__c FROM Booking__c 
                      WHERE Booking_Approver_Audit__c = 'Not Started'  
                      AND Verification_status__c = 'Accepted' AND Status__c = 'Booking In Process' 
                      Order By CreatedDate DESC limit 50];       
        
        if(lstBooking.size() > 0){
            for(Booking__c b: lstBooking){ 
                rMainWrapper rw = new rMainWrapper(b);
                rwList.add(rw);             
            }
        }  
    }
    
    public void Save() {        
        
        List <Booking__c> updateBookingList = new List <Booking__c>();
        boolean isError = true;  
        for (rMainWrapper rw: rwList) {
            if(rw.b.Select_All_Audit__c == true) {
                isError = false;
            }
        }    
        if(!isError){
            for (rMainWrapper rw: rwList) {
                rw.style0='';
                rw.style1='';
                rw.style2=''; 
                System.debug('List of booking for processing ' + rw);
                if(rw.b.Select_All_Audit__c == true){                                                 
                    if(rw.selectedVal == 'None'){                                       
                        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select Booking Approval Status to proceed'));
                        return;  
                    } else {
                        rw.b.Booking_Approver_Audit__c = rw.selectedVal; 
                    }
                    if(rw.b.Booking_Approver_Audit__c == 'Rejected' && String.ISBLANK(rw.comment)){
                        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please enter Comments'));
                        return;                      
                    } 
                    if(rw.b.Booking_Approver_Audit__c == 'Accepted') {
                        rw.b.Current_Status__c = 'Audit Accepted';
                    }                    
                    if(rw.b.Booking_Approver_Audit__c == 'Rejected') {
                        String userName = UserInfo.getName();
                        String commentValue = '\r\n'+'Rejected On : '+System.now()+' by '+userName+' with the comment : '+rw.comment;
                        rw.b.Status__c = 'Unprocessed';
                        rw.b.Current_Status__c = 'Audit Rejected';
                        rw.b.Verification_status__c = 'Rejected';
                         rw.b.Comment_Audit__c = rw.b.Comment_Audit__c == null ? commentValue :rw.b.Comment_Audit__c+' , '+ commentValue;
                    }  
                    rw.b.Audit_Approval_Date__c = System.Today();                                                           
                    updateBookingList.add(rw.b);                                                           
                }
            }
        } else {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Please select Booking to proceed'));
            return;    
        }
        
        if (updateBookingList.size() > 0){
            update updateBookingList;
        }
        getBookingList();
        return;
    }
    
    public pagereference Back() {
        return new pagereference('/lightning/page/home');
    }                        
    
    public class rMainWrapper {
        public Booking__c b {get; set;}
        public String bookingDate {get; set;}
        public String applicantNames {get; set;}
        public String style0 {get; set;}         
        public String style1 {get; set;}
        public String style2 {get; set;}        
        public List<SelectOption> options {get; set;}
         public string selectedVal {get; set;}
        public string comment {get; set;}
        
        public rMainWrapper(Booking__c b) {
            this.b = b;
            this.applicantNames = b.Primary_Applicant_Name__c;
            this.bookingDate = b.CreatedDate.format('dd/MM/yyyy');
                        
            options = new List<SelectOption>();
           // options.add(new SelectOption('None','None'));
            options.add(new SelectOption('Accepted','Accepted'));
            options.add(new SelectOption('Rejected','Rejected'));
            options.add(new SelectOption('None','None'));
           
            this.style0 = '';
            this.style1 = '';
            this.style2 = '';
            
           
            
        }
    }
}