force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Sub Project</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Email__c</fullName>
    <label>Primary Applicant Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/ReSale_Transfer_Type__c.field-meta.xml
<CustomField>
    <fullName>ReSale_Transfer_Type__c</fullName>
    <label>ReSale Transfer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
                <default>true</default>
                <label>None</label>
            </value>
            <value>
                <fullName>PMT</fullName>
            </value>
            <value>
                <fullName>SMT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
            </value>
            <value>
                <fullName>Booking In Process</fullName>
            </value>
            <value>
                <fullName>Cancellation In Progress</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <label>Tower</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Mobile_getBookingList.cls
@RestResource(urlMapping = '/getBookingList')
global class Mobile_getBookingList {

    @HttpPost
    global static void getBookingList(String email) {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response; 
        String responseString = '';
        String errorMessage = '';
        try{
            List<Booking__c> bklst = [select id,name,Status__c,Unit__r.Name,ReSale_Transfer_Type__c,Unit__r.Tower__r.Name,unit__r.Tower__r.Cluster__r.Name,unit__r.Tower__r.Cluster__r.Project__r.Name from Booking__c where Primary_Applicant_Email__c =:email and unit__r.Tower__r.Cluster__r.Project__r.Id != 'a0RTX000008zDTv2AM' ];
            List<Mobile_ApiUtility.responseBodyWrapper> resplst = new List<Mobile_ApiUtility.responseBodyWrapper>();
            if(bklst.size() > 0){
                for(Booking__c bk :bklst){
                    Mobile_ApiUtility.responseBodyWrapper  wrap = new Mobile_ApiUtility.responseBodyWrapper();
                    if(bk.Id != null){                        
                    wrap.bookingID = bk.Id;
                    } else {
                        wrap.bookingID = null;
                    }
                    if(bk.name != null){
                    wrap.bookingName = bk.name ;
                    } 
                    
                    if(bk.ReSale_Transfer_Type__c == 'SMT'){
                        wrap.isresale = true ;
                    }else {
                         wrap.isresale = false ;
                    }
                        
                    if(bk.Status__c != null){
                    wrap.bookingStatus = bk.Status__c;
                    }
                    if(bk.Unit__r.Name != null){
                        wrap.unitName = bk.Unit__r.Name;
                    }
                    if(bk.Unit__r.Tower__r.Name != null){
                    wrap.towerName = bk.Unit__r.Tower__r.Name;  
                    }
                    if(bk.unit__r.Tower__r.Cluster__r.Name != null){
                    wrap.clusterName =  bk.unit__r.Tower__r.Cluster__r.Name;
                    }
                    if(bk.unit__r.Tower__r.Cluster__r.Project__r.Name != null){
                        wrap.projectName = bk.unit__r.Tower__r.Cluster__r.Project__r.Name;
                    }
                    resplst.add(wrap);
                }
                responseString = (Mobile_ApiUtility.prepareResponse(resplst,'Operation Successfull','Success',200,true)).toString().replace('"','');
                res.responseBody = BLOB.valueOf(JSON.serialize(Mobile_ApiUtility.prepareResponse(resplst,'Operation Successfull','Success',200,true)));
                res.statusCode = 200;
            }
            else{
                res.responseBody = BLOB.valueOf(JSON.serialize(Mobile_ApiUtility.prepareResponse(resplst,'Operation Successfull','Success',200,true)));
                res.statusCode = 200;
            }
        }
        catch(Exception e){
            errorMessage = e.getMessage();
            res.responseBody = BLOB.valueOf(JSON.serialize(Mobile_ApiUtility.prepareResponse(null,'Error','Error',400,false)));
            res.statusCode = 400;
        }  
        Mobile_ApiUtility.createMobileAPILogs('getBookingList','Mobile_getBookingList',email,responseString,errorMessage,res.statusCode);
    }

}