force-app/main/default/objects/Mall_Stand_Roaster__c/Mall_Stand_Roaster__c.object-meta.xml
<CustomObject>
    <label>Mall Stand Roaster</label>
    <nameField>
        <displayFormat>MR - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mall Stand Roaster</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mall_Stand_Roaster__c/fields/Mall_Name__c.field-meta.xml
<CustomField>
    <fullName>Mall_Name__c</fullName>
    <label>Mall Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MOE</fullName>
            </value>
            <value>
                <fullName>DCC</fullName>
            </value>
            <value>
                <fullName>Moscow Exhibition</fullName>
            </value>
            <value>
                <fullName>MCC</fullName>
            </value>
            <value>
                <fullName>St Petersburg Exhibition</fullName>
            </value>
            <value>
                <fullName>A place in the Sun : UK Expo</fullName>
            </value>
            <value>
                <fullName>Movenpick JBR</fullName>
            </value>
            <value>
                <fullName>Sofitel Downtown</fullName>
            </value>
            <value>
                <fullName>United Expo, Singapore</fullName>
            </value>
            <value>
                <fullName>LPS Shanghai Exhibition</fullName>
            </value>
            <value>
                <fullName>Nakheel Mall</fullName>
            </value>
            <value>
                <fullName>Bur Juman</fullName>
            </value>
            <value>
                <fullName>Dubai Boat Show</fullName>
            </value>
            <value>
                <fullName>China Property Expo – Shanghai Expo Mart</fullName>
            </value>
            <value>
                <fullName>DFC</fullName>
            </value>
            <value>
                <fullName>Radisson Blu Marina</fullName>
            </value>
            <value>
                <fullName>IREX Mumbai – St. Regis 2024</fullName>
            </value>
            <value>
                <fullName>QLP China -2024</fullName>
            </value>
            <value>
                <fullName>Sobha Realty Metro Stand</fullName>
            </value>
            <value>
                <fullName>VR activation London</fullName>
            </value>
            <value>
                <fullName>APITS London</fullName>
            </value>
            <value>
                <fullName>Delhi Airport - Stand</fullName>
            </value>
            <value>
                <fullName>IREX Hyderabad – Hotel Trident</fullName>
            </value>
            <value>
                <fullName>APEX Expo– Javits Centre, New York, USA</fullName>
            </value>
            <value>
                <fullName>Sheraton Deira Creek Hotel</fullName>
            </value>
            <value>
                <fullName>BLS Global - Turkey</fullName>
            </value>
            <value>
                <fullName>TOI SOBHA EVENT 2024</fullName>
            </value>
            <value>
                <fullName>NRI ONE SINGAPORE 2024</fullName>
            </value>
            <value>
                <fullName>IREX NEW DELHI 2024</fullName>
            </value>
            <value>
                <fullName>CITYSCAPE QATAR - 2024</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mall_Stand_Roaster__c/fields/Promoter_Name__c.field-meta.xml
<CustomField>
    <fullName>Promoter_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Promoter Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Mall_Stand_Roaster</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MallStandController.cls
public class MallStandController {
    
    @AuraEnabled
    public static string updateLocation(string invoiceFieldJSON){
        Map<String, Object> fieldMap = (Map<String, Object>) JSON.deserializeUntyped(invoiceFieldJSON); 
        list<Mall_Stand_Roaster__c> locations = [select Id 
                                                 from Mall_Stand_Roaster__c
                                                 where 
                                                 Promoter_Name__c =: UserInfo.getUserId() and 
                                                 Start_Date__c =: system.today() and
                                                 End_Date__c  =: system.today()];
        if(locations.size()>0){
            return 'Location already captured.';
        }
        else{
            Mall_Stand_Roaster__c location = new Mall_Stand_Roaster__c();
            location.Promoter_Name__c = UserInfo.getUserId();
            location.Start_Date__c = system.today();
            location.End_Date__c = system.today();
            location.Mall_Name__c = String.valueOf(fieldMap.get('Mall_Name__c'));
            insert location;
            return 'success';
        }
    }
    
    @AuraEnabled
    public static boolean validateIfLocationUpdated(){
        list<Mall_Stand_Roaster__c> locations = [select Id 
                                                 from Mall_Stand_Roaster__c
                                                 where 
                                                 Promoter_Name__c =: UserInfo.getUserId() and 
                                                 Start_Date__c =: system.today() and
                                                 End_Date__c  =: system.today()];
        if(locations.size()>0){
            return true;
        }
        else{
            return false;
        }
    }
    
    @AuraEnabled(cacheable= true)  
    public static Id fetchSalesManagerId(String salesMgrName){             
        List<User> usrId = [select id from user where name = :salesMgrName];
        system.debug('debugguserid' + usrId[0].id);
        return usrId[0].id;
        
    }  
}