force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VIP</fullName>
            </value>
            <value>
                <fullName>Proprietor</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Channel_Relationship_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager_Name__c</fullName>
    <label>Channel Relationship Manager Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ChannelPartner_Id__c.field-meta.xml
<CustomField>
    <fullName>ChannelPartner_Id__c</fullName>
    <label>ChannelPartner Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_ID_1__c.field-meta.xml
<CustomField>
    <fullName>Email_ID_1__c</fullName>
    <label>Email ID 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_ID_2__c.field-meta.xml
<CustomField>
    <fullName>Email_ID_2__c</fullName>
    <label>Email ID 2</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile_No__c.field-meta.xml
<CustomField>
    <fullName>Mobile_No__c</fullName>
    <label>Mobile No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Office_No__c.field-meta.xml
<CustomField>
    <fullName>Office_No__c</fullName>
    <label>Office No.</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/PropStrength__Broker_Type__c.field-meta.xml
<CustomField>
    <fullName>PropStrength__Broker_Type__c</fullName>
    <label>Broker Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <label>Channel Partner</label>
            </value>
            <value>
                <fullName>Sobha Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RERA_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>RERA_Registration_No__c</fullName>
    <label>RERA Registration No.</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetPSBrokers.cls
@RestResource(urlMapping='/PSBrokers/*')
global class GetPSBrokers {
    @HttpGet
    global static List<Account> GetPSBrokersData() {
       List<Account> resAcc = new List<Account>();
        try {
            RestRequest request = RestContext.request;
            List<Account> contactList = [SELECT Id,Name,Email_ID_2__c,Email_ID_1__c,Mobile_No__c,Channel_Relationship_Manager_Name__c,
                                         Phone,RERA_Registration_No__c,Broker_Category__c,BillingCity,BillingStreet,ChannelPartner_Id__c,
                                         BillingPostalCode,BillingState,BillingCountry
                                         FROM Account 
                                         WHERE RecordType.Name = 'Broker' AND PropStrength__Broker_Type__c = 'Standard'];
            
            if(!contactList.isEmpty()) {
                for(Account sr : contactList) {  
                    Account res = new Account();
                    res.Id = sr.Id;
                    res.Name = sr.Name != null ? sr.Name : '';
                    res.ChannelPartner_Id__c = sr.ChannelPartner_Id__c != null ? sr.ChannelPartner_Id__c : '';
                    res.Email_ID_1__c = sr.Email_ID_1__c != null ? sr.Email_ID_1__c : '';
                    res.Email_ID_2__c = sr.Email_ID_2__c != null ? sr.Email_ID_2__c : '';
                    res.Mobile_No__c = sr.Mobile_No__c != null ? sr.Mobile_No__c : '';
                    res.Office_No__c = sr.Phone != null ? sr.Phone : '';
                    res.RERA_Registration_No__c = sr.RERA_Registration_No__c != null ? sr.RERA_Registration_No__c : '';
                    res.Address__c =   (sr.BillingStreet != null ? sr.BillingStreet : '' + ' ') +
                                    (sr.BillingCity != null ? sr.BillingCity : '') + ' ' + 
                                    (sr.BillingPostalCode != null ? sr.BillingPostalCode : '') + ' ' + 
                                    (sr.BillingState != null ? sr.BillingState : '') + ' ' + 
                                    (sr.BillingCountry != null ? sr.BillingCountry : '');
                    res.Is_Active__c = true;
                    res.Channel_Relationship_Manager_Name__c = sr.Channel_Relationship_Manager_Name__c != null ? sr.Channel_Relationship_Manager_Name__c : '';
                    res.Category__c = sr.Broker_Category__c != null ? sr.Broker_Category__c : '';
                    resAcc.add(res);
                }
            }
        } catch(Exception e){
            System.debug(e.getMessage());
        }
        return resAcc;
    }
}