force-app/main/default/objects/Account/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <label>Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nationality</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albanian</fullName>
            </value>
            <value>
                <fullName>Algerian</fullName>
            </value>
            <value>
                <fullName>American</fullName>
            </value>
            <value>
                <fullName>Andorran</fullName>
            </value>
            <value>
                <fullName>Angolan</fullName>
            </value>
            <value>
                <fullName>Antiguans</fullName>
            </value>
            <value>
                <fullName>Argentinean</fullName>
            </value>
            <value>
                <fullName>Armenian</fullName>
            </value>
            <value>
                <fullName>Australian</fullName>
            </value>
            <value>
                <fullName>Austrian</fullName>
            </value>
            <value>
                <fullName>Azerbaijani</fullName>
            </value>
            <value>
                <fullName>Bahamian</fullName>
            </value>
            <value>
                <fullName>Bahraini</fullName>
            </value>
            <value>
                <fullName>Bangladeshi</fullName>
            </value>
            <value>
                <fullName>Barbadian</fullName>
            </value>
            <value>
                <fullName>Barbudans</fullName>
            </value>
            <value>
                <fullName>Batswana</fullName>
            </value>
            <value>
                <fullName>Belarusian</fullName>
            </value>
            <value>
                <fullName>Belgian</fullName>
            </value>
            <value>
                <fullName>Belizean</fullName>
            </value>
            <value>
                <fullName>Beninese</fullName>
            </value>
            <value>
                <fullName>Bhutanese</fullName>
            </value>
            <value>
                <fullName>Bolivian</fullName>
            </value>
            <value>
                <fullName>Bosnian</fullName>
            </value>
            <value>
                <fullName>Brazilian</fullName>
            </value>
            <value>
                <fullName>British</fullName>
            </value>
            <value>
                <fullName>Bruneian</fullName>
            </value>
            <value>
                <fullName>Bulgarian</fullName>
            </value>
            <value>
                <fullName>Burkinabe</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit#</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Legal_Entity__c/Legal_Entity__c.object-meta.xml
<CustomObject>
    <label>Legal Entity</label>
    <nameField>
        <label>Legal Entity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Legal Entities</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Legal_Entity__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Legal_Entity__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Parent Legal Entity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Legal Entities</relationshipLabel>
    <relationshipName>Legal_Entities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration 1</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ST</fullName>
            </value>
            <value>
                <fullName>1 BR</fullName>
            </value>
            <value>
                <fullName>2 BR</fullName>
            </value>
            <value>
                <fullName>3 BR</fullName>
            </value>
            <value>
                <fullName>2DP</fullName>
            </value>
            <value>
                <fullName>3DP</fullName>
            </value>
            <value>
                <fullName>4DP</fullName>
            </value>
            <value>
                <fullName>4BR Villa</fullName>
            </value>
            <value>
                <fullName>5BR Villa</fullName>
            </value>
            <value>
                <fullName>GFA Plots</fullName>
            </value>
            <value>
                <fullName>Gardenia</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Canal Villa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NATIONALITY__c.field-meta.xml
<CustomField>
    <fullName>NATIONALITY__c</fullName>
    <label>NATIONALITY</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <formula>TEXT(Unit__r.Unit_Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Unit Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>2.5 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>3.5 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
            <value>
                <fullName>5 BHK</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>1.5 BHK</fullName>
            </value>
            <value>
                <fullName>Studio Apartment</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>APARTMENT</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>VILLAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Expiry_Days__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Days__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Expiry Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Max_Budget__c.field-meta.xml
<CustomField>
    <fullName>Max_Budget__c</fullName>
    <label>Max Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Min_Budget__c.field-meta.xml
<CustomField>
    <fullName>Min_Budget__c</fullName>
    <label>Min Budget</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/PossessionRequirement__c.field-meta.xml
<CustomField>
    <fullName>PossessionRequirement__c</fullName>
    <label>PossessionRequirement</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready to Move in (RTMI)</fullName>
            </value>
            <value>
                <fullName>Ready to Live In (RTLI)</fullName>
            </value>
            <value>
                <fullName>Under Construction (UC – 1 to 2 years)</fullName>
            </value>
            <value>
                <fullName>Under Construction (UC – 2 to 3 years)</fullName>
            </value>
            <value>
                <fullName>Under Construction (UC – More than 3 years)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Chargeable_Area__c.field-meta.xml
<CustomField>
    <fullName>Chargeable_Area__c</fullName>
    <label>Chargeable Area</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ST</fullName>
                <label>Studio</label>
            </value>
            <value>
                <fullName>2DP</fullName>
                <label>2 BR Duplex</label>
            </value>
            <value>
                <fullName>3DP</fullName>
                <label>3 BR Duplex</label>
            </value>
            <value>
                <fullName>4DP</fullName>
                <label>4 BR Duplex</label>
            </value>
            <value>
                <fullName>1 BR</fullName>
            </value>
            <value>
                <fullName>2 BR</fullName>
            </value>
            <value>
                <fullName>3 BR</fullName>
            </value>
            <value>
                <fullName>4BR Villa</fullName>
            </value>
            <value>
                <fullName>5BR Villa</fullName>
                <label>5 BR</label>
            </value>
            <value>
                <fullName>GFA Plots</fullName>
            </value>
            <value>
                <fullName>Gardenia</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Canal Villa</fullName>
            </value>
            <value>
                <fullName>4 BR</fullName>
            </value>
            <value>
                <fullName>1 Br + Study</fullName>
                <label>1 BR + Study</label>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Retail / Cafe</fullName>
            </value>
            <value>
                <fullName>2.5 BR</fullName>
            </value>
            <value>
                <fullName>6 BR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Legal_Entity__c.field-meta.xml
<CustomField>
    <fullName>Legal_Entity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Legal Entity</label>
    <referenceTo>Legal_Entity__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>Requested For EOI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestProformaInvoiceController.cls
@isTest
private class TestProformaInvoiceController {

    @isTest static void getOpportunityTestMethod()
    {
        Account acc= new Account();
        acc.Name='Tania Account';
        acc.Nationality__c='India';
        insert acc; 
        
        Project__c projectInstance = new Project__c();
        projectInstance.Name ='Sobha Hartland';
        projectInstance.Project_Code__c='123';
        projectInstance.Expiry_Days__c=60;
        projectInstance.PossessionRequirement__c='Under Construction (UC – 1 to 2 years)';
        projectInstance.Min_Budget__c=234.90;
        projectInstance.Max_Budget__c=788.90;
        projectInstance.Address__c='test Address';
        projectInstance.Configuration__c='1 BHK';
        insert projectInstance;
        
        Legal_Entity__c legalEntityInstance = new Legal_Entity__c();
        legalEntityInstance.Name='Sobha Hartland Greens - Phase III';
        insert legalEntityInstance;
       
        Unit__c unitInstance= new Unit__c();
        unitInstance.Name='GV23';
        unitInstance.Legal_Entity__c=legalEntityInstance.Id;
        unitInstance.Chargeable_Area__c	=9677.08;
        unitInstance.Unit_Status__c='EOI';
        unitInstance.Configuration__c='5 BR';
        unitInstance.Project_Property_Type__c='Residential';
        unitInstance.Puchase_Price__c=18386452.00;
        unitInstance.Tax_Rate_Basic__c='VAT 5%';
        insert unitInstance; 
                                    
    	List<Opportunity> oppList=new List<Opportunity>();
        Opportunity opp=new Opportunity();
        opp.Name='John Ram';
        opp.StageName='Qualification';
        opp.Project__c=projectInstance.Id;
        opp.AccountId=acc.Id;
        opp.CloseDate=system.today();
        opp.Unit__c= unitInstance.Id;
        opp.Proforma_Invoice_Type__c='Unit Price';
        opp.Proforma_Invoice_Sub_Type__c='Percentage';
        opp.AED_to_USD_Conversion_Rate__c=0.23344;
        opp.Input_Value__c=5.00;
        insert opp;
         
        Opportunity opp2=new Opportunity();
        opp2.Name='John Rames';
        opp2.StageName='Qualification';
        opp2.Project__c=projectInstance.Id;
        opp2.AccountId=acc.Id;
        opp2.CloseDate=system.today();
        opp2.Unit__c= unitInstance.Id;
        opp2.Proforma_Invoice_Type__c='Unit Price';
        opp2.Proforma_Invoice_Sub_Type__c='Amount';
        opp2.AED_to_USD_Conversion_Rate__c=0.23344;
        opp2.Input_Value__c=5567898.00;
        insert opp2;
        
        Opportunity opp3=new Opportunity();
        opp3.Name='John Ramesh';
        opp3.StageName='Qualification';
        opp3.Project__c=projectInstance.Id;
        opp3.AccountId=acc.Id;
        opp3.CloseDate=system.today();
        opp3.Unit__c= unitInstance.Id;
        opp3.Proforma_Invoice_Type__c='DLD Amount';
        //opp3.Proforma_Invoice_Sub_Type__c='Amount';
        opp3.AED_to_USD_Conversion_Rate__c=0.23344;
        opp3.Input_Value__c=5567898.00;
        insert opp3;
        
        //Calling methods
        ProformaInvoiceController.getOpportunity(opp.Id);
        ProformaInvoiceController.calculate('Percentage',5.00,opp.Id,18386452.00,opp.Id,false);
        ProformaInvoiceController.calculate('Amount',5567898.00,opp2.Id,18386452.00,opp2.Id,false);
        ProformaInvoiceController.updateParent('Unit Price',opp.Id,false);
		ProformaInvoiceController.updateParent('DLD Amount',opp3.Id,false);
        String profomaId = ProformaInvoiceController.createAndSubmit(opp.Id,'',67.34,45.4,false);
        ProformaInvoiceController.objectName(opp.Id);
        ProformaInvoiceController.generatePDFForBooking(profomaId,5567898.0);
        ProformaInvoiceController.sendEmailAfterApproval(profomaId);
        ProformaInvoiceController.generatePDF(opp.Id,'5567898',97.0,5567898.0);
        ProformaInvoiceController.getBooking(opp.Id);
        ProformaInvoiceController.generatePDF2(opp.Id,'5567898',97.0,5567898.0);
        ProformaInvoiceController.generatePDF3(opp.Id,'5567898',97.0,5567898.0);
        ProformaInvoiceController.checkPDFGeneration(opp.Id);
        

        List<Id> idsVal = New List<Id>();
        idsVal.add(Id.valueOf(profomaId));
        ProformaInvoiceController.generatePDF(idsVal);
        //passing the constructors
        ApexPages.StandardController sc = new ApexPages.standardController(opp);
        ProformaInvoiceController controller = new ProformaInvoiceController(sc);
    }
    
    
}