force-app/main/default/objects/Account/fields/All_Documents_Updated__c.field-meta.xml
<CustomField>
    <fullName>All_Documents_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Documents Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Emergency_CP_SC_ID__c.field-meta.xml
<CustomField>
    <fullName>Emergency_CP_SC_ID__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency CP/SC ID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legacy_Broker_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Broker_Id__c</fullName>
    <label>Legacy Broker Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <externalId>true</externalId>
    <label>Mobile (Unique Identifier)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Name_as_per_passport__c.field-meta.xml
<CustomField>
    <fullName>Name_as_per_passport__c</fullName>
    <label>Name as per passport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Name_as_per_trade_license__c.field-meta.xml
<CustomField>
    <fullName>Name_as_per_trade_license__c</fullName>
    <label>Name as per trade license</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PropStrength__Broker_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>PropStrength__Broker_Approval_Status__c</fullName>
    <label>Broker Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Broker Registration Done, pending with CHRM Manager</fullName>
                <label>Pending with CHRM Manager</label>
            </value>
            <value>
                <fullName>Pending with CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Approved by CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Agreement Created and Sent for Signatures</fullName>
            </value>
            <value>
                <fullName>Signed Agreement Received - Documents Awaiting</fullName>
            </value>
            <value>
                <fullName>All Missing Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>NOC Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh/ Sent for final signatures</fullName>
                <label>Pending with Ashish Parakh</label>
            </value>
            <value>
                <fullName>Executed Agreement Sent to CHRM</fullName>
            </value>
            <value>
                <fullName>Executed Agreement Sent to Broker</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Broker Registration Done</fullName>
            </value>
            <value>
                <fullName>Broker Empanelment Form Filled</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM Manager</fullName>
            </value>
            <value>
                <fullName>Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh</fullName>
                <label>Pending with Ashish Parakh1</label>
            </value>
            <value>
                <fullName>Rejected by Audit</fullName>
            </value>
            <value>
                <fullName>NOC Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and sent for signature</fullName>
            </value>
            <value>
                <fullName>NOC Is in Process</fullName>
            </value>
            <value>
                <fullName>Agreement - approved by CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Pending with CHRM / Rejected with CHRM</fullName>
            </value>
            <value>
                <fullName>Agreement Is in process</fullName>
            </value>
            <value>
                <fullName>Approved - by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Agreement Generated</fullName>
            </value>
            <value>
                <fullName>Executed Agreement sent to CRHM</fullName>
            </value>
            <value>
                <fullName>Signed Agreement Received - Documents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PropStrength__Broker_Type__c.field-meta.xml
<CustomField>
    <fullName>PropStrength__Broker_Type__c</fullName>
    <label>Broker Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <label>Channel Partner</label>
            </value>
            <value>
                <fullName>Sobha Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Passport_Number__c</fullName>
    <label>Passport Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Manager_User__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SalesManager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/TRN_Number__c.field-meta.xml
<CustomField>
    <fullName>TRN_Number__c</fullName>
    <label>TRN Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/Broker_Registration__c.object-meta.xml
<CustomObject>
    <label>Broker Registration</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Registration__c/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker - RERA</fullName>
            </value>
            <value>
                <fullName>Broker - UAE</fullName>
            </value>
            <value>
                <fullName>Broker - Intnl</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - UAE - Individual</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - Intnl - Individual</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - UAE - Company</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - Intnl - Company</fullName>
            </value>
            <value>
                <fullName>Broker – Intnl</fullName>
                <isActive>false</isActive>
                <label>Broker – Intnl</label>
            </value>
            <value>
                <fullName>Broker – RERA</fullName>
                <isActive>false</isActive>
                <label>Broker – RERA</label>
            </value>
            <value>
                <fullName>Broker – UAE</fullName>
                <isActive>false</isActive>
                <label>Broker – UAE</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl – Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl – Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl – Individual</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl – Individual</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl– Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl– Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – UAE – Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – UAE – Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – UAE – Individual</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – UAE – Individual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>Company/Individual Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Name_as_per_passport__c.field-meta.xml
<CustomField>
    <fullName>Name_as_per_passport__c</fullName>
    <label>Name as per passport</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Name_as_per_trade_license__c.field-meta.xml
<CustomField>
    <fullName>Name_as_per_trade_license__c</fullName>
    <label>Name as per trade license</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <label>Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Skip_Broker_Email_Notification__c.field-meta.xml
<CustomField>
    <fullName>Skip_Broker_Email_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If Checked, Email notification to Broker will not be triggered</description>
    <label>Skip Broker Email Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <label>New</label>
</RecordType>

force-app/main/default/classes/BRFileMigrationBatchTest.cls
@isTest
public class BRFileMigrationBatchTest  {
    
    @testSetup
    static void setup() {
        
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
        
        List<User> usr = BrokerRegistrationController.getUserManagerDetails(UserInfo.getUserId());
        // Create test data
        Broker_Registration__c testRecord = new Broker_Registration__c(
            FIrst_Name__c = 'Test',
            Last_Name__c = 'Broker',
            Email__c = 'test@example.com',
            Mobile__c = '1234567890',
            Name_as_per_trade_license__c = 'Test Trade License',
            Registration_Number__c = '123456',
            Broker_Category__c = 'Broker - RERA',
            Skip_Broker_Email_Notification__c = true
        );
        insert testRecord;
        
        Account acc1 = new Account();
        acc1.name = 'Test account 1';
        acc1.RecordTypeId = RecordTypeIdAccount;
        acc1.PropStrength__Broker_Type__c ='Standard';
        acc1.Broker_Category__c = 'Individual';
        acc1.Name_as_per_passport__c = 'passportName';
        acc1.All_Documents_Updated__c = false;
        acc1.Emergency_CP_SC_ID__c = false;
        acc1.Registration_Passport_Number__c = '123';
        acc1.TRN_Number__c ='456';
        acc1.Channel_Relationship_Manager__c = Userinfo.getUserId();
        acc1.Sales_Manager_User__c = Userinfo.getUserId();
        acc1.PropStrength__Broker_Approval_Status__c = 'All Missing Documents Uploaded';
        acc1.legacy_Broker_Id__c = testRecord.Id;
        insert acc1;
        
    }
    
    @isTest
    static void testBatchExecution() {
        // Instantiate the batch class
        BRFileMigrationBatch batch = new BRFileMigrationBatch(1);
        
        // Execute the batch
        Test.startTest();
        ID batchId = Database.executeBatch(batch);
        Test.stopTest();
        
    }
}