force-app/main/default/objects/Account/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <label>Alternate Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <externalId>true</externalId>
    <label>Mobile (Unique Identifier)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/Broker_Registration__c.object-meta.xml
<CustomObject>
    <label>Broker Registration</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Registration__c/fields/Account_Email__c.field-meta.xml
<CustomField>
    <fullName>Account_Email__c</fullName>
    <label>Account Email</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <label>Owner&apos;s Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker - RERA</fullName>
            </value>
            <value>
                <fullName>Broker - UAE</fullName>
            </value>
            <value>
                <fullName>Broker - Intnl</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - UAE - Individual</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - Intnl - Individual</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - UAE - Company</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - Intnl - Company</fullName>
            </value>
            <value>
                <fullName>Broker – Intnl</fullName>
                <isActive>false</isActive>
                <label>Broker – Intnl</label>
            </value>
            <value>
                <fullName>Broker – RERA</fullName>
                <isActive>false</isActive>
                <label>Broker – RERA</label>
            </value>
            <value>
                <fullName>Broker – UAE</fullName>
                <isActive>false</isActive>
                <label>Broker – UAE</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl – Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl – Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl – Individual</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl – Individual</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl– Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl– Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – UAE – Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – UAE – Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – UAE – Individual</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – UAE – Individual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Is_ValidAccountEmail__c.field-meta.xml
<CustomField>
    <fullName>Is_ValidAccountEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ValidAccountEmail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Is_ValidEmail__c.field-meta.xml
<CustomField>
    <fullName>Is_ValidEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ValidEmail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Is_ValidOwnerEmail__c.field-meta.xml
<CustomField>
    <fullName>Is_ValidOwnerEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ValidOwnerEmail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Is_ValidTelephone__c.field-meta.xml
<CustomField>
    <fullName>Is_ValidTelephone__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ValidTelephone</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Mobile_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Country_Code__c</fullName>
    <label>Mobile Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_With_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Telephone_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Telephone_Country_Code__c</fullName>
    <label>Telephone Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_With_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <label>New</label>
</RecordType>

force-app/main/default/classes/Nice_BR_EmailValidationBatchTest.cls
/***************************************************************************
Class      : Nice_BR_EmailValidationBatchTest
Purpose    : NICE - Test class for Nice_BR_EmailValidationBatch
Author     : Abhijeet
*****************************************************************************/

@isTest
public class Nice_BR_EmailValidationBatchTest {

    @testSetup
    static void setupTestData() {
        List<Broker_Registration__c> brokers = new List<Broker_Registration__c>();

        for (Integer i = 0; i < 5; i++) {
            brokers.add(new Broker_Registration__c(
                Mobile__c = '123456789' + i,
                Mobile_Country_Code__c = '+1',
                Telephone__c = '987654321' + i,
                Telephone_Country_Code__c = '+1',
                Is_ValidMobileNumber__c = false,
                Is_ValidTelephone__c = false,
                Broker_Category__c = 'Broker - RERA',
                Email__c = 'Test'+i+'@gmail.com',
                Alternate_Email__c = 'Test@gmail.com',
                Account_Email__c = 'Test.S@gmail.com',
                Is_ValidAccountEmail__c = false,
                Is_ValidEmail__c = false,
                Is_ValidOwnerEmail__c = false
                
            ));
        }
        insert brokers;
    }
    
    @isTest
    static void testBrokerValidEmails() {
        
        List<Broker_Registration__c> beforeBatch = [SELECT Id, Is_ValidEmail__c FROM Broker_Registration__c WHERE Is_ValidEmail__c = false];
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Nice_EmailValidationMock(true,false));

        Nice_BR_EmailValidationBatch batchJob = new Nice_BR_EmailValidationBatch();
        Database.executeBatch(batchJob, beforeBatch.size());

        Test.stopTest();

        List<Broker_Registration__c> updatedBrokers = [SELECT Id, Is_ValidEmail__c, Is_ValidOwnerEmail__c, Is_ValidAccountEmail__c FROM Broker_Registration__c];

        for (Broker_Registration__c broker : updatedBrokers) {
            System.assertEquals(true, broker.Is_ValidEmail__c, 'Valid Email validation failed for: ' + broker.Id);
            System.assertEquals(true, broker.Is_ValidOwnerEmail__c, 'Valid Owner Email validation failed for: ' + broker.Id);
            System.assertEquals(true, broker.Is_ValidAccountEmail__c, 'Valid Account Email validation failed for: ' + broker.Id);
        }
    }
    
    @isTest
    static void testBrokerInvalidEmails() {
        List<Broker_Registration__c> beforeBatch = [SELECT Id, Is_ValidEmail__c FROM Broker_Registration__c WHERE Is_ValidEmail__c = false];
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Nice_EmailValidationMock(false,false));

        Nice_BR_EmailValidationBatch batchJob = new Nice_BR_EmailValidationBatch();
        Database.executeBatch(batchJob, beforeBatch.size());

        Test.stopTest();

        List<Broker_Registration__c> updatedBrokers = [SELECT Id, Is_ValidEmail__c, Is_ValidOwnerEmail__c, Is_ValidAccountEmail__c FROM Broker_Registration__c];

        for (Broker_Registration__c broker : updatedBrokers) {
            System.assertEquals(false, broker.Is_ValidEmail__c, 'Valid Email validation failed for: ' + broker.Id);
            System.assertEquals(false, broker.Is_ValidOwnerEmail__c, 'Valid Owner Email validation failed for: ' + broker.Id);
            System.assertEquals(false, broker.Is_ValidAccountEmail__c, 'Valid Account Email validation failed for: ' + broker.Id);
        }
    }
}