force-app/main/default/objects/Account/fields/Alternate_Email__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email__c</fullName>
    <label>Alternate Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fourth_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Fourth_Mobile__c</fullName>
    <label>Fourth Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fourth_Mobile_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Fourth_Mobile_Country_Code__c</fullName>
    <label>Fourth Mobile Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_With_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Fourth_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Fourth_Mobile_Number__c</fullName>
    <label>Fourth Mobile Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fourth_Mobile_Number_E__c.field-meta.xml
<CustomField>
    <fullName>Fourth_Mobile_Number_E__c</fullName>
    <label>Fourth Mobile Number (E)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Fourth_Mobile_Number_M__c.field-meta.xml
<CustomField>
    <fullName>Fourth_Mobile_Number_M__c</fullName>
    <label>Fourth Mobile Number (M)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Email_E__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_E__c</fullName>
    <label>Primary Email (E)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Email_M__c.field-meta.xml
<CustomField>
    <fullName>Primary_Email_M__c</fullName>
    <label>Primary Email (M)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Primary_Mobile__c</fullName>
    <label>Primary Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Mobile_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Primary_Mobile_Country_Code__c</fullName>
    <label>Primary Mobile Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_With_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Mobile_Number__c</fullName>
    <label>Primary Mobile Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Mobile_Number_E__c.field-meta.xml
<CustomField>
    <fullName>Primary_Mobile_Number_E__c</fullName>
    <label>Primary Mobile Number (E)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_Mobile_Number_M__c.field-meta.xml
<CustomField>
    <fullName>Primary_Mobile_Number_M__c</fullName>
    <label>Primary Mobile Number (M)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_POA_Email__c.field-meta.xml
<CustomField>
    <fullName>Primary_POA_Email__c</fullName>
    <label>Primary POA Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_POA_Email_E__c.field-meta.xml
<CustomField>
    <fullName>Primary_POA_Email_E__c</fullName>
    <label>Primary POA Email (E)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_POA_Email_M__c.field-meta.xml
<CustomField>
    <fullName>Primary_POA_Email_M__c</fullName>
    <label>Primary POA Email (M)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_POA_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Primary_POA_Mobile__c</fullName>
    <label>Primary POA Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_POA_Mobile_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Primary_POA_Mobile_Country_Code__c</fullName>
    <label>Primary POA Mobile Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_With_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_POA_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_POA_Mobile_Number__c</fullName>
    <label>Primary POA Mobile Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_POA_Mobile_Number_E__c.field-meta.xml
<CustomField>
    <fullName>Primary_POA_Mobile_Number_E__c</fullName>
    <label>Primary POA Mobile Number (E)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Primary_POA_Mobile_Number_M__c.field-meta.xml
<CustomField>
    <fullName>Primary_POA_Mobile_Number_M__c</fullName>
    <label>Primary POA Mobile Number (M)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Mobile_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Mobile_Country_Code__c</fullName>
    <label>Secondary Mobile Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_With_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Mobile_Number__c</fullName>
    <label>Secondary Mobile Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_Mobile_Number_E__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Mobile_Number_E__c</fullName>
    <label>Secondary Mobile Number (E)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_POA_Email__c.field-meta.xml
<CustomField>
    <fullName>Secondary_POA_Email__c</fullName>
    <label>Secondary POA Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_POA_Email_E__c.field-meta.xml
<CustomField>
    <fullName>Secondary_POA_Email_E__c</fullName>
    <label>Secondary POA Email (E)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_POA_Email_M__c.field-meta.xml
<CustomField>
    <fullName>Secondary_POA_Email_M__c</fullName>
    <label>Secondary POA Email (M)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_POA_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Secondary_POA_Mobile__c</fullName>
    <label>Secondary POA Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_POA_Mobile_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Secondary_POA_Mobile_Country_Code__c</fullName>
    <label>Secondary POA Mobile Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_With_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_POA_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Secondary_POA_Mobile_Number__c</fullName>
    <label>Secondary POA Mobile Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_POA_Mobile_Number_E__c.field-meta.xml
<CustomField>
    <fullName>Secondary_POA_Mobile_Number_E__c</fullName>
    <label>Secondary POA Mobile Number (E)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Secondary_POA_Mobile_Number_M__c.field-meta.xml
<CustomField>
    <fullName>Secondary_POA_Mobile_Number_M__c</fullName>
    <label>Secondary POA Mobile Number (M)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tertiary_Mobile__c.field-meta.xml
<CustomField>
    <fullName>Tertiary_Mobile__c</fullName>
    <label>Tertiary Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tertiary_Mobile_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Tertiary_Mobile_Country_Code__c</fullName>
    <label>Tertiary Mobile Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Country_With_Codes</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Tertiary_Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Tertiary_Mobile_Number__c</fullName>
    <label>Tertiary Mobile Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tertiary_Mobile_Number_E__c.field-meta.xml
<CustomField>
    <fullName>Tertiary_Mobile_Number_E__c</fullName>
    <label>Tertiary Mobile Number (E)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/Tertiary_Mobile_Number_M__c.field-meta.xml
<CustomField>
    <fullName>Tertiary_Mobile_Number_M__c</fullName>
    <label>Tertiary Mobile Number (M)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/AccountTriggerHandler.cls
public class AccountTriggerHandler {
    
    public static Boolean isRecordUpdated = false;
    public static void updateChildRecordsCustomerUniqueIds(List<Account> lstAccount, Map<Id,Account> oldMapAccounts){
        Set<Id> accountIds = new Set<Id>();
        
        System.debug('Unique Id DEBUG account >'+lstAccount[0].Unique_Customer_ID__c);
        System.debug('Unique Id DEBUG old map account >'+oldMapAccounts.get(lstAccount[0].Id).Unique_Customer_ID__c);
        for(Account accRecord : lstAccount) {
            //if( (!String.isEmpty(accRecord.Unique_Customer_ID__c)) && oldMapAccounts.get(accRecord.Id).Unique_Customer_ID__c == NULL) {
            if(!String.isEmpty(accRecord.Unique_Customer_ID__c)) {
                accountIds.add(accRecord.Id);
            }
        }
        
        System.debug('Unique Id DEBUG count of account -> calling future method :-'+accountIds);
        if(accountIds.size() > 0 && !System.isBatch()) {
            
            AccountUpdateChildUniqueId.updateUniqueId(accountIds, false);
        }
    }
    
    /******************************************************************************************************************
    Method : processAccountFieldsBeforeSave
    Purpose : NICE - Apex class handler method for before insert, encrypts mobile numbers & emails if they are provided.
    Author : Artee Varma
    Date : 17-01-2025
    ******************************************************************************************************************/
    
    public static void processAccountFieldsBeforeSave(List<Account> newRecords) {        
        for (Account acc : newRecords) {
            //for primary mobile
            if (!String.isBlank(acc.Primary_Mobile_Country_Code__c) && !String.isBlank(acc.Primary_Mobile__c)) {
                String phoneNumber = acc.Primary_Mobile__c;
                if (phoneNumber.startsWith('0')) {
                    phoneNumber = phoneNumber.substringAfter('0');
                } 
                else if (phoneNumber.startsWith('+') && !String.isBlank(acc.Primary_Mobile_Country_Code__c)) {
                    phoneNumber = phoneNumber.substring(acc.Primary_Mobile_Country_Code__c.length()); 
                } 
                else {
                    phoneNumber = phoneNumber;
                }   
                acc.Primary_Mobile_Number__c = acc.Primary_Mobile_Country_Code__c + phoneNumber;
                acc.Primary_Mobile_Number_M__c = Nice_FieldMaskingUtility.maskPhoneNumber(acc.Primary_Mobile_Number__c);
                acc.Primary_Mobile_Number_E__c = Nice_AesEncryptionUtility.encryptMobile(acc.Primary_Mobile_Number__c);
            }
            //for secondary mobile
            if (!String.isBlank(acc.Secondary_Mobile_Country_Code__c) && !String.isBlank(acc.Secondary_Mobile__c)) {
                String secondaryMobile = acc.Secondary_Mobile__c;
                if (secondaryMobile.startsWith('0')) {
                    secondaryMobile = secondaryMobile.substringAfter('0');
                } 
                else if (secondaryMobile.startsWith('+') && !String.isBlank(acc.Secondary_Mobile_Country_Code__c)) {
                    secondaryMobile = secondaryMobile.substring(acc.Secondary_Mobile_Country_Code__c.length()); 
                } 
                else {
                    secondaryMobile = secondaryMobile;
                } 
                acc.Secondary_Mobile_Number__c = acc.Secondary_Mobile_Country_Code__c + secondaryMobile;
                acc.Secondary_Mobile_Number_M__c = Nice_FieldMaskingUtility.maskPhoneNumber(acc.Secondary_Mobile_Number__c);
                acc.Secondary_Mobile_Number_E__c = Nice_AesEncryptionUtility.encryptMobile(acc.Secondary_Mobile_Number__c);
            }
            //for tertiary mobile
            if (!String.isBlank(acc.Tertiary_Mobile_Country_Code__c) && !String.isBlank(acc.Tertiary_Mobile__c)) {
                String tertiaryPhone = acc.Tertiary_Mobile__c;
                if (tertiaryPhone.startsWith('0')) {
                    tertiaryPhone = tertiaryPhone.substringAfter('0');
                } 
                else if (tertiaryPhone.startsWith('+') && !String.isBlank(acc.Tertiary_Mobile_Country_Code__c)) {
                    tertiaryPhone = tertiaryPhone.substring(acc.Tertiary_Mobile_Country_Code__c.length()); 
                } 
                else {
                    tertiaryPhone = tertiaryPhone;
                } 
                acc.Tertiary_Mobile_Number__c = acc.Tertiary_Mobile_Country_Code__c + tertiaryPhone;
                acc.Tertiary_Mobile_Number_M__c = Nice_FieldMaskingUtility.maskPhoneNumber(acc.Tertiary_Mobile_Number__c);
                acc.Tertiary_Mobile_Number_E__c = Nice_AesEncryptionUtility.encryptMobile(acc.Tertiary_Mobile_Number__c);
            }
            //for fourth mobile
            if (!String.isBlank(acc.Fourth_Mobile_Country_Code__c) && !String.isBlank(acc.Fourth_Mobile__c)) {
                String fourthPhone = acc.Fourth_Mobile__c;
                if (fourthPhone.startsWith('0')) {
                    fourthPhone = fourthPhone.substringAfter('0');
                } 
                else if (fourthPhone.startsWith('+') && !String.isBlank(acc.Fourth_Mobile_Country_Code__c)) {
                    fourthPhone = fourthPhone.substring(acc.Fourth_Mobile_Country_Code__c.length()); 
                } 
                else {
                    fourthPhone = fourthPhone;
                }
                acc.Fourth_Mobile_Number__c = acc.Fourth_Mobile_Country_Code__c + fourthPhone;
                acc.Fourth_Mobile_Number_M__c = Nice_FieldMaskingUtility.maskPhoneNumber(acc.Fourth_Mobile_Number__c);
                acc.Fourth_Mobile_Number_E__c = Nice_AesEncryptionUtility.encryptMobile(acc.Fourth_Mobile_Number__c);
            }
            //for poa1 mobile
            if (!String.isBlank(acc.Primary_POA_Mobile_Country_Code__c) && !String.isBlank(acc.Primary_POA_Mobile__c)) {
                String poa1Phone = acc.Primary_POA_Mobile__c;
                if (poa1Phone.startsWith('0')) {
                    poa1Phone = poa1Phone.substringAfter('0');
                } 
                else if (poa1Phone.startsWith('+') && !String.isBlank(acc.Primary_POA_Mobile_Country_Code__c)) {
                    poa1Phone = poa1Phone.substring(acc.Primary_POA_Mobile_Country_Code__c.length()); 
                } 
                else {
                    poa1Phone = poa1Phone;
                }
                acc.Primary_POA_Mobile_Number__c = acc.Primary_POA_Mobile_Country_Code__c + poa1Phone;
                acc.Primary_POA_Mobile_Number_M__c = Nice_FieldMaskingUtility.maskPhoneNumber(acc.Primary_POA_Mobile_Number__c);
                acc.Primary_POA_Mobile_Number_E__c = Nice_AesEncryptionUtility.encryptMobile(acc.Primary_POA_Mobile_Number__c);
            }
            //for poa2 mobile
            if (!String.isBlank(acc.Secondary_POA_Mobile_Country_Code__c) && !String.isBlank(acc.Secondary_POA_Mobile__c)) {
                String poa2Phone = acc.Secondary_POA_Mobile__c;
                if (poa2Phone.startsWith('0')) {
                    poa2Phone = poa2Phone.substringAfter('0');
                } 
                else if (poa2Phone.startsWith('+') && !String.isBlank(acc.Secondary_POA_Mobile_Country_Code__c)) {
                    poa2Phone = poa2Phone.substring(acc.Secondary_POA_Mobile_Country_Code__c.length()); 
                } 
                else {
                    poa2Phone = poa2Phone;
                }
                acc.Secondary_POA_Mobile_Number__c = acc.Secondary_POA_Mobile_Country_Code__c + poa2Phone;
                acc.Secondary_POA_Mobile_Number_M__c = Nice_FieldMaskingUtility.maskPhoneNumber(acc.Secondary_POA_Mobile_Number__c);
                acc.Secondary_POA_Mobile_Number_E__c = Nice_AesEncryptionUtility.encryptMobile(acc.Secondary_POA_Mobile_Number__c);
            }
            //for primary email
            if (!String.isBlank(acc.Alternate_Email__c)) {
                acc.Secondary_Email_M__c = Nice_FieldMaskingUtility.maskEmail(acc.Alternate_Email__c);
                acc.Secondary_Email_E__c = Nice_AesEncryptionUtility.encryptEmail(acc.Alternate_Email__c);
            }
            //for secondary email
            if (!String.isBlank(acc.PersonEmail)) {
                acc.Primary_Email_M__c = Nice_FieldMaskingUtility.maskEmail(acc.PersonEmail);
                acc.Primary_Email_E__c = Nice_AesEncryptionUtility.encryptEmail(acc.PersonEmail);
            }
            //for poa1 email
            if (!String.isBlank(acc.Primary_POA_Email__c)) {
                acc.Primary_POA_Email_M__c = Nice_FieldMaskingUtility.maskEmail(acc.Primary_POA_Email__c);
                acc.Primary_POA_Email_E__c = Nice_AesEncryptionUtility.encryptEmail(acc.Primary_POA_Email__c);
            }
            //for poa2 email
            if (!String.isBlank(acc.Secondary_POA_Email__c)) {
                acc.Secondary_POA_Email_M__c = Nice_FieldMaskingUtility.maskEmail(acc.Secondary_POA_Email__c);
                acc.Secondary_POA_Email_E__c = Nice_AesEncryptionUtility.encryptEmail(acc.Secondary_POA_Email__c);
            }
        }
    }
    
    /******************************************************************************************************************
    Method : processAccountFieldsBeforeUpdate
    Purpose : NICE - Apex class handler method for before update, encrypts mobile numbers & emails if they are provided.
    Author : Artee Varma
    Date : 17-01-2025
    ******************************************************************************************************************/
    
    public static void processAccountFieldsBeforeUpdate(Map<Id, Account> newMap, Map<Id, Account> oldMap) {
        List<Account> accountToEncrypt = new List<Account>();
        
        for (Account acc : newMap.values()) {
            Boolean isPrimaryMobileChanged = oldMap == null || acc.Primary_Mobile__c != oldMap.get(acc.Id)?.Primary_Mobile__c;
            Boolean isPrimaryMobileCountryChanged = oldMap == null || acc.Primary_Mobile_Country_Code__c != oldMap.get(acc.Id)?.Primary_Mobile_Country_Code__c;
            Boolean isSecondaryMobileChanged = oldMap == null || acc.Secondary_Mobile__c != oldMap.get(acc.Id)?.Secondary_Mobile__c;
            Boolean isSecondaryMobileCountryChanged = oldMap == null || acc.Secondary_Mobile_Country_Code__c != oldMap.get(acc.Id)?.Secondary_Mobile_Country_Code__c;
            Boolean isTertiaryNumberChanged = oldMap == null || acc.Tertiary_Mobile_Number__c != oldMap.get(acc.Id)?.Tertiary_Mobile_Number__c;
            Boolean isTertiaryCountryChanged = oldMap == null || acc.Tertiary_Mobile_Country_Code__c != oldMap.get(acc.Id)?.Tertiary_Mobile_Country_Code__c;
            Boolean isFourthNumberChanged = oldMap == null || acc.Fourth_Mobile__c != oldMap.get(acc.Id)?.Fourth_Mobile__c;
            Boolean isFourthCountryChanged = oldMap == null || acc.Fourth_Mobile_Country_Code__c != oldMap.get(acc.Id)?.Fourth_Mobile_Country_Code__c;
            Boolean isPOA1NumberChanged = oldMap == null || acc.Primary_POA_Mobile__c != oldMap.get(acc.Id)?.Primary_POA_Mobile__c;
            Boolean isPOA1CountryChanged = oldMap == null || acc.Primary_POA_Mobile_Country_Code__c != oldMap.get(acc.Id)?.Primary_POA_Mobile_Country_Code__c;
            Boolean isPOA2NumberChanged = oldMap == null || acc.Secondary_POA_Mobile__c != oldMap.get(acc.Id)?.Secondary_POA_Mobile__c;
            Boolean isPOA2CountryChanged = oldMap == null || acc.Secondary_POA_Mobile_Country_Code__c != oldMap.get(acc.Id)?.Secondary_POA_Mobile_Country_Code__c;
            Boolean isPrimaryEmailChanged = oldMap == null || acc.PersonEmail != oldMap.get(acc.Id)?.PersonEmail;
            Boolean isSecondaryEmailChanged = oldMap == null || acc.Alternate_Email__c != oldMap.get(acc.Id)?.Alternate_Email__c;
            Boolean isPOA1EmailChanged = oldMap == null || acc.Primary_POA_Email__c != oldMap.get(acc.Id)?.Primary_POA_Email__c;
            Boolean isPOA2EmailChanged = oldMap == null || acc.Secondary_POA_Email__c != oldMap.get(acc.Id)?.Secondary_POA_Email__c;
            
            // for primary mobile number
            // Either primary mobile number is blank or changes in mobile/country code and not matching existing Primary_Mobile_Number__c
            Boolean shouldUpdatePrimaryMobile = String.isBlank(acc.Primary_Mobile_Number__c) ||
                (isPrimaryMobileChanged || isPrimaryMobileCountryChanged) &&
                acc.Primary_Mobile_Number__c != (acc.Primary_Mobile_Country_Code__c + acc.Primary_Mobile__c);
            
            System.debug('shouldUpdatePrimaryMobile==> ' + shouldUpdatePrimaryMobile);
            
            if (shouldUpdatePrimaryMobile && !String.isBlank(acc.Primary_Mobile__c)) {
                String primaryNumber = acc.Primary_Mobile__c;
                if (primaryNumber.startsWith('0')) {
                    primaryNumber = primaryNumber.substringAfter('0');
                } 
                else if (primaryNumber.startsWith('+') && !String.isBlank(acc.Primary_Mobile_Country_Code__c)) {
                    primaryNumber = primaryNumber.substring(acc.Primary_Mobile_Country_Code__c.length()); 
                } 
                else {
                    primaryNumber = primaryNumber;
                }   
                acc.Primary_Mobile_Number__c = acc.Primary_Mobile_Country_Code__c + primaryNumber;
                acc.Primary_Mobile_Number_M__c = Nice_FieldMaskingUtility.maskPhoneNumber(acc.Primary_Mobile_Number__c);
                acc.Primary_Mobile_Number_E__c = Nice_AesEncryptionUtility.encryptMobile(acc.Primary_Mobile_Number__c);
            }
            
            // for secondary mobile number
            // Either secondary mobile number is blank or changes in mobile/country code and not matching existing Secondary_Mobile_Number__c
            Boolean shouldUpdateSecondaryMobile = String.isBlank(acc.Secondary_Mobile_Number__c) ||
                (isSecondaryMobileChanged || isSecondaryMobileCountryChanged) &&
                acc.Secondary_Mobile_Number__c != (acc.Secondary_Mobile_Country_Code__c + acc.Secondary_Mobile__c);
            
            System.debug('shouldUpdateSecondaryMobile==> ' + shouldUpdateSecondaryMobile);
            
            if (shouldUpdateSecondaryMobile && !String.isBlank(acc.Secondary_Mobile__c)) {
                String secondaryMobile = acc.Secondary_Mobile__c;
                if (secondaryMobile.startsWith('0')) {
                    secondaryMobile = secondaryMobile.substringAfter('0');
                } 
                else if (secondaryMobile.startsWith('+') && !String.isBlank(acc.Secondary_Mobile_Country_Code__c)) {
                    secondaryMobile = secondaryMobile.substring(acc.Secondary_Mobile_Country_Code__c.length()); 
                } 
                else {
                    secondaryMobile = secondaryMobile;
                } 
                acc.Secondary_Mobile_Number__c = acc.Secondary_Mobile_Country_Code__c + secondaryMobile;
                acc.Secondary_Mobile_Number_M__c = Nice_FieldMaskingUtility.maskPhoneNumber(acc.Secondary_Mobile_Number__c);
                acc.Secondary_Mobile_Number_E__c = Nice_AesEncryptionUtility.encryptMobile(acc.Secondary_Mobile_Number__c);
            }
            
            // for tertiary mobile number
            // Either tertiary Mobile is blank or changes in mobile/country code and not matching existing Tertiary_Mobile_Number__c
            Boolean shouldUpdateTertiaryMobile = String.isBlank(acc.Tertiary_Mobile_Number__c) ||
                (isTertiaryNumberChanged || isTertiaryCountryChanged) &&
                acc.Tertiary_Mobile_Number__c != (acc.Tertiary_Mobile_Country_Code__c + acc.Tertiary_Mobile__c);
            
            System.debug('shouldUpdateTertiaryMobile==> ' + shouldUpdateTertiaryMobile);
            
            if (shouldUpdateTertiaryMobile && !String.isBlank(acc.Tertiary_Mobile__c)) {
                String tertiaryPhone = acc.Tertiary_Mobile__c;
                if (tertiaryPhone.startsWith('0')) {
                    tertiaryPhone = tertiaryPhone.substringAfter('0');
                } 
                else if (tertiaryPhone.startsWith('+') && !String.isBlank(acc.Tertiary_Mobile_Country_Code__c)) {
                    tertiaryPhone = tertiaryPhone.substring(acc.Tertiary_Mobile_Country_Code__c.length()); 
                } 
                else {
                    tertiaryPhone = tertiaryPhone;
                } 
                acc.Tertiary_Mobile_Number__c = acc.Tertiary_Mobile_Country_Code__c + tertiaryPhone;
                acc.Tertiary_Mobile_Number_M__c = Nice_FieldMaskingUtility.maskPhoneNumber(acc.Tertiary_Mobile_Number__c);
                acc.Tertiary_Mobile_Number_E__c = Nice_AesEncryptionUtility.encryptMobile(acc.Tertiary_Mobile_Number__c);
            }
            
            // for fourth mobile number
            // Either fourth Mobile is blank or changes in mobile/country code and not matching existing Fourth_Mobile_Number__c
            Boolean shouldUpdateFourthMobile = String.isBlank(acc.Fourth_Mobile_Number__c) ||
                (isFourthNumberChanged || isFourthCountryChanged) &&
                acc.Fourth_Mobile_Number__c != (acc.Fourth_Mobile_Country_Code__c + acc.Fourth_Mobile__c);
            
            System.debug('shouldUpdateFourthMobile==> ' + shouldUpdateFourthMobile);
            
            if (shouldUpdateFourthMobile && !String.isBlank(acc.Fourth_Mobile__c)) {
                String fourthPhone = acc.Fourth_Mobile__c;
                if (fourthPhone.startsWith('0')) {
                    fourthPhone = fourthPhone.substringAfter('0');
                } 
                else if (fourthPhone.startsWith('+') && !String.isBlank(acc.Fourth_Mobile_Country_Code__c)) {
                    fourthPhone = fourthPhone.substring(acc.Fourth_Mobile_Country_Code__c.length()); 
                } 
                else {
                    fourthPhone = fourthPhone;
                }
                acc.Fourth_Mobile_Number__c = acc.Fourth_Mobile_Country_Code__c + fourthPhone;
                acc.Fourth_Mobile_Number_M__c = Nice_FieldMaskingUtility.maskPhoneNumber(acc.Fourth_Mobile_Number__c);
                acc.Fourth_Mobile_Number_E__c = Nice_AesEncryptionUtility.encryptMobile(acc.Fourth_Mobile_Number__c);
            } 
            
            // for poa1 mobile number
            // Either poa1 Mobile is blank or changes in mobile/country code and not matching existing POA_1_Mobile_Number__c
            Boolean shouldUpdatePOA1Mobile = String.isBlank(acc.Primary_POA_Mobile_Number__c) ||
                (isPOA1NumberChanged || isPOA1CountryChanged) &&
                acc.Primary_POA_Mobile_Number__c != (acc.Primary_POA_Mobile_Country_Code__c + acc.Primary_POA_Mobile__c);
            
            System.debug('shouldUpdatePrimaryPOAMobile==> ' + shouldUpdatePOA1Mobile);
            
            if (shouldUpdatePOA1Mobile && !String.isBlank(acc.Primary_POA_Mobile__c)) {
                String poa1Phone = acc.Primary_POA_Mobile__c;
                if (poa1Phone.startsWith('0')) {
                    poa1Phone = poa1Phone.substringAfter('0');
                } 
                else if (poa1Phone.startsWith('+') && !String.isBlank(acc.Primary_POA_Mobile_Country_Code__c)) {
                    poa1Phone = poa1Phone.substring(acc.Primary_POA_Mobile_Country_Code__c.length()); 
                } 
                else {
                    poa1Phone = poa1Phone;
                }
                acc.Primary_POA_Mobile_Number__c = acc.Primary_POA_Mobile_Country_Code__c + poa1Phone;
                acc.Primary_POA_Mobile_Number_M__c = Nice_FieldMaskingUtility.maskPhoneNumber(acc.Primary_POA_Mobile_Number__c);
                acc.Primary_POA_Mobile_Number_E__c = Nice_AesEncryptionUtility.encryptMobile(acc.Primary_POA_Mobile_Number__c);
            } 
            
            // for poa2 mobile number
            // Either poa2 Mobile is blank or changes in mobile/country code and not matching existing POA_2_Mobile_Number__c
            Boolean shouldUpdatePOA2Mobile = String.isBlank(acc.Secondary_POA_Mobile_Number__c) ||
                (isPOA2NumberChanged || isPOA2CountryChanged) &&
                acc.Secondary_POA_Mobile_Number__c != (acc.Secondary_POA_Mobile_Country_Code__c + acc.Secondary_POA_Mobile__c);
            
            System.debug('shouldUpdateSecondaryPOAMobile==> ' + shouldUpdatePOA2Mobile);
            
            if (shouldUpdatePOA2Mobile && !String.isBlank(acc.Secondary_POA_Mobile__c)) {
                String poa2Phone = acc.Secondary_POA_Mobile__c;
                if (poa2Phone.startsWith('0')) {
                    poa2Phone = poa2Phone.substringAfter('0');
                } 
                else if (poa2Phone.startsWith('+') && !String.isBlank(acc.Secondary_POA_Mobile_Country_Code__c)) {
                    poa2Phone = poa2Phone.substring(acc.Secondary_POA_Mobile_Country_Code__c.length()); 
                } 
                else {
                    poa2Phone = poa2Phone;
                }
                acc.Secondary_POA_Mobile_Number__c = acc.Secondary_POA_Mobile_Country_Code__c + poa2Phone;
                acc.Secondary_POA_Mobile_Number_M__c = Nice_FieldMaskingUtility.maskPhoneNumber(acc.Secondary_POA_Mobile_Number__c);
                acc.Secondary_POA_Mobile_Number_E__c = Nice_AesEncryptionUtility.encryptMobile(acc.Secondary_POA_Mobile_Number__c);
            }            
            
            //for primary email
            if (!String.isBlank(acc.PersonEmail) && (isPrimaryEmailChanged || !(isPrimaryEmailChanged))) {
                System.debug('Primary Email Changed///');
                acc.Primary_Email_M__c = Nice_FieldMaskingUtility.maskEmail(acc.PersonEmail);
                acc.Primary_Email_E__c = Nice_AesEncryptionUtility.encryptEmail(acc.PersonEmail);
            }
            
            //for secondary email
            if (!String.isBlank(acc.Alternate_Email__c) && (isSecondaryEmailChanged || !(isSecondaryEmailChanged))) {
                System.debug('Secondary Email Changed///');
                acc.Secondary_Email_M__c = Nice_FieldMaskingUtility.maskEmail(acc.Alternate_Email__c);
                acc.Secondary_Email_E__c = Nice_AesEncryptionUtility.encryptEmail(acc.Alternate_Email__c);
            }
            
            //for poa1 email
            if (!String.isBlank(acc.Primary_POA_Email__c) && (isPOA1EmailChanged || !(isPOA1EmailChanged))) {
                System.debug('Primary POA Email Changed///');
                acc.Primary_POA_Email_M__c = Nice_FieldMaskingUtility.maskEmail(acc.Primary_POA_Email__c);
                acc.Primary_POA_Email_E__c = Nice_AesEncryptionUtility.encryptEmail(acc.Primary_POA_Email__c);
            }
            
            //for poa2 email
            if (!String.isBlank(acc.Secondary_POA_Email__c) && (isPOA2EmailChanged || !(isPOA2EmailChanged))) {
                System.debug('Secondary POA Email Changed///');
                acc.Secondary_POA_Email_M__c = Nice_FieldMaskingUtility.maskEmail(acc.Secondary_POA_Email__c);
                acc.Secondary_POA_Email_E__c = Nice_AesEncryptionUtility.encryptEmail(acc.Secondary_POA_Email__c);
            }
            
            accountToEncrypt.add(acc);
        }
    }
    //added by Artee on 17-01-2025
}