force-app/main/default/objects/Account/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Field_Update_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Update_Type__c</fullName>
    <description>Name Field Update Includes (Name as per passport, Name as per trade license)
Other Field Update Includes (Email ID, phone number, Address, sales manager, sales director)</description>
    <inlineHelpText>Name Field Update Includes (Name as per passport, Name as per trade license)
Other Field Update Includes (Email ID, phone number, Address, sales manager, sales director)</inlineHelpText>
    <label>Field Update Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name Field Update</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <externalId>true</externalId>
    <label>Mobile (Unique Identifier)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Name_as_per_trade_license__c.field-meta.xml
<CustomField>
    <fullName>Name_as_per_trade_license__c</fullName>
    <label>Name as per trade license</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Link_Expiry_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Registration_Link_Expiry_Date_Time__c</fullName>
    <label>Registration Link Expiry Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/Broker_Registration__c.object-meta.xml
<CustomObject>
    <label>Broker Registration</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Registration__c/fields/Field_Update_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Update_Type__c</fullName>
    <description>Name Field Update Includes (Name as per passport, Name as per trade license)
Other Field Update Includes (Email ID, phone number, Address, sales manager, sales director)</description>
    <inlineHelpText>Name Field Update Includes (Name as per passport, Name as per trade license)
Other Field Update Includes (Email ID, phone number, Address, sales manager, sales director)</inlineHelpText>
    <label>Field Update Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name Field Update</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>Company/Individual Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Name_as_per_trade_license__c.field-meta.xml
<CustomField>
    <fullName>Name_as_per_trade_license__c</fullName>
    <label>Name as per trade license</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Registration_Link_Expiry_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Registration_Link_Expiry_Date_Time__c</fullName>
    <label>Registration Link Expiry Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <label>Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CHRM Registration Done</fullName>
                <label>Broker Registration Done</label>
            </value>
            <value>
                <fullName>Rejected - Rejected by CHRM Manager</fullName>
                <label>Rejected by CHRM Manager</label>
            </value>
            <value>
                <fullName>Pending with CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Rejected - Rejected by CHRM OPS</fullName>
                <label>Rejected by CHRM OPS</label>
            </value>
            <value>
                <fullName>Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Rejected by Audit</fullName>
            </value>
            <value>
                <fullName>NOC Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and sent for signature</fullName>
            </value>
            <value>
                <fullName>NOC Is in Process</fullName>
            </value>
            <value>
                <fullName>Agreement - approved by CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Pending with CHRM / Rejected with CHRM</fullName>
            </value>
            <value>
                <fullName>All missing documents uploaded</fullName>
            </value>
            <value>
                <fullName>Approved - Agreement Is in process</fullName>
                <label>Agreement Is in process</label>
            </value>
            <value>
                <fullName>Approved - by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Agreement Generated</fullName>
            </value>
            <value>
                <fullName>Executed Agreement sent to CRHM</fullName>
                <label>Executed Agreement sent to CHRM</label>
            </value>
            <value>
                <fullName>Executed Agreement sent to broker</fullName>
            </value>
            <value>
                <fullName>CP/SC ID in Process</fullName>
                <label>Signed Agreement Received - Documents Awaited</label>
            </value>
            <value>
                <fullName>Pending with CHRM Manager</fullName>
            </value>
            <value>
                <fullName>CP/SC ID Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and send for Review</fullName>
                <label>Agreement created and sent for Review</label>
            </value>
            <value>
                <fullName>Agreement created and sent to witness</fullName>
            </value>
            <value>
                <fullName>Send for Approval</fullName>
                <label>Sent for Final Signatures</label>
            </value>
            <value>
                <fullName>Agreement Executed Manually</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Not Executed - Terminated</fullName>
            </value>
            <value>
                <fullName>Cancelled Agreement - As requested by Broker</fullName>
            </value>
            <value>
                <fullName>Cancelled Agreement- Broker Category Change</fullName>
            </value>
            <value>
                <fullName>Cancelled Agreement- Ownership Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <label>New</label>
</RecordType>

force-app/main/default/objects/Broker_Registration_Approval_Request__c/Broker_Registration_Approval_Request__c.object-meta.xml
<CustomObject>
    <label>Broker Registration Approval Request</label>
    <nameField>
        <displayFormat>BRA-{0000}</displayFormat>
        <label>Broker Registration Approval Request Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Registration Approval Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Registration_Approval_Request__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Registration Approval Request</relationshipLabel>
    <relationshipName>Broker_Registration_Approval_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration_Approval_Request__c/fields/Broker_Registration__c.field-meta.xml
<CustomField>
    <fullName>Broker_Registration__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Registration</label>
    <referenceTo>Broker_Registration__c</referenceTo>
    <relationshipLabel>Broker Registration Approval Request</relationshipLabel>
    <relationshipName>Broker_Registration_Approval_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration_Approval_Request__c/fields/Field_Update_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Update_Type__c</fullName>
    <description>Name Field Update Includes (Name as per passport, Name as per trade license)
Other Field Update Includes (Email ID, phone number, Address, sales manager, sales director)</description>
    <inlineHelpText>Name Field Update Includes (Name as per passport, Name as per trade license)
Other Field Update Includes (Email ID, phone number, Address, sales manager, sales director)</inlineHelpText>
    <label>Field Update Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name Field Update</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration_Approval_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
                <color>#57F17C</color>
                <label>Completed</label>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending With CHRM OPS Manager</fullName>
                <default>true</default>
                <label>Pending With CHRM OPS Manager</label>
            </value>
            <value>
                <fullName>Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM OPS Manager</fullName>
            </value>
            <value>
                <fullName>Rejected by Audit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BrokerRegFieldUpdateReqControllerTest.cls
@isTest
public class BrokerRegFieldUpdateReqControllerTest {
    
    @isTest
    static void testMethod1() {
        Account acc = TestDataFactorySobha.createAccount(null);
        insert acc;
        List<Broker_Registration_Approval_Request__c> insertList = new List<Broker_Registration_Approval_Request__c>();
        
        Broker_Registration_Approval_Request__c testApp = new Broker_Registration_Approval_Request__c(
            Broker_Account__c = acc.Id,
            Label__c = 'Mobile',
            API_Name__c = 'Mobile__c',
            Old_Value__c = '2345',
            New_Value__c = '1111',
            Status__c = 'Pending with CHRM OPS Manager',
            Field_Update_Type__c = 'Other'

        );
        insertList.add(testApp);
        insert insertList;
        Test.startTest();
        BrokerRegFieldUpdateReqController.getCustomeMetadatConfig('test');
                BrokerRegFieldUpdateReqController.getCustomeMetadatConfigAcc('test');

        testApp.Status__c = 'Completed';
        update testApp;
        Test.stopTest();
    }
    
    @isTest
    static void testMethod2() {
        Account acc = TestDataFactorySobha.createAccount(null);
        insert acc;
        Broker_Registration_Approval_Request__c testApp = new Broker_Registration_Approval_Request__c(
            Label__c = 'Mobile',
            API_Name__c = 'Mobile__c',
            Old_Value__c = '2345',
            New_Value__c = '1111',
            Status__c = 'Pending with CHRM OPS Manager',
            Field_Update_Type__c = 'Other',
            Broker_Account__c = acc.Id
        );
        insert testApp;
        
        Test.startTest();
        testApp.Status__c = 'Completed';
        update testApp;
        Test.stopTest();
    }

      @isTest
    static void testMethod3() {
           Broker_Registration__c testbroker = new Broker_Registration__c(
            First_Name__c = 'Existing',
            Last_Name__c = 'Broker',
            Email__c = 'existing@example.com',
            Mobile__c = '1234567890',
            Name_as_per_trade_license__c = 'Test Trade License',
            Registration_Number__c = '123456',Registration_Link_Expiry_Date_Time__c=System.now(),
            Broker_Category__c = 'Broker - RERA',
            Status__c = 'CP/SC ID in Process',
            Mandatory_Documents_Missing__c = true,
            Agreement_Created_Sent_Date__c = Date.today().addDays(-3),
            CHRM_Manager__c = userinfo.getuserId()
        );
        insert testbroker;
                BrokerRegFieldUpdateReqController.getAccountId(testBroker.id);

        Account acc = TestDataFactorySobha.createAccount(null);
        insert acc;
        List<Broker_Registration_Approval_Request__c> lst = new List<Broker_Registration_Approval_Request__c>();
        Broker_Registration_Approval_Request__c testApp = new Broker_Registration_Approval_Request__c(
            Label__c = 'Mobile',
            API_Name__c = 'Mobile__c',
            Old_Value__c = '2345',
            New_Value__c = '1111',
            Status__c = 'Pending with CHRM OPS Manager',
            Field_Update_Type__c = 'Other',
            Broker_Account__c = acc.Id
        );
        lst.add(testApp);
        Test.startTest();
        try {
       BrokerRegFieldUpdateReqController.insertRequestData(lst);
        } catch(Exception e) {
            System.debug(e.getMessage());
        }
        Test.stopTest();
    }
}