force-app/main/default/objects/Account/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CHRM_Ops_Email__c.field-meta.xml
<CustomField>
    <fullName>CHRM_Ops_Email__c</fullName>
    <label>CHRM Ops Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_ID_1__c.field-meta.xml
<CustomField>
    <fullName>Email_ID_1__c</fullName>
    <label>Email ID 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Name_as_per_trade_license__c.field-meta.xml
<CustomField>
    <fullName>Name_as_per_trade_license__c</fullName>
    <label>Name as per trade license</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/Broker_Renewal__c.object-meta.xml
<CustomObject>
    <label>Broker Renewal</label>
    <nameField>
        <displayFormat>BRN-{0000}</displayFormat>
        <label>Broker Renewal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Renewal</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Renewal__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Renewal</relationshipLabel>
    <relationshipName>Broker_Renewal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/fields/Broker_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Broker_Approval_Status__c</fullName>
    <label>Broker Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Broker Registration Done, pending with CHRM Manager</fullName>
            </value>
            <value>
                <fullName>Pending with CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Approved by CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Agreement Created and Sent for Signatures</fullName>
            </value>
            <value>
                <fullName>Signed Agreement Received - Documents Awaiting</fullName>
            </value>
            <value>
                <fullName>All Missing Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>NOC Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh/ Sent for final signatures</fullName>
            </value>
            <value>
                <fullName>Executed Agreement Sent to CHRM</fullName>
            </value>
            <value>
                <fullName>Executed Agreement Sent to Broker</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Broker Registration Done</fullName>
            </value>
            <value>
                <fullName>Broker Empanelment Form Filled</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM Manager</fullName>
            </value>
            <value>
                <fullName>Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Rejected by Audit</fullName>
            </value>
            <value>
                <fullName>NOC Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and sent for signature</fullName>
            </value>
            <value>
                <fullName>NOC Is in Process</fullName>
            </value>
            <value>
                <fullName>Agreement - approved by CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Pending with CHRM / Rejected with CHRM</fullName>
            </value>
            <value>
                <fullName>Agreement Is in process</fullName>
            </value>
            <value>
                <fullName>Approved - by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Agreement Generated</fullName>
            </value>
            <value>
                <fullName>Executed Agreement sent to CRHM</fullName>
            </value>
            <value>
                <fullName>Signed Agreement Received - Documents</fullName>
            </value>
            <value>
                <fullName>Agreement created and send for Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/fields/Email_ID_1__c.field-meta.xml
<CustomField>
    <fullName>Email_ID_1__c</fullName>
    <label>Email ID 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/fields/Name_as_per_trade_license__c.field-meta.xml
<CustomField>
    <fullName>Name_as_per_trade_license__c</fullName>
    <label>Name as per trade license</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Docusign_Result__e/Docusign_Result__e.object-meta.xml
<CustomObject>
    <label>Docusign Result</label>
    <pluralLabel>Docusign Result</pluralLabel>
</CustomObject>

force-app/main/default/objects/Docusign_Result__e/fields/Booking_Id__c.field-meta.xml
<CustomField>
    <fullName>Booking_Id__c</fullName>
    <label>Booking Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Docusign_Result__e/fields/MessageToDisplay__c.field-meta.xml
<CustomField>
    <fullName>MessageToDisplay__c</fullName>
    <label>MessageToDisplay</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Docusign_Settings__mdt/Docusign_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Docusign Settings</label>
    <pluralLabel>Docusign Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Docusign_Settings__mdt/fields/Booking_Form_Expiry_Days__c.field-meta.xml
<CustomField>
    <fullName>Booking_Form_Expiry_Days__c</fullName>
    <label>Booking Form Expiry Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BrokerRenewalAgreementDocusignHandler.cls
/*********************************************************************
 * Class Name  :   BrokerRenewalAgreementDocusignHandler
 * Description :   Helper Class of Flow Send Broker Renewal Agreement for Docusign (Flow)
 * Created Date:   23/05/2024
 * Authored By :   CloudSteer Technology Pte Ltd
 * -------------------------------------------------------------------
 * Version History : 
    Created By       :   Gourav Gour
    Last Modified By :   Gourav Gour 23/05/20024
 *********************************************************************/
public with sharing class BrokerRenewalAgreementDocusignHandler {
    @InvocableMethod
    public static void sendEnvelopeMethod(List<Id> renewId) {
        Id mySourceId = renewId[0];
        forForSigningFuture(mySourceId);
    } 
    @future(callout=true)
    public static void forForSigningFuture(Id mySourceId) {
        try {
            Docusign_Settings__mdt  docusignDefaultSettings = Docusign_Settings__mdt.getInstance('Org_Defaults');
            Map<String,String> emailToRoleMap = new Map<String,String>();
    
            Id myDocumentId = BrokerRenewalAgreementDocusignUtil.getFileId(mySourceId);
            Id myFileId = [SELECT id from ContentVersion where ContentDocumentId =:myDocumentId LIMIT 1].id;
            
            Broker_Renewal__c renewRec = BrokerRenewalAgreementDocusignUtil.getBrokerRenwal(mySourceId);

            Integer i=1;
            Decimal scaleValue;
            Integer yOffset;
            scaleValue = 1.0;
            yOffset = 5;

            //Pass the booking record id
            dfsle.Envelope myEnvelope = dfsle.EnvelopeService.getEmptyEnvelope(new dfsle.Entity(mySourceId));
        
            // Add document to the envelope
            myEnvelope = myEnvelope.withDocuments(dfsle.DocumentService.getDocuments(ContentVersion.getSObjectType(), new Set<Id> { myFileId }));
        
            List<dfsle.Recipient> recipientList = new List<dfsle.Recipient>();
            
            //CHRM_Ops Team - part 1 Added By Gourav Gour 31/05/2024
            String chrmopsSub = 'Broker Renewal Agreement Approval - '+renewRec.Name_as_per_trade_license__c ;
            
            String chrmopsBody = BrokerRenewalAgreementDocusignUtil.getCHRMOpsBody(renewRec.Name_as_per_trade_license__c);
            dfsle.Recipient.EmailSettings chrmopsEmailSetting = new dfsle.Recipient.EmailSettings('en',
                                                                                                'English',
                                                                                                chrmopsSub,
                                                                                                chrmopsBody);

            
            String chrmopsTeamApproveAnchor = 'chrmopsteamapprove';
            String chrmopsTeamDeclineAnchor = 'chrmopsteamdecline';
            dfsle.Tab chrmopsTeamApproveTab = new dfsle.ApproveTab()
                                                        .withAnchor(new dfsle.Tab.Anchor(
                                                            chrmopsTeamApproveAnchor, // Anchor string
                                                            false, // Do not allow white space in anchor string
                                                            false, // Anchor string is not case sensitive
                                                            'left', // Horizontal alignment in relation to the anchor text
                                                            true, // Ignore if the anchor text is not present in the document
                                                            true, // Must match the value of the anchor string in its entirety
                                                            'pixels', // Unit of the x and y offset properties
                                                            0, // X offset
                                                            20)); // Y offset
            dfsle.Tab chrmopsTeamDeclineTab = new dfsle.DeclineTab()
                                                        .withAnchor(new dfsle.Tab.Anchor(
                                                            chrmopsTeamDeclineAnchor, // Anchor string
                                                            false, // Do not allow white space in anchor string
                                                            false, // Anchor string is not case sensitive
                                                            'left', // Horizontal alignment in relation to the anchor text
                                                            true, // Ignore if the anchor text is not present in the document
                                                            true, // Must match the value of the anchor string in its entirety
                                                            'pixels', // Unit of the x and y offset properties
                                                            0, // X offset
                                                            20)); // Y offset
            String chrmOpsEmail = String.valueOf(renewRec.Broker_Account__r.CHRM_Ops_Email__c);                                             
            emailToRoleMap.put(chrmOpsEmail+'_'+i,'chrmops Team'); 
            i=i+1;
            dfsle.Recipient chrmopsTeam = dfsle.Recipient.fromSource(
                                                            'chrmops Team',
                                                            chrmOpsEmail,
                                                            null,
                                                            null,
                                                            null)
                                                        .withTabs(new List<dfsle.Tab> {
                                                            chrmopsTeamApproveTab,chrmopsTeamDeclineTab
                                                        })
                                                        .withEmailSettings(chrmopsEmailSetting);
            
            recipientList.add(chrmopsTeam);

            //Broker - part 2
            if(renewRec.Name_as_per_trade_license__c != null && renewRec.Email_ID_1__c != null) {
                emailToRoleMap.put(renewRec.Email_ID_1__c +'_'+i,'Authorised Representative');

                String sub = 'Broker Agreement Form';
                String body = BrokerRenewalAgreementDocusignUtil.docusignEmailBody(renewRec);

                dfsle.Recipient.EmailSettings applicantEmailSetting = new dfsle.Recipient.EmailSettings('en',
                                                                                                        'English',
                                                                                                        sub,
                                                                                                        body);
    
                String anchorString = 'brokersignsobha';

                List<dfsle.Tab> applicantsTabs = new List<dfsle.Tab>();
                String anchorInitialsString = 'brokerinitialsds';

                dfsle.Tab myInitialHereTab = new dfsle.InitialHereTab()
                                                            .withScale(0.8)
                                                            .withRequired(true) // Signing optional
                                                            .withAnchor(new dfsle.Tab.Anchor(
                                                                anchorInitialsString, // Anchor string
                                                                false, // Do not allow white space in anchor string
                                                                false, // Anchor string is not case sensitive
                                                                'left', // Horizontal alignment in relation to the anchor text
                                                                true, // Ignore if the anchor text is not present in the document
                                                                true, // Must match the value of the anchor string in its entirety
                                                                'pixels', // Unit of the x and y offset properties
                                                                0, // X offset
                                                                20)); // Y offset
                
                // Create a Sign Here tab for applicant
                dfsle.Tab mySignHereTab = new dfsle.SignHereTab()
                    .withScale(scaleValue) // 1.5 scale
                    .withRequired(true) // Signing mandatory
                    .withAnchor(new dfsle.Tab.Anchor(
                        anchorString, // Anchor string
                        false, // Do not allow white space in anchor string
                        false, // Anchor string is not case sensitive
                        'left', // Horizontal alignment in relation to the anchor text
                        true, // Ignore if the anchor text is not present in the document
                        true, // Must match the value of the anchor string in its entirety
                        'pixels', // Unit of the x and y offset properties
                        0, // X offset
                        yOffset)); // Y offset 

                applicantsTabs.add(mySignHereTab);
                applicantsTabs.add(myInitialHereTab);

                if (renewRec.Broker_Category__c.containsIgnoreCase('Company')) {
                    dfsle.SignHereTab.Stamp corpAppStamp = new dfsle.SignHereTab.Stamp('stamp',null,null,null,null,null,null,null);      
                    dfsle.Tab corpAppStampTab = new dfsle.SignHereTab().withStamp(corpAppStamp)
                                                .withScale(1.0) // 1.5 scale
                                                .withRequired(true) // Signing mandatory
                                                .withAnchor(new dfsle.Tab.Anchor(
                                                                    'brokerStamp', // Anchor string
                                                                    false, // Do not allow white space in anchor string
                                                                    false, // Anchor string is not case sensitive
                                                                    'left', // Horizontal alignment in relation to the anchor text
                                                                    true, // Ignore if the anchor text is not present in the document
                                                                    true, // Must match the value of the anchor string in its entirety
                                                                    'pixels', // Unit of the x and y offset properties
                                                                    0, // X offset
                                                                    0)
                                                            ); // Y offset

                    applicantsTabs.add(corpAppStampTab);
                }
                dfsle.Recipient myRecipient = dfsle.Recipient.fromSource(
                                                                        renewRec.Name_as_per_trade_license__c,
                                                                        renewRec.Email_ID_1__c,
                                                                        null, 
                                                                        null,
                                                                        null)
                                                                    .withTabs(applicantsTabs)
                                                                    //.withAuthentication(auth)
                                                                    .withEmailSettings(applicantEmailSetting);
                recipientList.add(myRecipient);

                i = i+1;
            }
            Integer expiryDays = Integer.valueOf(docusignDefaultSettings.Booking_Form_Expiry_Days__c);

            dfsle.Notifications expirySettings = new dfsle.Notifications(
                                                                    false, // Indicates that reminders are enabled
                                                                    null, // Number of days to wait before sending a reminder
                                                                    null, // Number of days between reminders
                                                                    true, // Whether or not the envelope expires and is voided
                                                                    expiryDays, // Number of days before the envelope expires
                                                                    null, // Number of days before expiration to remind the recipient
                                                                    false // Placeholder for deprecated field
                                                                ); 
        
            //Add the signers...
            myEnvelope = myEnvelope
                        .withRecipients(recipientList)
                        .withNotifications(expirySettings );
            
            // Send the envelope!
            if(!Test.isRunningTest()) {
                myEnvelope = dfsle.EnvelopeService.sendEnvelope(
                    myEnvelope,
                    true
                );
                
                String envelopeId = String.valueOf(myEnvelope.docuSignId);
                BrokerRenewalAgreementDocusignUtil.docusignPostProcessing(envelopeId, mySourceId, myDocumentId, emailToRoleMap);
                Broker_Renewal__c renew = new Broker_Renewal__c(Id = mySourceId, Broker_Approval_Status__c = 'Agreement created and send for Review');
                update renew;        
            }
            Docusign_Result__e event = new Docusign_Result__e();
            event.MessageToDisplay__c = 'Broker Registration Form sent successfully sent for Docusign.';
            event.Booking_Id__c = mySourceId;
            event.User_Id__c = UserInfo.getUserId();
            EventBus.publish(event);
        } 
        catch (Exception e) {
            Docusign_Result__e event = new Docusign_Result__e();
            event.MessageToDisplay__c = 'Error sending Broker Registration for Docusign - '+e.getMessage();
            event.Booking_Id__c = mySourceId;
            event.User_Id__c = UserInfo.getUserId();
            EventBus.publish(event);
        }
    }
}