force-app/main/default/objects/Account/fields/Broker_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Broker_Sub_Type__c</fullName>
    <label>Broker Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>PropStrength__Broker_Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Broker RERA</fullName>
            </value>
            <value>
                <fullName>Broker UAE</fullName>
            </value>
            <value>
                <fullName>Broker International</fullName>
            </value>
            <value>
                <fullName>Sobha Connect UAE</fullName>
            </value>
            <value>
                <fullName>Sobha Connect International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/PropStrength__Broker_Type__c.field-meta.xml
<CustomField>
    <fullName>PropStrength__Broker_Type__c</fullName>
    <label>Broker Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <label>Channel Partner</label>
            </value>
            <value>
                <fullName>Sobha Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Stand_Lead__c.field-meta.xml
<CustomField>
    <fullName>Stand_Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Stand Lead</label>
    <referenceTo>Stand_Lead__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Stand_Lead__c/Stand_Lead__c.object-meta.xml
<CustomObject>
    <label>Stand Lead</label>
    <nameField>
        <displayFormat>SL-{000000}</displayFormat>
        <label>Lead Stand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>StandLeads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stand_Lead__c/fields/is_deliverable__c.field-meta.xml
<CustomField>
    <fullName>is_deliverable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is deliverable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Nice_SL_EmailValidationBatchTest.cls
/***************************************************************************
Class      : Nice_SL_EmailValidationBatchTest
Purpose    : NICE - Test class for Nice_SL_EmailValidationBatch 
Author     : Abhijeet
*****************************************************************************/

@isTest
public class Nice_SL_EmailValidationBatchTest {

    @testSetup
    static void setupTestData() {
       Account acc = new Account();
        acc.Name = 'Test';
        acc.PropStrength__Broker_Type__c = 'Standard';
        acc.Broker_Sub_Type__c = 'Broker International';
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Broker').getRecordTypeId();
        insert acc;     
       Project__C prj = new Project__C();
       prj.Name = 'Sobha Hartland';
       prj.Project_Code__c = '442';
       insert prj;
        List<Stand_Lead__c> leads = new List<Stand_Lead__c>();
        for (Integer i = 0; i < 1; i++) {
            leads.add(new Stand_Lead__c(
                Last_Name__c = 'Test' +i,
                Email__c = 'tests@example.com' + i,
                is_deliverable__c = false
            ));
        }
        insert leads;
    }
    
    @isTest
    static void testStandValidEmails() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Nice_EmailValidationMock(true,false));
        Nice_SL_EmailValidationBatch batchJob = new Nice_SL_EmailValidationBatch();
        Database.executeBatch(batchJob, 1);
        Test.stopTest();
        List<Stand_Lead__c> updatedLeads = [SELECT Id, is_deliverable__c FROM Stand_Lead__c];
        for (Stand_Lead__c lead : updatedLeads) {
            System.assertEquals(true, lead.is_deliverable__c, 'Email number validation failed for: ' + lead.Id);
        }
    }
    
    @isTest
    static void testStandInvalidEmails() {
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new Nice_EmailValidationMock(true,false));
        Nice_SL_EmailValidationBatch batchJob = new Nice_SL_EmailValidationBatch();
        Database.executeBatch(batchJob, 1);
        Test.stopTest();
        List<Stand_Lead__c> updatedStandLeads = [SELECT Id, is_deliverable__c FROM Stand_Lead__c];
        for (Stand_Lead__c lead : updatedStandLeads) {
            System.assertEquals(false, lead.is_deliverable__c, 'Email number validation failed for: ' + lead.Id);
        }
    }
}