force-app/main/default/objects/Account/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email_ID_1__c.field-meta.xml
<CustomField>
    <fullName>Email_ID_1__c</fullName>
    <label>Email ID 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/PropStrength__Broker_Type__c.field-meta.xml
<CustomField>
    <fullName>PropStrength__Broker_Type__c</fullName>
    <label>Broker Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <label>Channel Partner</label>
            </value>
            <value>
                <fullName>Sobha Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendMailToBroker_test.cls
@isTest
public class SendMailToBroker_test {
    @isTest
    static void SendMailToBrokerMethod() {
        List<Id> accIds = new List<Id>();
        Account acc1 = TestDataFactorySobha.createAccount(null);
        acc1.PropStrength__Broker_Type__c ='Sobha Connect';
        acc1.Broker_Category__c = 'Individual';
        acc1.Name = 'Test 1';
        acc1.Email_Id_1__c = 'Test@Test.com';
        insert acc1;
        accIds.add(acc1.Id);
        Test.startTest();
        SendMailToBroker.sendEmail(accIds);
        Test.stopTest();
    }
}