force-app/main/default/objects/Account/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_ID_1__c.field-meta.xml
<CustomField>
    <fullName>Email_ID_1__c</fullName>
    <label>Email ID 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legacy_Broker_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Broker_Id__c</fullName>
    <label>Legacy Broker Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <externalId>true</externalId>
    <label>Mobile (Unique Identifier)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Name_as_per_trade_license__c.field-meta.xml
<CustomField>
    <fullName>Name_as_per_trade_license__c</fullName>
    <label>Name as per trade license</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SC_Id__c.field-meta.xml
<CustomField>
    <fullName>SC_Id__c</fullName>
    <label>SC Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Meeting_Tracker__c/Broker_Meeting_Tracker__c.object-meta.xml
<CustomObject>
    <label>Broker Meeting Tracker</label>
    <nameField>
        <displayFormat>BMT-{0000}</displayFormat>
        <label>Broker Meeting Tracker</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Meeting Tracker</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Meeting_Tracker__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Meeting Tracker</relationshipLabel>
    <relationshipName>Broker_Meeting_Tracker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Meeting_Tracker__c/fields/Broker_Name__c.field-meta.xml
<CustomField>
    <fullName>Broker_Name__c</fullName>
    <label>Broker Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Meeting_Tracker__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CP ID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Channel_Partner__c.Black_listed_user__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Broker Meeting Tracker</relationshipLabel>
    <relationshipName>Broker_Meeting_Tracker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Meeting_Tracker__c/fields/Meeting_Date__c.field-meta.xml
<CustomField>
    <fullName>Meeting_Date__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Meeting Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Broker_Meeting_Tracker__c/fields/Meeting_organized_by__c.field-meta.xml
<CustomField>
    <fullName>Meeting_organized_by__c</fullName>
    <label>Meeting organized by</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Channel Team Lead</fullName>
            </value>
            <value>
                <fullName>Sales Team</fullName>
            </value>
            <value>
                <fullName>Yourself</fullName>
            </value>
            <value>
                <fullName>CRM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Meeting_Tracker__c/fields/Person_met__c.field-meta.xml
<CustomField>
    <fullName>Person_met__c</fullName>
    <label>Name of the Person met</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Meeting_Tracker__c/fields/Plan_of_Meeting__c.field-meta.xml
<CustomField>
    <fullName>Plan_of_Meeting__c</fullName>
    <label>Plan of Meeting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Introduction</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
            <value>
                <fullName>Follow-Up</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Meeting_Tracker__c/fields/SC_ID__c.field-meta.xml
<CustomField>
    <fullName>SC_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SC ID (Enter FULL NAME as per Passport)</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sobha_Connect__c.Black_listed_user__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Sobha_Connect__c</referenceTo>
    <relationshipLabel>Broker Meeting Tracker</relationshipLabel>
    <relationshipName>Broker_Meeting_Tracker</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/Broker_Registration__c.object-meta.xml
<CustomObject>
    <label>Broker Registration</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Registration__c/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker - RERA</fullName>
            </value>
            <value>
                <fullName>Broker - UAE</fullName>
            </value>
            <value>
                <fullName>Broker - Intnl</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - UAE - Individual</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - Intnl - Individual</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - UAE - Company</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - Intnl - Company</fullName>
            </value>
            <value>
                <fullName>Broker – Intnl</fullName>
                <isActive>false</isActive>
                <label>Broker – Intnl</label>
            </value>
            <value>
                <fullName>Broker – RERA</fullName>
                <isActive>false</isActive>
                <label>Broker – RERA</label>
            </value>
            <value>
                <fullName>Broker – UAE</fullName>
                <isActive>false</isActive>
                <label>Broker – UAE</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl – Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl – Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl – Individual</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl – Individual</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl– Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl– Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – UAE – Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – UAE – Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – UAE – Individual</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – UAE – Individual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/CPID__c.field-meta.xml
<CustomField>
    <fullName>CPID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CPID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Channel_Partner__c.Black_listed_user__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Broker Registrations</relationshipLabel>
    <relationshipName>Broker_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>Company/Individual Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Name_as_per_trade_license__c.field-meta.xml
<CustomField>
    <fullName>Name_as_per_trade_license__c</fullName>
    <label>Name as per trade license</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <label>Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <label>New</label>
</RecordType>

force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Channel_Partners2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Email_ID_1__c.field-meta.xml
<CustomField>
    <fullName>Email_ID_1__c</fullName>
    <label>Email ID 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/PSM_BMT_Broker_Batch_Test.cls
@isTest
public class PSM_BMT_Broker_Batch_Test {
    @isTest
    static void testPSMBMTBrokerBatch() {
       // User u = [select id from user where userrole.name like '%Sales Manager%' limit 1];
        Channel_Partner__c chPartner = new Channel_Partner__c();
        chPartner.Name = 'Test Channel Partner';
        chPartner.Expiry_Date__c = System.today();
      //  chPartner.Channel_Relationship_Manager__c = UserInfo.getUserId();
        chPartner.Email_ID_1__c='test@test.com';
        insert chPartner;
        
        
        Broker_Meeting_Tracker__c bmt = new Broker_Meeting_Tracker__c(Meeting_Date__c = system.today(),Broker_Name__c = 'bTest',
                                                                      Meeting_organized_by__c = 'CRM',
                                                                      Person_met__c = 'Test',Plan_of_Meeting__c= 'Introduction',
                                                                      Channel_Partner__c = chPartner.Id);  

        Insert bmt;
         Broker_Registration__c brReg = new Broker_Registration__c(
            First_Name__c = 'Existing',
            Last_Name__c = 'Broker',
            Email__c = 'existing@example.com',
            Mobile__c = '1234567890',
            Name_as_per_trade_license__c = 'Test Trade License',
            Registration_Number__c = '123456',
            Broker_Category__c = 'Broker - RERA',
             CPID__c = chPartner.Id
        );
       // insert brReg;
       //Account acc = TestDataFactorySobha.createAccount(null);
       
          RecordType brokerRecordType = [SELECT Id FROM RecordType WHERE Name = 'broker' AND SObjectType = 'Account' LIMIT 1];
         Account acc = new Account();
        acc.Name = 'Test Broker Account';
        
        acc.RecordTypeId = brokerRecordType.Id;
         acc.Legacy_Broker_Id__c = chPartner.Id;
        insert acc;
       
        
        Test.startTest();
        PSM_BMT_Broker_Batch batch = new PSM_BMT_Broker_Batch();
        Database.executeBatch(batch);
        Broker_Meeting_Tracker__c bmtrec = [SELECT Id from Broker_Meeting_Tracker__c LIMIT 1];
        List<Id> recordIds=  new List<Id>{bmtrec.Id};
        PSM_BMT_Broker_Batch batch1 = new PSM_BMT_Broker_Batch(recordIds);
        Database.executeBatch(batch1);
        String inputQuery = 'SELECT Id, Channel_Partner__c, SC_ID__c FROM Broker_Meeting_Tracker__c WHERE Broker_Account__c = NULL';
        PSM_BMT_Broker_Batch batch2 = new PSM_BMT_Broker_Batch(inputQuery);
        Database.executeBatch(batch2);
        
        Test.StopTest();
    }
}