force-app/main/default/objects/Account/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Company</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email_ID_1__c.field-meta.xml
<CustomField>
    <fullName>Email_ID_1__c</fullName>
    <label>Email ID 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Field_Update_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Field_Update_Request_Status__c</fullName>
    <label>Field Update Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Pending With CHRM OPS Manager</fullName>
            </value>
            <value>
                <fullName>Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM OPS Manager</fullName>
            </value>
            <value>
                <fullName>Rejected by Audit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Field_Update_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Update_Type__c</fullName>
    <description>Name Field Update Includes (Name as per passport, Name as per trade license)
Other Field Update Includes (Email ID, phone number, Address, sales manager, sales director)</description>
    <inlineHelpText>Name Field Update Includes (Name as per passport, Name as per trade license)
Other Field Update Includes (Email ID, phone number, Address, sales manager, sales director)</inlineHelpText>
    <label>Field Update Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name Field Update</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PropStrength__Broker_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>PropStrength__Broker_Approval_Status__c</fullName>
    <label>Broker Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Broker Registration Done, pending with CHRM Manager</fullName>
                <label>Pending with CHRM Manager</label>
            </value>
            <value>
                <fullName>Pending with CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Approved by CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Agreement Created and Sent for Signatures</fullName>
            </value>
            <value>
                <fullName>Signed Agreement Received - Documents Awaiting</fullName>
            </value>
            <value>
                <fullName>All Missing Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>NOC Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh/ Sent for final signatures</fullName>
                <label>Pending with Ashish Parakh</label>
            </value>
            <value>
                <fullName>Executed Agreement Sent to CHRM</fullName>
            </value>
            <value>
                <fullName>Executed Agreement Sent to Broker</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Broker Registration Done</fullName>
            </value>
            <value>
                <fullName>Broker Empanelment Form Filled</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM Manager</fullName>
            </value>
            <value>
                <fullName>Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh</fullName>
                <label>Pending with Ashish Parakh1</label>
            </value>
            <value>
                <fullName>Rejected by Audit</fullName>
            </value>
            <value>
                <fullName>NOC Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and sent for signature</fullName>
            </value>
            <value>
                <fullName>NOC Is in Process</fullName>
            </value>
            <value>
                <fullName>Agreement - approved by CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Pending with CHRM / Rejected with CHRM</fullName>
            </value>
            <value>
                <fullName>Agreement Is in process</fullName>
            </value>
            <value>
                <fullName>Approved - by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Agreement Generated</fullName>
            </value>
            <value>
                <fullName>Executed Agreement sent to CRHM</fullName>
            </value>
            <value>
                <fullName>Signed Agreement Received - Documents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PropStrength__Broker_Type__c.field-meta.xml
<CustomField>
    <fullName>PropStrength__Broker_Type__c</fullName>
    <label>Broker Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <label>Channel Partner</label>
            </value>
            <value>
                <fullName>Sobha Connect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Send_Policy_Mandate_Letter__c.field-meta.xml
<CustomField>
    <fullName>Send_Policy_Mandate_Letter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Policy Mandate Letter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Account_Approval_History__c/Broker_Account_Approval_History__c.object-meta.xml
<CustomObject>
    <label>Broker Account Approval History</label>
    <nameField>
        <displayFormat>BAA-{0000}</displayFormat>
        <label>Broker Account Approval History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Account Approval Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Account_Approval_History__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Account Approval Histories</relationshipLabel>
    <relationshipName>Broker_Account_Approval_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Account_Approval_History__c/fields/Field_Update_Type__c.field-meta.xml
<CustomField>
    <fullName>Field_Update_Type__c</fullName>
    <label>Field Update Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Name Field Update</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Account_Approval_History__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending With CHRM OPS Manager</fullName>
            </value>
            <value>
                <fullName>Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM OPS Manager</fullName>
            </value>
            <value>
                <fullName>Rejected by Audit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BrokerAccountFieldUpdateReqCont_test.cls
@isTest
public class BrokerAccountFieldUpdateReqCont_test {
    
    @testsetup
    public static void createData() {
        
List<Account> accList = new List<Account>();
        List<Account> accList2 = new List<Account>();
        Account acc1 = TestDataFactorySobha.createAccount(null);
        acc1.PropStrength__Broker_Type__c ='Sobha Connect';
        acc1.Broker_Category__c = 'Individual';
        acc1.Name = 'Test 1';
        acc1.Field_Update_Request_Status__c = 'Pending With CHRM OPS Manager';
        acc1.PropStrength__Broker_Approval_Status__c  = 'Executed Agreement Sent to Broker';
        
        accList.add(acc1);
        Account acc3 = TestDataFactorySobha.createAccount(null);
        acc3.PropStrength__Broker_Type__c ='Sobha Connect';
        acc3.Broker_Category__c = 'Individual';
        acc3.Name = 'Test 2';
        accList2.add(acc3);
        Account acc2 = TestDataFactorySobha.createAccount(null);
        acc2.PropStrength__Broker_Type__c ='Standard';
        acc2.Broker_Category__c = 'Individual';
        acc2.Name = 'Test 3';
        acc2.Field_Update_Request_Status__c = 'Pending With CHRM OPS Manager';
        acc2.PropStrength__Broker_Approval_Status__c  = 'Executed Agreement Sent to Broker';
        accList.add(acc2);
        Account acc4 = TestDataFactorySobha.createAccount(null);
        acc4.PropStrength__Broker_Type__c ='Standard';
        acc4.Broker_Category__c = 'Individual';
        acc4.Name = 'Test 4';
        accList2.add(acc4);
        insert accList;
        Test.startTest();
        insert accList2;
        Broker_Account_Approval_History__c rec = new Broker_Account_Approval_History__c();
        rec.Broker_Account__c = acc2.Id;
        rec.Status__c = 'Pending with Audit';
        insert rec;
        Broker_Account_Approval_History__c rec2 = new Broker_Account_Approval_History__c();
        rec2.Broker_Account__c = acc1.Id;
        rec2.Status__c = 'Pending with Audit';
        insert rec2;
        List<Account> updateList = new List<Account>();
        acc2.Email_Id_1__c = 'Test@Test.com';
        acc2.Send_Policy_Mandate_Letter__c = true;
        acc2.Field_Update_Request_Status__c = 'Pending With CHRM OPS Manager';
        acc1.Email_Id_1__c = 'Test@Test.com';
        acc1.Send_Policy_Mandate_Letter__c = true;
        acc1.PropStrength__Broker_Approval_Status__c = 'Broker Registration Done';
        updateList.add(acc1);
        updateList.add(acc2);
        update updateList;
    }
    
    @isTest
    public static void testGetCustomeMetadatConfig(){
        BrokerAccountFieldUpdateReqController.getCustomeMetadatConfig('Other');
    }
    
	@isTest
    public static void testInsertRequestData(){
        List<Broker_Account_Approval_History__c> insertList = new List<Broker_Account_Approval_History__c>();
        for(Broker_Account_Approval_History__c baah : [select id, Broker_Account__c, Field_Update_Type__c from Broker_Account_Approval_History__c]){
            insertList.add(baah.clone(false, false, false, false));
        }    
        BrokerAccountFieldUpdateReqController.insertRequestData(insertList);              
    }
}