force-app/main/default/objects/Account/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Legacy_Broker_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Broker_Id__c</fullName>
    <label>Legacy Broker Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sobha_Connect__c.field-meta.xml
<CustomField>
    <fullName>Sobha_Connect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sobha Connect</label>
    <referenceTo>Sobha_Connect__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/Broker_Registration__c.object-meta.xml
<CustomObject>
    <label>Broker Registration</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Registration__c/fields/CPID__c.field-meta.xml
<CustomField>
    <fullName>CPID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CPID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Channel_Partner__c.Black_listed_user__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Broker Registrations</relationshipLabel>
    <relationshipName>Broker_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/SCID__c.field-meta.xml
<CustomField>
    <fullName>SCID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SCID</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sobha_Connect__c.Black_listed_user__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Sobha_Connect__c</referenceTo>
    <relationshipLabel>Broker Registrations</relationshipLabel>
    <relationshipName>Broker_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <label>New</label>
</RecordType>

force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/Events__c.object-meta.xml
<CustomObject>
    <label>Events</label>
    <nameField>
        <label>Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Channel_Partner__c.Black_listed_user__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Sobha_Connect__c.field-meta.xml
<CustomField>
    <fullName>Sobha_Connect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sobha Connect</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Sobha_Connect__c.Black_listed_user__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Sobha_Connect__c</referenceTo>
    <relationshipLabel>Events</relationshipLabel>
    <relationshipName>Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/Sobha_Connect__c.object-meta.xml
<CustomObject>
    <label>Sobha Connect</label>
    <nameField>
        <displayFormat>SC - {0000}</displayFormat>
        <label>Sobha Connect Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sobha Connect</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/PSM_ERF_Broker_Batch.cls
/* DESIGNED ONLY FOR BATCH SIZE 1 */
//Test Class - PSM_ERF_Broker_Batch_Test
global class PSM_ERF_Broker_Batch implements Database.Batchable<sObject>, Database.Stateful {

    public static String CLASS_NAME = 'PSM_ERF_Broker_Batch';
    private List<Id> recordIds;
    private String queryParam;
    
    // Constructor to accept record IDs
    public PSM_ERF_Broker_Batch() {
    }

    // Constructor to accept record IDs
    public PSM_ERF_Broker_Batch(List<Id> ids) {
        this.recordIds = ids;
    }
    
    // Constructor to accept query as param
    public PSM_ERF_Broker_Batch(String qParam) {
        this.queryParam = qParam;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //String query = 'SELECT Id, name,Channel_Partner__c, Sobha_Connect__c,Broker_Account__c from events__c where Broker_Account__c = null';
        //return Database.getQueryLocator(query);
        
        String query;
        
        if (recordIds != null && !recordIds.isEmpty()) {
            // Filter based on provided record IDs
            query = 'SELECT Id, Name, Channel_Partner__c, Sobha_Connect__c, Broker_Account__c ' +
                    'FROM Events__c ' +
                    'WHERE Id IN :recordIds';
        } else if(String.isNotEmpty(queryParam)){
            query = queryParam;
        } else {
            // Default behavior if no IDs are provided
            query = 'SELECT Id, Name, Channel_Partner__c, Sobha_Connect__c, Broker_Account__c ' +
                    'FROM Events__c ' +
                    'WHERE Broker_Account__c = NULL';
        }
        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Events__c> scope) {
        
        Map<String, String> brmAccountMap = new Map<String, String>();
        Map<String, String> brmBrokerMap = new Map<String, String>();
        List<String> scIdsToSearchInBR = new List<String>();
        List<String> cpIdsToSearchInBR = new List<String>();
        
        Map<String, String> brBrokerMap = new Map<String, String>();
        
        String eventId = scope[0].Id;
        
        /* Iterate through Events */
        for(Events__c event : scope) {
            if(event.channel_partner__c == null && event.Sobha_Connect__c == null) {
                continue;
            }
            if(event.channel_partner__C != null) {
                brmBrokerMap.put(event.Id, event.channel_partner__c);
                cpIdsToSearchInBR.add(event.channel_partner__c);
            }
            else {
                brmBrokerMap.put(event.Id, event.Sobha_Connect__c);
                scIdsToSearchInBR.add(event.Sobha_Connect__c);
            }
        }
        
        System.debug('brmAccountMap' + brmAccountMap);
        System.debug('brmBrokerMap' + brmBrokerMap);
        System.debug('cpIdsToSearchInBR' + cpIdsToSearchInBR);
        System.debug('scIdsToSearchInBR' + scIdsToSearchInBR );

        
        List<Broker_Registration__c> brokerRegistrations = [SELECT Id,SCID__c,CPID__c from Broker_Registration__c WHERE SCID__c IN :scIdsToSearchInBR OR CPID__c IN :cpIdsToSearchInBR];
        List<String> brIds = new List<String>();
        
        System.debug('brIds' + brokerRegistrations);
        for(Broker_Registration__c br: brokerRegistrations ) {
            if(br.cpid__c != null) {
                brBrokerMap.put(br.cpid__c, br.id);
            }
            else {
                brBrokerMap.put(br.scid__c, br.id);
            }
            brIds.add(br.id);

        }
        
        List<Account> psAccounts = [SELECT Id, name, Legacy_Broker_Id__c from account where recordtype.name = 'broker' and (Legacy_Broker_Id__c  IN :brIds OR Legacy_Broker_Id__c  IN:cpIdsToSearchInBR OR Legacy_Broker_Id__c  IN :scIdsToSearchInBR)];
        system.debug('FRUIT1' + psAccounts);
        
        if(psAccounts.size() > 0) {
            Events__c event = new Events__c(id = eventId);
            event.Broker_Account__c = psAccounts[0].Id;
            Database.SaveResult[] srList = Database.update(new List<Events__c>{event}, false);
            trackDML(CLASS_NAME, srList);
        }
        
        
    }   

    global void finish(Database.BatchableContext BC) {
    }
    
    public static void trackDML(String className, Database.SaveResult[] srList) {
        List<Error_log__c> allErrorList = new List<Error_log__c>();
        for (Database.SaveResult sr : srList) {
            if (sr.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('Successfully inserted record. Record ID: ' + sr.getId());
            }
            else {
                // Operation failed, so get all errors 
                String errorsCombined = '';               
                for(Database.Error err : sr.getErrors()) {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('Object fields that affected this error: ' + err.getFields());
                    errorsCombined += err.getStatusCode() + ': ' + err.getMessage() + '\n';
                }
                
                Error_Log__c trackRec = new Error_Log__c(Class__c = className, Message__c = errorsCombined );
                allErrorList.add(trackRec);
            }
        }
        if(allErrorList.size() > 0) {
            Database.insert(allErrorList, false);
        }
    }
}