force-app/main/default/objects/Account/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Partner</label>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <externalId>true</externalId>
    <label>Mobile (Unique Identifier)</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Name_as_per_trade_license__c.field-meta.xml
<CustomField>
    <fullName>Name_as_per_trade_license__c</fullName>
    <label>Name as per trade license</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RERA_Number__c.field-meta.xml
<CustomField>
    <fullName>RERA_Number__c</fullName>
    <label>RERA Number</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RERA_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>RERA_Registration_No__c</fullName>
    <label>RERA Registration No.</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sobha_Connect__c.field-meta.xml
<CustomField>
    <fullName>Sobha_Connect__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sobha Connect</label>
    <referenceTo>Sobha_Connect__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Emergency_Created_ID__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Created_ID__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency Created ID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Passport_No__c.field-meta.xml
<CustomField>
    <fullName>Passport_No__c</fullName>
    <label>Registration/Passport Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/RERA_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>RERA_Registration_No__c</fullName>
    <externalId>true</externalId>
    <label>RERA Registration No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/Sobha_Connect__c.object-meta.xml
<CustomObject>
    <label>Sobha Connect</label>
    <nameField>
        <displayFormat>SC - {0000}</displayFormat>
        <label>Sobha Connect Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sobha Connect</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sobha_Connect__c/fields/Emergency_Created_ID__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Created_ID__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emergency Created ID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration/Passport Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/RERA_Number__c.field-meta.xml
<CustomField>
    <fullName>RERA_Number__c</fullName>
    <label>RERA Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BrokerAccountController_Test.cls
@isTest
public class BrokerAccountController_Test {
    @isTest
    static void testGetUserManagerDetails() {
        
        User manager = TestDataFactorySobha.createUser(null);        
        insert manager;
        
        User user = TestDataFactorySobha.createUser(null);        
        insert user;
        
        Test.startTest();
        List<User> result = BrokerAccountController.getUserManagerDetails(String.valueOf(user.Id));
        Test.stopTest();
    }

    @isTest
    static void testCreateRecord() {        
        Account acc = TestDataFactorySobha.createAccount(null);
        
        Test.startTest();
        Account result = BrokerAccountController.createRecord(acc);
        Test.stopTest();        
    }

    @isTest
    static void testIsDuplicate() {
        
        Account acc = TestDataFactorySobha.createAccount(null);
        acc.Name_as_per_trade_license__c = 'testing';
        insert acc;       
        Account duplicateAcc = new Account(
            Name = 'Duplicate Account',
            Email__c = 'duplicate@example.com',
            Mobile__c = '1111111111',
            RecordTypeId=Schema.SObjectType.Account.getRecordTypeInfosByName().get('Broker').getRecordTypeId(),
            Name_as_per_trade_license__c = 'TradeLicense456'
        );
        insert duplicateAcc;        
        Test.startTest();
        Boolean isDuplicate = BrokerAccountController.isDuplicate(duplicateAcc);
        Test.stopTest();        
    }

    @isTest
    static void testValidateRegistrationNo() {
        
        Channel_Partner__c cp = new Channel_Partner__c(
            Passport_No__c = 'Passport123',
            RERA_Registration_No__c = 'RERA123',
            OwnerId = UserInfo.getUserId(),
            Emergency_Created_ID__c = true
        );
        insert cp;

        Sobha_Connect__c sc = new Sobha_Connect__c(
            Registration__c = 'Reg123',
            RERA_Number__c = 'RERA456',
            OwnerId = UserInfo.getUserId(),
            Emergency_Created_ID__c = true
        );
        insert sc;

        
        Test.startTest();
        Integer brokerCount = BrokerAccountController.validateRegistrationNo('Passport123', 'Broker');
        Integer sobhaCount = BrokerAccountController.validateRegistrationNo('Reg123', 'Sobha Connect');
        Test.stopTest();
    }

    @isTest
    static void testGetReportingManger() {
        
         User manager = TestDataFactorySobha.createUser(null);        
        insert manager;
        
        User user = TestDataFactorySobha.createUser(null);        
        insert user;

        
        Test.startTest();
        Id reportingManagerId = BrokerAccountController.getReportingManger(String.valueOf(user.Id));
        Test.stopTest();
    }
}