force-app/main/default/objects/Account/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <displayFormat>C{0000}</displayFormat>
    <label>Code</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email_ID_1__c.field-meta.xml
<CustomField>
    <fullName>Email_ID_1__c</fullName>
    <label>Email ID 1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/PropStrength__Broker_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>PropStrength__Broker_Approval_Status__c</fullName>
    <label>Broker Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Broker Registration Done, pending with CHRM Manager</fullName>
                <label>Pending with CHRM Manager</label>
            </value>
            <value>
                <fullName>Pending with CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Approved by CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Agreement Created and Sent for Signatures</fullName>
            </value>
            <value>
                <fullName>Signed Agreement Received - Documents Awaiting</fullName>
            </value>
            <value>
                <fullName>All Missing Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>NOC Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh/ Sent for final signatures</fullName>
                <label>Pending with Ashish Parakh</label>
            </value>
            <value>
                <fullName>Executed Agreement Sent to CHRM</fullName>
            </value>
            <value>
                <fullName>Executed Agreement Sent to Broker</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Broker Registration Done</fullName>
            </value>
            <value>
                <fullName>Broker Empanelment Form Filled</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM Manager</fullName>
            </value>
            <value>
                <fullName>Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh</fullName>
                <label>Pending with Ashish Parakh1</label>
            </value>
            <value>
                <fullName>Rejected by Audit</fullName>
            </value>
            <value>
                <fullName>NOC Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and sent for signature</fullName>
            </value>
            <value>
                <fullName>NOC Is in Process</fullName>
            </value>
            <value>
                <fullName>Agreement - approved by CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Pending with CHRM / Rejected with CHRM</fullName>
            </value>
            <value>
                <fullName>Agreement Is in process</fullName>
            </value>
            <value>
                <fullName>Approved - by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Agreement Generated</fullName>
            </value>
            <value>
                <fullName>Executed Agreement sent to CRHM</fullName>
            </value>
            <value>
                <fullName>Signed Agreement Received - Documents</fullName>
            </value>
            <value>
                <fullName>Amendment Signed by Broker</fullName>
            </value>
            <value>
                <fullName>Amendment Final Signature Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Docusign_Recipient_Status_Sobha__c/Docusign_Recipient_Status_Sobha__c.object-meta.xml
<CustomObject>
    <label>Docusign Recipient Status Sobha</label>
    <nameField>
        <label>Docusign Recipient Status Sobha Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Docusign Recipient Status Sobha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Docusign_Recipient_Status_Sobha__c/fields/Application_Booking__c.field-meta.xml
<CustomField>
    <fullName>Application_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Application / Booking</label>
    <referenceTo>PropStrength__Application_Booking__c</referenceTo>
    <relationshipLabel>Docusign Recipient Status Sobha</relationshipLabel>
    <relationshipName>Docusign_Recipient_Status_Sobha</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Docusign_Recipient_Status_Sobha__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Docusign Recipient Status Sobha</relationshipLabel>
    <relationshipName>Docusign_Recipient_Status_Sobha</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Docusign_Recipient_Status_Sobha__c/fields/Envelope_Recipient_Type__c.field-meta.xml
<CustomField>
    <fullName>Envelope_Recipient_Type__c</fullName>
    <label>Envelope Recipient Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applicant</fullName>
            </value>
            <value>
                <fullName>Sales manager</fullName>
            </value>
            <value>
                <fullName>Secondary Sales manager</fullName>
            </value>
            <value>
                <fullName>Sales Head</fullName>
            </value>
            <value>
                <fullName>Secondary Sales Head</fullName>
            </value>
            <value>
                <fullName>Sales Ops</fullName>
            </value>
            <value>
                <fullName>Audit Team</fullName>
            </value>
            <value>
                <fullName>Seller Representative</fullName>
            </value>
            <value>
                <fullName>Document Controller</fullName>
            </value>
            <value>
                <fullName>Broker</fullName>
            </value>
            <value>
                <fullName>chrmops Team</fullName>
            </value>
            <value>
                <fullName>Broker Registration - Ashish Parakh SignOff</fullName>
            </value>
            <value>
                <fullName>Chief Audit Officer</fullName>
            </value>
            <value>
                <fullName>Document Controller2</fullName>
            </value>
            <value>
                <fullName>Broker Registration Witness</fullName>
            </value>
            <value>
                <fullName>Broker Registration - Email Category SignOff</fullName>
            </value>
            <value>
                <fullName>Authorized Signatory</fullName>
            </value>
            <value>
                <fullName>Buyer</fullName>
            </value>
            <value>
                <fullName>Seller</fullName>
            </value>
            <value>
                <fullName>Resale CRM Ops</fullName>
            </value>
            <value>
                <fullName>Resale Audit</fullName>
            </value>
            <value>
                <fullName>POA</fullName>
            </value>
            <value>
                <fullName>Sobha LLC</fullName>
            </value>
            <value>
                <fullName>CRM Document Controller</fullName>
            </value>
            <value>
                <fullName>Authorised Representative</fullName>
            </value>
            <value>
                <fullName>Development Team</fullName>
            </value>
            <value>
                <fullName>Legal Team</fullName>
            </value>
            <value>
                <fullName>Primary Customer</fullName>
            </value>
            <value>
                <fullName>Account Team</fullName>
            </value>
            <value>
                <fullName>DLD Executive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Docusign_Recipient_Status_Sobha__c/fields/Envelope_Type__c.field-meta.xml
<CustomField>
    <fullName>Envelope_Type__c</fullName>
    <label>Envelope Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Booking Form</fullName>
            </value>
            <value>
                <fullName>SPA</fullName>
            </value>
            <value>
                <fullName>SPA Addendum</fullName>
            </value>
            <value>
                <fullName>Broker Registration - Agreement</fullName>
            </value>
            <value>
                <fullName>Broker Registration - NOC</fullName>
            </value>
            <value>
                <fullName>Resale NOC</fullName>
            </value>
            <value>
                <fullName>Resale process</fullName>
            </value>
            <value>
                <fullName>Broker Agreement</fullName>
            </value>
            <value>
                <fullName>MOU</fullName>
            </value>
            <value>
                <fullName>DSPA</fullName>
            </value>
            <value>
                <fullName>Transfer &amp; Assignment</fullName>
            </value>
            <value>
                <fullName>NOC TR</fullName>
            </value>
            <value>
                <fullName>Handover of Possession</fullName>
            </value>
            <value>
                <fullName>Undertaking Letter</fullName>
            </value>
            <value>
                <fullName>Home Orientation Undertaking Letter</fullName>
            </value>
            <value>
                <fullName>DSR</fullName>
            </value>
            <value>
                <fullName>NOC</fullName>
            </value>
            <value>
                <fullName>Amendment Letter</fullName>
                <isActive>false</isActive>
                <label>Amendment Letter</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Docusign_Recipient_Status_Sobha__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <length>56</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Docusign_Recipient_Status_Sobha__c/fields/Transaction_Request__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transaction Request</label>
    <referenceTo>PropStrength__Transaction_Requests__c</referenceTo>
    <relationshipLabel>Docusign Recipient Status Sobha</relationshipLabel>
    <relationshipName>Docusign_Recipient_Status_Sobha</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Docusign_Recipient_Status_Sobha__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>56</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVAILABLE</fullName>
                <label>Available</label>
            </value>
            <value>
                <fullName>BUSY</fullName>
                <label>Busy</label>
            </value>
            <value>
                <fullName>BREAK</fullName>
                <label>Break</label>
            </value>
            <value>
                <fullName>OUTCALL</fullName>
                <label>OutCall</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DocusignRecipientStatusSobhaTrigHelper.cls
/*********************************************************************
 * Class Name  :   DocusignRecipientStatusSobhaTrigHelper
 * Description :   Helper Class of DocusignRecipientStatusSobhaTrigger
 * Created Date:   31/01/2024
 * Authored By :   CloudSteer Technology Pte Ltd
 * -------------------------------------------------------------------
 * Version History : 
   Created By       :   Nishank Manwani
   Last Modified By :   Nishank Manwani 31/01/2024
                        Deepak Sharma 31/01/2024
                        Gourav Gour 13/05/2024

 *********************************************************************/
public class DocusignRecipientStatusSobhaTrigHelper {
    //Added by Nishank Manwani on 31/01/2024 to update Type Field
    public static void updateTypeField(List<Docusign_Recipient_Status_Sobha__c> esList, Map<Id,Docusign_Recipient_Status_Sobha__c> esMap) {
        List<PropStrength__Transaction_Requests__c> updateTransactionReq = new List<PropStrength__Transaction_Requests__c>();
        List<Account> updateAccount = new List<Account>();
        for(Docusign_Recipient_Status_Sobha__c es : esList) {
            if(es.Name == 'Audit Team' && es.Transaction_Request__c != null) {
                es.Type__c = 'Approver';
            } else if (es.Name == 'CRM Document Controller' && es.Transaction_Request__c != null) {
                es.Type__c = 'Stamp';
            }
            System.debug('es.Status__c****');
            System.debug(es.Status__c);
            System.debug(es.Envelope_Type__c);
            System.debug(es.Transaction_Request__c);
            System.debug(es.Envelope_Recipient_Type__c);
            
            if(esMap != null) {
                
                if(es.Envelope_Type__c == 'Broker Agreement' && es.Broker_Account__c!= null && es.Envelope_Recipient_Type__c == 'Sobha LLC' && (es.Status__c == 'Delivered' || es.Status__c == 'Completed' ) && (es.Status__c != esMap.get(es.Id).Status__c)) {
                    updateAccount.add(new Account(Id=es.Broker_Account__c, PropStrength__Broker_Approval_Status__c = 'Signed Agreement Received - Documents Awaiting'));
                }
                if(es.Envelope_Type__c == 'NOC' && es.Broker_Account__c!= null && es.Name == 'Audit Team' && (es.Status__c == 'Delivered' || es.Status__c == 'Completed' )  && (es.Status__c != esMap.get(es.Id).Status__c)) {
                    updateAccount.add(new Account(Id=es.Broker_Account__c, PropStrength__Broker_Approval_Status__c = 'Pending with Ashish Parakh/ Sent for final signatures'));
                }
                if(es.Envelope_Type__c == 'Amendment Letter' && es.Broker_Account__c!= null && es.Envelope_Recipient_Type__c == 'Authorised Representative' && (es.Status__c == 'Delivered' || es.Status__c == 'Completed' )  && (es.Status__c != esMap.get(es.Id).Status__c)) {
                    updateAccount.add(new Account(Id=es.Broker_Account__c, PropStrength__Broker_Approval_Status__c = 'Amendment Signed by Broker'));
                }
                if(es.Envelope_Type__c == 'Amendment Letter' && es.Broker_Account__c!= null && es.Envelope_Recipient_Type__c == system.label.Siniya_Island_Final_Signatory_Name && (es.Status__c == 'Delivered' || es.Status__c == 'Completed' )  && (es.Status__c != esMap.get(es.Id).Status__c)) {
                    updateAccount.add(new Account(Id=es.Broker_Account__c, PropStrength__Broker_Approval_Status__c = 'Amendment Final Signature Completed'));
                }
                // if(es.Envelope_Type__c == 'NOC' && es.Broker_Account__c!= null && es.Envelope_Recipient_Type__c.contains('Broker Registration - ') && (es.Status__c == 'Delivered' || es.Status__c == 'Completed' ) && (es.Status__c != esMap.get(es.Id).Status__c)) {
                //     updateAccount.add(new Account(Id=es.Broker_Account__c, PropStrength__Broker_Approval_Status__c = 'Executed Agreement Sent to CHRM'));
                //     DocusignRecipientStatusSobhaTrigHelper.sendEmailNotification(es.Broker_Account__c);
                // }
            }
        }
        if(!updateTransactionReq.isEmpty()) {
            update updateTransactionReq;
        }
        if(!updateAccount.isEmpty()) {
            update updateAccount;
        }
    }

    //Added by Nishank Manwani on 06/02/2024 to send Email on final signature for NOC and Broker Registration
    @future(callout=true)
    public static void sendEmailNotification(Id accId) {
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        System.debug(accId);  
        Account acc = [SELECT Id, Name, Code__c, Email_ID_1__c FROM Account WHERE Id = :accId];
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSubject('Final NOC and Agreement Letter');
        //mail.setPlainTextBody('Dear CRM Team,\n\nPlease note Transfer of Property for unit '+house+', booking ID '+bookName+' has been approved by audit for processing.\n\nIt is in your queue for execution. Please complete the execution and close the step.\n\nRegards,\nSalesforce');
        mail.setHtmlBody('<html><body>Dear Team,<br/><br/>The Final NOC and Agreement Letter are ready to be sent to the below mentioned Broker.<br/>Request you to please take this forward.<br/><br/>Broker Name : '+acc.Name+'<br/>Broker Code : '+acc.Code__c+'<br/><br/>Thank You</body></html>');
        mail.setToAddresses(new List<String>{acc.Email_ID_1__c});

        System.debug(mail);
        emailList.add(mail);
        
        System.debug(emailList);
        if(emailList != null && emailList.size()>0 ) {
            System.debug(emailList);
            Messaging.SendEmailResult[] result = Messaging.sendEmail(emailList);
            System.debug('result***');
            System.debug(result);
            EmailMessage newEmail = new EmailMessage();
            newEmail.ToAddress = acc.Email_ID_1__c;
            newEmail.Subject = 'Final NOC and Agreement Letter';
            newEmail.HtmlBody = mail.getHtmlBody();
            newEmail.RelatedToId = accId;
            newEmail.Status = '3';
            insert newEmail;
        }
    }

    //Added by Nishank Manwani on 06/02/2024 to send Email on final signature for NOC and Broker Registration
    // Email subject body updated by Gourav Gour 06/06/2024
    @future(callout=true)
    public static void sendEmailNotificationBroker(Id accId) {
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        System.debug(accId);  

        Account acc = [SELECT Id, Name, Code__c, Email_ID_1__c, OwnerId, Channel_Relationship_Manager__c, Channel_Relationship_Manager__r.Name FROM Account WHERE Id = :accId];
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSubject('Sobha Realty Registration - Executed Agreement');
        //mail.setHtmlBody('<html><body>Dear '+acc.Name+',<br/><br/>Sobha Realty Registration - Executed Agreement <br/><br/>Please do not hesitate to contact me regarding any questions you may have.<br/><br/>We look forward to a mutually beneficial and successful business relationship with you. <br/><br/>Thank you.<br/><br/>Best Regards,<br/><br/>'+acc.Channel_Relationship_Manager__r.Name+'</body></html>');
        // updated By Gourav Gour 17/07/2024
        //mail.setHtmlBody('<html><body>Dear '+acc.Name+',<br/><br/>Sobha Realty Registration - Executed Agreement <br/><br/>Please do not hesitate to contact me regarding any questions you may have.<br/><br/>We look forward to a mutually beneficial and successful business relationship with you. <br/><br/>Thank you.<br/><br/>Best Regards,<br/><br/>CHRM Manager</body></html>');
        mail.setHtmlBody('<html><body>Dear '+acc.Name+',<br/><br/>Hope this email finds you well. I am pleased to inform you that your Sobha Registration – Agreement has been Executed. Please find attached Executed Agreement & NOC for your reference.  <br/><br/>Please do not hesitate to contact me regarding any questions you may have.<br/><br/>We look forward to a mutually beneficial and successful business relationship with you. <br/><br/>Thank you.<br/><br/>Best Regards,<br/><br/>'+acc.Channel_Relationship_Manager__r.Name+'</body></html>');
        mail.setToAddresses(new List<String>{acc.Email_ID_1__c});

        Map<Id,ContentVersion> attachmentMap = new Map<Id,ContentVersion>();
        List<ContentDocumentLink> contDocLinks = [SELECT Id, ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId = :accId];
        if(!contDocLinks.isEmpty()) {
            Set<Id> cdIds= new Set<Id>();
            for(ContentDocumentLink cd : contDocLinks) {
                cdIds.add(cd.ContentDocumentId);
            }
            Messaging.EmailFileAttachment efa1 = new Messaging.EmailFileAttachment();
            Messaging.EmailFileAttachment efa2 = new Messaging.EmailFileAttachment();
            Messaging.EmailFileAttachment efa3 = new Messaging.EmailFileAttachment();
            List<Messaging.EmailFileAttachment> fileAttachList = new List<Messaging.EmailFileAttachment>();
            List<ContentDocument> documents = [SELECT Id, Title, FileExtension, ContentSize FROM ContentDocument WHERE Id IN :cdIds AND Title LIKE :'NOC -%' ORDER BY CreatedDate DESC LIMIT 1];
            if(!documents.isEmpty()) {
                List<ContentVersion> contentVersions = [SELECT Id, VersionData, Title, FileExtension FROM ContentVersion WHERE ContentDocumentId = :documents[0].Id];
                if(!contentVersions.isEmpty()) {
                    efa1.setFileName(contentVersions[0].Title + '.' + contentVersions[0].FileExtension);
                    efa1.setBody(contentVersions[0].VersionData); 
                    fileAttachList.add(efa1);
                }
            }
            List<ContentDocument> documents1 = [SELECT Id, Title, FileExtension, ContentSize FROM ContentDocument WHERE Id IN :cdIds AND Title LIKE :'%Broker%' AND (NOt Title LIKE '%NOC%') AND (NOt Title LIKE '%Agreement%') ORDER BY CreatedDate DESC LIMIT 1];
            if(!documents1.isEmpty()) {
                List<ContentVersion> contentVersions = [SELECT Id, VersionData, Title, FileExtension FROM ContentVersion WHERE ContentDocumentId = :documents1[0].Id];
                if(!contentVersions.isEmpty()) {
                    efa2.setFileName(contentVersions[0].Title + '.' + contentVersions[0].FileExtension);
                    efa2.setBody(contentVersions[0].VersionData); 
                    //fileAttachList.add(efa2);
                }
            }
            List<ContentDocument> documents2 = [SELECT Id, Title, FileExtension, ContentSize FROM ContentDocument WHERE Id IN :cdIds AND Title LIKE :'Agreement -%' ORDER BY CreatedDate DESC LIMIT 1];
            if(!documents2.isEmpty()) {
                List<ContentVersion> contentVersions = [SELECT Id, VersionData, Title, FileExtension FROM ContentVersion WHERE ContentDocumentId = :documents2[0].Id];
                if(!contentVersions.isEmpty()) {
                    efa3.setFileName(contentVersions[0].Title + '.' + contentVersions[0].FileExtension);
                    efa3.setBody(contentVersions[0].VersionData); 
                    fileAttachList.add(efa3);
                }
            }

            if(!fileAttachList.isEmpty()) {
                mail.setFileAttachments(fileAttachList);
            }
        }
        mail.setTargetObjectId(acc.OwnerId);
        mail.setWhatId(acc.Id);
        mail.setSaveAsActivity(true);
        mail.setTreatTargetObjectAsRecipient(false); 

        System.debug(mail);
        emailList.add(mail);
        
        System.debug(emailList);
        if(emailList != null && emailList.size()>0 ) {
            System.debug(emailList);
            Messaging.SendEmailResult[] result = Messaging.sendEmail(emailList);
            System.debug('result***');
            System.debug(result);
            EmailMessage newEmail = new EmailMessage();
            newEmail.ToAddress = acc.Email_ID_1__c;
            newEmail.Subject = 'Final NOC and Agreement Letter';
            newEmail.HtmlBody = mail.getHtmlBody();
            newEmail.RelatedToId = accId;
            newEmail.Status = '3';
           // insert newEmail;
        }
    }

    //Added by Nishank Manwani on 08/02/2024 to update Handover Field
    public static void updateHandover(List<Docusign_Recipient_Status_Sobha__c> esList, Map<Id,Docusign_Recipient_Status_Sobha__c> esMap) {
        List<PropStrength__Application_Booking__c> updateBooking = new List<PropStrength__Application_Booking__c>();
        List<Docusign_Recipient_Status_Sobha__c> statusSobhaList = [SELECT Id, Envelope_Type__c, Status__c FROM Docusign_Recipient_Status_Sobha__c WHERE (Envelope_Type__c = 'Handover of Possession' OR Envelope_Type__c = 'Undertaking Letter') AND Application_Booking__c != null];
        Map<String, String> mapOfType = new Map<String, String>();

        for(Docusign_Recipient_Status_Sobha__c sb : statusSobhaList) {
            mapOfType.put(sb.Envelope_Type__c, sb.Status__c);
        }

        for(Docusign_Recipient_Status_Sobha__c es : esList) {
            if(esMap != null) {
                if(mapOfType.containsKey('Undertaking Letter') && (mapOfType.get('Undertaking Letter') == 'Delivered' || mapOfType.get('Undertaking Letter') == 'Completed' ) && es.Envelope_Type__c == 'Handover of Possession' && es.Application_Booking__c!= null && (es.Status__c == 'Delivered' || es.Status__c == 'Completed' ) && (es.Status__c != esMap.get(es.Id).Status__c)) {
                    updateBooking.add(new PropStrength__Application_Booking__c(Id=es.Application_Booking__c, Handover_Date__c = System.Now(), Handover_Completed__c = true));
                }
                if(mapOfType.containsKey('Handover of Possession') && (mapOfType.get('Handover of Possession') == 'Delivered' || mapOfType.get('Handover of Possession') == 'Completed' ) && es.Envelope_Type__c == 'Undertaking Letter' && es.Application_Booking__c!= null && (es.Status__c == 'Delivered' || es.Status__c == 'Completed' ) && (es.Status__c != esMap.get(es.Id).Status__c)) {
                    updateBooking.add(new PropStrength__Application_Booking__c(Id=es.Application_Booking__c, Handover_Date__c = System.Now(), Handover_Completed__c = true));
                }
            }
        
            if(!updateBooking.isEmpty()) {
                update updateBooking;
            }
        }
    }

    //Added by Nishank Manwani on 20/05/2024 to update Home Orientation Received Date Field
    public static void updateHomeOrientation(List<Docusign_Recipient_Status_Sobha__c> esList, Map<Id,Docusign_Recipient_Status_Sobha__c> esMap) {
        List<PropStrength__Application_Booking__c> updateBooking = new List<PropStrength__Application_Booking__c>();
        List<Docusign_Recipient_Status_Sobha__c> statusSobhaList = [SELECT Id, Envelope_Type__c, Status__c FROM Docusign_Recipient_Status_Sobha__c WHERE (Envelope_Type__c = 'Home Orientation Undertaking Letter') AND Application_Booking__c != null];
        Map<String, String> mapOfType = new Map<String, String>();

        for(Docusign_Recipient_Status_Sobha__c sb : statusSobhaList) {
            mapOfType.put(sb.Envelope_Type__c, sb.Status__c);
        }

        for(Docusign_Recipient_Status_Sobha__c es : esList) {
            if(esMap != null) {
                if(mapOfType.containsKey('Home Orientation Undertaking Letter') && (mapOfType.get('Home Orientation Undertaking Letter') == 'Delivered' || mapOfType.get('Home Orientation Undertaking Letter') == 'Completed' ) && es.Envelope_Type__c == 'Home Orientation Undertaking Letter' && es.Application_Booking__c!= null && (es.Status__c == 'Delivered' || es.Status__c == 'Completed' ) && (es.Status__c != esMap.get(es.Id).Status__c)) {
                    Time elevenFiftyThreePM = Time.newInstance(23, 53, 0, 0);
                    DateTime reminderDateTime = DateTime.newInstance(System.Today(), elevenFiftyThreePM);
                    updateBooking.add(new PropStrength__Application_Booking__c(Id=es.Application_Booking__c, Home_Orientation_Undertaking_Receive_Dt__c = System.Now(), HO_Escalation_Reminder_Flow_Date__c = reminderDateTime));
                }
            }
        
            if(!updateBooking.isEmpty()) {
                update updateBooking;
            }
        }
    }
}