force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Dialing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
                <default>true</default>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Cote D&apos;Ivoire</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Ghana</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Israel</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email1</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UAE</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>Bosnia-Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/Social_Media_Lead__c.object-meta.xml
<CustomObject>
    <label>Social Media Lead</label>
    <nameField>
        <displayFormat>SML-{00000}</displayFormat>
        <label>FB Leads Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Social Media Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Social_Media_Lead__c/fields/Ad_ID__c.field-meta.xml
<CustomField>
    <fullName>Ad_ID__c</fullName>
    <label>Ad ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Ad_Name__c.field-meta.xml
<CustomField>
    <fullName>Ad_Name__c</fullName>
    <label>Ad Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/AdSet_Id__c.field-meta.xml
<CustomField>
    <fullName>AdSet_Id__c</fullName>
    <label>AdSet Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/AdSet_Name__c.field-meta.xml
<CustomField>
    <fullName>AdSet_Name__c</fullName>
    <label>AdSet Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <inlineHelpText>Email of the facebook lead</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Form_ID__c.field-meta.xml
<CustomField>
    <fullName>Form_ID__c</fullName>
    <label>Form ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Form_Name__c.field-meta.xml
<CustomField>
    <fullName>Form_Name__c</fullName>
    <label>Form Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <inlineHelpText>full Name of facebook lead</inlineHelpText>
    <label>Full Name</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Lead_Created_Time__c.field-meta.xml
<CustomField>
    <fullName>Lead_Created_Time__c</fullName>
    <label>Lead Created Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Lead_ID__c.field-meta.xml
<CustomField>
    <fullName>Lead_ID__c</fullName>
    <externalId>true</externalId>
    <label>Lead ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <inlineHelpText>Mobile Number with Country Code</inlineHelpText>
    <label>Mobile Number</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Mobile_Number_No_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number_No_Country_Code__c</fullName>
    <label>Mobile Number (No Country Code)</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Page_ID__c.field-meta.xml
<CustomField>
    <fullName>Page_ID__c</fullName>
    <label>Page ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Platform_ig__c.field-meta.xml
<CustomField>
    <fullName>Platform_ig__c</fullName>
    <label>Platform ig</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Recording_URL__c.field-meta.xml
<CustomField>
    <fullName>Recording_URL__c</fullName>
    <label>Recording URL</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Social_Media_Lead__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <label>Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>propertyfinder</fullName>
            </value>
            <value>
                <fullName>yallacompare</fullName>
            </value>
            <value>
                <fullName>HOD</fullName>
            </value>
            <value>
                <fullName>ETQ</fullName>
            </value>
            <value>
                <fullName>PropertyGuru</fullName>
            </value>
            <value>
                <fullName>Bayt</fullName>
            </value>
            <value>
                <fullName>TTRU</fullName>
            </value>
            <value>
                <fullName>HF</fullName>
            </value>
            <value>
                <fullName>Xiongma</fullName>
            </value>
            <value>
                <fullName>HFLRS</fullName>
            </value>
            <value>
                <fullName>GFN</fullName>
            </value>
            <value>
                <fullName>ETERNITY CHINA</fullName>
            </value>
            <value>
                <fullName>HFSO</fullName>
            </value>
            <value>
                <fullName>HFSH2</fullName>
            </value>
            <value>
                <fullName>LGMRU</fullName>
            </value>
            <value>
                <fullName>JEAF</fullName>
            </value>
            <value>
                <fullName>EXCHSH2</fullName>
            </value>
            <value>
                <fullName>AFF-NABD</fullName>
            </value>
            <value>
                <fullName>AZ-AFF</fullName>
            </value>
            <value>
                <fullName>toutiao</fullName>
            </value>
            <value>
                <fullName>AFF - YX</fullName>
            </value>
            <value>
                <fullName>Google-search</fullName>
                <label>google-search</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>Trim(FirstName + &apos; &apos;+ LastName)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/trgSocialMediaLeadHelper_test.cls
@isTest
public class trgSocialMediaLeadHelper_test {
    
    @TestSetup
    static void testPrepareLeadfromSML() {
        Account acc = TestDataFactorySobha.createAccount(null);
        insert acc;
        User u = TestDataFactorySobha.createUser(null);
        insert u;
        Contact cont = TestDataFactorySobha.createContact(null);
        cont.email = 'test1@gmail.com';
        insert cont;
        List<Social_media_lead__c> smlList = new list<Social_media_lead__c>();
        Social_media_lead__c sml = new Social_media_lead__c();
        sml.Form_ID__c  = '123046341703539';
        sml.Page_ID__c  = '4534623232322';
        sml.AdSet_Id__c ='3253242432423';
        sml.Lead_ID__c  = '4523188';
        sml.Source__c   = 'Facebook';
        sml.Email__c    = 'test1@gmail.com';
        sml.Full_Name__c = 'tesstfb';
        sml.processed__c = false;
        sml.Country__c = 'AE';
        sml.Ad_ID__c = '111111';
        sml.Ad_Name__c = 'FaceBookAd';
        sml.AdSet_Name__c = 'FaceBookAddSet';
        sml.Lead_Created_Time__c = datetime.newInstance(2023, 3, 15, 12, 30, 0);
        sml.Platform_ig__c = 'Platform';
        sml.Page_Name__c = 'pageName';
        sml.Form_Name__c = 'newForm';
        sml.Full_Name__c = 'Full Name';
        sml.Phone_Number__c = '12345678';
        sml.Mobile_Number__c = '330613272013';
        sml.Mobile_Number_No_Country_Code__c = '0613272013';
        sml.Recording_URL__c = 'URL';
        insert sml;   
        trgSocialMediaLeadHelper.PrepareLeadfromSML(new list<Social_media_lead__c>{sml}, null);
        List<Social_media_lead__c> sml1List = new list<Social_media_lead__c>();
        Social_media_lead__c sml1 = new Social_media_lead__c();
        sml1.Form_ID__c  = '123046341703539';
        sml1.Page_ID__c  = '4534623232322';
        sml1.AdSet_Id__c ='3253242432423';
        sml1.Lead_ID__c  = '4523188';
        sml1.Source__c   = 'Facebook';
        sml1.Email__c    = 'test@gmail.com';
        sml1.Full_Name__c = 'tesstfb';
        sml1.processed__c = false;
        sml1.Country__c = 'AE';
        sml1.Ad_ID__c = '111111';
        sml1.Ad_Name__c = 'FaceBookAd';
        sml1.AdSet_Name__c = 'FaceBookAddSet';
        sml1.Lead_Created_Time__c = datetime.newInstance(2023, 3, 15, 12, 30, 0);
        sml1.Platform_ig__c = 'Platform';
        sml1.Page_Name__c = 'pageName';
        sml1.Form_Name__c = 'newForm';
        sml1.Full_Name__c = 'Full Name';
        sml1.Phone_Number__c = '12345678';
        sml1.Mobile_Number__c = '330613272013';
        sml1.Mobile_Number_No_Country_Code__c = '0613272013';
        sml1.Recording_URL__c = 'URL';
        insert sml1; 
        trgSocialMediaLeadHelper.PrepareLeadfromSML(new list<Social_media_lead__c>{sml1}, null);
    }
    
    @isTest
    public static void testMethod1(){
        
    }
}