force-app/main/default/objects/Account/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <defaultValue>&apos;+971&apos;</defaultValue>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>+61</fullName>
            </value>
            <value>
                <fullName>+65</fullName>
            </value>
            <value>
                <fullName>+852</fullName>
            </value>
            <value>
                <fullName>+86</fullName>
            </value>
            <value>
                <fullName>+91</fullName>
            </value>
            <value>
                <fullName>+971</fullName>
            </value>
            <value>
                <fullName>+93</fullName>
            </value>
            <value>
                <fullName>+54</fullName>
            </value>
            <value>
                <fullName>+43</fullName>
            </value>
            <value>
                <fullName>+973</fullName>
            </value>
            <value>
                <fullName>+880</fullName>
            </value>
            <value>
                <fullName>+55</fullName>
            </value>
            <value>
                <fullName>+1</fullName>
            </value>
            <value>
                <fullName>+506</fullName>
            </value>
            <value>
                <fullName>+225</fullName>
            </value>
            <value>
                <fullName>+45</fullName>
            </value>
            <value>
                <fullName>+20</fullName>
            </value>
            <value>
                <fullName>+358</fullName>
            </value>
            <value>
                <fullName>+33</fullName>
            </value>
            <value>
                <fullName>+49</fullName>
            </value>
            <value>
                <fullName>+233</fullName>
            </value>
            <value>
                <fullName>+30</fullName>
            </value>
            <value>
                <fullName>+36</fullName>
            </value>
            <value>
                <fullName>+62</fullName>
            </value>
            <value>
                <fullName>+353</fullName>
            </value>
            <value>
                <fullName>+972</fullName>
            </value>
            <value>
                <fullName>+39</fullName>
            </value>
            <value>
                <fullName>+81</fullName>
            </value>
            <value>
                <fullName>+254</fullName>
            </value>
            <value>
                <fullName>+82</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Emirates_ID__c.field-meta.xml
<CustomField>
    <fullName>Emirates_ID__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Emirates ID</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CLE__Mobile_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>CLE__Mobile_Encrypted__c</fullName>
    <label>Mobile</label>
    <length>20</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CLE__Phone_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>CLE__Phone_Encrypted__c</fullName>
    <label>Phone</label>
    <length>20</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>+91</fullName>
            </value>
            <value>
                <fullName>+1</fullName>
            </value>
            <value>
                <fullName>+93</fullName>
            </value>
            <value>
                <fullName>+7</fullName>
            </value>
            <value>
                <fullName>+44</fullName>
            </value>
            <value>
                <fullName>+971</fullName>
            </value>
            <value>
                <fullName>+966</fullName>
            </value>
            <value>
                <fullName>+965</fullName>
            </value>
            <value>
                <fullName>+968</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Emirates_ID__c.field-meta.xml
<CustomField>
    <fullName>Emirates_ID__c</fullName>
    <label>Emirates ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>Passport_Number__c</fullName>
    <label>Passport Number</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VCC1__Calling_Number_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>VCC1__Calling_Number_Encrypted__c</fullName>
    <label>Calling Number</label>
    <length>15</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VCC1__Mobile_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>VCC1__Mobile_Encrypted__c</fullName>
    <label>Mobile</label>
    <length>15</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Contact/fields/VCC1__Phone_Encrypted__c.field-meta.xml
<CustomField>
    <fullName>VCC1__Phone_Encrypted__c</fullName>
    <label>Phone</label>
    <length>15</length>
    <maskChar>asterisk</maskChar>
    <maskType>lastFour</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Country_Code_Master__c/Country_Code_Master__c.object-meta.xml
<CustomObject>
    <label>Country Code Master</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Country Code Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country Code Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_Code_Master__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country_Name__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>+91</fullName>
            </value>
            <value>
                <fullName>+1</fullName>
            </value>
            <value>
                <fullName>+44</fullName>
            </value>
            <value>
                <fullName>+7</fullName>
            </value>
            <value>
                <fullName>+966</fullName>
            </value>
            <value>
                <fullName>+965</fullName>
            </value>
            <value>
                <fullName>+971</fullName>
            </value>
            <value>
                <fullName>+968</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country_Code_Master__c/fields/Country_Name__c.field-meta.xml
<CustomField>
    <fullName>Country_Name__c</fullName>
    <label>Country Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Oman</fullName>
            </value>
            <value>
                <fullName>Saudi Arabia</fullName>
            </value>
            <value>
                <fullName>UAE</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>Russia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Country_Code_Master__c/fields/Phone_length__c.field-meta.xml
<CustomField>
    <fullName>Phone_length__c</fullName>
    <label>Phone length</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ContactTriggerHelper_Test.cls
@isTest
public class ContactTriggerHelper_Test {
    @isTest
    static void testMethod1(){
        Account acc = TestDataFactorySobha.createAccount(null);
        insert acc;
        Account acc2 = TestDataFactorySobha.createAccount(null);
        insert acc2;
        Country_Code_Master__c codeMaster = new Country_Code_Master__c();
        codeMaster.Country_Name__c = 'India';
        codeMaster.Country_Code__c = '+91';
        codeMaster.Phone_length__c = 13;
        insert codeMaster;
        Contact cont = TestDataFactorySobha.createContact(null);
        cont.Birthdate = System.Today();
        cont.Country_Code__c = '+91';
        cont.VCC1__Mobile_Encrypted__c = '123454321';
        cont.AccountId =acc.Id;
        cont.VCC1__Phone_Encrypted__c = '9876543210';
        cont.VCC1__Calling_Number_Encrypted__c = '2345677777';
        cont.CLE__Mobile_Encrypted__c = '1234343434';
        cont.CLE__Phone_Encrypted__c = '2345455234';
        cont.Passport_Number__c = '65432123';
        cont.Emirates_ID__c = '784-1234-1234567-1';
        cont.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        insert cont;
        Contact cont2 = TestDataFactorySobha.createContact(null);
        cont2.Birthdate = System.Today();
        cont2.CLE__Phone_Encrypted__c = '2345455234';
        cont2.CLE__Mobile_Encrypted__c = '23432323';
        cont2.Emirates_ID__c = '784-1234-1234567-1';
        cont2.AccountId =acc.Id;
        cont2.VCC1__Calling_Number_Encrypted__c = '2323232323232';
        cont2.Passport_Number__c = '65432123';
        cont2.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        insert cont2;
        Contact cont3 = TestDataFactorySobha.createContact(null);
        cont3.Birthdate = System.Today();
        cont3.CLE__Phone_Encrypted__c = '2345455234';
        cont3.CLE__Mobile_Encrypted__c = '23432323';
        cont3.Emirates_ID__c = '784-1234-1214237-1';
        cont3.AccountId =acc.Id;
        cont3.VCC1__Calling_Number_Encrypted__c = '2323232323232';
        cont3.Passport_Number__c = '65432123';
        cont3.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        insert cont3;
        
        cont.LastName = 'testCont';
        cont.Emirates_ID__c = '784-1234-1214237-1';
        Update cont;
        
        List<Contact> conList = new List<Contact>();
        conList.add(cont);
        cont2.AccountId = acc2.Id;
        conList.add(cont2);
        cont3.AccountId = acc2.Id;
        conList.add(cont3);

        ContactTriggerHelper.updateNameEmailAddress(conList);
    }
}