force-app/main/default/objects/Account/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Dialing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>United Arab Emirates</fullName>
                <default>true</default>
                <label>United Arab Emirates</label>
            </value>
            <value>
                <fullName>Singapore</fullName>
            </value>
            <value>
                <fullName>United Kingdom</fullName>
            </value>
            <value>
                <fullName>United States</fullName>
            </value>
            <value>
                <fullName>Hong Kong</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Costa Rica</fullName>
            </value>
            <value>
                <fullName>Cote D&apos;Ivoire</fullName>
            </value>
            <value>
                <fullName>Denmark</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Finland</fullName>
            </value>
            <value>
                <fullName>France</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>Ghana</fullName>
            </value>
            <value>
                <fullName>Greece</fullName>
            </value>
            <value>
                <fullName>Hungary</fullName>
            </value>
            <value>
                <fullName>Indonesia</fullName>
            </value>
            <value>
                <fullName>Ireland</fullName>
            </value>
            <value>
                <fullName>Israel</fullName>
            </value>
            <value>
                <fullName>Italy</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/Applicant_Details__c.object-meta.xml
<CustomObject>
    <label>Applicant Details</label>
    <nameField>
        <label>Applicant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ApplicantDetails</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant_Details__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UAE</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bonaire</fullName>
            </value>
            <value>
                <fullName>Bosnia-Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant_Details__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Country_City_State_Mapping__c/Country_City_State_Mapping__c.object-meta.xml
<CustomObject>
    <label>Country City State Mapping</label>
    <nameField>
        <displayFormat>CCS-{00000}</displayFormat>
        <label>Country City State Mapping Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Country_City_State_Mappings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ApplicantLocationInputController.cls
public class ApplicantLocationInputController {

  /*@AuraEnabled(Cacheable = true)
    public static List<Applicant_Details__c> getCurrentValues( String recordId) {
        return[SELECT Id,Country__c,City__c, State__c 
               FROM Applicant_Details__c 
              WHERE Id = :recordId];
    }*/
    
    @AuraEnabled(Cacheable = true)
    public static List<pickListWrapper> getCountryList() {
        List<pickListWrapper> countryWrapList = new List<pickListWrapper>();
        // Describe the Account.Industry field
        Schema.DescribeFieldResult fieldDescription = Applicant_Details__c.Country__c.getDescribe();
        // Get picklist values from field description
        List<Schema.PicklistEntry> entries = fieldDescription.getPicklistValues();
        // Do something with entries
        for (Schema.PicklistEntry entry : entries) {
            if(entry.isActive()) {
                pickListWrapper countryWrap = new pickListWrapper();
                countryWrap.label = entry.getLabel();
                countryWrap.value = entry.getValue();
                countryWrapList.add(countryWrap);
            }
        }
        return countryWrapList;
    }
    
    @AuraEnabled(Cacheable = true)
    public Static List<pickListWrapper> getStates(String country) {
        List<pickListWrapper> stateWrapList = new List<pickListWrapper>();
        Set<String> addedCities = new Set<String>();
        List<Country_City_State_Mapping__c> countryRelatedStateList = [SELECT ID,Country__c, State__c,City__c 
                                                                       FROM Country_City_State_Mapping__c
                                                                       WHERE Country__c =:country];
        if(!countryRelatedStateList.isEmpty()) {
            for(Country_City_State_Mapping__c countryStateMap : countryRelatedStateList) {
                if(!addedCities.contains(countryStateMap.State__c)) {
                    pickListWrapper stateWrap = new pickListWrapper();
                    stateWrap.label = countryStateMap.State__c;
                    stateWrap.value = countryStateMap.State__c;
                    stateWrapList.add(stateWrap);
                    addedCities.add(countryStateMap.State__c);
                }
            }
        }
        system.debug(stateWrapList);
        return stateWrapList;
    }
    
    @AuraEnabled(Cacheable = true)
    public Static List<pickListWrapper> getCities(String state) {
        List<pickListWrapper> cityWrapList = new List<pickListWrapper>();
        Set<String> addedCities = new Set<String>();
        List<Country_City_State_Mapping__c> countryRelatedStateList = [SELECT ID,Country__c, State__c,City__c 
                                                                       FROM Country_City_State_Mapping__c
                                                                       WHERE State__c =:state];
        if(!countryRelatedStateList.isEmpty()) {
            for(Country_City_State_Mapping__c countryCityMap : countryRelatedStateList) {
                if(!addedCities.contains(countryCityMap.City__c)) {
                    pickListWrapper cityWrap = new pickListWrapper();
                    cityWrap.label = countryCityMap.City__c;
                    cityWrap.value = countryCityMap.City__c;
                    cityWrapList.add(cityWrap);
                    addedCities.add(countryCityMap.City__c);
                }
            }
        }
        system.debug(cityWrapList);
        return cityWrapList;
    }

    Public class pickListWrapper {
        @AuraEnabled
        Public String label{get;set;}
        @AuraEnabled
        Public String value{get;set;}
    }
}