force-app/main/default/objects/Account/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Modified_by_guest_user__c.field-meta.xml
<CustomField>
    <fullName>Modified_by_guest_user__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Modified by guest user</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/PropStrength__Broker_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>PropStrength__Broker_Approval_Status__c</fullName>
    <label>Broker Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Broker Registration Done, pending with CHRM Manager</fullName>
                <label>Pending with CHRM Manager</label>
            </value>
            <value>
                <fullName>Pending with CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Approved by CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Agreement Created and Sent for Signatures</fullName>
            </value>
            <value>
                <fullName>Signed Agreement Received - Documents Awaiting</fullName>
            </value>
            <value>
                <fullName>All Missing Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>NOC Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh/ Sent for final signatures</fullName>
                <label>Pending with Ashish Parakh</label>
            </value>
            <value>
                <fullName>Executed Agreement Sent to CHRM</fullName>
            </value>
            <value>
                <fullName>Executed Agreement Sent to Broker</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Broker Registration Done</fullName>
            </value>
            <value>
                <fullName>Broker Empanelment Form Filled</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM Manager</fullName>
            </value>
            <value>
                <fullName>Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh</fullName>
                <label>Pending with Ashish Parakh1</label>
            </value>
            <value>
                <fullName>Rejected by Audit</fullName>
            </value>
            <value>
                <fullName>NOC Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and sent for signature</fullName>
            </value>
            <value>
                <fullName>NOC Is in Process</fullName>
            </value>
            <value>
                <fullName>Agreement - approved by CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Pending with CHRM / Rejected with CHRM</fullName>
            </value>
            <value>
                <fullName>Agreement Is in process</fullName>
            </value>
            <value>
                <fullName>Approved - by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Agreement Generated</fullName>
            </value>
            <value>
                <fullName>Executed Agreement sent to CRHM</fullName>
            </value>
            <value>
                <fullName>Signed Agreement Received - Documents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Registration_Link_Expiry_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Registration_Link_Expiry_Date_Time__c</fullName>
    <label>Registration Link Expiry Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/BR_Document_History__c/BR_Document_History__c.object-meta.xml
<CustomObject>
    <description>This object is used in broker portal my profile page where the document expiry has to be noted</description>
    <label>BR Document History</label>
    <nameField>
        <displayFormat>BRH-{0000}</displayFormat>
        <label>BR Document History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Document Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BR_Document_History__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BR Document Histories (Broker Account)</relationshipLabel>
    <relationshipName>BR_Document_Histories1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BR_Document_History__c/fields/Broker_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Broker_Renewal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Renewal</label>
    <referenceTo>Broker_Renewal__c</referenceTo>
    <relationshipLabel>BR Document Histories</relationshipLabel>
    <relationshipName>BR_Document_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BR_Document_History__c/fields/Expiry_date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_date__c</fullName>
    <label>Expiry date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BR_Document_History__c/fields/File_Type__c.field-meta.xml
<CustomField>
    <fullName>File_Type__c</fullName>
    <label>File Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Vat Excemption</fullName>
            </value>
            <value>
                <fullName>Visa Copy</fullName>
            </value>
            <value>
                <fullName>Emirates Id</fullName>
            </value>
            <value>
                <fullName>RERA Certificate</fullName>
            </value>
            <value>
                <fullName>Secondary Document</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/Broker_Renewal__c.object-meta.xml
<CustomObject>
    <label>Broker Renewal</label>
    <nameField>
        <displayFormat>BRN-{0000}</displayFormat>
        <label>Broker Renewal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Renewal</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Renewal__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Renewal</relationshipLabel>
    <relationshipName>Broker_Renewal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/fields/Modified_by_guest_user__c.field-meta.xml
<CustomField>
    <fullName>Modified_by_guest_user__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Modified by guest user</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/fields/Registration_Link_Expiry_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Registration_Link_Expiry_Date_Time__c</fullName>
    <label>Registration Link Expiry Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ContentDistributionBatch_Test.cls
@isTest
private class ContentDistributionBatch_Test {
    @testSetup
    static void setupTestData() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User' LIMIT 1];
        User guestUser = new User(
            Alias = 'bguest',
            Email = 'broker_guestuser@test.com',
            EmailEncodingKey = 'UTF-8',
            LastName = 'Broker Account Site Guest User',
            LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US',
            ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            UserName = 'broker_guestuser@test.com'
        );
        insert guestUser;
        System.runAs(guestUser) {
            Account acc = TestDataFactorySobha.createAccount(null);
            acc.PropStrength__Broker_Approval_Status__c = 'Broker Empanelment Form Filled';
            acc.Registration_Link_Expiry_Date_Time__c = System.now().addDays(2);
            acc.Modified_by_guest_user__c = true;
            insert acc;
            
            Broker_Renewal__c brkRenew= TestDataFactorySobha.createBrokerRenewal(null);
            brkRenew.Modified_by_guest_user__c = true;
            insert brkRenew;
            
            BR_Document_History__c brd= new BR_Document_History__c();
            brd.Expiry_date__c=Date.Today().addDays(2);
            brd.File_Name__c='TestFile.pdf';
            brd.File_Type__c='Test';
            brd.Broker_Account__c = acc.Id;
            insert brd;
            
            BR_Document_History__c brd2  = new BR_Document_History__c();
            brd2.Expiry_date__c=Date.Today().addDays(2);
            brd2.File_Name__c='TestFile.pdf';
            brd2.File_Type__c='Test';
            brd2.Broker_Renewal__c = brkRenew.Id;
            insert brd2;
            
            ContentVersion contentVersion = new ContentVersion(
                Title = 'Noc.pdf',
                PathOnClient = 'Penguins.jpg',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true
            );
            insert contentVersion; 
            
            ContentVersion contentVersion2 = new ContentVersion(
                Title = 'Noc.pdf',
                PathOnClient = 'Penguins.jpg',
                VersionData = Blob.valueOf('Test Content'),
                IsMajorVersion = true
            );
            insert contentVersion2;
            
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            
            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = brd.id;
            cdl.ContentDocumentId = documents[0].Id;
            cdl.shareType = 'V';
            insert cdl;
            
            ContentDocumentLink cdl2 = New ContentDocumentLink();
            cdl2.LinkedEntityId = brd2.id;
            cdl2.ContentDocumentId = documents[1].Id;
            cdl2.shareType = 'V';
            insert cdl2;
        }
    }

    @isTest
    static void testExecuteBatch() {
        Test.startTest();
        ContentDistributionBatch batch = new ContentDistributionBatch();
        Database.executeBatch(batch);
        Test.stopTest();
    }
}