force-app/main/default/objects/Account/fields/MasterRecord__c.field-meta.xml
<CustomField>
    <fullName>MasterRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Master Record</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Call_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Call_Attempt_Status__c</fullName>
    <label>Call Attempt Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
            </value>
            <value>
                <fullName>Not Actioned</fullName>
            </value>
            <value>
                <fullName>Visit confirmed</fullName>
            </value>
            <value>
                <fullName>Visit proposed</fullName>
            </value>
            <value>
                <fullName>Junk Lead</fullName>
            </value>
            <value>
                <fullName>Invalid Enquiry</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Not Actioned - No Shuffle</fullName>
            </value>
            <value>
                <fullName>Not Shuffle</fullName>
            </value>
            <value>
                <fullName>Recycled Lead</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Follow up - email</fullName>
            </value>
            <value>
                <fullName>Follow up - social</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Source__c</fullName>
    <label>Lead Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>inbound-emailer</fullName>
            </value>
            <value>
                <fullName>Print</fullName>
                <label>print</label>
            </value>
            <value>
                <fullName>Television</fullName>
                <label>television</label>
            </value>
            <value>
                <fullName>Outdoor</fullName>
                <label>outdoor</label>
            </value>
            <value>
                <fullName>Radio</fullName>
                <label>radio</label>
            </value>
            <value>
                <fullName>Events</fullName>
                <label>events</label>
            </value>
            <value>
                <fullName>Exhibitions</fullName>
                <label>exhibitions</label>
            </value>
            <value>
                <fullName>Cityscape</fullName>
                <label>cityscape</label>
            </value>
            <value>
                <fullName>Tollfree</fullName>
                <label>tollfree</label>
            </value>
            <value>
                <fullName>Facebook LeadGen</fullName>
                <label>facebook leadGen</label>
            </value>
            <value>
                <fullName>Cairo_07FEB2019_Tarek</fullName>
                <label>cairo_07FEB2019_tarek</label>
            </value>
            <value>
                <fullName>Lagos_12Jan2019_Anil</fullName>
                <label>lagos_12Jan2019_Anil</label>
            </value>
            <value>
                <fullName>Affiliate-araby-ads</fullName>
                <label>affiliate-araby-ads</label>
            </value>
            <value>
                <fullName>Direct-website</fullName>
                <label>direct-website</label>
            </value>
            <value>
                <fullName>Email</fullName>
                <label>email</label>
            </value>
            <value>
                <fullName>Google-display</fullName>
                <label>google-display</label>
            </value>
            <value>
                <fullName>Google-search</fullName>
                <label>google-search</label>
            </value>
            <value>
                <fullName>Portal-bayut</fullName>
                <label>portal-bayut</label>
            </value>
            <value>
                <fullName>Portal-dubizzle</fullName>
                <label>portal-dubizzle</label>
            </value>
            <value>
                <fullName>Portal-propertyfinder</fullName>
                <label>portal-propertyfinder</label>
            </value>
            <value>
                <fullName>Publisher-etiquettels</fullName>
                <label>publisher-etiquettels</label>
            </value>
            <value>
                <fullName>Publisher-linkedin</fullName>
                <label>publisher-linkedin</label>
            </value>
            <value>
                <fullName>Publisher-nabd</fullName>
                <label>publisher-nabd</label>
            </value>
            <value>
                <fullName>Publisher-oath</fullName>
                <label>publisher-oath</label>
            </value>
            <value>
                <fullName>Publisher-skynews</fullName>
                <label>publisher-skynews</label>
            </value>
            <value>
                <fullName>Publisher-taboola</fullName>
                <label>publisher-taboola</label>
            </value>
            <value>
                <fullName>Publisher-times-of-india</fullName>
                <label>publisher-times-of-india</label>
            </value>
            <value>
                <fullName>SMS</fullName>
                <label>sms</label>
            </value>
            <value>
                <fullName>Social-facebook</fullName>
                <label>social-facebook</label>
            </value>
            <value>
                <fullName>Social-facebook-messenger</fullName>
                <label>social-facebook-messenger</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/MasterRecord__c.field-meta.xml
<CustomField>
    <fullName>MasterRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MasterRecord</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/UTM_Campaign__c.field-meta.xml
<CustomField>
    <fullName>UTM_Campaign__c</fullName>
    <label>UTM Campaign</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Lead_Sub_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sub_Source__c</fullName>
    <label>Lead Sub Source</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>LeadSource</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Live ads</fullName>
            </value>
            <value>
                <fullName>Print</fullName>
            </value>
            <value>
                <fullName>Television</fullName>
            </value>
            <value>
                <fullName>Outdoor</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Exhibitions</fullName>
            </value>
            <value>
                <fullName>Mall</fullName>
            </value>
            <value>
                <fullName>Cityscape</fullName>
            </value>
            <value>
                <fullName>Tollfree</fullName>
            </value>
            <value>
                <fullName>Facebook LeadGen</fullName>
            </value>
            <value>
                <fullName>Cairo_07FEB2019_Tarek</fullName>
            </value>
            <value>
                <fullName>Lagos_12Jan2019_Anil</fullName>
            </value>
            <value>
                <fullName>bayut</fullName>
            </value>
            <value>
                <fullName>dubizzle</fullName>
            </value>
            <value>
                <fullName>affiliate-araby-ads</fullName>
            </value>
            <value>
                <fullName>direct-website</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>google-display</fullName>
            </value>
            <value>
                <fullName>google-search</fullName>
            </value>
            <value>
                <fullName>portal-bayut</fullName>
            </value>
            <value>
                <fullName>portal-dubizzle</fullName>
            </value>
            <value>
                <fullName>portal-propertyfinder</fullName>
            </value>
            <value>
                <fullName>publisher-etiquettels</fullName>
            </value>
            <value>
                <fullName>publisher-linkedin</fullName>
            </value>
            <value>
                <fullName>publisher-nabd</fullName>
            </value>
            <value>
                <fullName>publisher-oath</fullName>
            </value>
            <value>
                <fullName>publisher-skynews</fullName>
            </value>
            <value>
                <fullName>publisher-taboola</fullName>
            </value>
            <value>
                <fullName>publisher-times-of-india</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Next_Action_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Action_Date__c</fullName>
    <label>Presales Next Action Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/S_Budget_In_lacs__c.field-meta.xml
<CustomField>
    <fullName>S_Budget_In_lacs__c</fullName>
    <label>Budget (In Mn)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Task_Type__c.field-meta.xml
<CustomField>
    <fullName>Task_Type__c</fullName>
    <label>Task Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Visit</fullName>
            </value>
            <value>
                <fullName>Call back by SM</fullName>
            </value>
            <value>
                <fullName>Revisit</fullName>
            </value>
            <value>
                <fullName>Booking Procedure</fullName>
            </value>
            <value>
                <fullName>No Further Action Needed</fullName>
            </value>
            <value>
                <fullName>Meeting</fullName>
            </value>
            <value>
                <fullName>Email Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/reEnquiryLayoutForTSAController_isTest.cls
@isTest
public class reEnquiryLayoutForTSAController_isTest {
    
    @isTest  
  static void TaskTest() {
    Project__c p = createProject('Xa_prj','111');
    Account acc = createPATemplate('TestPA1' , 'testleada@ozonetest.com', '9876544441', false);
               
    List<Lead> llist = createLead(3);
    List<Opportunity>  oList = createOpptyForAccount(acc.Id, p.Id, 3);
   
      task t = new task();
      t.Subject = 'New Task';
      t.Task_Type__c = 'Sales Call';
      t.Call_Attempt_Status__c = 'No Contact';
      t.Next_Action_Date__c = System.today().adddays(5);
      t.activityDate = System.Today();
      t.whatId = oList[0].Id;
      t.UTM_Campaign__c = 'test';
      t.call_time__c = TaskManagementServices.FormatTime(system.now());
      insert t;
      
      reEnquiryLayoutForTSAController.getTaskData(lList[0].Id);

}
    
    public static Project__c createProject(String ProjName, String ProjectCode){
        Project__c objProject = new Project__c(Name = ProjName, Project_Code__c = projectCode);
        insert objProject;
        return objProject;
    }
    public static Account createPATemplate(String accName, String Email, String Mobile, Boolean isMaster) {
    List<RecordType> personAccountRecordType =  [SELECT Id FROM RecordType WHERE Name = 'Person Account' and SObjectType = 'Account'];
    Account a = new Account(lastName=accName, personEmail = email, personMobilePhone= Mobile, RecordTypeId = personAccountRecordType[0].id, MasterRecord__c = isMaster);
    insert a;
    return a;
  }
    public static List<Lead> createLead(Integer numofLeads) {
    List<Lead> leads = new List<Lead>();
        for(Integer i=0; i<numofLeads; i++) {            
            Lead l = new Lead(firstName = 'first' , lastName='radiusLead' + i, Email='radiuslead' +i +'@radiustest.com' , mobilePhone='123456789' + i);            
            leads.add(l);
        }
        insert leads;
        return leads;  
  }
    public static List<Opportunity> createOpptyForAccount(Id  accId, Id ProjId, Integer numOfOpp){
    List<Opportunity> oList = new List<Opportunity>();
    Date closeDate; 
    for(Integer i =0;i<numOfOpp; i++){
      closeDate = Date.newInstance(2015, 8,29);
      Opportunity o = new Opportunity(Name = 'Opp-'+i, StageName='Opportunity Identified', Amount=5000000, AccountId =accId, Status__c ='Active', LeadSource = 'Direct', Lead_Sub_source__c = 'Cross Project', S_Budget_In_lacs__c = 5000000, Project__c = ProjId,closeDate=System.today());
      oList.add(o);            
    }
    insert oList;
    return oList;
  }
}