force-app/main/default/objects/Account/fields/Modified_by_guest_user__c.field-meta.xml
<CustomField>
    <fullName>Modified_by_guest_user__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Modified by guest user</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/BR_Document_History__c/BR_Document_History__c.object-meta.xml
<CustomObject>
    <description>This object is used in broker portal my profile page where the document expiry has to be noted</description>
    <label>BR Document History</label>
    <nameField>
        <displayFormat>BRH-{0000}</displayFormat>
        <label>BR Document History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BR Document Histories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BR_Document_History__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>BR Document Histories (Broker Account)</relationshipLabel>
    <relationshipName>BR_Document_Histories1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BR_Document_History__c/fields/Broker_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Broker_Renewal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Renewal</label>
    <referenceTo>Broker_Renewal__c</referenceTo>
    <relationshipLabel>BR Document Histories</relationshipLabel>
    <relationshipName>BR_Document_Histories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BR_Document_History__c/fields/Content_Distribution_Created__c.field-meta.xml
<CustomField>
    <fullName>Content_Distribution_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Content Distribution Created</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/Broker_Renewal__c.object-meta.xml
<CustomObject>
    <label>Broker Renewal</label>
    <nameField>
        <displayFormat>BRN-{0000}</displayFormat>
        <label>Broker Renewal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Renewal</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Renewal__c/fields/Broker_Account__c.field-meta.xml
<CustomField>
    <fullName>Broker_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Broker Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Broker</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Broker Renewal</relationshipLabel>
    <relationshipName>Broker_Renewal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Broker_Renewal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/fields/Modified_by_guest_user__c.field-meta.xml
<CustomField>
    <fullName>Modified_by_guest_user__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Modified by guest user</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ContentDistributionBatch.cls
global class ContentDistributionBatch Implements Database.Batchable<sObject>, Schedulable {
    global List<ContentDocumentLink> start(Database.BatchableContext BC) {
        return [SELECT Id, ContentDocumentId, LinkedEntityId 
                FROM ContentDocumentLink 
                WHERE ContentDocumentId IN (SELECT Id 
                                            FROM ContentDocument 
                                            WHERE CreatedBy.Name = 'Broker Account Site Guest User')];
    }

    public void execute(SchedulableContext context) {
        ContentDistributionBatch batch = new ContentDistributionBatch();
        Database.executeBatch(batch);
    }

    global void execute(Database.BatchableContext BC, List<ContentDocumentLink> scope) {
        List<ContentDocumentLink> createDistribution = new List<ContentDocumentLink>();
        List<ContentDocumentLink> tempCdlList = new List<ContentDocumentLink>();
        Map<Id, BR_Document_History__c> bhMap = new Map<Id, BR_Document_History__c>();
        Set<Id> bhParentId = new Set<Id>();

        for(ContentDocumentLink cd : scope) {
            if(cd.LinkedEntityId != null) {
                String parentName = cd.LinkedEntityId.getSObjectType().getDescribe().getName();
                if(parentName.equalsIgnoreCase('BR_Document_History__c')) {
                    bhParentId.add(cd.LinkedEntityId);
                    tempCdlList.add(cd);
                }
            }
        }

        if(!tempCdlList.isEmpty()) {
            if(!bhParentId.isEmpty()) {
                bhMap = new Map<Id, BR_Document_History__c>([SELECT Id FROM BR_Document_History__c WHERE Id IN :bhParentId AND (Broker_Renewal__r.Modified_by_guest_user__c = true OR Broker_Account__r.Modified_by_guest_user__c = true) AND Content_Distribution_Created__c = FALSE]);
            }

            Map<Id, BR_Document_History__c> updateBrHistory = new Map<Id, BR_Document_History__c>();
            
            for(ContentDocumentLink cd : tempCdlList) {
                String parentName = cd.LinkedEntityId.getSObjectType().getDescribe().getName();
                if(parentName.equalsIgnoreCase('BR_Document_History__c') && !bhMap.isEmpty() && bhMap.containsKey(cd.LinkedEntityId)) {
                    createDistribution.add(cd);
                    if(!updateBrHistory.containsKey(cd.LinkedEntityId)) {
                        updateBrHistory.put(cd.LinkedEntityId, new BR_Document_History__c(Id=cd.LinkedEntityId, Content_Distribution_Created__c = true));
                    }
                }
            }

            if(!createDistribution.isEmpty()) {
                ContentDocumentLinkTriggerHelper.createContentDistribution(createDistribution);
            }
            if(!updateBrHistory.isEmpty()) {
                update updateBrHistory.values();
            }
        }
    }

    global void finish(Database.BatchableContext BC) {
        Datetime nextRunTime = System.now().addMinutes(2);
        String cronExp = nextRunTime.format('s m H d M \'?\' yyyy');
        //System.schedule('ContentDistributionBatch_5minutes'+System.now().addDays(Integer.valueof((Math.random() * 100))), cronExp, new ContentDistributionBatch() );
    }
}