force-app/main/default/objects/Account/fields/Sales_Director__c.field-meta.xml
<CustomField>
    <fullName>Sales_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <label>Sales Manager</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit#</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Mode__c.field-meta.xml
<CustomField>
    <fullName>Mode__c</fullName>
    <label>Mode</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTC Deposits</fullName>
                <label>OTC Deposit(Cash counter)</label>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Website</fullName>
            </value>
            <value>
                <fullName>CDM Cash</fullName>
                <label>CDM Cash (Cash Deposit in Machine)</label>
            </value>
            <value>
                <fullName>CDM Cheque</fullName>
                <label>CDM Cheque (Cheque Deposit in Machine)</label>
            </value>
            <value>
                <fullName>International Wire Transfer</fullName>
                <label>IWT(International)</label>
            </value>
            <value>
                <fullName>Domestic Wire Transfer</fullName>
                <label>DWT(Domestic)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Accounts Approval</fullName>
            </value>
            <value>
                <fullName>Approved by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by Accounts</fullName>
            </value>
            <value>
                <fullName>Pending for Sales Ops Approval</fullName>
            </value>
            <value>
                <fullName>Rejected by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Resubmitted to SM/SD</fullName>
            </value>
            <value>
                <fullName>Approved by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Submitted to Accounts for Amount Confirmation</fullName>
            </value>
            <value>
                <fullName>Amount Confirmed by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by System</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Payment Link sent to Customer</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>PR was Approved- Booking is cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2 AND 5) OR (1 AND 2 AND 3 AND 4) OR (6 AND 2 AND 3 AND 4)</booleanFilter>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Not_Available_for_Sales__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>$User.Id</field>
            <operation>equals</operation>
            <valueField>Unit__c.Allocated_SM__r.Id</valueField>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>notEqual</operation>
            <value>Unreleased</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Allocated_SM__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Hold</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Unit_Hold__c.field-meta.xml
<CustomField>
    <fullName>Unit_Hold__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit Hold</label>
    <referenceTo>Unit_Hold__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Unit_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Status__c</fullName>
    <label>Unit Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Available</fullName>
            </value>
            <value>
                <fullName>Refuge</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
            <value>
                <fullName>Unreleased</fullName>
            </value>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>Requested For EOI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Hold__c/Unit_Hold__c.object-meta.xml
<CustomObject>
    <label>Unit Hold</label>
    <nameField>
        <displayFormat>UH-{0000}</displayFormat>
        <label>Unit Hold  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Unit Hold</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit_Hold__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Unit Hold</relationshipLabel>
    <relationshipName>Unit_Hold</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Hold__c/fields/Sales_Director__c.field-meta.xml
<CustomField>
    <fullName>Sales_Director__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Director</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit_Hold</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Hold__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit_Hold2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Hold__c/fields/Sales_VP__c.field-meta.xml
<CustomField>
    <fullName>Sales_VP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales VP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit_Hold1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Hold__c/fields/SVP__c.field-meta.xml
<CustomField>
    <fullName>SVP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SVP</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Unit_Hold3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Hold__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Unit</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND 2</booleanFilter>
        <filterItems>
            <field>Unit__c.Unit_Status__c</field>
            <operation>equals</operation>
            <value>Available</value>
        </filterItems>
        <filterItems>
            <field>Unit__c.Not_Available_for_Sales__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Unit Hold</relationshipLabel>
    <relationshipName>Unit_Hold</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit_Hold__c/fields/Unit_Hold_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Unit_Hold_Approval_Status__c</fullName>
    <label>Unit Hold Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending with VP</fullName>
            </value>
            <value>
                <fullName>Pending with CSO</fullName>
            </value>
            <value>
                <fullName>Approved by VP</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected by VP</fullName>
            </value>
            <value>
                <fullName>Rejected by CSO</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Pending with SVP</fullName>
            </value>
            <value>
                <fullName>Approved by SVP</fullName>
            </value>
            <value>
                <fullName>Rejected by SVP</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
                <isActive>false</isActive>
                <label>Rejected</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit_Hold__c/fields/Unit_Hold_Requested__c.field-meta.xml
<CustomField>
    <fullName>Unit_Hold_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unit Hold Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVAILABLE</fullName>
                <label>Available</label>
            </value>
            <value>
                <fullName>BUSY</fullName>
                <label>Busy</label>
            </value>
            <value>
                <fullName>BREAK</fullName>
                <label>Break</label>
            </value>
            <value>
                <fullName>OUTCALL</fullName>
                <label>OutCall</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UnitHoldTriggerHandler.cls
public without sharing class UnitHoldTriggerHandler {
    public static void beforeInsert(List<Unit_Hold__c> newList){
        User currentUser = [select id,firstname,lastname,managerId,manager.managerid,manager.manager.managerid,userrole.name from user where id =: userinfo.getUserId()];
         for(Unit_Hold__c uh : newList){
            if(uh.Unit_Hold_Requested__c == true ){
                uh.status__c='inactive';
                if(currentUser.userrole.name != null 
                && currentUser.userrole.name.containsIgnoreCase('Sales Manager')){
                    uh.sales_manager__c = currentUser.id;
                    uh.sales_Director__c = currentUser.managerid;
                    uh.sales_vp__c = currentUser.manager.managerid;
                    uh.SVP__c = currentUser.manager.manager.managerid;
                }else if(currentUser.userrole.name != null 
                && currentUser.userrole.name.containsIgnoreCase('Sales Head')){
                    uh.sales_Director__c = currentUser.id;
                    uh.sales_vp__c = currentUser.managerid;
                    uh.SVP__c = currentUser.manager.managerid;
                }
                uh.Reason__c = 'Requested by Sales Manager/Director - '+currentUser.FirstName +' '+currentUser.lastName;
                uh.Unit_Hold_Approval_Status__c = 'Submitted';
            }
        }
        
    }
    public static void afterInsert(List<Unit_Hold__c> newList){
        /*List<unit_hold__Share> shareRecordToInsert = new List<unit_hold__Share>();
        for(Unit_Hold__c u : newList){
            if(u.Unit_Hold_Requested__c == true ){
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('Submitting request for unit hold approval');
                req1.setObjectId(u.id);
                // Submit on behalf of a specific submitter
                req1.setSubmitterId(userinfo.getuserid()); 
                if(test.isRunningTest()){
                // Submit the approval request for the account
                Approval.ProcessResult result = Approval.process(req1);
                }
                
            }
        }*/
        //insert shareRecordToInsert;
    }
    public static void updateStatusToActive(List<Unit_Hold__c> newList,Map<Id,Unit_Hold__c> oldMap){
        for(Unit_Hold__c uh : newList){
            if(uh.Unit_Hold_Approval_Status__c == 'Approved' && uh.Unit_Hold_Approval_Status__c != oldMap.get(uh.id).Unit_Hold_Approval_Status__c){
               uh.status__c = 'Active';
            }
        }
    }
    public static void validateApproval(List<Unit_Hold__c> newList,Map<Id,Unit_Hold__c> oldMap){
        List<Id> unitsToQuery = new List<Id>();
        List<Unit_Hold__c> unitHoldToValidate = new List<Unit_Hold__c>();
        for(Unit_Hold__c uh : newList){
            if(uh.Unit_Hold_Approval_Status__c != null 
            && uh.Unit_Hold_Approval_Status__c != oldMap.get(uh.id).Unit_Hold_Approval_Status__c
            && (uh.Unit_Hold_Approval_Status__c.contains('Approved')
        || uh.Unit_Hold_Approval_Status__c.contains('Pending'))){
                unitsToQuery.add(uh.unit__c);
                unitHoldToValidate.add(uh);
            }
        }
        if(!unitsToQuery.isEmpty()){
            Map<Id,Unit__c> mapOfUnit = new Map<Id,Unit__c>([SELECT ID,unit_status__c FROM Unit__c WHERE ID IN: unitsToQuery]);
            List<Payment_Request__c> prList = [SELECT ID,unit__c,Status__c FROM Payment_Request__c
            WHERE ((Mode__c != 'Website' )
            OR (Mode__c ='Website' AND Payment_Request_Wrapper__r.Payment_Link_Expiry__c >: System.now()))
            AND (Not (Status__c Like '%Rejected%'))
            AND Status__c != 'PR was Approved- Booking is cancelled'
                and unit__c IN: unitsToQuery
                and status__c != null];
            Map<Id,List<Payment_Request__c>> mapUnitToPaymentRequest =  new Map<Id,List<Payment_Request__c>>();
            for(Payment_Request__c pr : prList){
                if(!mapUnitToPaymentRequest.containsKey(pr.unit__C)){
                    mapUnitToPaymentRequest.put(pr.unit__C,new List<Payment_Request__c>());
                }
                mapUnitToPaymentRequest.get(pr.unit__C).add(pr);
            }
            for(Unit_Hold__c uh : unitHoldToValidate){
                if(mapOfUnit.containsKey(uh.unit__c) && (mapOfUnit.get(uh.unit__c).unit_status__c != 'Available'
                || (mapUnitToPaymentRequest.get(uh.unit__C)!= null && mapUnitToPaymentRequest.get(uh.unit__C).size() > 0))
                ){
                    if(mapUnitToPaymentRequest.get(uh.unit__C)!= null && mapUnitToPaymentRequest.get(uh.unit__C).size() > 0){
                    for(Payment_Request__c pr : mapUnitToPaymentRequest.get(uh.unit__C)){
                        if(pr.status__c.contains('Approved') ){
                            uh.addError('Unit chosen has been already placed on hold due to PR being approved.');
                        }else{
                            uh.addError('This request cannot be submitted as PR has been already submitted for this unit');
                        }
                        
                    }
                }
                    
                }
            }
        }
    }
    public static void updateSmSdOnUnit(List<Unit_Hold__c> newList,Map<Id,Unit_Hold__c> oldMap){
        List<Unit__c> unitToUpdate = new List<Unit__c>();
        List<Unit_Hold__c> unitHoldToUpdate = new List<Unit_Hold__c>();
        for(Unit_Hold__c uh : newList){
            if(uh.Unit_Hold_Approval_Status__c == 'Approved' && uh.Unit_Hold_Approval_Status__c != oldMap.get(uh.id).Unit_Hold_Approval_Status__c){
                Integer numberOfHours = 0;
                if(uh.Request_Time__c.containsIgnoreCase('Hour')){
                    numberOfHours = Integer.valueOf(uh.Request_Time__c.split(' ')[0]);
                }else{
                    numberOfHours =  Integer.valueOf(uh.Request_Time__c.split(' ')[0])*24;
                }
                unitToUpdate.add(new unit__c(id = uh.unit__c, 
                allocated_sm__c = uh.createdbyid,
                SM_Allocation_DateTime__c = system.now(),
                SM_Allocation_reset_hours__c = numberOfHours,
                unit_status__c = 'Hold',
                Time_To_Validate_PR__c = system.now().addHours(numberOfHours),
                Unit_Hold__c = uh.id
                ));
                unitHoldToUpdate.add(new Unit_Hold__C (id = uh.id , Time_To_Validate_PR__c = system.now().addHours(numberOfHours)));
            }
        }
        if(!unitToUpdate.isEmpty()){
            update unitToUpdate;
             //get all remaining unit hold and mark them rejected
            Set<Id> unitHoldIds = (new Map<Id, Unit_Hold__c>([SELECT Id FROM Unit_Hold__c where unit__c in : unitToUpdate 
            and Unit_Hold_Approval_Status__c like '%Pending%' and id not in: newList])).keySet();
            Set<Id> pIds = (new Map<Id, ProcessInstance>([SELECT Id,Status,TargetObjectId FROM ProcessInstance where Status='Pending' and TargetObjectId in :unitHoldIds])).keySet();
            Set<Id> pInstanceWorkitems = (new Map<Id, ProcessInstanceWorkitem>([SELECT Id,ProcessInstanceId FROM ProcessInstanceWorkitem WHERE ProcessInstanceId in :pIds])).keySet();
            for(Id uhId : unitHoldIds){
                unitHoldToUpdate.add(new Unit_Hold__C(id = uhId, rejection_reason__c = 'Rejected because '+newList[0].Name + 'has been approved'));
            }
            update unitHoldToUpdate;
           
            List<Approval.ProcessWorkitemRequest> allReq = new List<Approval.ProcessWorkitemRequest>(); 
            for (Id pInstanceWorkitemsId:pInstanceWorkitems){
                system.debug(pInstanceWorkitemsId);
                    Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
                    req2.setComments('Automated Rejection -  '+newList[0].name +' has been approved for '+newList[0].request_time__c);
                    req2.setAction('Reject'); //to approve use 'Approve'
                    req2.setNextApproverIds(new Id[] {UserInfo.getUserId()});

                    // Use the ID from the newly created item to specify the item to be worked
                    req2.setWorkitemId(pInstanceWorkitemsId);

                    // Add the request for approval
                    allReq.add(req2);
            }
            Approval.ProcessResult[] result2 =  Approval.process(allReq);
        }
       
    }
    public static void unitHoldRejectionValidation(List<Unit_Hold__c> newList , Map<Id,Unit_Hold__c> oldMap){
        for(Unit_Hold__c uh : newList){
        
            /*if(uh.Unit_Hold_Approval_Status__c != null 
            && uh.Unit_Hold_Approval_Status__c.contains('Rejected')
            && String.isblank(uh.rejection_reason__c)
            && uh.Unit_Hold_Approval_Status__c != oldMap.get(uh.id).Unit_Hold_Approval_Status__c){
                uh.addError('Please update rejection comments on unit hold record before and try again');
            }*/
            if(uh.Unit_Hold_Approval_Status__c != oldMap.get(uh.id).Unit_Hold_Approval_Status__c 
            && uh.Unit_Hold_Approval_Status__c != Null
            && !uh.Unit_Hold_Approval_Status__c.containsignorecase('Rejected')
            && uh.rejection_reason__c != null){
                uh.rejection_reason__c = null;
            }
            
        }

    }
    @future
    public static void updateComments(String triggerData, String triggerOldData){
        List<Unit_Hold__c> newRecords = (List<Unit_Hold__c>)Json.deserialize(triggerData,List<Unit_Hold__c>.class);
        Map<Id, Unit_Hold__c> oldMap = (Map<Id,Unit_Hold__c>)Json.deserialize(triggerOldData, Map<Id,Unit_Hold__c>.class);
        
        
        Set<Id> updatedRecordIds = new Set<Id>();
        
        for (Unit_Hold__c record : newRecords) {
            Unit_Hold__c oldRecord = oldMap.get(record.Id);
            if (record.Unit_Hold_Approval_Status__c != oldRecord.Unit_Hold_Approval_Status__c
            && record.Unit_Hold_Approval_Status__c != Null
            && record.Unit_Hold_Approval_Status__c.containsignorecase('Rejected')
           ) {
                updatedRecordIds.add(record.Id);
            }
        }
        
        if (!updatedRecordIds.isEmpty()) {
            list<Unit_Hold__c> recordsTUpdate = new list<Unit_Hold__c>();
            
            for (Id record : updatedRecordIds) {
                // Replace this with your logic to retrieve latest approval comment from related object
                String latestApprovalComment = getLatestApprovalComment(record);
                
                if (latestApprovalComment != null) {
                    recordsTUpdate.add(new Unit_Hold__c(id = record,rejection_reason__c=latestApprovalComment));
                }
            }
             
            if(recordsTUpdate.size()>0){
                system.debug('~~~ToUpdate: '+recordsTUpdate);
                update recordsTUpdate;
            }
            
            
            
        }
    }
    public static String getLatestApprovalComment(String registrationId) {
        List<String> latestApprovalComments = new List<String>();

   // Query ProcessInstance and ProcessInstanceStep records for the given recordId
   List<ProcessInstance> processInstances = [SELECT Id, TargetObjectId 
                                             FROM ProcessInstance 
                                             WHERE TargetObjectId = :registrationId];
   String returnString;
   if (processInstances.isEmpty() && !test.isRunningTest()) {
       return returnString; // No approval process for the given recordId
   }
   
   Map<Id, List<ProcessInstanceStep>> stepsMap = new Map<Id, List<ProcessInstanceStep>>();

   List<ProcessInstanceStep> steps = [SELECT Id, StepStatus, Comments, CreatedDate, ProcessInstanceId
                                      FROM ProcessInstanceStep 
                                      WHERE ProcessInstanceId IN :processInstances
                                      ORDER BY CreatedDate DESC LIMIT 1];

   // Group ProcessInstanceSteps by ProcessInstanceId
   for (ProcessInstanceStep step : steps) {
       if (!stepsMap.containsKey(step.ProcessInstanceId)) {
           stepsMap.put(step.ProcessInstanceId, new List<ProcessInstanceStep>());
       }
       stepsMap.get(step.ProcessInstanceId).add(step);
   }
   
   // Loop through ProcessInstance records and retrieve the latest comment from stepsMap
   for (ProcessInstance processInstance : processInstances) {
       if (stepsMap.containsKey(processInstance.Id)) {
           List<ProcessInstanceStep> instanceSteps = stepsMap.get(processInstance.Id);
           if (!instanceSteps.isEmpty()) {
               ProcessInstanceStep latestStep = instanceSteps[0]; // The first entry is the latest one due to the sorting
               latestApprovalComments.add(latestStep.Comments);
               returnString=latestStep.Comments;
           }
       }
   }

   return returnString;
   }
}