force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Last_Call_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Call_Attempt_Status__c</fullName>
    <defaultValue>&quot;Not Actioned&quot;</defaultValue>
    <label>Presales Last Call Attempt Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Last_call_attempt_status__c.field-meta.xml
<CustomField>
    <fullName>Last_call_attempt_status__c</fullName>
    <label>Presales Last Call Attempt Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Other_Applicants_Email__c.field-meta.xml
<CustomField>
    <fullName>Other_Applicants_Email__c</fullName>
    <label>Other Applicants Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Other_Applicants_Name__c.field-meta.xml
<CustomField>
    <fullName>Other_Applicants_Name__c</fullName>
    <label>Other Applicants Name</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Secondary_Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Secondary Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Opportunities (Secondary Sales Manager)</relationshipLabel>
    <relationshipName>Opportunities8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVAILABLE</fullName>
                <label>Available</label>
            </value>
            <value>
                <fullName>BUSY</fullName>
                <label>Busy</label>
            </value>
            <value>
                <fullName>BREAK</fullName>
                <label>Break</label>
            </value>
            <value>
                <fullName>OUTCALL</fullName>
                <label>OutCall</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityTriggerTest.cls
@isTest
public class OpportunityTriggerTest {

    @isTest
    static void testInsertOpp() {

        Profile adminProfile = [SELECT Id FROM Profile WHERE Name = 'System administrator' LIMIT 1];

        // Create Presales Head user
        User managerUser = new User(
            FirstName = 'Manager',
            LastName = 'New',
            Email = 'ManagerNew@example.com.invalid',
            ProfileId = adminProfile.Id,
            IsActive = true,
            Username = 'ManagerNew@example.com.invalid',
            Alias = 'preHd',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            LocalesIdKey = 'en_US',
            TimezonesIdKey = 'America/Los_Angeles'           
        );
        insert managerUser;
        
        Account acc = new Account(Name='test acc');
        insert acc;
        
        // Call the method to update Lead status
        Test.startTest();
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.Name = 'Test';
        objOpportunity.CloseDate = System.today();
        objOpportunity.AccountId = acc.Id; 
        objOpportunity.Status__c = 'Active'; 
        objOpportunity.StageName = 'Opportunity Identified'; 
        objOpportunity.Other_Applicants_Email__c = 'test1233337new0@gmail.com';
        objOpportunity.Other_Applicants_Name__c =' Test New';
        objOpportunity.Secondary_Sales_Manager__c = UserInfo.getUserId();
        insert objOpportunity;
        
        objOpportunity.Secondary_Sales_Manager__c = managerUser.Id;
        update objOpportunity;
        
        Test.stopTest();

    }
    
    @isTest
    static void testUpdateLeadStatus() {
        
        Lead lead = new Lead(Last_Call_Attempt_Status__c = 'Not Attempted',LastName ='Web engage', MobilePhone = '0000',Phone = '0001');
        insert lead;
        
        database.leadConvert lc = new database.leadConvert();
        lc.setLeadId(lead.id);
        lc.setConvertedStatus('Qualified');
        Database.LeadConvertResult lcr = Database.convertLead(lc);

        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        // Call the method to update Lead status
        Test.startTest();
        opp.Last_Call_Attempt_Status__c = 'TEST';
        update opp;
        Test.stopTest();

    }

}