force-app/main/default/objects/Business_Process__c/Business_Process__c.object-meta.xml
<CustomObject>
    <label>Business Process</label>
    <nameField>
        <label>Business Process Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Processes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Process__c/fields/Process_Flow__c.field-meta.xml
<CustomField>
    <fullName>Process_Flow__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Process Flow</label>
    <referenceTo>Process_Flow__c</referenceTo>
    <relationshipLabel>Business Processes</relationshipLabel>
    <relationshipName>Business_Processes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Business_Process__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Business_Process_Step__c/Business_Process_Step__c.object-meta.xml
<CustomObject>
    <label>Business Process Step</label>
    <nameField>
        <label>Business Process Steps Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Business Process Steps</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Business_Process_Step__c/fields/Business_Process_Steps_Name_Custom__c.field-meta.xml
<CustomField>
    <fullName>Business_Process_Steps_Name_Custom__c</fullName>
    <label>Business Process Steps Full Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Business_Process_Step__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Not Actioned</fullName>
                <default>true</default>
                <label>Not Actioned</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Process_Flow__c/Process_Flow__c.object-meta.xml
<CustomObject>
    <label>Process Flow</label>
    <nameField>
        <label>Process Flow Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Process Flow</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Process_Flow__c/fields/Process_Flow_Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Flow_Unique_Name__c</fullName>
    <label>Process Flow Unique Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Process_Flow_Step__c/Process_Flow_Step__c.object-meta.xml
<CustomObject>
    <label>Process Flow Step</label>
    <nameField>
        <displayFormat>PFS-{0000}</displayFormat>
        <label>Process Flow Step Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Process Flow Steps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/InvocableBulkAccept_Test.cls
@isTest
public class InvocableBulkAccept_Test {

    
    @testSetup
    static void setupTestData() {
        Contact con= new Contact();
        con.FirstName='For';
        con.LastName='TAT Emails';
        insert con;
        
        Process_Flow__c pF= new Process_Flow__c();
        pF.Name='Test PF';
        pF.Process_Flow_Unique_Name__c='testPF';
        insert pF;
        
        Process_Flow_Step__c pFS= new Process_Flow_Step__c();
        pFS.Process_Flow__c=pF.Id;
        insert pFS;
        
        Business_Process__c bP= new Business_Process__c();
        bP.Name='Test business process';
        bp.Process_Flow__c=pF.Id;
        insert bP;
        
        Business_Process_Step__c bPS= new Business_Process_Step__c();
        bPS.Name='test Name 1';
        bPS.Business_Process__c=bP.Id;
        bPS.Business_Process_Steps_Name_Custom__c='Test business step process full name';
        bPS.Status__c='Open';
        bPS.Sequence__c=1;
        insert bPS;
        
        Business_Process_Step__c bPS1= new Business_Process_Step__c();
		bPS1.Name='test Name 2';
        bPS1.Business_Process__c=bP.Id;
        bPS1.Business_Process_Steps_Name_Custom__c='Test business step process full name 2';
        bPS1.Status__c='Not Actioned';
        bPS1.Sequence__c=1;
        insert bPS1;
        
        
        
    }

   
    @isTest
    static void testBulkAcceptFunctionality() {
        
       // List<Business_Process_Step__c> bps1= new List<Business_Process_Step__c>();
        //bps1=[SELECT Id,Name from Business_Process_Step__c WHERE Status__c='Open'];
        List<Id> idees= new List<Id>();
        for(Business_Process_Step__c bps1 : [SELECT Id,Name from Business_Process_Step__c WHERE Status__c='Open'])
        {
            idees.add(bps1.Id);
        }
        
        InvocableBulkAccept.InputValues iV1= new InvocableBulkAccept.InputValues();
        iV1.actionName='Accept';
        iV1.ids=idees;
        
        List<InvocableBulkAccept.InputValues> listIv1=new List<InvocableBulkAccept.InputValues>();
        listIv1.add(iV1);
        InvocableBulkAccept.BulkUpdateRecordList(listIv1);

        InvocableBulkAccept.InputValues iV2= new InvocableBulkAccept.InputValues();
        iV2.actionName='Approve';
        iV2.ids=idees;
        
        List<InvocableBulkAccept.InputValues> listIv2=new List<InvocableBulkAccept.InputValues>();
        listIv2.add(iV2);
        InvocableBulkAccept.BulkUpdateRecordList(listIv2);
        
        InvocableBulkAccept.InputValues iV3= new InvocableBulkAccept.InputValues();
        iV3.actionName='Reject';
        iV3.ids=idees;
        
        List<InvocableBulkAccept.InputValues> listIv3=new List<InvocableBulkAccept.InputValues>();
        listIv3.add(iV3);
        InvocableBulkAccept.BulkUpdateRecordList(listIv3);
    }

  
    
}