force-app/main/default/objects/Broker_Renewal__c/Broker_Renewal__c.object-meta.xml
<CustomObject>
    <label>Broker Renewal</label>
    <nameField>
        <displayFormat>BRN-{0000}</displayFormat>
        <label>Broker Renewal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Renewal</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Renewal__c/fields/All_Documents_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>All_Documents_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Documents Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/fields/All_Mandatory_Documents__c.field-meta.xml
<CustomField>
    <fullName>All_Mandatory_Documents__c</fullName>
    <defaultValue>false</defaultValue>
    <label>All Mandatory Documents</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/fields/Broker_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Broker_Approval_Status__c</fullName>
    <label>Broker Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Broker Registration Done, pending with CHRM Manager</fullName>
            </value>
            <value>
                <fullName>Pending with CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Approved by CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Agreement Created and Sent for Signatures</fullName>
            </value>
            <value>
                <fullName>Signed Agreement Received - Documents Awaiting</fullName>
            </value>
            <value>
                <fullName>All Missing Documents Uploaded</fullName>
            </value>
            <value>
                <fullName>NOC Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh/ Sent for final signatures</fullName>
            </value>
            <value>
                <fullName>Executed Agreement Sent to CHRM</fullName>
            </value>
            <value>
                <fullName>Executed Agreement Sent to Broker</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM Ops</fullName>
            </value>
            <value>
                <fullName>Broker Registration Done</fullName>
            </value>
            <value>
                <fullName>Broker Empanelment Form Filled</fullName>
            </value>
            <value>
                <fullName>Rejected by CHRM Manager</fullName>
            </value>
            <value>
                <fullName>Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Rejected by Audit</fullName>
            </value>
            <value>
                <fullName>NOC Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and sent for signature</fullName>
            </value>
            <value>
                <fullName>NOC Is in Process</fullName>
            </value>
            <value>
                <fullName>Agreement - approved by CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Pending with CHRM / Rejected with CHRM</fullName>
            </value>
            <value>
                <fullName>Agreement Is in process</fullName>
            </value>
            <value>
                <fullName>Approved - by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Agreement Generated</fullName>
            </value>
            <value>
                <fullName>Executed Agreement sent to CRHM</fullName>
            </value>
            <value>
                <fullName>Signed Agreement Received - Documents</fullName>
            </value>
            <value>
                <fullName>Sent for Final Signatures</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/fields/NOC_Generated__c.field-meta.xml
<CustomField>
    <fullName>NOC_Generated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>NOC Generated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BrokerRenewalTriggerHelper.cls
public without sharing class BrokerRenewalTriggerHelper {
    public static void sendNocForFinalSignature(List<Broker_Renewal__c> renewList, Map<Id, Broker_Renewal__c> oldRenewMap) {
        for(Broker_Renewal__c renewRec : renewList) {
            if( (renewRec.Broker_Approval_Status__c == 'Pending with Ashish Parakh/ Sent for final signatures' || 
               renewRec.Broker_Approval_Status__c == 'Sent for Final Signatures' )&& renewRec.Broker_Approval_Status__c != oldRenewMap.get(renewRec.Id).Broker_Approval_Status__c) {
                BrokerRenewalNocDocusignHandler.forForSigningFuture(renewRec.Id);
            }
        }
    }
    
    public static void sendNocForAuditApprovalProcess(List<Broker_Renewal__c> renewList, Map<Id, Broker_Renewal__c> oldRenewMap) {
        List<Broker_Renewal__c> renewListForApproval = new List<Broker_Renewal__c>();
        for(Broker_Renewal__c renewRec : renewList) {
            if(renewRec.NOC_Generated__c && renewRec.Broker_Approval_Status__c == 'NOC Generated' && renewRec.Broker_Approval_Status__c != oldRenewMap.get(renewRec.Id).Broker_Approval_Status__c) {
                renewListForApproval.add(renewRec);
            }
        }
        if(!renewListForApproval.isEmpty()) {
            for(Broker_Renewal__c rec : renewListForApproval) {
                Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                req1.setComments('NOC for audit approval when NOC Pending with Audit');
                req1.setObjectId(rec.Id);
                req1.setSubmitterId(rec.ownerId);
                req1.setProcessDefinitionNameOrId('NOC_Audit_Approval1');
                req1.setSkipEntryCriteria(false);  
                // Line commented By Gourav Gour 8/8/2024 
              //  Approval.ProcessResult result = Approval.process(req1);
            }
        }
    }
    //Added by Gourav gour on 24/05/2024 to update status as per checkboxes
    public static void updateStatus(List<Broker_Renewal__c> renewList, Map<Id, Broker_Renewal__c> oldRenewMap) {
        for(Broker_Renewal__c renew : renewList) {
            if(renew.All_Documents_Uploaded__c && renew.All_Documents_Uploaded__c != oldRenewMap.get(renew.Id).All_Documents_Uploaded__c) {
                renew.Broker_Approval_Status__c = 'All Missing Documents Uploaded';
            }
            if(renew.All_Mandatory_Documents__c && renew.All_Mandatory_Documents__c != oldRenewMap.get(renew.Id).All_Mandatory_Documents__c) {
                //renew.Broker_Approval_Status__c = 'Agreement Is in process';
            }
        }
    }
}