force-app/main/default/objects/Finance_Report_Records__c/Finance_Report_Records__c.object-meta.xml
<CustomObject>
    <label>Finance Report Record</label>
    <nameField>
        <displayFormat>FR-{00000}</displayFormat>
        <label>Finance Report Records Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Finance Report Records</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Finance_Report_Records__c/fields/Process_CR__c.field-meta.xml
<CustomField>
    <fullName>Process_CR__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Process CR</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CRDateCalculationqueueable.cls
global class CRDateCalculationqueueable implements Queueable, Database.AllowsCallouts{
	global List<String> frrList = new List<String>();
    global CRDateCalculationqueueable(List<String> frrIdList){
        frrList = new list<String>(frrIdList);
    }
    global void execute(QueueableContext context) { 
        System.debug('frrlist:'+ frrList);
        List<Finance_Report_Records__c> fList = new List<Finance_Report_Records__c>();
        List<Finance_Report_Records__c> frrUpdateList = new List<Finance_Report_Records__c>();
       
        fList = [SELECT Id,Process_CR__c
                 FROM Finance_Report_Records__c 
                 WHERE Id IN : frrList];
        
        for(Finance_Report_Records__c fr : fList){
            fr.Process_CR__c = false;
            frrUpdateList.add(fr);
        }
       
        if(frrUpdateList != null && !frrUpdateList.isEmpty()) 
            Database.SaveResult[] resultLstfrr = Database.update(frrUpdateList);
    }

}