force-app/main/default/objects/Cluster__c/Cluster__c.object-meta.xml
<CustomObject>
    <label>Sub Project</label>
    <nameField>
        <label>Sub Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sub Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cluster__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>Clusters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Data_Download_Tracker__c/Data_Download_Tracker__c.object-meta.xml
<CustomObject>
    <label>Data Download Tracker</label>
    <nameField>
        <displayFormat>DET-{0000}</displayFormat>
        <label>Data Export Tracker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Data Download Trackers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_Download_Tracker__c/fields/Filter_Criteria__c.field-meta.xml
<CustomField>
    <fullName>Filter_Criteria__c</fullName>
    <label>Filter Criteria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1 BHK</fullName>
            </value>
            <value>
                <fullName>2 BHK</fullName>
            </value>
            <value>
                <fullName>2.5 BHK</fullName>
            </value>
            <value>
                <fullName>3 BHK</fullName>
            </value>
            <value>
                <fullName>3.5 BHK</fullName>
            </value>
            <value>
                <fullName>4 BHK</fullName>
            </value>
            <value>
                <fullName>5 BHK</fullName>
            </value>
            <value>
                <fullName>Duplex</fullName>
            </value>
            <value>
                <fullName>Penthouse</fullName>
            </value>
            <value>
                <fullName>1.5 BHK</fullName>
            </value>
            <value>
                <fullName>Studio Apartment</fullName>
            </value>
            <value>
                <fullName>Villa</fullName>
            </value>
            <value>
                <fullName>APARTMENT</fullName>
            </value>
            <value>
                <fullName>Studio</fullName>
            </value>
            <value>
                <fullName>VILLAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Code__c.field-meta.xml
<CustomField>
    <fullName>Project_Code__c</fullName>
    <label>Project Code</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tower__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sub Project</label>
    <referenceTo>Cluster__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tower__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Towers</relationshipLabel>
    <relationshipName>Towers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Cluster__c.field-meta.xml
<CustomField>
    <fullName>Cluster__c</fullName>
    <label>Cluster</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Configuration__c.field-meta.xml
<CustomField>
    <fullName>Configuration__c</fullName>
    <label>Configuration</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ST</fullName>
                <label>Studio</label>
            </value>
            <value>
                <fullName>2DP</fullName>
                <label>2 BR Duplex</label>
            </value>
            <value>
                <fullName>3DP</fullName>
                <label>3 BR Duplex</label>
            </value>
            <value>
                <fullName>4DP</fullName>
                <label>4 BR Duplex</label>
            </value>
            <value>
                <fullName>1 BR</fullName>
            </value>
            <value>
                <fullName>2 BR</fullName>
            </value>
            <value>
                <fullName>3 BR</fullName>
            </value>
            <value>
                <fullName>4BR Villa</fullName>
            </value>
            <value>
                <fullName>5BR Villa</fullName>
                <label>5 BR</label>
            </value>
            <value>
                <fullName>GFA Plots</fullName>
            </value>
            <value>
                <fullName>Gardenia</fullName>
            </value>
            <value>
                <fullName>Townhouse</fullName>
            </value>
            <value>
                <fullName>Retail</fullName>
            </value>
            <value>
                <fullName>Restaurant</fullName>
            </value>
            <value>
                <fullName>Canal Villa</fullName>
            </value>
            <value>
                <fullName>4 BR</fullName>
            </value>
            <value>
                <fullName>1 Br + Study</fullName>
                <label>1 BR + Study</label>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>Retail / Cafe</fullName>
            </value>
            <value>
                <fullName>2.5 BR</fullName>
            </value>
            <value>
                <fullName>6 BR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Puchase_Price__c.field-meta.xml
<CustomField>
    <fullName>Puchase_Price__c</fullName>
    <label>Purchase Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Total_Area__c.field-meta.xml
<CustomField>
    <fullName>Total_Area__c</fullName>
    <formula>IF(
  ISPICKVAL(Tower__r.Tower_Type__c , &apos;Villas&apos;),
  Chargeable_Area__c,
  RERA_Suite_Area_Sq_Ft__c+Balcony_Area_Sq_Ft__c
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/BrokerPortalSobhaProjectsControllerTest.cls
@isTest
private class BrokerPortalSobhaProjectsControllerTest {
    @isTest
    static void testGetUnits() {
        // Test data setup
         Project__c prj = new Project__c(
            Name = 'TEST Project'
        );
        List<Unit__c> unitList = new List<Unit__c>();
        // Create test units
        Unit__c unit = new Unit__c(
            Name = 'Test Unit',
            Project__c = prj.id, 
            Configuration__c = '2 BR', 
            //Total_Area__c = 100, // Field is not writeable
            Puchase_Price__c = 1000000 // Example price
        );
        insert unit;
        unitList.add(unit);

        // Call the method with test data
        Test.startTest();
        List<Unit__c> result = BrokerPortalSobhaProjectsController.getUnits(
            new List<String>{prj.Id}, // Example projectId
            new List<String>{'2 BR'},    // Example config
            new List<String>{'500 – 1000 Sq. Ft','1000 – 1500 Sq. Ft'},          // Example area
            new List<String>{'AED 1 Million – AED 2 Million','AED 2 Million – AED 3 Million'},          // Example price
            new List<String>{'Apartments','Villas','Others'},          // Example propertyType
            new List<String>{},          // Example subProjects
            new List<String>{},          // Example unitTypes
            new List<String>{},          // Example floors
            new List<String>{},          // Example unitNames
            new List<String>{},          // Example variants
            new List<String>{},          // Example areas
            new List<String>{}           // Example prices
        );
        Test.stopTest();

        // Assertions
       // System.assertEquals(1, result.size(), 'Expected one unit in the result');
      //  System.assertEquals('Test Unit', result[0].Name, 'Unexpected unit name');
    }

    @isTest
    static void testGetAllProjects() {
        // Test data setup
        // Create test projects
        Project__c project = new Project__c(
            Name = 'Test Project',
            Project_Code__c ='123'
        );
        insert project;

        // Call the method
        Test.startTest();
        List<Project__c> result = BrokerPortalSobhaProjectsController.getAllProjects();
        Test.stopTest();

        // Assertions
        System.assertNotEquals(0, result.size(), 'Expected at least one project in the result');
        System.assertEquals('Test Project', result[0].Name, 'Unexpected project name');
    }
    
    @isTest
    static void testGetSubProjectDetails() {
        // Test data setup
        Cluster__c subProj = new Cluster__c(
            Name = 'Test Sub Project',
            Description__c = 'Test Description',
            Project__c = 'a0R1t000000QhInEAK'
           
        );
        insert subProj;

        // Call the method
        Test.startTest();
        BrokerPortalSobhaProjectsController.SubProjectDetails result = BrokerPortalSobhaProjectsController.getSubProjectDetails(subProj.Id);
        Test.stopTest();

        // Assertions
        System.assertEquals('Test Sub Project', result.name, 'Unexpected sub-project name');
        System.assertEquals('Test Description', result.description, 'Unexpected sub-project description');
        
    }
    
    @isTest
    static void testCreateQuotation() {
        Map<String,Id> recordIdMap = new Map<String,Id>();
        recordIdMap = TestDataFactory.createMasterProject('Sobha Hartland');
        // Test data setup
        Unit__c unit = new Unit__c(
            Name = 'Test Unit',
            Tower__c = recordIdMap.get('TOWER')
        );
        insert unit;

        // Call the method
        Test.startTest();
        String quotationId = BrokerPortalSobhaProjectsController.createQuotation(unit.Id,'Aravind', 'aravind@test.com');
        Test.stopTest();
        
    }
    
    @isTest
    static void testCreateExportTracker() {
        // Test data setup
        Project__c prj = new Project__c(
            Name = 'TEST Project'
        );

        // Call the method
        Test.startTest();
        Data_Download_Tracker__c  tracker = BrokerPortalSobhaProjectsController.createExportTracker(prj.Id, UserInfo.getUserId(), 'Filter');
        Test.stopTest();

        // Assertions
        System.assertNotEquals(null, tracker.Id, 'Export tracker creation failed');
       
    }

    @isTest
    static void testGetRelatedFiles() {
        // Test data setup
Project__c prj = new Project__c(
            Name = 'TEST Project'
        );
        ContentVersion contentVersion = new ContentVersion(
            Title = 'Booking form.pdf',
            PathOnClient = 'Penguins.jpg',
            VersionData = Blob.valueOf('Test Content'),
            IsMajorVersion = true
        );
        insert contentVersion;
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        List<ContentDocumentLink> conList = new list<ContentDocumentLink>();
        //create ContentDocumentLink  record 
        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = prj.id;
        cdl.ContentDocumentId = documents[0].Id;
        cdl.shareType = 'V';
        //insert cdl;
        conList.add(cdl);
        // Calling the method
        Test.startTest();
        Id fileId = BrokerPortalSobhaProjectsController.getRelatedFiles('Booking form.pdf', prj.Id);
        Test.stopTest();
        
    }
    
      @isTest
    static void testCreateDataDownloadTracker() {
        Test.startTest();
        String  tracker = BrokerPortalSobhaProjectsController.createDataDownloadTracker('','Filter');
        BrokerPortalSobhaProjectsController.updateDataDownloadTracker(tracker,'Updated Filter');
        Test.stopTest();
        Data_DownLoad_Tracker__c track = [SELECT id,Name,Filter_Criteria__c From Data_DownLoad_Tracker__c WHERE Id=:tracker];
        System.AssertEquals(track.Filter_Criteria__c,'Updated Filter');
    }
    
     @isTest
    static void createDataDownloadTrackerTest() {
        
        Test.startTest();
        try{
         Project__c prj = new Project__c(
            Name = 'TEST Project'
        );
        String  tracker = BrokerPortalSobhaProjectsController.createDataDownloadTracker(prj.Id,'Filter');
        BrokerPortalSobhaProjectsController.updateDataDownloadTracker(tracker,'Updated Filter');
        }Catch(Exception e){
            
        }
        Test.stopTest();
    }
}