force-app/main/default/objects/Lead_Source__c/Lead_Source__c.object-meta.xml
<CustomObject>
    <label>Lead Source</label>
    <nameField>
        <label>Lead Source Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead_Source__c/fields/Adgroup__c.field-meta.xml
<CustomField>
    <fullName>Adgroup__c</fullName>
    <label>Adgroup</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Source__c/fields/Digital_Source__c.field-meta.xml
<CustomField>
    <fullName>Digital_Source__c</fullName>
    <label>Digital Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>facebook-lead-ad</fullName>
            </value>
            <value>
                <fullName>instagram-lead-ad</fullName>
            </value>
            <value>
                <fullName>instagram-story-ads</fullName>
            </value>
            <value>
                <fullName>Social Media</fullName>
            </value>
            <value>
                <fullName>affiliate</fullName>
            </value>
            <value>
                <fullName>google</fullName>
            </value>
            <value>
                <fullName>pogrammatic</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Source__c/fields/GCLID__c.field-meta.xml
<CustomField>
    <fullName>GCLID__c</fullName>
    <label>GCLID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Source__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <label>Goal</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Source__c/fields/Landing_Page_URL__c.field-meta.xml
<CustomField>
    <fullName>Landing_Page_URL__c</fullName>
    <label>Landing Page URL</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Lead_Source__c/fields/Last_Mile_Conversion__c.field-meta.xml
<CustomField>
    <fullName>Last_Mile_Conversion__c</fullName>
    <label>Last Mile Conversion</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Source__c/fields/Match_Type__c.field-meta.xml
<CustomField>
    <fullName>Match_Type__c</fullName>
    <label>Match Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Source__c/fields/Placement__c.field-meta.xml
<CustomField>
    <fullName>Placement__c</fullName>
    <label>Placement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Source__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Lead Sources</relationshipLabel>
    <relationshipName>Lead_Sources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Source__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <label>Project Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Source__c/fields/UTM_Campaign__c.field-meta.xml
<CustomField>
    <fullName>UTM_Campaign__c</fullName>
    <label>UTM Campaign</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Source__c/fields/UTM_Medium__c.field-meta.xml
<CustomField>
    <fullName>UTM_Medium__c</fullName>
    <label>UTM Medium</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead_Source__c/fields/UTM_Source__c.field-meta.xml
<CustomField>
    <fullName>UTM_Source__c</fullName>
    <label>UTM Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>facebook</fullName>
            </value>
            <value>
                <fullName>instagram</fullName>
            </value>
            <value>
                <fullName>affiliate</fullName>
            </value>
            <value>
                <fullName>icubeswire</fullName>
            </value>
            <value>
                <fullName>optimise</fullName>
            </value>
            <value>
                <fullName>adzberry</fullName>
            </value>
            <value>
                <fullName>propertyfinder</fullName>
            </value>
            <value>
                <fullName>arabayads</fullName>
            </value>
            <value>
                <fullName>LinkedIn</fullName>
            </value>
            <value>
                <fullName>ballyhoo</fullName>
            </value>
            <value>
                <fullName>flickstree</fullName>
            </value>
            <value>
                <fullName>adlantic</fullName>
            </value>
            <value>
                <fullName>platformance</fullName>
            </value>
            <value>
                <fullName>YallaCompare</fullName>
            </value>
            <value>
                <fullName>HOD</fullName>
            </value>
            <value>
                <fullName>Etiquette</fullName>
            </value>
            <value>
                <fullName>google</fullName>
            </value>
            <value>
                <fullName>mrn</fullName>
            </value>
            <value>
                <fullName>pogrammatic</fullName>
            </value>
            <value>
                <fullName>PropertyGuru</fullName>
            </value>
            <value>
                <fullName>Bayt</fullName>
            </value>
            <value>
                <fullName>HF</fullName>
            </value>
            <value>
                <fullName>Xiongma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead_Source__c/fields/Web_Source__c.field-meta.xml
<CustomField>
    <fullName>Web_Source__c</fullName>
    <label>Web Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/reEnquiryLayoutForTSAController.cls
public  class reEnquiryLayoutForTSAController {
    @AuraEnabled(cacheable= true)  
    public static List<Task> getTaskData(String leadLookup){
        system.debug('enteredd');
        return [select id,Last_Mile_Conversion__c,Keyword__c,CreatedDate,GCLID__c,Adgroup__c,Placement__c,Match_Type__c,Lead_Lookup__r.CreatedDate,Lead_Lookup__r.Web_Source__c, Lead_Lookup__r.Project_Name__c,Lead_Lookup__r.Campaign_Name__c,Are_you_looking_for__c, UTM_Source__c,Lead_Lookup__r.Project__c, Landing_Page_URL__c, Lead_Source__c, Digital_Source__c, Lead_Lookup__r.Lead_Sub_Source__c, Web_Source__c, Goal__c, UTM_Campaign__c, UTM_Content__c,UTM_Medium__c,Budget__c from Task where Lead_Lookup__c =: leadLookup and  Lead_Lookup__r.IsReenquire__c = true]; 
    }
}