force-app/main/default/objects/Broker_Registration__c/Broker_Registration__c.object-meta.xml
<CustomObject>
    <label>Broker Registration</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Registration__c/fields/Agreement_Created_Sent_Date__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Created_Sent_Date__c</fullName>
    <label>Agreement Created/Sent Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker - RERA</fullName>
            </value>
            <value>
                <fullName>Broker - UAE</fullName>
            </value>
            <value>
                <fullName>Broker - Intnl</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - UAE - Individual</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - Intnl - Individual</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - UAE - Company</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - Intnl - Company</fullName>
            </value>
            <value>
                <fullName>Broker – Intnl</fullName>
                <isActive>false</isActive>
                <label>Broker – Intnl</label>
            </value>
            <value>
                <fullName>Broker – RERA</fullName>
                <isActive>false</isActive>
                <label>Broker – RERA</label>
            </value>
            <value>
                <fullName>Broker – UAE</fullName>
                <isActive>false</isActive>
                <label>Broker – UAE</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl – Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl – Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl – Individual</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl – Individual</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl– Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl– Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – UAE – Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – UAE – Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – UAE – Individual</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – UAE – Individual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/CHRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>CHRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relations Team Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Broker_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>Company/Individual Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Mandatory_Documents_Missing__c.field-meta.xml
<CustomField>
    <fullName>Mandatory_Documents_Missing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Mandatory Documents Missing?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Name_as_per_trade_license__c.field-meta.xml
<CustomField>
    <fullName>Name_as_per_trade_license__c</fullName>
    <label>Name as per trade license</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <label>Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CHRM Registration Done</fullName>
                <label>Broker Registration Done</label>
            </value>
            <value>
                <fullName>Rejected - Rejected by CHRM Manager</fullName>
                <label>Rejected by CHRM Manager</label>
            </value>
            <value>
                <fullName>Pending with CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Rejected - Rejected by CHRM OPS</fullName>
                <label>Rejected by CHRM OPS</label>
            </value>
            <value>
                <fullName>Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Rejected by Audit</fullName>
            </value>
            <value>
                <fullName>NOC Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and sent for signature</fullName>
            </value>
            <value>
                <fullName>NOC Is in Process</fullName>
            </value>
            <value>
                <fullName>Agreement - approved by CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Pending with CHRM / Rejected with CHRM</fullName>
            </value>
            <value>
                <fullName>All missing documents uploaded</fullName>
            </value>
            <value>
                <fullName>Approved - Agreement Is in process</fullName>
                <label>Agreement Is in process</label>
            </value>
            <value>
                <fullName>Approved - by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Agreement Generated</fullName>
            </value>
            <value>
                <fullName>Executed Agreement sent to CRHM</fullName>
                <label>Executed Agreement sent to CHRM</label>
            </value>
            <value>
                <fullName>Executed Agreement sent to broker</fullName>
            </value>
            <value>
                <fullName>CP/SC ID in Process</fullName>
                <label>Signed Agreement Received - Documents Awaited</label>
            </value>
            <value>
                <fullName>Pending with CHRM Manager</fullName>
            </value>
            <value>
                <fullName>CP/SC ID Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and send for Review</fullName>
                <label>Agreement created and sent for Review</label>
            </value>
            <value>
                <fullName>Agreement created and sent to witness</fullName>
            </value>
            <value>
                <fullName>Send for Approval</fullName>
                <label>Sent for Final Signatures</label>
            </value>
            <value>
                <fullName>Agreement Executed Manually</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Not Executed - Terminated</fullName>
            </value>
            <value>
                <fullName>Cancelled Agreement - As requested by Broker</fullName>
            </value>
            <value>
                <fullName>Cancelled Agreement- Broker Category Change</fullName>
            </value>
            <value>
                <fullName>Cancelled Agreement- Ownership Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <label>New</label>
</RecordType>

force-app/main/default/classes/BrokerFormMissingDocsReminderBatchTest.cls
@isTest
public class BrokerFormMissingDocsReminderBatchTest {

    @TestSetup
    static void setup() {
        Broker_Registration__c rec1 = new Broker_Registration__c(
            First_Name__c = 'Existing',
            Last_Name__c = 'Broker',
            Email__c = 'existing@example.com',
            Mobile__c = '1234567890',
            Name_as_per_trade_license__c = 'Test Trade License',
            Registration_Number__c = '123456',
            Broker_Category__c = 'Broker - RERA',
            Status__c = 'CP/SC ID in Process',
            Mandatory_Documents_Missing__c = true,
            Agreement_Created_Sent_Date__c = Date.today().addDays(-3),
            CHRM_Manager__c = userinfo.getuserId()
        );

        Broker_Registration__c rec2 = new Broker_Registration__c(
            First_Name__c = 'Existing2',
            Last_Name__c = 'Broker',
            Email__c = 'existing2@example.com',
            Mobile__c = '12345678902',
            Name_as_per_trade_license__c = 'Test Trade License2',
            Registration_Number__c = '1234562',
            Broker_Category__c = 'Broker - RERA',
            Status__c = 'CP/SC ID in Process',
            Mandatory_Documents_Missing__c = true,
            Agreement_Created_Sent_Date__c = Date.today().addDays(-12),
            CHRM_Manager__c = userinfo.getuserId()
        );

        Broker_Registration__c rec3 = new Broker_Registration__c(
            First_Name__c = 'Existing3',
            Last_Name__c = 'Broker',
            Email__c = 'existing3@example.com',
            Mobile__c = '12345678903',
            Name_as_per_trade_license__c = 'Test Trade License3',
            Registration_Number__c = '1234563',
            Broker_Category__c = 'Broker - RERA',
            Status__c = 'CP/SC ID in Process',
            Mandatory_Documents_Missing__c = true,
            Agreement_Created_Sent_Date__c = Date.today().addDays(-23),
            CHRM_Manager__c = userinfo.getuserId()
        );

        insert new List<Broker_Registration__c>{rec1, rec2, rec3};
    }
    @isTest static void testBatchExecution() {

        Test.startTest();

        TRY{
            	Database.executeBatch(new BrokerFormMissingDocsReminderBatch());

        }catch(exception e){
            
        }
        
        Test.stopTest();
    }
}