force-app/main/default/objects/Broker_Registration__c/Broker_Registration__c.object-meta.xml
<CustomObject>
    <label>Broker Registration</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Registration__c/fields/crmOps__c.field-meta.xml
<CustomField>
    <fullName>crmOps__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Ops</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Broker_Registrations2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CHRM Registration Done</fullName>
                <label>Broker Registration Done</label>
            </value>
            <value>
                <fullName>Rejected - Rejected by CHRM Manager</fullName>
                <label>Rejected by CHRM Manager</label>
            </value>
            <value>
                <fullName>Pending with CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Rejected - Rejected by CHRM OPS</fullName>
                <label>Rejected by CHRM OPS</label>
            </value>
            <value>
                <fullName>Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Rejected by Audit</fullName>
            </value>
            <value>
                <fullName>NOC Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and sent for signature</fullName>
            </value>
            <value>
                <fullName>NOC Is in Process</fullName>
            </value>
            <value>
                <fullName>Agreement - approved by CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Pending with CHRM / Rejected with CHRM</fullName>
            </value>
            <value>
                <fullName>All missing documents uploaded</fullName>
            </value>
            <value>
                <fullName>Approved - Agreement Is in process</fullName>
                <label>Agreement Is in process</label>
            </value>
            <value>
                <fullName>Approved - by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Agreement Generated</fullName>
            </value>
            <value>
                <fullName>Executed Agreement sent to CRHM</fullName>
                <label>Executed Agreement sent to CHRM</label>
            </value>
            <value>
                <fullName>Executed Agreement sent to broker</fullName>
            </value>
            <value>
                <fullName>CP/SC ID in Process</fullName>
                <label>Signed Agreement Received - Documents Awaited</label>
            </value>
            <value>
                <fullName>Pending with CHRM Manager</fullName>
            </value>
            <value>
                <fullName>CP/SC ID Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and send for Review</fullName>
                <label>Agreement created and sent for Review</label>
            </value>
            <value>
                <fullName>Agreement created and sent to witness</fullName>
            </value>
            <value>
                <fullName>Send for Approval</fullName>
                <label>Sent for Final Signatures</label>
            </value>
            <value>
                <fullName>Agreement Executed Manually</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Not Executed - Terminated</fullName>
            </value>
            <value>
                <fullName>Cancelled Agreement - As requested by Broker</fullName>
            </value>
            <value>
                <fullName>Cancelled Agreement- Broker Category Change</fullName>
            </value>
            <value>
                <fullName>Cancelled Agreement- Ownership Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <label>New</label>
</RecordType>

force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVAILABLE</fullName>
                <label>Available</label>
            </value>
            <value>
                <fullName>BUSY</fullName>
                <label>Busy</label>
            </value>
            <value>
                <fullName>BREAK</fullName>
                <label>Break</label>
            </value>
            <value>
                <fullName>OUTCALL</fullName>
                <label>OutCall</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BrokerRegistrationTrgHelper.cls
/* Helper Class for BrokerRegistrationTrgHandler */
public class BrokerRegistrationTrgHelper {

    public static String CLASS_NAME = 'brokerRegistrationTrgHelper';

     /* All Docs uploaded actions */
    Public static void handleAllDocsUploadEvent(List<Broker_Registration__c> brokerRegUpdates) {
        
        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
        List<Broker_Registration__c> brokerRegFlagUpdates = new List<Broker_Registration__c>();
        Map<String,String> brEmailRecipientMap = new Map<String,String>();
        List<Error_Log__c> errorLogs = new List<Error_Log__c>();
        
        for (Broker_Registration__c brokerReg : brokerRegUpdates) {
            system.debug('inside for line22'+brokerReg.crmOps__r.Email);
            Broker_Registration__c brokerToUpdate = new Broker_Registration__c(Id = brokerReg.Id);
            brokerToUpdate.Status__c = 'All missing documents uploaded';
            brokerRegFlagUpdates.add(brokerToUpdate);
            brEmailRecipientMap.put(brokerReg.Id, brokerReg.crmOps__c != NULL ? brokerReg.crmOps__r.Email : 'NA' );
            
        }
        
        Database.SaveResult[] flagStampStatus = Database.update(brokerRegFlagUpdates, false);
        
        // Iterate through each returned result
        for (Database.SaveResult sr : flagStampStatus) {
            
            if (sr.isSuccess()) {
                for(Database.Error err : sr.getErrors()) {
                    Error_Log__c thisError = new Error_Log__c(Class__c = CLASS_NAME, Message__c = err.getStatusCode() + ': ' + err.getMessage());
                    errorLogs.add(thisError);
                }
            }
        }
        
        if(errorLogs.size() > 0) {
            Database.insert(errorLogs, FALSE);
        }
    }
    
   
}