force-app/main/default/objects/Broker_Registration__c/Broker_Registration__c.object-meta.xml
<CustomObject>
    <label>Broker Registration</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Registration__c/fields/Broker_Category__c.field-meta.xml
<CustomField>
    <fullName>Broker_Category__c</fullName>
    <label>Broker Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Broker - RERA</fullName>
            </value>
            <value>
                <fullName>Broker - UAE</fullName>
            </value>
            <value>
                <fullName>Broker - Intnl</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - UAE - Individual</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - Intnl - Individual</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - UAE - Company</fullName>
            </value>
            <value>
                <fullName>Sobha Connect - Intnl - Company</fullName>
            </value>
            <value>
                <fullName>Broker – Intnl</fullName>
                <isActive>false</isActive>
                <label>Broker – Intnl</label>
            </value>
            <value>
                <fullName>Broker – RERA</fullName>
                <isActive>false</isActive>
                <label>Broker – RERA</label>
            </value>
            <value>
                <fullName>Broker – UAE</fullName>
                <isActive>false</isActive>
                <label>Broker – UAE</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl – Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl – Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl – Individual</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl – Individual</label>
            </value>
            <value>
                <fullName>Sobha Connect – Intnl– Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – Intnl– Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – UAE – Company</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – UAE – Company</label>
            </value>
            <value>
                <fullName>Sobha Connect – UAE – Individual</fullName>
                <isActive>false</isActive>
                <label>Sobha Connect – UAE – Individual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Broker_Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Broker_Created_Date__c</fullName>
    <label>Broker Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/CHRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>CHRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relations Team Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Broker_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/CHRM_ManagerHead__c.field-meta.xml
<CustomField>
    <fullName>CHRM_ManagerHead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relations Team Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Broker_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Days_since_Agreement_shared__c.field-meta.xml
<CustomField>
    <fullName>Days_since_Agreement_shared__c</fullName>
    <formula>IF( NOT(ISNULL(Agreement_Created_Sent_Date__c)), TODAY() -  Agreement_Created_Sent_Date__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days since Agreement shared</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>Company/Individual Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/frmBrokerRegistrationName__c.field-meta.xml
<CustomField>
    <fullName>frmBrokerRegistrationName__c</fullName>
    <formula>IF( OR(ISPICKVAL( Broker_Category__c , &apos;Sobha Connect - UAE - Individual&apos;), ISPICKVAL( Broker_Category__c , &apos;Sobha Connect - Intnl - Individual&apos;)), Name_as_per_passport__c , Name_as_per_trade_license__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>frmBrokerRegistrationName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/frmCHRMMgrName__c.field-meta.xml
<CustomField>
    <fullName>frmCHRMMgrName__c</fullName>
    <formula>CHRM_Manager__r.FirstName + &quot; &quot; +  CHRM_Manager__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>frmCHRMMgrName</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/list_of_missing_documents__c.field-meta.xml
<CustomField>
    <fullName>list_of_missing_documents__c</fullName>
    <label>list of missing documents</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Missing_Documents__c.field-meta.xml
<CustomField>
    <fullName>Missing_Documents__c</fullName>
    <label>Missing Documents</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>Broker_Category__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Registration Form</fullName>
            </value>
            <value>
                <fullName>RERA Certificate</fullName>
            </value>
            <value>
                <fullName>Trade License</fullName>
            </value>
            <value>
                <fullName>VAT Certificate</fullName>
            </value>
            <value>
                <fullName>Identification Documents</fullName>
            </value>
            <value>
                <fullName>Passport Copy</fullName>
            </value>
            <value>
                <fullName>Visa Copy</fullName>
            </value>
            <value>
                <fullName>Emirates ID</fullName>
            </value>
            <value>
                <fullName>POA/MOA</fullName>
            </value>
            <value>
                <fullName>Translated Company Documents</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Registration_Link__c.field-meta.xml
<CustomField>
    <fullName>Registration_Link__c</fullName>
    <formula>$Label.Broker_Registration_Site_URL &amp; &apos;?id=&apos; &amp; Id</formula>
    <label>Registration Link</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CHRM Registration Done</fullName>
                <label>Broker Registration Done</label>
            </value>
            <value>
                <fullName>Rejected - Rejected by CHRM Manager</fullName>
                <label>Rejected by CHRM Manager</label>
            </value>
            <value>
                <fullName>Pending with CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Rejected - Rejected by CHRM OPS</fullName>
                <label>Rejected by CHRM OPS</label>
            </value>
            <value>
                <fullName>Pending with Audit</fullName>
            </value>
            <value>
                <fullName>Pending with Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Rejected by Audit</fullName>
            </value>
            <value>
                <fullName>NOC Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and sent for signature</fullName>
            </value>
            <value>
                <fullName>NOC Is in Process</fullName>
            </value>
            <value>
                <fullName>Agreement - approved by CHRM OPS</fullName>
            </value>
            <value>
                <fullName>Pending with CHRM / Rejected with CHRM</fullName>
            </value>
            <value>
                <fullName>All missing documents uploaded</fullName>
            </value>
            <value>
                <fullName>Approved - Agreement Is in process</fullName>
                <label>Agreement Is in process</label>
            </value>
            <value>
                <fullName>Approved - by Ashish Parakh</fullName>
            </value>
            <value>
                <fullName>Agreement Generated</fullName>
            </value>
            <value>
                <fullName>Executed Agreement sent to CRHM</fullName>
                <label>Executed Agreement sent to CHRM</label>
            </value>
            <value>
                <fullName>Executed Agreement sent to broker</fullName>
            </value>
            <value>
                <fullName>CP/SC ID in Process</fullName>
                <label>Signed Agreement Received - Documents Awaited</label>
            </value>
            <value>
                <fullName>Pending with CHRM Manager</fullName>
            </value>
            <value>
                <fullName>CP/SC ID Generated</fullName>
            </value>
            <value>
                <fullName>Agreement created and send for Review</fullName>
                <label>Agreement created and sent for Review</label>
            </value>
            <value>
                <fullName>Agreement created and sent to witness</fullName>
            </value>
            <value>
                <fullName>Send for Approval</fullName>
                <label>Sent for Final Signatures</label>
            </value>
            <value>
                <fullName>Agreement Executed Manually</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Not Executed - Terminated</fullName>
            </value>
            <value>
                <fullName>Cancelled Agreement - As requested by Broker</fullName>
            </value>
            <value>
                <fullName>Cancelled Agreement- Broker Category Change</fullName>
            </value>
            <value>
                <fullName>Cancelled Agreement- Ownership Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <label>New</label>
</RecordType>

force-app/main/default/objects/Broker_Registration__c/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <label>Renewal</label>
</RecordType>

force-app/main/default/objects/brokerCategoryMandatoryFiles__mdt/brokerCategoryMandatoryFiles__mdt.object-meta.xml
<CustomObject>
    <label>brokerCategoryMandatoryFiles</label>
    <pluralLabel>brokerCategoryMandatoryFiless</pluralLabel>
</CustomObject>

force-app/main/default/objects/brokerCategoryMandatoryFiles__mdt/fields/MandatoryFiles__c.field-meta.xml
<CustomField>
    <fullName>MandatoryFiles__c</fullName>
    <label>MandatoryFiles</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/brokerCategoryMandatoryFiles__mdt/fields/OptionalFiles__c.field-meta.xml
<CustomField>
    <fullName>OptionalFiles__c</fullName>
    <label>OptionalFiles</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AVAILABLE</fullName>
                <label>Available</label>
            </value>
            <value>
                <fullName>BUSY</fullName>
                <label>Busy</label>
            </value>
            <value>
                <fullName>BREAK</fullName>
                <label>Break</label>
            </value>
            <value>
                <fullName>OUTCALL</fullName>
                <label>OutCall</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ApprovalEmailForBrokerRegController.cls
global class ApprovalEmailForBrokerRegController {
    global static Id currentId {get;set;}
    public static list<string> mandatoryFileList {get;set;} 
    public static list<String> optionalFiles {get;set;}
    public static String registrationlink {get;set;}
    public static String mailSentDate {get;set;}
    public static String createdDate {get;set;}
    public static String commentstext {get;set;}
    public static Boolean showLinkActiveContent {get;set;}
    
    
    
    public static Broker_Registration__c getrelatedTo() {
        /*list<String> comments = getLatestApprovalComments(currentId);
        if(comments.size()>0){
            commentstext=comments[0];    
        }else{
            commentstext=''; 
        }*/
        String comments = getLatestApprovalCommentNew(currentId);
        if(comments!=null){
            commentstext=comments;    
        }else{
            commentstext=''; 
        }
        
        system.debug('etntecontroller');
        Broker_Registration__c brg =  [
            Select id,Name,Comments__c,Owner.Name,Days_since_Agreement_shared__c,CreatedBy.Name,CHRM_Manager__r.Name,Broker_Category__c,frmCHRMMgrName__c,Registration_Link__c,frmBrokerRegistrationName__c,Broker_Created_Date__c,CHRM_ManagerHead__r.name,Status__c,First_Name__c,Last_Name__c,
            list_of_missing_documents__c, Missing_Documents__c, recordtype.name
            FROM Broker_Registration__c where id=:currentId];
        DateTime currentDateTime = DateTime.now();
        mailSentDate =formatDateTime(currentDateTime);
        if(brg.Broker_Created_Date__c!=null){
            createdDate=formatDateTime(brg.Broker_Created_Date__c);  
        }
        showLinkActiveContent = true;
        if(brg.recordtype.name=='Renewal'){
            showLinkActiveContent = false;
        }
        
        
        
        mandatoryFileList = new list<string>();
        optionalFiles = new list<String>();
        if(brg.Registration_Link__c != null){
             registrationlink=brg.Registration_Link__c;
        }
        if(brg.Broker_Category__c != null){
        	getMandatoryFiles(brg.Broker_Category__c);    
        }
        
        return brg;
    }
    
    public static list<String> getMandatoryFiles(String brokerCat){
        system.debug(brokerCat);
        //list<string> mandatoryFileList = new list<string>();
        List<brokerCategoryMandatoryFiles__mdt> mandatoryFile = [select id,Label, MasterLabel,MandatoryFiles__c,OptionalFiles__c  from brokerCategoryMandatoryFiles__mdt where Label = :brokerCat];
        //mandatoryFileList.addAll(mandatoryFile);
        for(brokerCategoryMandatoryFiles__mdt file: mandatoryFile){
            for(string st : file.MandatoryFiles__c.split(',')){
                mandatoryFileList.add(st);
            }
            // Process Optional Files
            if(file.OptionalFiles__c!=null){
                for (String optFile : file.OptionalFiles__c.split(',')) {
                    optionalFiles.add(optFile);
                }    
            }
            
        }
        
        system.debug(mandatoryFileList);
        
        return mandatoryFileList;
        
        
        
    }
    public static List<String> getLatestApprovalComments(Id recordId) {
        List<String> latestApprovalComments = new List<String>();
        
        // Query ProcessInstance and ProcessInstanceStep records for the given recordId
        List<ProcessInstance> processInstances = [SELECT Id, TargetObjectId 
                                                  FROM ProcessInstance 
                                                  WHERE TargetObjectId = :recordId];
        
        if (processInstances.isEmpty()) {
            return latestApprovalComments; // No approval process for the given recordId
        }
        
        Map<Id, List<ProcessInstanceStep>> stepsMap = new Map<Id, List<ProcessInstanceStep>>();
        
        if(processInstances != null){
            List<ProcessInstanceStep> steps = [SELECT Id, StepStatus, Comments, CreatedDate,ProcessInstanceId
                                               FROM ProcessInstanceStep 
                                               WHERE ProcessInstanceId IN :processInstances
                                               ORDER BY CreatedDate DESC];
            for (ProcessInstanceStep step : steps) {
                if (!stepsMap.containsKey(step.ProcessInstanceId)) {
                    stepsMap.put(step.ProcessInstanceId, new List<ProcessInstanceStep>());
                }
                stepsMap.get(step.ProcessInstanceId).add(step);
            }
        }
        
        
        
        // Group ProcessInstanceSteps by ProcessInstanceId
        
        
        // Loop through ProcessInstance records and retrieve the latest comment from stepsMap
        for (ProcessInstance processInstance : processInstances) {
            if (stepsMap.containsKey(processInstance.Id)) {
                List<ProcessInstanceStep> instanceSteps = stepsMap.get(processInstance.Id);
                if (!instanceSteps.isEmpty()) {
                    ProcessInstanceStep latestStep = instanceSteps[0]; // The first entry is the latest one due to the sorting
                    latestApprovalComments.add(latestStep.Comments);
                }
            }
        }
        
        return latestApprovalComments;
    }
    
    public Static String formatDateTime(DateTime dt) {
        return dt.format('dd/MM/yyyy hh:mm a', 'Asia/Dubai');
    }
    
    
    
    public static String getLatestApprovalCommentNew(String registrationId) {
         List<String> latestApprovalComments = new List<String>();

    // Query ProcessInstance and ProcessInstanceStep records for the given recordId
    List<ProcessInstance> processInstances = [SELECT Id, TargetObjectId 
                                              FROM ProcessInstance 
                                              WHERE TargetObjectId = :registrationId];
    String returnString;
    if (processInstances.isEmpty()) {
        return returnString; // No approval process for the given recordId
    }
    
    Map<Id, List<ProcessInstanceStep>> stepsMap = new Map<Id, List<ProcessInstanceStep>>();

    List<ProcessInstanceStep> steps = [SELECT Id, StepStatus, Comments, CreatedDate, ProcessInstanceId
                                       FROM ProcessInstanceStep 
                                       WHERE ProcessInstanceId IN :processInstances
                                       ORDER BY CreatedDate DESC LIMIT 1];

    // Group ProcessInstanceSteps by ProcessInstanceId
    for (ProcessInstanceStep step : steps) {
        if (!stepsMap.containsKey(step.ProcessInstanceId)) {
            stepsMap.put(step.ProcessInstanceId, new List<ProcessInstanceStep>());
        }
        stepsMap.get(step.ProcessInstanceId).add(step);
    }
    
    // Loop through ProcessInstance records and retrieve the latest comment from stepsMap
    for (ProcessInstance processInstance : processInstances) {
        if (stepsMap.containsKey(processInstance.Id)) {
            List<ProcessInstanceStep> instanceSteps = stepsMap.get(processInstance.Id);
            if (!instanceSteps.isEmpty()) {
                ProcessInstanceStep latestStep = instanceSteps[0]; // The first entry is the latest one due to the sorting
                latestApprovalComments.add(latestStep.Comments);
                returnString=latestStep.Comments;
            }
        }
    }

    return returnString;
    }
    
    
    
}