force-app/main/default/objects/Broker_Registration__c/Broker_Registration__c.object-meta.xml
<CustomObject>
    <label>Broker Registration</label>
    <nameField>
        <displayFormat>BR-{0000}</displayFormat>
        <label>Broker Registration Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Registrations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Registration__c/fields/CHRM_Manager__c.field-meta.xml
<CustomField>
    <fullName>CHRM_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relations Team Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Broker_Registrations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/CHRM_ManagerHead__c.field-meta.xml
<CustomField>
    <fullName>CHRM_ManagerHead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relations Team Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Broker_Registrations1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <label>Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/RERA_Number__c.field-meta.xml
<CustomField>
    <fullName>RERA_Number__c</fullName>
    <label>RERA Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Broker_Registrations3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Registration__c/recordTypes/New.recordType-meta.xml
<RecordType>
    <fullName>New</fullName>
    <active>true</active>
    <label>New</label>
</RecordType>

force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel_Partner__c/fields/Channel_Relationship_Head__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relations Team Lead</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Channel_Partners3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Channel_Partners2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Channel_Relationship_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager_Name__c</fullName>
    <formula>Channel_Relationship_Manager__r.FirstName + &apos; &apos; + Channel_Relationship_Manager__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Channel Relationship Manager Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Passport_No__c.field-meta.xml
<CustomField>
    <fullName>Passport_No__c</fullName>
    <label>Registration/Passport Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/RERA_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>RERA_Registration_No__c</fullName>
    <externalId>true</externalId>
    <label>RERA Registration No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Channel_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Channel_Relationship_Head__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Passport_No__c.field-meta.xml
<CustomField>
    <fullName>Passport_No__c</fullName>
    <label>Passport No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RERA_Number__c.field-meta.xml
<CustomField>
    <fullName>RERA_Number__c</fullName>
    <label>RERA Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/RERA_Registration_No__c.field-meta.xml
<CustomField>
    <fullName>RERA_Registration_No__c</fullName>
    <externalId>true</externalId>
    <label>RERA Registration No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Head__c.field-meta.xml
<CustomField>
    <fullName>Sales_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sales_Head</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/Sobha_Connect__c.object-meta.xml
<CustomObject>
    <label>Sobha Connect</label>
    <nameField>
        <displayFormat>SC - {0000}</displayFormat>
        <label>Sobha Connect Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sobha Connect</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Sobha_Connect__c/fields/Channel_Relationship_Head__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sobha_Connect1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sobha_Connect</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Registration__c.field-meta.xml
<CustomField>
    <fullName>Registration__c</fullName>
    <label>Registration/Passport Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/RERA_Number__c.field-meta.xml
<CustomField>
    <fullName>RERA_Number__c</fullName>
    <label>RERA Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Sales_Head__c.field-meta.xml
<CustomField>
    <fullName>Sales_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sobha_Connect3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sobha_Connect__c/fields/Sales_Manager__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sobha_Connect2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TradeLicenseSearchController.cls
public class TradeLicenseSearchController {
    @AuraEnabled
    public static List<RecordWrapper> getRecordsData(String firstSearchKey) {
         List<RecordWrapper> wrapList = new List<RecordWrapper>();
        if(firstSearchKey == ''){
            return wrapList;
        }
       
        List<Channel_Partner__c> channelpartnerList = [SELECT Id,Name,Channel_Relationship_Manager__c,Channel_Relationship_Manager_Name__c,Channel_Relationship_Head__r.Name 
                                                       From Channel_Partner__c where 
                                                       Passport_No__c =: firstSearchKey OR RERA_Registration_No__c =: firstSearchKey];
        List<Sobha_Connect__c> sobhaConnectList = [SELECT Id,Name,Sales_Manager__r.Name,Sales_Head__r.Name From Sobha_Connect__c where Registration__c =: firstSearchKey];
        List<Broker_Registration__c> brokerList = [SELECT Id,Name,CHRM_Manager__r.Name,CHRM_ManagerHead__r.Name From Broker_Registration__c where RERA_Number__c =: firstSearchKey OR Registration_Number__c =: firstSearchKey];
        wrapList.add(new RecordWrapper(channelpartnerList, sobhaConnectList,brokerList));
        return wrapList;
        
    }
    public class RecordWrapper{
        @AuraEnabled public List<Channel_Partner__c> channelpartnerList{get;set;}
        @AuraEnabled public List<Sobha_Connect__c> sobhaConnectList{get;set;}
        @AuraEnabled public List<Broker_Registration__c> brokerList{get;set;}
        public RecordWrapper(List<Channel_Partner__c> channelpartnerList, List<Sobha_Connect__c> sobhaConnectList,List<Broker_Registration__c> brokerList){
            this.channelpartnerList = channelpartnerList;
            this.sobhaConnectList = sobhaConnectList;
            this.brokerList = brokerList;
        }
    }
}