force-app/main/default/objects/Broker_Registration_Settings__mdt/Broker_Registration_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Broker Registration Settings</label>
    <pluralLabel>Broker Registration Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Broker_Registration_Settings__mdt/fields/Missing_Docs_Reminder_1st__c.field-meta.xml
<CustomField>
    <fullName>Missing_Docs_Reminder_1st__c</fullName>
    <label>Missing Docs Reminder 1st</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Broker_Registration_Settings__mdt/fields/Missing_Docs_Reminder_2nd__c.field-meta.xml
<CustomField>
    <fullName>Missing_Docs_Reminder_2nd__c</fullName>
    <label>Missing Docs Reminder 2nd</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Broker_Registration_Settings__mdt/fields/Missing_Docs_Reminder_3rd__c.field-meta.xml
<CustomField>
    <fullName>Missing_Docs_Reminder_3rd__c</fullName>
    <label>Missing Docs Reminder 3rd</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Broker_Registration_Settings__mdt/fields/Missing_Docs_Reminder_4th__c.field-meta.xml
<CustomField>
    <fullName>Missing_Docs_Reminder_4th__c</fullName>
    <label>Missing Docs Reminder  4th</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Broker_Registration_Settings__mdt/fields/Missing_Docs_Reminder_5th__c.field-meta.xml
<CustomField>
    <fullName>Missing_Docs_Reminder_5th__c</fullName>
    <label>Missing Docs Reminder 5th</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Broker_Registration_Settings__mdt/fields/Missing_Docs_Reminder_6th__c.field-meta.xml
<CustomField>
    <fullName>Missing_Docs_Reminder_6th__c</fullName>
    <label>Missing Docs Reminder 6th</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Broker_Registration_Settings__mdt/fields/Missing_Docs_Reminder_7th__c.field-meta.xml
<CustomField>
    <fullName>Missing_Docs_Reminder_7th__c</fullName>
    <label>Missing Docs Reminder 7th</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/Broker_Renewal__c.object-meta.xml
<CustomObject>
    <label>Broker Renewal</label>
    <nameField>
        <displayFormat>BRN-{0000}</displayFormat>
        <label>Broker Renewal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker Renewal</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Broker_Renewal__c/fields/Channel_Relationship_Head__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Broker_Renewal1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Broker_Renewal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Broker_Renewal__c/fields/Days_since_Agreement_shared__c.field-meta.xml
<CustomField>
    <fullName>Days_since_Agreement_shared__c</fullName>
    <formula>IF( NOT(ISNULL(Generate_Agreement_Date__c)), TODAY() - Generate_Agreement_Date__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days since Agreement shared</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Alternate_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Email_ID__c</fullName>
    <label>Alternate Email ID</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Channel_Relationship_Head__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Head__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Head</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Channel_Relationship_Manager__c.field-meta.xml
<CustomField>
    <fullName>Channel_Relationship_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Relationship Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/BrokerRenewalMissingDocsReminderBatch.cls
global class BrokerRenewalMissingDocsReminderBatch implements Database.Batchable<sObject>, Database.Stateful, Schedulable {

    private Map<String,Contact> contacts;
    private EmailTemplate chrmManagerEmailTemplate;
    private EmailTemplate chrmHeadEmailTemplate;
    private EmailTemplate vpEmailTemplate;
    private Broker_Registration_Settings__mdt settings;
    
    global BrokerRenewalMissingDocsReminderBatch() {
        contacts = new Map<String,Contact>();
        list<EmailTemplate> templateList = [SELECT Id, DeveloperName FROM EmailTemplate WHERE DeveloperName = 'Broker_Renewal_CHRMMgrReminder1' OR DeveloperName = 'Broker_Renewal_CHRMMgrReminder2' OR DeveloperName = 'Broker_Renewal_VP_Reminder_3'];
        for(EmailTemplate et : templateList) {
            if(et.DeveloperName == 'Broker_Renewal_CHRMMgrReminder1') {
                chrmManagerEmailTemplate = et;
            }
            if(et.DeveloperName == 'Broker_Renewal_CHRMMgrReminder2') {
                chrmHeadEmailTemplate = et;
            }
            if(et.DeveloperName == 'Broker_Renewal_VP_Reminder_3') {
                vpEmailTemplate = et;
            }
        }
        settings = [
            SELECT Missing_Docs_Reminder_1st__c, Missing_Docs_Reminder_2nd__c, Missing_Docs_Reminder_3rd__c, 
                Missing_Docs_Reminder_4th__c, Missing_Docs_Reminder_5th__c, Missing_Docs_Reminder_6th__c, 
                Missing_Docs_Reminder_7th__c
            FROM Broker_Registration_Settings__mdt
            WHERE DeveloperName = 'Broker_Account_Congif'
            LIMIT 1
        ];
    }

    public void execute(SchedulableContext sc) {
        Database.executeBatch(new BrokerRenewalMissingDocsReminderBatch());
    }
    
    public static void run(){
        System.schedule(Test.isRunningTest() ? 'Test BrokerRenewalMissingDocsReminderBatch' : 'BrokerRenewalMissingDocsReminderBatch', '0 0 4 * * ?', new BrokerRenewalMissingDocsReminderBatch());
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Name, Days_since_Agreement_shared__c, Channel_Relationship_Manager__r.Email, '+
                        'Channel_Relationship_Head__r.Email, Channel_Relationship_Manager__r.FirstName, Channel_Relationship_Manager__r.LastName, '+
                        'Channel_Relationship_Head__r.FirstName, Channel_Relationship_Head__r.LastName, Channel_Relationship_Manager__r.Manager.Email '+
                        'FROM Broker_Renewal__c WHERE Days_since_Agreement_shared__c >= 3' ;
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Broker_Renewal__c> scope) {
        Map<String,Contact> newContacts = new Map<String,Contact>();
        Map<Broker_Renewal__c, String> pendingBrokerToRecipients = new Map<Broker_Renewal__c,String>();
        Map<Broker_Renewal__c, List<String>> pendingBrokerToCCs = new Map<Broker_Renewal__c,List<String>>();
        Map<Broker_Renewal__c, EmailTemplate> pendingBrokerToTemplate = new Map<Broker_Renewal__c,EmailTemplate>();
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();

        for (Broker_Renewal__c registration : scope) {
            Integer daysSinceSent = Integer.valueOf(registration.Days_since_Agreement_shared__c);
            String recipient = registration.Channel_Relationship_Manager__r?.Email;
            Contact recipientRecord = new Contact(
                FirstName = registration.Channel_Relationship_Manager__r?.FirstName, 
                LastName = registration.Channel_Relationship_Manager__r?.LastName, 
                Email = 'test'+recipient+'check',
                Alternate_Email_ID__c = recipient
            );
            EmailTemplate template = null;
            List<String> cc = new List<String>();
            
            if (daysSinceSent == settings.Missing_Docs_Reminder_1st__c || daysSinceSent == settings.Missing_Docs_Reminder_2nd__c || daysSinceSent == settings.Missing_Docs_Reminder_3rd__c) {
                // Send email reminder to CHRM Manager
                template = chrmManagerEmailTemplate;
            } else if (daysSinceSent == settings.Missing_Docs_Reminder_4th__c || daysSinceSent == settings.Missing_Docs_Reminder_5th__c || daysSinceSent == settings.Missing_Docs_Reminder_6th__c) {
                // Send email reminder to CHRM Head
                cc.add(registration.Channel_Relationship_Manager__r.Manager?.Email);
                template = chrmHeadEmailTemplate;
            } else if (daysSinceSent >= settings.Missing_Docs_Reminder_7th__c && Math.mod((daysSinceSent - Integer.valueOf(settings.Missing_Docs_Reminder_7th__c)), Integer.valueOf(settings.Missing_Docs_Reminder_1st__c)) == 0) {
                // Send email reminder to VP every 3 days after 20th day
                cc.add(System.Label.VP_Email);
                cc.add(registration.Channel_Relationship_Manager__r.Manager?.Email);
                //template = vpEmailTemplate;
                template = chrmHeadEmailTemplate;
            }

            if( template == null ) continue;

            if( !contacts.containsKey(recipient) ) {
                if( !newContacts.containsKey(recipient) ) 
                    newContacts.put(recipient, recipientRecord);

                pendingBrokerToRecipients.put(registration, recipient);
                pendingBrokerToTemplate.put(registration, template);
                pendingBrokerToCCs.put(registration, cc);
            } else {
                emailList.add( createEmailMessage( registration, contacts.get( recipient ), template, cc) );
            }
        }

        insert newContacts.values();

        contacts.putAll( newContacts );

        for(Broker_Renewal__c registration : pendingBrokerToRecipients.keySet()) {
            String recipient = pendingBrokerToRecipients.get( registration );
            EmailTemplate template = pendingBrokerToTemplate.get( registration );
            List<String> cc = pendingBrokerToCCs.get( registration );
            emailList.add( createEmailMessage( registration, contacts.get( recipient ), template, cc) );
        }
        
        // Send email reminders
        if (!emailList.isEmpty()) {
            try{
            Messaging.sendEmail(emailList);
            }catch(exception e){
                
            }
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        // Perform any post-processing tasks if needed
        delete contacts.values();
    }
    
    private Messaging.SingleEmailMessage createEmailMessage(Broker_Renewal__c registration, Contact recipient, EmailTemplate template, List<String> cc) {
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        email.setToAddresses(new String[] { recipient.Alternate_Email_ID__c });
        email.setCCAddresses(cc);
        email.setTemplateId(template.Id);
        email.setWhatId(registration.Id);
        email.setTargetObjectId(recipient.Id);
        return email;
    }
}