force-app/main/default/objects/API_Callout_Log__c/API_Callout_Log__c.object-meta.xml
<CustomObject>
    <label>API Callout Log</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Callout Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Callout_Log__c/fields/Context_User__c.field-meta.xml
<CustomField>
    <fullName>Context_User__c</fullName>
    <description>To capture context user, i.e. UserInfo.getUserId() + UserInfo.getUserName()</description>
    <label>Context User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Callout_Log__c/fields/Data_Source__c.field-meta.xml
<CustomField>
    <fullName>Data_Source__c</fullName>
    <description>The record/s ids for this request derived the data from</description>
    <label>Data Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Callout_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <description>JSON/serialized body</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/Nice_LoggerUtility.cls
/***************************************************************************
Class      : Nice_LoggerUtility
Test Class : Nice_LoggerTest
Purpose    : Nice - An Apex utility class helps to log all the api activities with the detailed information.
Author     : Ashok Kumar M
*****************************************************************************/
public class Nice_LoggerUtility {
    
    public static Void createLog(String source, String requestBody, String responseBody, integer statusCode){
        
        API_Callout_Log__c errLog = new API_Callout_Log__c();
        errLog.Context_User__c = UserInfo.getUserId();
        errLog.Data_Source__c = source;
        errLog.Request_Body__c = requestBody;
        errLog.Response_Body__c = responseBody;
        errLog.Response_Status_Code__c = statusCode;
        insert errLog;
        
    }
    
}