force-app/main/default/objects/API_Callout_Log__c/API_Callout_Log__c.object-meta.xml
<CustomObject>
    <label>API Callout Log</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>API Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Callout Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/API_Callout_Log__c/fields/Context_User__c.field-meta.xml
<CustomField>
    <fullName>Context_User__c</fullName>
    <description>To capture context user, i.e. UserInfo.getUserId() + UserInfo.getUserName()</description>
    <label>Context User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Callout_Log__c/fields/Data_Source__c.field-meta.xml
<CustomField>
    <fullName>Data_Source__c</fullName>
    <description>The record/s ids for this request derived the data from</description>
    <label>Data Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Callout_Log__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <description>To capture Endpoint</description>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/API_Callout_Log__c/fields/Request_Body__c.field-meta.xml
<CustomField>
    <fullName>Request_Body__c</fullName>
    <description>JSON/serialized body</description>
    <label>Request Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_Callout_Log__c/fields/Request_Headers__c.field-meta.xml
<CustomField>
    <fullName>Request_Headers__c</fullName>
    <description>To capture all the Headers&apos; Keys-Values mappings</description>
    <label>Request Headers</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/API_Callout_Log__c/fields/Response_Status__c.field-meta.xml
<CustomField>
    <fullName>Response_Status__c</fullName>
    <label>Response Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WebEng_Field_Transformation__mdt/WebEng_Field_Transformation__mdt.object-meta.xml
<CustomObject>
    <label>WebEng Field Transformation</label>
    <pluralLabel>WebEng Field Transformations</pluralLabel>
</CustomObject>

force-app/main/default/objects/WebEng_Field_Transformation__mdt/fields/Transformed_Value__c.field-meta.xml
<CustomField>
    <fullName>Transformed_Value__c</fullName>
    <label>Transformed Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WebEng_Field_Transformation__mdt/fields/Web_Eng_Sync_Field__c.field-meta.xml
<CustomField>
    <fullName>Web_Eng_Sync_Field__c</fullName>
    <label>Web Eng Sync Field</label>
    <referenceTo>WebEng_Sync_Fields__mdt</referenceTo>
    <relationshipLabel>WebEng Field Transformations</relationshipLabel>
    <relationshipName>WebEng_Field_Transformations</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/WebEng_Sync_Fields__mdt/WebEng_Sync_Fields__mdt.object-meta.xml
<CustomObject>
    <label>Web Eng Sync Field</label>
    <pluralLabel>Web Eng Sync Fields</pluralLabel>
</CustomObject>

force-app/main/default/classes/WebEngageUtility.cls
//Test Class: TestLeadTrigger
public class WebEngageUtility {
    
    public static String getTransformedValue(WebEng_Sync_Fields__mdt  singleMap, String actualFieldValue){
        List<WebEng_Field_Transformation__mdt> transformationMap = new List<WebEng_Field_Transformation__mdt>();
        
        transformationMap = [SELECT Transformed_Value__c,Transform_Key__c  
                             FROM WebEng_Field_Transformation__mdt 
                             WHERE Web_Eng_Sync_Field__c = :singleMap.Id 
                             AND Transform_Key__c = :actualFieldValue LIMIT 1];
        
        
        system.debug('transformationMap::'+transformationMap);
        // system.debug('transformationMap.Transformed_Value__c::'+transformationMap.Transformed_Value__c);
        system.debug('actualFieldValue::'+actualFieldValue);
        return (!transformationMap.isEmpty())  ? transformationMap[0].Transformed_Value__c : '' ;
    }
    
    
    
    public static String getEventName(String leadStatus){
        String eventName =
            (leadStatus == 'Qualified') ? 'Lead Qualified' :
        ((leadStatus == 'Lost' || leadStatus == 'UnQualified') ? 'Lead Lost' :
         'Lead Disposition');
             return eventName;
        
    }
    public static Void createLog(HttpRequest hReq,HTTPResponse hRes,String className, String errMsg){
        API_Callout_Log__c errLog = new API_Callout_Log__c();
        errLog.Context_User__c = UserInfo.getUserId();
        errLog.Data_Source__c = className;
        errLog.EndPoint__c = hreq.getEndpoint();
        errLog.Method__c = hreq.getMethod();
        errLog.Request_Body__c = truncateToFieldSize(hReq.getBody(),API_Callout_Log__c.fields.Request_Body__c.getDescribe().getLength());//hReqBody;
        String requestHeaders = 'Content-Type:'+ hReq.getHeader('Content-Type') + ', Authorization:'+ hReq.getHeader('Authorization');
        // Get  request headers
        errLog.Request_Headers__c = truncateToFieldSize(requestHeaders, API_Callout_Log__c.fields.Request_Headers__c.getDescribe().getLength());
        
        if(hRes != null ) {
            errLog.Response_Status_Code__c = hRes.getStatusCode();
            errLog.Response_Status__c = hRes.getStatus();
            errLog.Response_Body__c = truncateToFieldSize(hRes.getBody(),API_Callout_Log__c.fields.Response_Body__c.getDescribe().getLength());
        }
        else {
            //errLog.Response_Status_Code__c = 500;
            errLog.Response_Status__c = 'Salesforce error';
            errLog.Response_Body__c = errMsg;
        }
        
        insert errLog;
        
    }
    
    public static Void createLog(String errorMsg,Id recId, String className){
        API_Callout_Log__c errLog = new API_Callout_Log__c();
        errLog.Context_User__c = UserInfo.getUserId();
        errLog.Data_Source__c = className;
        errLog.Response_Body__c = recId;
        
        errLog.Response_Body__c = errorMsg;
        
        insert errLog;
        
        
    }
    public static String truncateToFieldSize(String str,Integer lengthLimit){
        return String.isNotBlank(str) && str.length() > lengthLimit ? str.substring(0,lengthLimit) : str;
    }
    
    
}