force-app/main/default/objects/Lead/fields/is_serviced__c.field-meta.xml
<CustomField>
    <fullName>is_serviced__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is_Serviced</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Presales_Agent__c.field-meta.xml
<CustomField>
    <fullName>Presales_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Presales Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Route_To_Saturday_Queue1__c.field-meta.xml
<CustomField>
    <fullName>Route_To_Saturday_Queue1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Route To Saturday Queue1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Route_To_Sunday_Queue1__c.field-meta.xml
<CustomField>
    <fullName>Route_To_Sunday_Queue1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Route To Sunday Queue1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchClassToManageLeadSpillOver.cls
global without sharing class BatchClassToManageLeadSpillOver implements Database.Batchable <sObject> {
    global List < Lead> start(Database.BatchableContext BC) {
        List < Lead> leadList = new List < Lead > ();

        leadList = [SELECT ID,Route_To_Saturday_Queue1__c,Route_To_Sunday_Queue1__c  FROM Lead WHERE (CreatedDate = today OR CreatedDate = yesterday) AND is_serviced__c = false AND (Route_To_Sunday_Queue1__c = true OR Route_To_Saturday_Queue1__c = true)];
        return leadList;
    }

    global void execute(Database.BatchableContext BC, List < Lead > scope) {
        Database.DMLOptions dmo = new Database.DMLOptions();
        dmo.assignmentRuleHeader.useDefaultRule = true;
       
        List<Lead> leadList = scope;
        for(Lead l : leadList){
            /*if(l.Route_To_Saturday_Queue1__c == true){
                l.Route_To_Saturday_Queue1__c = false;
                l.Route_To_Sunday_Queue1__c = true;
            }
           else  if(l.Route_To_Sunday_Queue1__c == true){
                l.Route_To_Saturday_Queue1__c = false;
                l.Route_To_Sunday_Queue1__c = false;
            }*/
            l.presales_agent__c = null;
            l.setOptions(dmo);
        }
        
        Database.update(leadList);
       
    }

    global void finish(Database.BatchableContext BC) {}
   


}