force-app/main/default/objects/Lead/fields/Owner_Profile__c.field-meta.xml
<CustomField>
    <fullName>Owner_Profile__c</fullName>
    <formula>Owner:User.Profile.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Owner Profile</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Presales_Agent__c.field-meta.xml
<CustomField>
    <fullName>Presales_Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Presales Agent</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeadOwnerReassign.cls
global class LeadOwnerReassign implements Database.Batchable <sObject>,Database.AllowsCallouts{
    Public String Query;
    
    public LeadOwnerReassign() {
        Query = 'Select id,name,Presales_Agent__c, OwnerId,owner.Name,Owner_Profile__c,createddate from Lead where  Owner_Profile__c = \'\' and Owner.Name != \'Careers Lead\' and Owner.Name != \'Unassigned Leads\' order by createddate desc ';
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext info, List<Lead> scope){
           //SocialMediaLeadServices.getFBleads(scope);
         //  LeadUtility.leadOwnerReassign(scope);
          List<Lead> llst = new List<Lead>();
         for(Lead lead : scope){
             if(lead.Presales_Agent__c != null){
                 if(lead.Presales_Agent__c != lead.OwnerId){
                     lead.OwnerId = lead.Presales_Agent__c;
                 }
             }
             llst.add(lead);
        }
        upsert llst;
    }
    
    global void finish(Database.BatchableContext info){     
    }  
}