force-app/main/default/objects/Feature_Flag__mdt/Feature_Flag__mdt.object-meta.xml
<CustomObject>
    <description>This is a feature flag to control features at org-level</description>
    <label>Feature Flag</label>
    <pluralLabel>Feature Flags</pluralLabel>
</CustomObject>

force-app/main/default/objects/Feature_Flag__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/Payment_Request__c.object-meta.xml
<CustomObject>
    <label>Payment Request</label>
    <nameField>
        <displayFormat>PR-{0000000}</displayFormat>
        <label>Payment Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Request__c/fields/Account_Received_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Received_Date__c</fullName>
    <label>Account Received Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Amount_Allocated__c.field-meta.xml
<CustomField>
    <fullName>Amount_Allocated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Amount Allocated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Amount_Confirmed_By_Accounts__c.field-meta.xml
<CustomField>
    <fullName>Amount_Confirmed_By_Accounts__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Amount Confirmed By Accounts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Final_Approver__c.field-meta.xml
<CustomField>
    <fullName>Final_Approver__c</fullName>
    <label>Final Approver</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Instrument_Date__c.field-meta.xml
<CustomField>
    <fullName>Instrument_Date__c</fullName>
    <label>Instrument Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Instrument_Number__c.field-meta.xml
<CustomField>
    <fullName>Instrument_Number__c</fullName>
    <label>Instrument Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Original_Amount__c.field-meta.xml
<CustomField>
    <fullName>Original_Amount__c</fullName>
    <label>Original Amount</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Others__c.field-meta.xml
<CustomField>
    <fullName>Others__c</fullName>
    <label>Others</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Upkeep/refurbishment Charges</fullName>
            </value>
            <value>
                <fullName>DEWA Charges</fullName>
            </value>
            <value>
                <fullName>NOC Charges</fullName>
            </value>
            <value>
                <fullName>Late Payment Charges</fullName>
            </value>
            <value>
                <fullName>Cancellation Charges</fullName>
            </value>
            <value>
                <fullName>Cheque Dishonored Charges</fullName>
            </value>
            <value>
                <fullName>Community Management Service fees</fullName>
            </value>
            <value>
                <fullName>Title Deed Charges</fullName>
            </value>
            <value>
                <fullName>Security Deposit</fullName>
            </value>
            <value>
                <fullName>Mortgage Fees</fullName>
            </value>
            <value>
                <fullName>Resale – NOC (Title Deed)</fullName>
            </value>
            <value>
                <fullName>Resale – NOC (Off plan)</fullName>
            </value>
            <value>
                <fullName>SPA Reissuance Fees</fullName>
            </value>
            <value>
                <fullName>Ownership Change</fullName>
            </value>
            <value>
                <fullName>Pre-registration To Pre-title Deed</fullName>
            </value>
            <value>
                <fullName>Plot title Deed</fullName>
            </value>
            <value>
                <fullName>Plot Resale NOC</fullName>
            </value>
            <value>
                <fullName>Service charges</fullName>
            </value>
            <value>
                <fullName>Resale NOC (Title Deed)</fullName>
            </value>
            <value>
                <fullName>Resale NOC (Oqood)</fullName>
            </value>
            <value>
                <fullName>Title Deed Fees (Units)</fullName>
            </value>
            <value>
                <fullName>Title Deed Fees (Villas)</fullName>
            </value>
            <value>
                <fullName>Title Deed Fees (Plots)</fullName>
            </value>
            <value>
                <fullName>Mortgage Fees (Ejara)</fullName>
            </value>
            <value>
                <fullName>Mortgage Fees (Traditonal)</fullName>
            </value>
            <value>
                <fullName>SPA reissuance fees (per book)</fullName>
            </value>
            <value>
                <fullName>Name addition/deletion</fullName>
            </value>
            <value>
                <fullName>Ownership changes</fullName>
            </value>
            <value>
                <fullName>DLD Cancellation Charges</fullName>
            </value>
            <value>
                <fullName>Admin Charges (General)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Payment_Request__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Request</label>
    <referenceTo>Payment_Request__c</referenceTo>
    <relationshipLabel>Payment Requests</relationshipLabel>
    <relationshipName>Payment_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Reference_Number__c.field-meta.xml
<CustomField>
    <fullName>Reference_Number__c</fullName>
    <label>Reference Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending for Accounts Approval</fullName>
            </value>
            <value>
                <fullName>Approved by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by Accounts</fullName>
            </value>
            <value>
                <fullName>Pending for Sales Ops Approval</fullName>
            </value>
            <value>
                <fullName>Rejected by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Resubmitted to SM/SD</fullName>
            </value>
            <value>
                <fullName>Approved by Sales Ops</fullName>
            </value>
            <value>
                <fullName>Submitted to Accounts for Amount Confirmation</fullName>
            </value>
            <value>
                <fullName>Amount Confirmed by Accounts</fullName>
            </value>
            <value>
                <fullName>Rejected by System</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Payment Link sent to Customer</fullName>
            </value>
            <value>
                <fullName>Partially Approved</fullName>
            </value>
            <value>
                <fullName>PR was Approved- Booking is cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Towards_Other_Charges_Amount__c.field-meta.xml
<CustomField>
    <fullName>Towards_Other_Charges_Amount__c</fullName>
    <label>Towards Other Charges Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Towards_Pre_Registration_Amount__c.field-meta.xml
<CustomField>
    <fullName>Towards_Pre_Registration_Amount__c</fullName>
    <label>Towards Pre-Registration Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Payment_Request__c/fields/Towards_Unit_Price_Amount__c.field-meta.xml
<CustomField>
    <fullName>Towards_Unit_Price_Amount__c</fullName>
    <label>Towards Unit Price Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PaymentRequestButtonController.cls
public without sharing class PaymentRequestButtonController {
	@AuraEnabled
    public static string confirmAmount(Double amount, string referenceNo, string accountReceivedDate, string prId){
        string res = '';
        Boolean PR_Deallocation_Feature = Feature_Flag__mdt.getAll().containsKey('PR_Deallocation') && Feature_Flag__mdt.getInstance('PR_Deallocation').Active__c;//Fix for amount deductions in DWT and CDM-Cash
        
        Payment_Request__c pr = new Payment_Request__c(Id=prId);
        
        if(PR_Deallocation_Feature){
            List<Payment_Request__c> prs = [SELECT id,Amount__c,Original_Amount__c FROM Payment_Request__c WHERE Id = :prId];
            if(!prs.isEmpty()) pr = prs[0];
        }

        try{
            if(PR_Deallocation_Feature && pr.Amount__c != amount){//If confirmed amount has changed, remove allocations
                pr.Towards_Unit_Price_Amount__c = null;
                pr.Towards_Pre_Registration_Amount__c = null;
                pr.Towards_Other_Charges_Amount__c = null;
                pr.Others__c = null;
                pr.Amount_Allocated__c = false;
            }

            pr.Amount__c = amount;
            pr.Reference_Number__c = referenceNo;
            pr.Account_Received_Date__c = Date.valueOf(accountReceivedDate);
            pr.Amount_Confirmed_By_Accounts__c = true;
            pr.Final_Approver__c = UserInfo.getUserId();
            pr.Status__c = 'Amount Confirmed by Accounts';
            
        	update pr;
            res = 'SUCCESS';
        }
        catch(Exception e){
            res = e.getMessage();
        }
        return res;
    }
    
    @AuraEnabled
    public static string resubmitToSM(string prId, string remarks){
        string res = '';
        Payment_Request__c pr = new Payment_Request__c(Id=prId);
        pr.Status__c = 'Resubmitted to SM/SD';
        pr.Remarks__c = remarks;
        try{
        	update pr;
            res = 'SUCCESS';
        }
        catch(Exception e){
            res = e.getMessage();
        }
        return res;
    }
    
    @AuraEnabled
    public static string updatePaymentRequest(string prId, string instrumentNumber, string instrumentDate, string referenceNumber){
        string res = '';
        Payment_Request__c pr = new Payment_Request__c(Id=prId);
        if(instrumentNumber!=null && instrumentNumber!='')
        	pr.Instrument_Number__c = instrumentNumber;
        if(instrumentDate!=null && instrumentDate!='')
        	pr.Instrument_Date__c = Date.valueOf(instrumentDate);
        if(referenceNumber!=null && referenceNumber!='')
        	pr.Reference_Number__c = referenceNumber;
        try{
        	update pr;
            res = 'SUCCESS';
        }
        catch(Exception e){
            res = e.getMessage();
        }
        return res;
    }
}