force-app/main/default/objects/Churned_Leads__c/Churned_Leads__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Authorized Profile To Push Churned Leads</label>
</CustomObject>

force-app/main/default/objects/Lead/fields/Primary_Number__c.field-meta.xml
<CustomField>
    <fullName>Primary_Number__c</fullName>
    <label>Primary Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RDS_Country_Code__c.field-meta.xml
<CustomField>
    <fullName>RDS_Country_Code__c</fullName>
    <label>Country Code</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RDS_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>+61</fullName>
            </value>
            <value>
                <fullName>+65</fullName>
            </value>
            <value>
                <fullName>+852</fullName>
            </value>
            <value>
                <fullName>+86</fullName>
            </value>
            <value>
                <fullName>+91</fullName>
            </value>
            <value>
                <fullName>+971</fullName>
            </value>
            <value>
                <fullName>+93</fullName>
            </value>
            <value>
                <fullName>+54</fullName>
            </value>
            <value>
                <fullName>+43</fullName>
            </value>
            <value>
                <fullName>+973</fullName>
            </value>
            <value>
                <fullName>+880</fullName>
            </value>
            <value>
                <fullName>+55</fullName>
            </value>
            <value>
                <fullName>+1</fullName>
            </value>
            <value>
                <fullName>+506</fullName>
            </value>
            <value>
                <fullName>+225</fullName>
            </value>
            <value>
                <fullName>+45</fullName>
            </value>
            <value>
                <fullName>+20</fullName>
            </value>
            <value>
                <fullName>+358</fullName>
            </value>
            <value>
                <fullName>+33</fullName>
            </value>
            <value>
                <fullName>+49</fullName>
            </value>
            <value>
                <fullName>+233</fullName>
            </value>
            <value>
                <fullName>+30</fullName>
            </value>
            <value>
                <fullName>+36</fullName>
            </value>
            <value>
                <fullName>+62</fullName>
            </value>
            <value>
                <fullName>+353</fullName>
            </value>
            <value>
                <fullName>+972</fullName>
            </value>
            <value>
                <fullName>+39</fullName>
            </value>
            <value>
                <fullName>+81</fullName>
            </value>
            <value>
                <fullName>+254</fullName>
            </value>
            <value>
                <fullName>+82</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PushToBitVoice_Test.cls
@isTest
public Class PushToBitVoice_Test{
  public static testMethod void testPushToBitVoice() {
    Churned_Leads__c c = new Churned_Leads__c(Name = 'System Administrator');
    insert c;
    Test.startTest();
    Lead leadRecord = new Lead();
    leadRecord.FirstName = 'Sri';
    leadRecord.LastName = 'K';
    leadRecord.Email = 'sri.k@gmail.com';
    leadRecord.Status = 'Open';
    leadRecord.RDS_Country_Code__c = '971';
    leadRecord.Primary_Number__c = '8786534567';
    insert leadRecord;
    
    List<Lead> lstRecords = new list<Lead>();lstRecords.add(leadRecord);
    ApexPages.StandardSetController ssc = new ApexPages.StandardSetController(lstRecords);
    ssc.setSelected(lstRecords);
    PushToBitVoice pbv = new PushToBitVoice(ssc);
    pbv.push();
    
    Test.stopTest();
  }
}