force-app/main/default/objects/Contact/fields/Last_Call_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Call_Attempt_Status__c</fullName>
    <label>Presales Last Call Attempt Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Call_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Call_Attempt_Status__c</fullName>
    <label>Call Attempt Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Actioned</fullName>
            </value>
            <value>
                <fullName>Not Actioned</fullName>
            </value>
            <value>
                <fullName>Visit confirmed</fullName>
            </value>
            <value>
                <fullName>Visit proposed</fullName>
            </value>
            <value>
                <fullName>Junk Lead</fullName>
            </value>
            <value>
                <fullName>Invalid Enquiry</fullName>
            </value>
            <value>
                <fullName>Invalid Number</fullName>
            </value>
            <value>
                <fullName>Not Actioned - No Shuffle</fullName>
            </value>
            <value>
                <fullName>Not Shuffle</fullName>
            </value>
            <value>
                <fullName>Recycled Lead</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Follow up</fullName>
            </value>
            <value>
                <fullName>Follow up - email</fullName>
            </value>
            <value>
                <fullName>Follow up - social</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Last_Call_Attempt_Status__c.field-meta.xml
<CustomField>
    <fullName>Last_Call_Attempt_Status__c</fullName>
    <defaultValue>&quot;Not Actioned&quot;</defaultValue>
    <label>Presales Last Call Attempt Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SetAutoDial_After_3_Hours_Test.cls
@isTest
Class SetAutoDial_After_3_Hours_Test {
    Private Static TestMethod Void callBack() {
        Lead leadRecord = new Lead();
        leadRecord.LastName = 'Test';
        leadRecord.MobilePhone = '8987898765';
        leadRecord.Last_Call_Attempt_Status__c = 'New';
        insert leadRecord;
        Test.StartTest();
            List<task> t = new List<task>{ new task(
            WhoID = leadRecord.id,
            Subject='Donni',
            Status='Completed',
            Priority='Normal',
            Call_Attempt_Status__c = 'No Contact')};
            insert t;
        Test.StopTest();
    }
    Private Static TestMethod Void callBack2() {
        Lead leadRecord = new Lead();
        leadRecord.LastName = 'Test';
        leadRecord.MobilePhone = '8987898765';
        leadRecord.Last_Call_Attempt_Status__c = 'New';
        insert leadRecord;
        Test.StartTest();
            List<task> t = new List<task>{ new task(
            WhoID = leadRecord.id,
            Subject='',
            Status='Completed',
            Priority='Normal',
            Call_Attempt_Status__c = 'No Contact',
            Next_Action_Date__c = System.Now().addHours(3))};
            insert t;
        Test.StopTest();
    }
}