force-app/main/default/objects/Assignment_Group_Name__c/Assignment_Group_Name__c.object-meta.xml
<CustomObject>
    <label>Assignment Group</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Assignment Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment_Group_Name__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cases</fullName>
                <default>true</default>
                <label>Cases</label>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Case</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Assignment_Groups__c/Assignment_Groups__c.object-meta.xml
<CustomObject>
    <description>Used to assign ownership of records users via Apex</description>
    <label>Group Member</label>
    <nameField>
        <label>Group Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Group Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Assignment_Groups__c/fields/Group_Name__c.field-meta.xml
<CustomField>
    <fullName>Group_Name__c</fullName>
    <label>Assignment Group Name</label>
    <referenceTo>Assignment_Group_Name__c</referenceTo>
    <relationshipLabel>Group Members</relationshipLabel>
    <relationshipName>Assignment_Groups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_Mb_CreateRequest.cls
@isTest
public class Test_Mb_CreateRequest {

    @isTest
    static void testGetBookingListWithRecords() {
        
        Assignment_Group_Name__c assignmentGroupName = new Assignment_Group_Name__c();
        assignmentGroupName.Type__c = 'Cases';
        assignmentGroupNamE.Name = 'Test';
        Insert assignmentGroupName;
        
        Assignment_Groups__c assignmentGroup = new Assignment_Groups__c();
        assignmentGroup.Active__c = 'True';
        assignmentGroup.Name = 'Test';
        assignmentGroup.Rank__c = 1;
        assignmentGroup.Group_Name__c = assignmentGroupName.Id;
        Insert assignmentGroup;
        
        Case c = new Case();
        c.SuppliedEmail = 'test@gmail.com';
        c.SuppliedPhone = '98765432';
        c.description = 'description';
        insert c;
        
        /*  List<string> strList = new List<string>();
        strList.add('A');
        strList.add('B');
        List<Mobile_createRequest.CaseRequestWrapper> wrapperList = accountCController.getNameValues(strList); */
        
        Mobile_TestUtil.createBooking();
        List<booking__c> book = [select id, name from booking__c order by createddate asc limit 1];
        
        Mobile_createRequest.CaseRequestWrapper cwrap = new Mobile_createRequest.CaseRequestWrapper();
        cwrap.email = 'test@gmail.com';
        cwrap.mobile = '9876543321';
        cwrap.description = 'description';
        cwrap.requestType = 'SPA';
        cwrap.bookingId = book[0].Id;
        String jsonBody = JSON.serialize(cwrap);
        
        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/createRequest'; 
        req.httpMethod = 'Post';
        req.addHeader('Content-Type', 'application/json'); 
        req.requestBody = Blob.valueof(jsonBody);
        RestContext.request = req;
        
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        Test.startTest();
        	Mobile_createRequest.doCreateCase();
        Test.stopTest();
    }
    
    @isTest
    static void testGetBookingListWithOutRecords() {
        
        Assignment_Group_Name__c assignmentGroupName = new Assignment_Group_Name__c();
        assignmentGroupName.Type__c = 'Cases';
        assignmentGroupNamE.Name = 'Test';
        Insert assignmentGroupName;
        
        Assignment_Groups__c assignmentGroup = new Assignment_Groups__c();
        assignmentGroup.Active__c = 'True';
        assignmentGroup.Name = 'Test';
        assignmentGroup.Rank__c = 1;
        assignmentGroup.Group_Name__c = assignmentGroupName.Id;
        Insert assignmentGroup;
        
        Case c = new Case();
        c.SuppliedEmail = 'test@gmail.com';
        c.SuppliedPhone = '98765432';
        c.description = 'description';
        insert c;
        
        /*  List<string> strList = new List<string>();
        strList.add('A');
        strList.add('B');
        List<Mobile_createRequest.CaseRequestWrapper> wrapperList = accountCController.getNameValues(strList); */
        
        Mobile_TestUtil.createBooking();
        List<booking__c> book = [select id, name from booking__c order by createddate asc limit 1];
        
        Mobile_createRequest.CaseRequestWrapper cwrap = new Mobile_createRequest.CaseRequestWrapper();
        /*cwrap.email = 'test@gmail.com';
        cwrap.mobile = '9876543321';
        cwrap.description = 'description';
        cwrap.requestType = 'SPA';
        cwrap.bookingId = book[0].Id;*/
        String jsonBody = JSON.serialize(cwrap);
        
        RestRequest req = new RestRequest();
        req.requestURI = '/services/apexrest/createRequest'; 
        req.httpMethod = 'Post';
        req.addHeader('Content-Type', 'application/json'); 
        req.requestBody = Blob.valueof(jsonBody);
        RestContext.request = req;
        
        RestResponse res = new RestResponse();
        RestContext.response = res;
        
        Test.startTest();
        	Mobile_createRequest.doCreateCase();
        Test.stopTest();
    }
}