force-app/main/default/objects/Payment_Plan__c/Payment_Plan__c.object-meta.xml
<CustomObject>
    <label>Payment Plan</label>
    <nameField>
        <label>Payment Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <displayFormat>SH-{000}</displayFormat>
        <label>Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Basic_Sale_Price_Modified__c.field-meta.xml
<CustomField>
    <fullName>Basic_Sale_Price_Modified__c</fullName>
    <label>Basic Sale Price (Modified)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Basic_Sale_Price_Original__c.field-meta.xml
<CustomField>
    <fullName>Basic_Sale_Price_Original__c</fullName>
    <label>Basic Sale Price (Original)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount in Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Payment_Plan__c.field-meta.xml
<CustomField>
    <fullName>Payment_Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Plan</label>
    <referenceTo>PropStrength__Payment_Plan__c</referenceTo>
    <relationshipLabel>Quote</relationshipLabel>
    <relationshipName>Quote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Quote_for_Multi_Properties__c.field-meta.xml
<CustomField>
    <fullName>Quote_for_Multi_Properties__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote for Multi Properties</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/QuoteTriggerHandler_Test.cls
@isTest
public class QuoteTriggerHandler_Test {
    @isTest
    static void testMethod1() { 
        List<Quote__c> quoteList = new List<Quote__c>(); 
        PropStrength__Projects__c proStrProj = TestDataFactorySobha.createProject(null);
        insert proStrProj;
        PropStrength__Payment_Plan__c proPStrPayPlan = TestDataFactorySobha.createPaymentPlan(null);   
        insert proPStrPayPlan;                  

        Quote__c q = new Quote__c(Basic_Sale_Price_Original__c = 10000, Basic_Sale_Price_Modified__c = 9000, Discount_Amount__c = 1000, Total_Discount__c = 1000,Quote_for_Multi_Properties__c = true,Payment_Plan__c =proPStrPayPlan.Id,Discount_Type__c = 'Discount');
        system.debug('quote here'+q);
        insert q; 
        Quote__c qt = [select id,Total_Discount__c from quote__c where id=:q.id];
        system.debug('quote here 2'+qt.Total_Discount__c);
        quoteList.add(q);
    }
}