force-app/main/default/objects/Account_Master__c/Account_Master__c.object-meta.xml
<CustomObject>
    <label>Account Master</label>
    <nameField>
        <label>Account Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <label>Booking</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Booking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Booking_Date__c.field-meta.xml
<CustomField>
    <fullName>Booking_Date__c</fullName>
    <label>Booking Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Channel_Partner__c.field-meta.xml
<CustomField>
    <fullName>Channel_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please Select a Channel Partner if Booking Source is &apos;Channel Partner&apos;</inlineHelpText>
    <label>Channel Partner</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Channel_Partner__c.Black_listed_user__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Channel_Partner__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Primary_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name__c</fullName>
    <label>Primary Applicant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Receipts__c.field-meta.xml
<CustomField>
    <fullName>Receipts__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Receipt__c.Project_Unit__c</field>
            <operation>equals</operation>
            <valueField>$Source.Unit__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Sales_Managers__c.field-meta.xml
<CustomField>
    <fullName>Sales_Managers__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Stage_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Stage_of_Booking__c</fullName>
    <label>Stage of Booking</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EOI</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Booked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Tower__c.field-meta.xml
<CustomField>
    <fullName>Tower__c</fullName>
    <label>Tower</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Booking</relationshipLabel>
    <relationshipName>Booking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel_Partner__c/Channel_Partner__c.object-meta.xml
<CustomObject>
    <label>Channel Partner</label>
    <nameField>
        <label>Channel Partner Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Channel Partners</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/fields/Adjustment_Entry__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Entry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Adjustment Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Business_Unit__c.field-meta.xml
<CustomField>
    <fullName>Business_Unit__c</fullName>
    <label>Business Unit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/GL_Date__c.field-meta.xml
<CustomField>
    <fullName>GL_Date__c</fullName>
    <label>GL Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Payment_Towards__c.field-meta.xml
<CustomField>
    <fullName>Payment_Towards__c</fullName>
    <label>Payment Towards</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Corporate Account</fullName>
                <default>true</default>
                <label>Corporate Account</label>
            </value>
            <value>
                <fullName>ESCROW Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Primary_Applicant_Name__c.field-meta.xml
<CustomField>
    <fullName>Primary_Applicant_Name__c</fullName>
    <formula>Booking__r.Primary_Applicant_Name__c</formula>
    <label>Primary Applicant Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Voucher_Number__c.field-meta.xml
<CustomField>
    <fullName>Voucher_Number__c</fullName>
    <formula>TEXT(YEAR(Today())) &amp; &apos;/&apos; &amp; Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Voucher Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Adjustment_Entry__c.field-meta.xml
<CustomField>
    <fullName>Adjustment_Entry__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Adjustment Entry</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Amount_Rs__c.field-meta.xml
<CustomField>
    <fullName>Amount_Rs__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount (AED)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Cheque_DD_Date__c.field-meta.xml
<CustomField>
    <fullName>Cheque_DD_Date__c</fullName>
    <label>Cheque Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Debit_Account__c.field-meta.xml
<CustomField>
    <fullName>Debit_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Debit Account</label>
    <referenceTo>Account_Master__c</referenceTo>
    <relationshipLabel>Receipts (Debit Account)</relationshipLabel>
    <relationshipName>Receipts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demand</label>
    <referenceTo>Demand__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Project_Unit__c.field-meta.xml
<CustomField>
    <fullName>Project_Unit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Unit</label>
    <referenceTo>Unit__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Number__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Number__c</fullName>
    <formula>IF( Advance_Receipt__c  = true, IF( Tax_Receipt__c = true, (Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Project_Unit__r.Tower__r.Name ,2) &amp; &apos;-&apos; &amp; Project_Unit__r.Name &amp; &apos;/&apos; &amp; TEXT(Receipt_Date__c) &amp; &apos;/&apos; &amp; &apos;AdvTax-&apos; &amp; Name,(Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Project_Unit__r.Tower__r.Name ,2) &amp; &apos;-&apos; &amp; Project_Unit__r.Name &amp; &apos;/&apos; &amp; TEXT(Receipt_Date__c) &amp; &apos;/&apos; &amp; &apos;Adv-&apos; &amp; Name), 
(Project__r.RDS_Short_Name__c) &amp; &apos;/&apos; &amp; Left( Project_Unit__r.Tower__r.Name ,2) &amp; &apos;-&apos; &amp; Project_Unit__r.Name &amp; &apos;/&apos; &amp; TEXT(Receipt_Date__c) &amp; &apos;/&apos; &amp; Name)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Receipt Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Receipt_Status__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Status__c</fullName>
    <label>Receipt Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cheque Hold</fullName>
            </value>
            <value>
                <fullName>Cleared</fullName>
            </value>
            <value>
                <fullName>Dishonored</fullName>
            </value>
            <value>
                <fullName>PDC</fullName>
            </value>
            <value>
                <fullName>Physical Verification Rejected</fullName>
            </value>
            <value>
                <fullName>Processed-Sent for Banking</fullName>
            </value>
            <value>
                <fullName>UnProcessed</fullName>
                <default>true</default>
                <label>UnProcessed</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/RemarksText__c.field-meta.xml
<CustomField>
    <fullName>RemarksText__c</fullName>
    <label>Remarks</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Tower__c/Tower__c.object-meta.xml
<CustomObject>
    <label>Tower</label>
    <nameField>
        <label>Tower Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Towers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/Unit__c.object-meta.xml
<CustomObject>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Unit__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Units</relationshipLabel>
    <relationshipName>Units</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Unit__c/fields/Stage_of_Booking__c.field-meta.xml
<CustomField>
    <fullName>Stage_of_Booking__c</fullName>
    <formula>TEXT(Booking__r.Stage_of_Booking__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Stage of Booking</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/N_UnitWiseCollectionReport.cls
public class N_UnitWiseCollectionReport{
    public date fromDate {get;set;}
    public date toDate {get;set;}
    public String unitNo {get;set;}
    public List<Demand__c> demandList;
    public List<Receipt__c> receiptList;
    public List<wrapperClass> wrap{get;set;}
    public List<wrapperClass> wrapListToDisplay{get;set;}
    public List<wrapperClass> wrapListToDownload{get;set;}
    public String amount;
    public Decimal totalDebitAmount;
    public Decimal totalCreditAmount;
    public String totalDebitAmountString {get;set;}
    public String totalCreditAmountString {get;set;}
    public String debitAmountString;
    public String creditAmountString;
    public String debitBalanceString {get;set;}
    public String creditBalanceString {get;set;}   
    public Boolean details{get;set;}           
    
    public N_UnitWiseCollectionReport(){               
        details = false;                                   
    }
    
    ///// This report will only contain Credit Note and Receipts             
    public PageReference getReport(){
        wrap = new list<wrapperClass>();
        wrapListToDisplay = new list<wrapperClass>();
        wrapListToDownload = new list<wrapperClass>();
        amount = '';
        totalDebitAmount = 0.0;
        totalCreditAmount = 0.0;   
        debitAmountString = '';
        creditAmountString = '';   
        totalDebitAmountString = '';
        totalCreditAmountString = '';    
        debitBalanceString = '';
        creditBalanceString = '';    
        details = true;
        
        //////// Receipt Query                           
        String rcptQuery = ' SELECT Id, Name, Booking__r.Primary_Applicant_Name__c, Project_Unit__r.Name, Booking__r.Tower__c, Mode__c, Business_Unit__c, GL_Date__c, Booking__r.Name, Booking__r.Stage_of_Booking__c, Debit_Account__r.Name, '+
            ' Currency__c, Amount_Rs__c, Receipt_Number__c, Receipt_Status__c, Demand__c, Demand__r.Name, Description__c, Voucher_Number__c, DraweeBank__c, Booking__r.Sales_Managers__r.Name, Booking__r.Channel_Partner__r.Name, '+
            ' Booking__r.Booking_Date__c, Bank_Reference_Number__c, Cheque_DD_Date__c, Receipt_Date__c, Payment_Towards__c, RemarksText__c, Adjustment_Entry__c FROM Receipt__c WHERE Receipt_Status__c IN(\'Cleared\', \'Processed-Sent for Banking\', \'PDC\')';
        if(fromDate != null && toDate != null){
            rcptQuery += ' AND GL_Date__c >= :fromDate AND GL_Date__c <= :toDate';           
        } 
        if(unitNo != null && String.isNotBlank(unitNo)){
            rcptQuery += ' AND Project_Unit__r.Name Like ' + '\'%' + unitNo+ '%\'';
        }  
        receiptList = Database.Query(rcptQuery + ' ORDER BY GL_Date__c LIMIT 50000');     
        system.debug('receipt size::: ' + receiptList.size());                                                                                             
        
        if(!receiptList.isEmpty()){
            for(Receipt__c r: receiptList){  
                String type = '';
                if(r.Mode__c != 'Credit Note')
                    type = 'Receipt';
                else
                    type = 'Credit Note';              
                if(r.Amount_Rs__c != null){
                    amount = InFormat(r.Amount_Rs__c);
                    creditAmountString = InFormat(r.Amount_Rs__c);
                    totalCreditAmount += r.Amount_Rs__c;
                }                                              
                wrap.add(new wrapperClass(r.Business_Unit__c, r.Booking__r.Primary_Applicant_Name__c, r.Project_Unit__r.Name, r.Booking__r.Tower__c, r.Booking__r.Name, r.GL_Date__c, r.Booking__r.Stage_of_Booking__c, r.Mode__c, r.Receipt_Status__c, r.Currency__c, amount, creditAmountString, '', type, r.Voucher_Number__c, r.Bank_Reference_Number__c, '', r.Name, r.Booking__r.Sales_Managers__r.Name, r.Booking__r.Channel_Partner__r.Name, r.Booking__r.Booking_Date__c.Date(), r.Cheque_DD_Date__c, r.Receipt_Date__c, r.Payment_Towards__c, r.RemarksText__c, r.DraweeBank__c, r.Adjustment_Entry__c, r.Debit_Account__r.Name));
            }
        }         
        totalCreditAmountString = INFormat(totalCreditAmount);                 
        wrap.sort();  
        //// Display only 999 records on page but allow to download upto 99999 records              
        if(wrap != null && wrap.size() > 999 && wrap.size() < 99999){
            for(wrapperClass w: wrap){
                if(wrapListToDisplay != null && wrapListToDisplay.size() < 999){
                    wrapListToDisplay.add(w);                    
                }                   
            }
            wrapListToDownload.addall(wrap);      
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning,'This report has large number of rows. Please download to see full results.'));
        } else if (wrap != null && wrap.size() > 99999){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning,'This report has large number of rows. Please select a shorter time duration.'));
        }
        else {
            wrapListToDownload.addall(wrap);
            wrapListToDisplay.addall(wrap);
        }  
        system.debug('display size::: ' + wrapListToDisplay.size());    
        system.debug('download size::: ' + wrapListToDownload.size());
        system.debug('wrap::: ' + wrap.size());  
        return null;       
    }
    
    public class wrapperClass implements Comparable {
        public String buName{get;set;}
        public String customerName{get;set;}
        public String unitNo{get;set;}
        public String buildingName{get;set;}
        public String bookingNumber{get;set;}
        public Date GLDate{get;set;} 
        public String bookingStatus{get;set;}
        public String rcptMode{get;set;}
        public String rcptStatus{get;set;}
        public String currenc{get;set;}
        public String enteredAmount{get;set;}  
        public String credit{get;set;}
        public String debit{get;set;}  
        public String type {get;set;}
        public String docNo {get;set;}
        public String vocNo {get;set;}
        public String bankRefNo {get;set;}
        public String msName {get;set;}
        public String sm {get;set;}
        public String cp{get;set;}
        public Date bookingDate {get;set;}
        public Date maturityDate {get;set;}
        public Date receiptDate {get;set;}
        public String paymentTowards {get;set;}
        public String remarks {get;set;}
        public String bankName {get;set;}
        public Boolean adjustmentEntry {get;set;}
        public String debitAccountName {get;set;}
        
        public wrapperClass(String buName, String customerName, String unitNo, String buildingName, String bookingNumber, Date GLDate, String bookingStatus, String rcptMode, String rcptStatus, String currenc, String enteredAmount, String credit, String debit, String type, String vocNo, String bankRefNo, String msName, String docNo, String sm, String cp, Date bookingDate, Date maturityDate, Date receiptDate, String paymentTowards, String remarks, String bankName, Boolean adjustmentEntry, String debitAccountName){
            this.buName = buName ;
            this.customerName = customerName;
            this.unitNo = unitNo;
            this.buildingName = buildingName;
            this.bookingNumber = bookingNumber;
            this.GLDate = GLDate;
            this.bookingStatus = bookingStatus;
            this.rcptMode = rcptMode;
            this.rcptStatus = rcptStatus;
            this.currenc = currenc;
            this.enteredAmount = enteredAmount;
            this.credit = credit;
            this.debit = debit;
            this.type = type;
            this.docNo = docNo;
            this.vocNo = vocNo;
            this.bankRefNo = bankRefNo;
            this.msName = msName;
            this.sm = sm;
            this.cp = cp;
            this.bookingDate = bookingDate;
            this.maturityDate = maturityDate;
            this.receiptDate = receiptDate;
            this.paymentTowards = paymentTowards;
            this.remarks = remarks;
            this.bankName = bankName;
            this.adjustmentEntry = adjustmentEntry;
            this.debitAccountName = debitAccountName;
        }  
        
        public Integer compareTo(Object ObjToCompare) {
            wrapperClass wrapper = (wrapperClass)(ObjToCompare);
            return sortByDate(wrapper);
        }
        private Integer sortByDate(wrapperClass wrapper) {
            if (this.GLDate > wrapper.GLDate) {
                return 1;
            }
            if (this.GLDate == wrapper.GLDate) {
                return 0;
            }
            return -1;
        }         
    }
    
    public static String INFormat(Decimal money) {
        Boolean negative = false;
        if(money < 0) {
            negative = true;
        }
        if(money == null) {
            return 'NIL';
        }
        Decimal tempMoney = money;
        String m0 = tempMoney.setscale(0,RoundingMode.HALF_UP).toPlainString();
        String decimalPart;
        List<String> tempStr = new List<String>();
        if(String.isNotBlank(m0)) {
            tempStr = m0.split('\\.');
            if(tempStr != null && tempStr.size() == 2) {
                decimalPart = tempStr[1];
            }
        }
        String m1 = String.valueOf(math.abs(money.setscale(0,RoundingMode.HALF_UP))).reverse();
        String mF = '';
        for(Integer i=0; i < m1.length() ; i++) {
            mF += m1.substring(i,i+1);         
            if(i==2 || i==5 || i==8 || i==11 || i==14) {
                mF += ',';
            }
        }
        mf = mf.reverse();
        if(mf.substring(0,1).equals(',')) {
            mf = mf.substring(1);
        }
        if(String.isNotBlank(decimalPart)) 
            mf = mf + '.'  + decimalPart;
        if(!negative)
            mf = mf;
        else
            mf = '- ' + mf;
        return mf;
    }       
}