force-app/main/default/objects/Demand__c/Demand__c.object-meta.xml
<CustomObject>
    <label>Demand</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Demand Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Demands</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Demand__c/fields/Agreement_Value_Paid__c.field-meta.xml
<CustomField>
    <fullName>Agreement_Value_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Agreement Value Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Debit_Paid__c.field-meta.xml
<CustomField>
    <fullName>Debit_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Debit Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Debit_Tax_Paid__c.field-meta.xml
<CustomField>
    <fullName>Debit_Tax_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Debit VAT Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Interest_On_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Interest_On_Paid_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Interest On Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Demands</relationshipLabel>
    <relationshipName>Demands</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Service_Tax_on_Agreement_Value_Paid__c.field-meta.xml
<CustomField>
    <fullName>Service_Tax_on_Agreement_Value_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>VAT on Agreement Value Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Tax_On_Interest_On_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Tax_On_Interest_On_Paid_Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>VAT On Interest On Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Interest_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Interest Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Interest_Amount_Waived__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Amount_Waived__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Interest Amount Waived</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Interest_Tax_Paid__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Tax_Paid__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Interest VAT Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Demand__c/fields/Total_Interest_Tax_Waived__c.field-meta.xml
<CustomField>
    <fullName>Total_Interest_Tax_Waived__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Total Interest VAT Waived</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ledger__c/Ledger__c.object-meta.xml
<CustomObject>
    <label>Ledger</label>
    <nameField>
        <displayFormat>L-{000000}</displayFormat>
        <label>Ledger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ledgers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ledger__c/fields/Activity__c.field-meta.xml
<CustomField>
    <fullName>Activity__c</fullName>
    <label>Activity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Debit</fullName>
            </value>
            <value>
                <fullName>Credit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Charge_Name__c.field-meta.xml
<CustomField>
    <fullName>Charge_Name__c</fullName>
    <label>Charge Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demand</label>
    <referenceTo>Demand__c</referenceTo>
    <relationshipLabel>Ledgers</relationshipLabel>
    <relationshipName>Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Ledgers</relationshipLabel>
    <relationshipName>Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Receipt__c.field-meta.xml
<CustomField>
    <fullName>Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Ledgers</relationshipLabel>
    <relationshipName>Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Receipt_Details__c.field-meta.xml
<CustomField>
    <fullName>Receipt_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Receipt Details</label>
    <referenceTo>Receipt_Details__c</referenceTo>
    <relationshipLabel>Ledgers</relationshipLabel>
    <relationshipName>Ledgers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Ledger__c/fields/Tax_Ledger__c.field-meta.xml
<CustomField>
    <fullName>Tax_Ledger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VAT Ledger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>AEDToUSDConversionRate</label>
</CustomObject>

force-app/main/default/objects/Receipt__c/Receipt__c.object-meta.xml
<CustomObject>
    <label>Receipt</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Receipt Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demand</label>
    <referenceTo>Demand__c</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt__c/fields/Parent_Receipt__c.field-meta.xml
<CustomField>
    <fullName>Parent_Receipt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Receipt</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Advance Receipts</relationshipLabel>
    <relationshipName>Receipts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/Receipt_Details__c.object-meta.xml
<CustomObject>
    <label>Receipt Details</label>
    <nameField>
        <displayFormat>RD-{00000}</displayFormat>
        <label>Receipt Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Receipt Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Receipt_Details__c/fields/Charge_1_Amount_Apportioned__c.field-meta.xml
<CustomField>
    <fullName>Charge_1_Amount_Apportioned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge 1 Amount Apportioned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/fields/Charge_1_Tax_Apportioned__c.field-meta.xml
<CustomField>
    <fullName>Charge_1_Tax_Apportioned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Charge 1 VAT Apportioned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/fields/Debit_Amount_Apportioned__c.field-meta.xml
<CustomField>
    <fullName>Debit_Amount_Apportioned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Debit Amount Apportioned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/fields/Debit_Charge_Name__c.field-meta.xml
<CustomField>
    <fullName>Debit_Charge_Name__c</fullName>
    <label>Debit Charge Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Interest Charges</fullName>
            </value>
            <value>
                <fullName>Brokerage Reversal</fullName>
            </value>
            <value>
                <fullName>Cheque Bounce</fullName>
            </value>
            <value>
                <fullName>Interior Charges</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/fields/Debit_Tax_Apportioned__c.field-meta.xml
<CustomField>
    <fullName>Debit_Tax_Apportioned__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Debit VAT Apportioned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/fields/Demand__c.field-meta.xml
<CustomField>
    <fullName>Demand__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Demand</label>
    <referenceTo>Demand__c</referenceTo>
    <relationshipLabel>Receipt Details</relationshipLabel>
    <relationshipName>Receipt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/fields/Interest_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount_Paid__c</fullName>
    <label>Interest Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/fields/Interest_Amount_Waived__c.field-meta.xml
<CustomField>
    <fullName>Interest_Amount_Waived__c</fullName>
    <label>Interest Amount Waived</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/fields/Interest_on_late_amount_paid__c.field-meta.xml
<CustomField>
    <fullName>Interest_on_late_amount_paid__c</fullName>
    <formula>If ( (DATEVALUE(CreatedDate) &gt;  Demand__r.Due_Date__c ),
(Total_Amount_adjusted__c *  
$Setup.ROI_del__c.ROI__c * (  DATEVALUE(CreatedDate) -  Demand__r.Due_Date__c )),0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Interest on late amount paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/fields/Receipts__c.field-meta.xml
<CustomField>
    <fullName>Receipts__c</fullName>
    <label>Receipts</label>
    <referenceTo>Receipt__c</referenceTo>
    <relationshipLabel>Receipt Details</relationshipLabel>
    <relationshipName>Receipt_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/fields/Tax_On_Interest_on_Late_Amount_Paid__c.field-meta.xml
<CustomField>
    <fullName>Tax_On_Interest_on_Late_Amount_Paid__c</fullName>
    <formula>Interest_on_late_amount_paid__c * 18/100</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>VAT On Interest on Late Amount Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/fields/Tax_on_Interest_Paid__c.field-meta.xml
<CustomField>
    <fullName>Tax_on_Interest_Paid__c</fullName>
    <label>VAT on Interest Paid</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Receipt_Details__c/fields/Tax_On_Interest_Waived__c.field-meta.xml
<CustomField>
    <fullName>Tax_On_Interest_Waived__c</fullName>
    <label>VAT On Interest Waived</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TriggerReceiptDetailHandler.cls
public with sharing class TriggerReceiptDetailHandler {

    public static boolean afterUpdateTriggerFirstRun = true;
    public static boolean afterInsertTriggerFirstRun = true;
    
    public static void creditToDemands(Set<Id> rdIdSet) {
        String tempQuery ='';
        for (Integer i = 2; i <= 15; i++) {
            tempQuery += 'Charge_' + i + '_Amount_Apportioned__c' + ',';
            tempQuery += 'Charge_' + i + '_Tax_Apportioned__c' + ',';
        }
        if (tempQuery.length() > 0 && tempQuery.substring(tempQuery.length() - 1).equals(','))
            tempQuery = tempQuery.substring(0, tempQuery.length() - 1);
        List<Receipt_Details__c> rdList = new List<Receipt_Details__c>();
        
        String rdQuery = 'Select Id, Name,Debit_Amount_Apportioned__c, Debit_Tax_Apportioned__c, Interest_on_late_amount_paid__c, Tax_On_Interest_on_Late_Amount_Paid__c,Interest_Amount_Paid__c,Interest_Amount_Waived__c,Tax_on_Interest_Paid__c,Tax_On_Interest_Waived__c, Demand__c, Demand__r.Id,Charge_1_Amount_Apportioned__c, Charge_1_Tax_Apportioned__c,' + tempQuery + 
                            ' from Receipt_Details__c where id in :rdIdSet';
        System.debug('rdQuery:' + rdQuery);
        
        rdList = Database.Query (rdQuery);
        Set<Id> demandIdSet = new Set<Id>();
        if(rdList != null) {
            for(Receipt_details__c rd : rdList){
                demandIdSet.add(rd.Demand__c);
            }
        
            List<Demand__c> dList = new List<Demand__c>();
            String tempQuery1 = '';
            for (Integer i = 1; i <= 15; i++) {
                tempQuery1 += 'Charge_' + i + '_Paid__c' + ',';
                tempQuery1 += 'Charge_' + i + '_Tax_Paid__c' + ',';
            }
            if (tempQuery1.length() > 0 && tempQuery1.substring(tempQuery1.length() - 1).equals(','))
                tempQuery1 = tempQuery1.substring(0, tempQuery1.length() - 1);
            String demandQuery = 'Select Id, Name,Debit_Paid__c, Debit_Tax_Paid__c, Agreement_Value_Paid__c, Service_Tax_on_Agreement_Value_Paid__c,Interest_On_Paid_Amount__c,Tax_On_Interest_On_Paid_Amount__c,Total_Interest_Amount_Paid__c,Total_Interest_Amount_Waived__c,Total_Interest_Tax_Paid__c,Total_Interest_Tax_Waived__c,' + tempQuery1 + 
                                ' from Demand__c where id in :demandIdSet';
            dList = Database.Query (demandQuery);
            
            Map<Id, Demand__c> dMap = new Map<Id, Demand__c>();
            if(dlist != null && !dList.isEmpty()) {
                for(Demand__c d : dList){
                    dMap.put(d.Id, d);
                }
                for(Receipt_Details__c rd : rdList) {
                    System.debug('rd: in receipt details credit to demands trigger:' + rd);
                    Demand__c d = dMap.get(rd.Demand__r.Id);
                    if(rd.Interest_on_late_amount_paid__c != null)
                        d.Interest_On_Paid_Amount__c += rd.Interest_on_late_amount_paid__c;
                    if(rd.Tax_On_Interest_on_Late_Amount_Paid__c != null)
                        d.Tax_On_Interest_On_Paid_Amount__c += rd.Tax_On_Interest_on_Late_Amount_Paid__c;                    
                    if(rd.Interest_Amount_Paid__c != null)
                        d.Total_Interest_Amount_Paid__c += rd.Interest_Amount_Paid__c;
                    if(rd.Tax_on_Interest_Paid__c != null)
                        d.Total_Interest_Tax_Paid__c += rd.Tax_on_Interest_Paid__c; 
                    if(rd.Interest_Amount_Waived__c != null)
                        d.Total_Interest_Amount_Waived__c += rd.Interest_Amount_Waived__c;
                    if(rd.Tax_On_Interest_Waived__c != null){
                        d.Total_Interest_Tax_Waived__c += rd.Tax_On_Interest_Waived__c;
                    }
                    if(rd.Debit_Amount_Apportioned__c != null){
                        d.Debit_Paid__c += rd.Debit_Amount_Apportioned__c;
                    }
                    if(rd.Debit_Tax_Apportioned__c != null)
                        d.Debit_Tax_Paid__c += rd.Debit_Tax_Apportioned__c;
                        
                    if(rd.Charge_1_Amount_Apportioned__c != null)
                        d.Agreement_Value_Paid__c += rd.Charge_1_Amount_Apportioned__c;
                    if(rd.Charge_1_Tax_Apportioned__c != null){
                        d.Service_Tax_on_Agreement_Value_Paid__c += rd.Charge_1_Tax_Apportioned__c;
                    }
                    for(Integer i = 2; i<=15; i++) {
                     System.debug('Inside for loop');
                        if((Decimal) rd.get('Charge_' + i + '_Amount_Apportioned__c') != null)
                            d.put('Charge_' + i + '_Paid__c', (Decimal) d.get('Charge_' + i + '_Paid__c') + (Decimal) rd.get('Charge_' + i + '_Amount_Apportioned__c'));
                        if((Decimal) rd.get('Charge_' + i + '_Tax_Apportioned__c') != null){
                            d.put('Charge_' + i + '_Tax_Paid__c', (Decimal) d.get('Charge_' + i + '_Tax_Paid__c') + (Decimal) rd.get('Charge_' + i + '_Tax_Apportioned__c'));
                           System.debug('Charge_' + i + '_Tax_Paid__c' + ':::: ' + 'Charge_' + i + '_Tax_Paid__c');
                        }
                    }
                }
                update dList;
            }
        }
        
    }

    public static void debitFromDemands(Set<Id> rdIdSet) {
        String tempQuery ='';
        for (Integer i = 1; i <= 15; i++) {
            tempQuery += 'Charge_' + i + '_Amount_Apportioned__c' + ',';
            tempQuery += 'Charge_' + i + '_Tax_Apportioned__c' + ',';
        }
        if (tempQuery.length() > 0 && tempQuery.substring(tempQuery.length() - 1).equals(','))
            tempQuery = tempQuery.substring(0, tempQuery.length() - 1);
        List<Receipt_Details__c> rdList = new List<Receipt_Details__c>();
        String rdQuery = 'Select Id, Name,Debit_Amount_Apportioned__c, Debit_Tax_Apportioned__c,Interest_on_late_amount_paid__c, Tax_On_Interest_on_Late_Amount_Paid__c,Interest_Amount_Paid__c,Interest_Amount_Waived__c,Tax_on_Interest_Paid__c,Tax_On_Interest_Waived__c, Demand__c, Demand__r.Id,' + tempQuery + 
                            ' from Receipt_Details__c where id in :rdIdSet';
        rdList = Database.Query (rdQuery);
        Set<Id> demandIdSet = new Set<Id>();
        Map<Id, List<Receipt_Details__c>> demandReceiptMap = new Map<Id, List<Receipt_Details__c>>();
        if(rdList != null && !rdList.isEmpty()) {
            for(Receipt_details__c rd : rdList){
                demandIdSet.add(rd.Demand__c);
                List<Receipt_Details__c> tempList = new List<Receipt_Details__c>();
                if(demandReceiptMap.containsKey(rd.Demand__r.Id)) {
                    tempList = demandReceiptMap.get(rd.Demand__r.Id);
                } 
                tempList.add(rd);
                demandReceiptMap.put(rd.Demand__r.Id,tempList);
            }
        
            List<Demand__c> dList = new List<Demand__c>();
            String tempQuery1 = '';
            for (Integer i = 1; i <= 15; i++) {
                tempQuery1 += 'Charge_' + i + '_Paid__c' + ',';
                tempQuery1 += 'Charge_' + i + '_Tax_Paid__c' + ',';
            }
            if (tempQuery1.length() > 0 && tempQuery1.substring(tempQuery1.length() - 1).equals(','))
                tempQuery1 = tempQuery1.substring(0, tempQuery1.length() - 1);
            String demandQuery = 'Select Id, Name,Debit_Paid__c, Debit_Tax_Paid__c, Agreement_Value_Paid__c, Service_Tax_on_Agreement_Value_Paid__c,Interest_On_Paid_Amount__c,Tax_On_Interest_On_Paid_Amount__c,Total_Interest_Amount_Paid__c,Total_Interest_Amount_Waived__c,Total_Interest_Tax_Paid__c,Total_Amount_Paid__c, Total_Interest_Tax_Waived__c,' + tempQuery1 + 
                                ' from Demand__c where id in :demandIdSet';
            dList = Database.Query (demandQuery);
            
            Map<Id, Demand__c> dMap = new Map<Id, Demand__c>();
            if(dlist != null) {
                for(Demand__c d : dList){
                    dMap.put(d.Id, d);
                }
                for(Id dId : demandReceiptMap.keySet()) {
                    Demand__c d = dMap.get(dId);
                    for(Receipt_Details__c rd : demandReceiptMap.get(dId)) {
                        if(rd.Interest_on_late_amount_paid__c != null)
                            d.Interest_On_Paid_Amount__c -= rd.Interest_on_late_amount_paid__c;
                        if(rd.Tax_On_Interest_on_Late_Amount_Paid__c != null)
                            d.Tax_On_Interest_On_Paid_Amount__c -= rd.Tax_On_Interest_on_Late_Amount_Paid__c;
                        if(rd.Interest_Amount_Paid__c != null)
                            d.Total_Interest_Amount_Paid__c -= rd.Interest_Amount_Paid__c;
                        if(rd.Tax_on_Interest_Paid__c != null)
                            d.Total_Interest_Tax_Paid__c -= rd.Tax_on_Interest_Paid__c; 
                        if(rd.Interest_Amount_Waived__c != null)
                            d.Total_Interest_Amount_Waived__c -= rd.Interest_Amount_Waived__c;
                        if(rd.Tax_On_Interest_Waived__c != null)
                            d.Total_Interest_Tax_Waived__c -= rd.Tax_On_Interest_Waived__c;
                        if(rd.Debit_Amount_Apportioned__c != null)
                            d.Debit_Paid__c -= rd.Debit_Amount_Apportioned__c;
                        if(rd.Debit_Tax_Apportioned__c != null)
                            d.Debit_Tax_Paid__c -= rd.Debit_Tax_Apportioned__c;
                        if(rd.Charge_1_Amount_Apportioned__c != null)
                            d.Agreement_Value_Paid__c -= rd.Charge_1_Amount_Apportioned__c;
                   ///// Added by Neha on 17/6/19                            
                        if(rd.Charge_1_Tax_Apportioned__c != null)
                            d.Service_Tax_on_Agreement_Value_Paid__c -= rd.Charge_1_Tax_Apportioned__c;
                        for(Integer i =2; i<=15; i++) {
                            if((Decimal) rd.get('Charge_' + i + '_Amount_Apportioned__c') != null)
                                d.put('Charge_' + i + '_Paid__c', (Decimal) d.get('Charge_' + i + '_Paid__c') - (Decimal) rd.get('Charge_' + i + '_Amount_Apportioned__c'));
                            if((Decimal) rd.get('Charge_' + i + '_Tax_Apportioned__c') != null)
                                d.put('Charge_' + i + '_Tax_Paid__c', (Decimal) d.get('Charge_' + i + '_Tax_Paid__c') - (Decimal) rd.get('Charge_' + i + '_Tax_Apportioned__c'));
                        }
                        System.debug('Amount on demand ' + d.Name + ' after deducting receipt details:' + rd.Name + ':' + d);
                    }
                }                
                update dList;
            }
        }        
    }

    public static void createCreditLedgers(Set<Id> rdIdSet) {
        String tempQuery ='';
        for (Integer i = 1; i <= 15; i++) {
            tempQuery += 'Charge_' + i + '_Amount_Apportioned__c' + ',';
            tempQuery += 'Charge_' + i + '_Tax_Apportioned__c' + ',';
            tempQuery += 'Charge' + i + 'Name__c' + ',';
        }
        if (tempQuery.length() > 0 && tempQuery.substring(tempQuery.length() - 1).equals(','))
            tempQuery = tempQuery.substring(0, tempQuery.length() - 1);
        List<Receipt_Details__c> rdList = new List<Receipt_Details__c>();
        String rdQuery = 'Select Id, Name,Debit_Charge_Name__c, Debit_Amount_Apportioned__c, Debit_Tax_Apportioned__c, Demand__c,Receipts__r.Opportunity__c, Transaction_Date__c,Receipts__c, Receipts__r.Id,' + tempQuery + 
                            ' from Receipt_Details__c where id in :rdIdSet';
        rdList = Database.Query (rdQuery);
        Set<Id> demandIdSet = new Set<Id>();
        List<Ledger__c> llist = new List<Ledger__c>();
        if(rdList != null) {
            for(Receipt_details__c rd : rdList) {
                if(rd.Debit_Amount_Apportioned__c != null && rd.Debit_Amount_Apportioned__c != 0) {
                    Ledger__c l = new Ledger__c();
                        l.Charge_Name__c = rd.Debit_Charge_Name__c;
                        l.Amount__c = rd.Debit_Amount_Apportioned__c;
                        l.Activity__c = 'Credit';
                        l.Demand__c = rd.Demand__c;
                        l.Receipt__c = rd.Receipts__r.Id;
                        l.Receipt_Details__c = rd.Id;
                        l.Opportunity__c = rd.Receipts__r.Opportunity__c;
                        l.Transaction_Date__c = rd.Transaction_Date__c;
                        llist.add(l);
                }
                if(rd.Debit_Tax_Apportioned__c != null && rd.Debit_Tax_Apportioned__c != 0) {
                    Ledger__c l = new Ledger__c();
                        l.Charge_Name__c = rd.Debit_Charge_Name__c;
                        l.Amount__c = rd.Debit_Tax_Apportioned__c;
                        l.Activity__c = 'Credit';
                        l.Demand__c = rd.Demand__c;
                        l.Receipt__c = rd.Receipts__r.Id;
                        l.Receipt_Details__c = rd.Id;
                        l.Opportunity__c = rd.Receipts__r.Opportunity__c;
                        l.Transaction_Date__c = rd.Transaction_Date__c;
                        l.Tax_ledger__c = true;
                        l.Transaction_Date__c = rd.Transaction_Date__c;
                        llist.add(l);
                }
                if(rd.Charge_1_Amount_Apportioned__c != null && rd.Charge_1_Amount_Apportioned__c != 0) {
                    Ledger__c l = new Ledger__c();
                        l.Charge_Name__c = 'Flat Cost';
                        l.Amount__c = rd.Charge_1_Amount_Apportioned__c;
                        l.Activity__c = 'Credit';
                        l.Demand__c = rd.Demand__c;
                        l.Receipt__c = rd.Receipts__r.Id;
                        l.Receipt_Details__c = rd.Id;
                        l.Opportunity__c = rd.Receipts__r.Opportunity__c;
                        l.Transaction_Date__c = rd.Transaction_Date__c;
                        llist.add(l);
                }
                if(rd.Charge_1_Tax_Apportioned__c != null && rd.Charge_1_Tax_Apportioned__c != 0) {
                    Ledger__c l = new Ledger__c();
                        l.Charge_Name__c = 'Flat Cost';
                        l.Amount__c = rd.Charge_1_Tax_Apportioned__c;
                        l.Activity__c = 'Credit';
                        l.Demand__c = rd.Demand__c;
                        l.Receipt__c = rd.Receipts__r.Id;
                        l.Receipt_Details__c = rd.Id;
                        l.Opportunity__c = rd.Receipts__r.Opportunity__c;
                        l.Transaction_Date__c = rd.Transaction_Date__c;
                        l.Tax_ledger__c = true;
                        llist.add(l);
                }
                for(Integer i =2; i<=15; i++) {
                    if( rd.get('Charge_' + i + '_Amount_Apportioned__c') != null &&  (Decimal) rd.get('Charge_' + i + '_Amount_Apportioned__c') != 0) {
                        Ledger__c l = new Ledger__c();
                            l.Charge_Name__c = (String) rd.get('Charge' + i + 'Name__c');
                            l.Amount__c =  (Decimal) rd.get('Charge_' + i + '_Amount_Apportioned__c') ;
                            l.Activity__c = 'Credit';
                            l.Demand__c = rd.Demand__c;
                            l.Receipt__c = rd.Receipts__r.Id;
                            l.Receipt_Details__c = rd.Id;
                            l.Opportunity__c = rd.Receipts__r.Opportunity__c;
                            l.Transaction_Date__c = rd.Transaction_Date__c;
                            l.Tax_ledger__c = true;
                            llist.add(l);
                    }
                    if( rd.get('Charge_' + i + '_Tax_Apportioned__c') != null &&  (Decimal) rd.get('Charge_' + i + '_Tax_Apportioned__c') != 0) {
                        Ledger__c l = new Ledger__c();
                            l.Charge_Name__c = (String) rd.get('Charge' + i + 'Name__c');
                            l.Amount__c =  (Decimal) rd.get('Charge_' + i + '_Tax_Apportioned__c') ;
                            l.Activity__c = 'Credit';
                            l.Demand__c = rd.Demand__c;
                            l.Receipt__c = rd.Receipts__r.Id;
                            l.Receipt_Details__c = rd.Id;
                            l.Opportunity__c = rd.Receipts__r.Opportunity__c;
                            l.Transaction_Date__c = rd.Transaction_Date__c;
                            l.Tax_ledger__c = true;
                            llist.add(l);
                    }
                }
                
            }
            if(!llist.isEmpty() && llist.size() > 0) {
                insert llist;
            }
            
        }
    }
    public static void deleteCreditLedgers(Set<Id> rdIdSet) {
        List<Ledger__c> llist = new List<Ledger__c>();
        llist = [Select Id from Ledger__c  where Receipt_Details__c in :rdIdSet];
        if(!llist.isEmpty() && llist.size() > 0) {
            delete llist;
        }
    }
    
    public static void cleanupLedgersAftercancellation(Set<Id> rdIdSet) {
        // update all the ledgers as cancelled
        List<Ledger__c> llist = new List<Ledger__c>();
        List<Ledger__c>  newLedgerslist = new List<Ledger__c>();
        List<Ledger__c>  debitLedgers = new List<Ledger__c>();
        llist = [Select Id, Charge_Name__c, Amount__c, Demand__c, Demand__r.Id, Receipt__r.Cheque_DD__c, Opportunity__c,Tax_Ledger__c from Ledger__c  
                 where Receipt_Details__c in :rdIdSet];
        Set<Id> affectedDemandIds = new Set<Id>();
        if(!llist.isEmpty() && llist.size() > 0) {
            for(Ledger__c l : llist) {
                l.cancelled__c = true;
                l.Remarks__c =  'APPORTIONMENT REVERSAL';
                
                System.debug('Existing Credit Ledger to be reversed:' +l);
                Ledger__c ld = new Ledger__c();
                ld.Charge_Name__c = l.Charge_Name__c;
                ld.Amount__c = l.Amount__c;
                ld.Activity__c = 'Debit';
                ld.Demand__c = l.Demand__c;
                ld.Opportunity__c = l.Opportunity__c;
                ld.Transaction_Date__c = system.today();
                ld.Tax_Ledger__c = l.Tax_Ledger__c;
                ld.Remarks__c = 'Receipt No : ' + l.Receipt__r.Cheque_DD__c + ' rejected on  ' + system.now().format('dd/MM/yyyy');
                newLedgerslist.add(ld);
            }
            update llist;
            insert newLedgerslist;            
        }
    }
}