force-app/main/default/objects/CSO_Announcment__c/CSO_Announcment__c.object-meta.xml
<CustomObject>
    <label>CSO Announcement</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Announcement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSO Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CSO_Announcment__c/fields/Notification__c.field-meta.xml
<CustomField>
    <fullName>Notification__c</fullName>
    <label>Notification</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/CSO_Announcment__c/fields/Valid_Till__c.field-meta.xml
<CustomField>
    <fullName>Valid_Till__c</fullName>
    <label>Valid Till</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CSOs_General_Instructions__c/CSOs_General_Instructions__c.object-meta.xml
<CustomObject>
    <label>CSOs General Instruction</label>
    <nameField>
        <displayFormat>GI-{0000}</displayFormat>
        <label>GI</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSOs General Instructions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CSOs_General_Instructions__c/fields/Instruction__c.field-meta.xml
<CustomField>
    <fullName>Instruction__c</fullName>
    <label>Instruction</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Notification__c/Notification__c.object-meta.xml
<CustomObject>
    <label>Notification</label>
    <nameField>
        <displayFormat>N-{00000000}</displayFormat>
        <label>Notification Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CsoAnnouncementBoard.cls
public with sharing class CsoAnnouncementBoard {
         @AuraEnabled(Cacheable=true)
        public static List<CSO_Announcment__c> getAllActiveAnnouncements(Integer pageSize){
            List<CSO_Announcment__c> annList = new List<CSO_Announcment__c>();
            try {
                // Retrieve records from the last 7 days
                Date last7Days = Date.today().addDays(-7);
                annList = [SELECT Id, Name, Title__c, Active__c, CreatedDate, Notification__c 
                           FROM CSO_Announcment__c 
                           WHERE Active__c = true AND Valid_Till__c >= TODAY
                           ORDER BY CreatedDate DESC 
                           LIMIT :pageSize ];
            } catch (Exception e) {
                throw new AuraHandledException(e.getMessage());
            }
            return annList;
        }

        @AuraEnabled(Cacheable=true)
        public static List<CSOs_General_Instructions__c> getGeneralInstructions() {
            //List<CSOs_General_Instructions__c> instructions;
            List<CSOs_General_Instructions__c> gi= new List<CSOs_General_Instructions__c>();
            try {
             
                gi=[SELECT Id,Instruction__c,Sequence__c FROM CSOs_General_Instructions__c WHERE Active__c = true ORDER BY Sequence__c ASC];
                //instructions=gi'  
            } catch (Exception e) {
                
                System.debug('Exception: ' + e.getMessage());
            }
    
            return gi;
        }
}