force-app/main/default/objects/Nice_Calling_List_Disposition_Mapping__mdt/Nice_Calling_List_Disposition_Mapping__mdt.object-meta.xml
<CustomObject>
    <label>Nice Calling List Disposition Mapping</label>
    <pluralLabel>Nice Calling List Dispositions Mapping</pluralLabel>
</CustomObject>

force-app/main/default/objects/Nice_Calling_List_Disposition_Mapping__mdt/fields/Call_Disposition_L1__c.field-meta.xml
<CustomField>
    <fullName>Call_Disposition_L1__c</fullName>
    <label>Call Disposition L1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nice_Calling_List_Disposition_Mapping__mdt/fields/Call_Disposition_L2__c.field-meta.xml
<CustomField>
    <fullName>Call_Disposition_L2__c</fullName>
    <label>Call Disposition L2</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nice_Calling_List_Disposition_Mapping__mdt/fields/Call_Disposition_L3__c.field-meta.xml
<CustomField>
    <fullName>Call_Disposition_L3__c</fullName>
    <label>Call Disposition L3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Nice_Calling_List_Disposition_Mapping__mdt/fields/Tag_Id__c.field-meta.xml
<CustomField>
    <fullName>Tag_Id__c</fullName>
    <label>Tag Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Task Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Call_Disposition_L1__c.field-meta.xml
<CustomField>
    <fullName>Call_Disposition_L1__c</fullName>
    <label>Call Disposition L1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Advance collections</fullName>
            </value>
            <value>
                <fullName>Dues collection</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Call_Disposition_L2__c.field-meta.xml
<CustomField>
    <fullName>Call_Disposition_L2__c</fullName>
    <label>Call Disposition L2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Call_Disposition_L1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NPV benefit Customer interested</fullName>
            </value>
            <value>
                <fullName>Not interested in NPV</fullName>
            </value>
            <value>
                <fullName>NPV dispute</fullName>
            </value>
            <value>
                <fullName>Non NPV disputes</fullName>
            </value>
            <value>
                <fullName>PCC</fullName>
            </value>
            <value>
                <fullName>No contact / unable to reach</fullName>
            </value>
            <value>
                <fullName>PTP</fullName>
            </value>
            <value>
                <fullName>SPA/pre-reg required by customer</fullName>
            </value>
            <value>
                <fullName>Adjustment/transfer funds</fullName>
            </value>
            <value>
                <fullName>Paid not realised in SOA</fullName>
            </value>
            <value>
                <fullName>Cancellation/termination</fullName>
            </value>
            <value>
                <fullName>New sales overdue</fullName>
            </value>
            <value>
                <fullName>Mortgage</fullName>
            </value>
            <value>
                <fullName>Disputes / delays / deviation case</fullName>
            </value>
            <value>
                <fullName>Resale</fullName>
            </value>
            <value>
                <fullName>3rd party payments representative</fullName>
            </value>
            <value>
                <fullName>Fraud related</fullName>
            </value>
            <value>
                <fullName>Call Transfer / Case transfer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Call_Disposition_L3__c.field-meta.xml
<CustomField>
    <fullName>Call_Disposition_L3__c</fullName>
    <label>Call Disposition L3</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Call_Disposition_L2__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single unit advance</fullName>
            </value>
            <value>
                <fullName>Multiple units advance payment</fullName>
            </value>
            <value>
                <fullName>PTP this month</fullName>
            </value>
            <value>
                <fullName>PTP this week</fullName>
            </value>
            <value>
                <fullName>call back yes</fullName>
            </value>
            <value>
                <fullName>call back no</fullName>
            </value>
            <value>
                <fullName>Excess commitments to customer</fullName>
            </value>
            <value>
                <fullName>Customer misunderstanding NPV benefit</fullName>
            </value>
            <value>
                <fullName>False communication via sales / brokers</fullName>
            </value>
            <value>
                <fullName>LP related</fullName>
            </value>
            <value>
                <fullName>booking related</fullName>
            </value>
            <value>
                <fullName>Call Transfer / Case transfer</fullName>
            </value>
            <value>
                <fullName>Resale SOA dispute</fullName>
            </value>
            <value>
                <fullName>Customer finalising bank for mortgage</fullName>
            </value>
            <value>
                <fullName>NPV interested customer</fullName>
            </value>
            <value>
                <fullName>Pre-approval / Offer letter received</fullName>
            </value>
            <value>
                <fullName>100% payments shortfall</fullName>
            </value>
            <value>
                <fullName>excess amounts refund related</fullName>
            </value>
            <value>
                <fullName>PTP next month</fullName>
            </value>
            <value>
                <fullName>call back request</fullName>
            </value>
            <value>
                <fullName>3rd party payments representative</fullName>
            </value>
            <value>
                <fullName>SPA required</fullName>
            </value>
            <value>
                <fullName>Discrepancy in SPA</fullName>
            </value>
            <value>
                <fullName>Oqood pending</fullName>
            </value>
            <value>
                <fullName>Oqood document requested</fullName>
            </value>
            <value>
                <fullName>Incorrect escrow payments - transfer requested</fullName>
            </value>
            <value>
                <fullName>Cancel-swap movement of funds</fullName>
            </value>
            <value>
                <fullName>cancel-refund requested</fullName>
            </value>
            <value>
                <fullName>Re-allocation of funds - different units</fullName>
            </value>
            <value>
                <fullName>Re-allocation of funds -within same SOA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Task__c/fields/Calling_ID__c.field-meta.xml
<CustomField>
    <fullName>Calling_ID__c</fullName>
    <externalId>true</externalId>
    <label>Calling ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Comments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Task_NICE_Event__e/Task_NICE_Event__e.object-meta.xml
<CustomObject>
    <label>Task NICE Event</label>
    <pluralLabel>Task NICE Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Task_NICE_Event__e/fields/Task_Id__c.field-meta.xml
<CustomField>
    <fullName>Task_Id__c</fullName>
    <label>Task Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Nice_TaskDispositionHandler.cls
/******************************************************
	Class : Nice_TaskDispositionHandler
    Test Class : Nice_TaskDispositionHandlerTest
    Purpose : NICE - Apex class handles publishing platform events, retrieving dependent picklist values, updating task records with call disposition details, and fetching a Tag ID based on disposition mappings.
    Author : Artee Varma
*******************************************************/

public class Nice_TaskDispositionHandler {
    @AuraEnabled
    public static void publishEvent(String jsonString){
        EventWrapper wrapper = (EventWrapper)JSON.deserialize(jsonString, EventWrapper.class);
        if (String.isBlank(jsonString)) {
            throw new AuraHandledException('no json found');
        }
        try {
            Task_NICE_Event__e event = new Task_NICE_Event__e(
                Event_Type__c = wrapper.Event_Type,
            Task_Id__c = wrapper.Task_Id,
            UserId__c = wrapper.UserId
                );
            System.debug('wrapper.UserId=> ' +  wrapper.UserId);
            System.debug('wrapper.Task_Id=> ' +  wrapper.Task_Id);
            
            EventBus.publish(event);
            System.debug('Task LWC published!');
        } catch (Exception e) {
            throw new AuraHandledException('Failed to publish Task NICE Event: ' + e.getMessage());
        }
    }
    class EventWrapper{
        @AuraEnabled
        public String Task_Id;
        @AuraEnabled
        public String UserId;
        @AuraEnabled
        public String Event_Type;
    }
    
    @AuraEnabled
    // String crmcallDispositionL1, String crmcallDispositionL2, String crmcallDispositionL3
    public static String updateTask(String taskId, String callDispositionL1, String callDispositionL2, String callDispositionL3, String updatedTaskComment ) {
      
        try {
            Task__c taskRecord = [SELECT Id,Calling_ID__c FROM Task__c WHERE Id = :taskId LIMIT 1];
            taskRecord.Call_Disposition_L1__c = callDispositionL1;
            taskRecord.Call_Disposition_L2__c = callDispositionL2;
            taskRecord.Call_Disposition_L3__c = callDispositionL3;

            /* Added by Ashwini form CRM Call disposition */
            taskRecord.Notes__c = updatedTaskComment;
           
            Update taskRecord;
            
            //get and store tag id based on call disposition
            //callDispositionL1, callDispositionL2, callDispositionL3
            String tagId = getTagId(callDispositionL1, callDispositionL2, callDispositionL3);
        	System.debug('tag id==> ' + tagId);
            
            if(taskRecord.Calling_ID__c != null && tagId != null){
                Nice_DispositionAPI.postToUpdateDisposition(taskRecord.Id, taskRecord.Calling_ID__c, tagId);
                return 'Task updated successfully and called Update Disposition API!';
            } else{
                System.debug('Unable to call Update Disposition API as Calling Id or Tag Id is missing!');
                return null;
            }
            
        } catch (Exception e) {
            throw new AuraHandledException('Error updating Task: ' + e.getMessage());
        }
    }
    
    // Method to fetch TagId based on dependent picklist values
    //String callDispositionL1, String callDispositionL2, String callDispositionL
    public static String getTagId(String callDispositionL1, String callDispositionL2, String callDispositionL3) {
      
        List<Nice_Calling_List_Disposition_Mapping__mdt> nice_cd_metadataRecords = new List<Nice_Calling_List_Disposition_Mapping__mdt>();
        
        // Query for Call Disposition values
        if (!String.isBlank(callDispositionL1) && !String.isBlank(callDispositionL2) && !String.isBlank(callDispositionL3)) {
            nice_cd_metadataRecords = [
            SELECT Id, Label, Call_Disposition_L1__c, Call_Disposition_L2__c, Call_Disposition_L3__c, Tag_Id__c
            FROM Nice_Calling_List_Disposition_Mapping__mdt
            WHERE Call_Disposition_L1__c = :callDispositionL1
            AND Call_Disposition_L2__c = :callDispositionL2
            AND Call_Disposition_L3__c = :callDispositionL3
            LIMIT 1
        ];
        }
    	
        // Return TagId if a matching record is found
        if (!nice_cd_metadataRecords.isEmpty()) {
            System.debug('Returned Tag Id: ' + nice_cd_metadataRecords[0].Tag_Id__c);
            return nice_cd_metadataRecords[0].Tag_Id__c;
        } else {
            System.debug('Returned Tag Id: Else ' );
            return null;
        }
    }


    /*Added by Ashwini to send tag id when call disposition fields changed manually from org*/
    public class TaskUpdateRequest {
    @InvocableVariable(required=true)
    public String taskId;

    @InvocableVariable(required=true)
    public String callingId;

    @InvocableVariable(required=true)
    public String tagId;
    }

    //refrenced in flow: Nice_UpdatetagIds.
      @InvocableMethod
    public static List<String> sendTagIdOnTaskUpdate(List<TaskUpdateRequest> requests) {
        List<String> responses = new List<String>();

        for (TaskUpdateRequest request : requests) {
            if (request.callingId != null && request.tagId != null) {
                Nice_DispositionAPI.postToUpdateDisposition(request.taskId, request.callingId, request.tagId);
                responses.add('Task updated successfully and called Update Disposition API!');
            } else {
                System.debug('Unable to call Update Disposition API as Calling Id or Tag Id is missing!');
                responses.add(null);
            }
        }
        return responses;
    }

    /*Added by Ashwini to send tag id when call disposition fields changed manually from org*/

}